{
 "title": "Code Ready Analytics Stats",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "graphite" }
  ]
 },
 "panels": [
  {
   "title": "Component Analysis - Response Time Moving Average",
   "type": "graph",
   "description": "Moving Average of Component Analysis API calls aka LSP calls",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "osio.prometheus.bayesian.analytics_api_http_request_average.*component_analysis*GET*200"
    }
   ]
  },
  {
   "title": "Component Analysis - Success Count",
   "type": "graph",
   "description": "Component Analysis success count ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "osio.prometheus.bayesian.analytics_api_http_request_total.*get_component_analysis*GET*200"
    }
   ]
  },
  {
   "title": "Component Analysis - Failure Count",
   "type": "graph",
   "description": "Component Analysis failure count ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "osio.prometheus.bayesian.analytics_api_http_request_total.*get_component_analysis*GET*4??"
    }
   ]
  }
 ]
}