{
 "title": "Telemeter",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(kube_pod_info, cluster)"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\"}, namespace)"
   },
   {
    "name": "statefulsets",
    "query": "label_values(kube_statefulset_status_replicas_ready{cluster=\"$cluster\", namespace=\"$namespace\"}, statefulset)"
   },
   {
    "name": "deployments",
    "query": "label_values(kube_deployment_status_replicas_available{cluster=\"$cluster\", namespace=\"$namespace\"}, deployment)"
   },
   {
    "name": "handler",
    "query": "label_values(http_requests_total{job=\"telemeter-server\",namespace=\"$namespace\"}, handler)"
   }
  ]
 },
 "panels": [
  { "title": "Number of Pods available", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$statefulsets",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "repeat": "statefulsets",
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_statefulset_status_replicas_ready{namespace=\"$namespace\",statefulset=\"$statefulsets\"} / kube_statefulset_status_replicas{namespace=\"$namespace\",statefulset=\"$statefulsets\"}"
    }
   ]
  },
  {
   "title": "$statefulsets",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_statefulset_status_replicas_ready{namespace=\"$namespace\",statefulset=\"$statefulsets\"} / kube_statefulset_status_replicas{namespace=\"$namespace\",statefulset=\"$statefulsets\"}"
    }
   ]
  },
  {
   "title": "$statefulsets",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_statefulset_status_replicas_ready{namespace=\"$namespace\",statefulset=\"$statefulsets\"} / kube_statefulset_status_replicas{namespace=\"$namespace\",statefulset=\"$statefulsets\"}"
    }
   ]
  },
  {
   "title": "$statefulsets",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_statefulset_status_replicas_ready{namespace=\"$namespace\",statefulset=\"$statefulsets\"} / kube_statefulset_status_replicas{namespace=\"$namespace\",statefulset=\"$statefulsets\"}"
    }
   ]
  },
  {
   "title": "$deployments",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "repeat": "deployments",
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{namespace=\"$namespace\",deployment=\"$deployments\"} / kube_deployment_status_replicas{namespace=\"$namespace\",deployment=\"$deployments\"}"
    }
   ]
  },
  {
   "title": "$deployments",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{namespace=\"$namespace\",deployment=\"$deployments\"} / kube_deployment_status_replicas{namespace=\"$namespace\",deployment=\"$deployments\"}"
    }
   ]
  },
  { "title": "Handlers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "All Handlers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(\n   rate(http_requests_total{job=\"telemeter-server\",namespace=\"$namespace\"}[5m]),\n  \"status_code\", \"${1}xx\", \"code\", \"([0-9])..\"\n)) by (status_code)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "$handler handler",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "repeat": "handler",
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(\n   rate(http_requests_total{handler=\"$handler\",job=\"telemeter-server\",namespace=\"$namespace\"}[5m]),\n  \"status_code\", \"${1}xx\", \"code\", \"([0-9])..\"\n)) by (status_code)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "$handler handler",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(\n   rate(http_requests_total{handler=\"$handler\",job=\"telemeter-server\",namespace=\"$namespace\"}[5m]),\n  \"status_code\", \"${1}xx\", \"code\", \"([0-9])..\"\n)) by (status_code)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  { "title": "Oauth Client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Oauth Client Response Codes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(\n   rate(client_api_requests_total{namespace=\"$namespace\",client=\"oauth\"}[5m]),\n  \"status_code\", \"${1}xx\", \"code\", \"([0-9])..\"\n)) by (status_code)",
     "legendFormat": "{{ status_code }}"
    }
   ]
  },
  {
   "title": "Resource Usage: Namespace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\"}) by (pod_name)",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "CPU Quota",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(label_replace(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod)"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\"}) by (pod)"
      },
      {
       "expr": "sum(label_replace(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod) / sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\"}) by (pod)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\"}) by (pod)"
      },
      {
       "expr": "sum(label_replace(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod) / sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\"}) by (pod)"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\", container_name!=\"\"}) by (pod_name)",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Memory Quota",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(label_replace(container_memory_usage_bytes{namespace=\"$namespace\",container_name!=\"\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod)"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\"}) by (pod)"
      },
      {
       "expr": "sum(label_replace(container_memory_usage_bytes{namespace=\"$namespace\",container_name!=\"\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod) / sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\"}) by (pod)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\"}) by (pod)"
      },
      {
       "expr": "sum(label_replace(container_memory_usage_bytes{namespace=\"$namespace\",container_name!=\"\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod) / sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\"}) by (pod)"
      }
     ]
    }
   ]
  }
 ]
}