{
 "title": "Github Mirror",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Hits and misses: totals per hour",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "requests" }
   ],
   "targets": [
    {
     "expr": "sum(increase(request_latency_seconds_count{endpoint=\"github-mirror\",cache=\"HIT\"}[1h]))",
     "legendFormat": "hit"
    },
    {
     "expr": "sum(increase(request_latency_seconds_count{endpoint=\"github-mirror\",cache=\"MISS\"}[1h]))",
     "legendFormat": "miss"
    }
   ]
  },
  {
   "title": "Hits and misses: Percentage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 * sum(rate(request_latency_seconds_count{cache=\"HIT\",endpoint=\"github-mirror\"}[5m])) / sum(rate(request_latency_seconds_count{endpoint=\"github-mirror\"}[5m]))",
     "legendFormat": "hit"
    },
    {
     "expr": "100 * sum(rate(request_latency_seconds_count{cache=\"MISS\",endpoint=\"github-mirror\"}[5m])) / sum(rate(request_latency_seconds_count{endpoint=\"github-mirror\"}[5m]))",
     "legendFormat": "miss"
    }
   ]
  },
  {
   "title": "Latencies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(request_latency_seconds_bucket{endpoint=\"github-mirror\"}[5m])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(request_latency_seconds_bucket{endpoint=\"github-mirror\"}[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(request_latency_seconds_bucket{endpoint=\"github-mirror\"}[5m])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "requests/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(request_latency_seconds_count{endpoint=\"github-mirror\"}[5m]))",
     "legendFormat": "reqs"
    }
   ]
  },
  {
   "title": "Memory (RSS)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "megabytes" }
   ],
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{endpoint=\"github-mirror\"} / 1024^2)",
     "legendFormat": "rss"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(process_cpu_seconds_total{endpoint=\"github-mirror\"}[5m]))",
     "legendFormat": "usage"
    }
   ]
  }
 ]
}