{
 "title": "Red Hat Devfile Registry Service",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "ociRoute",
    "query": "label_values(haproxy_backend_http_responses_total, route)"
   },
   {
    "name": "namespace",
    "query": "label_values(index_http_request_duration_seconds_bucket, namespace)"
   },
   {
    "name": "indexRoute",
    "query": "label_values(haproxy_backend_http_responses_total, route)"
   }
  ]
 },
 "panels": [
  { "title": "Router", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Index Server Availability",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1 -\nsum(increase(haproxy_backend_http_responses_total{route=\"$indexRoute\",code=\"5xx\"}[$__range]))\n/\nsum(increase(haproxy_backend_http_responses_total{route=\"$indexRoute\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Index Server Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (code) (rate(haproxy_backend_http_responses_total{route=\"$indexRoute\"}[5m]))"
    }
   ]
  },
  {
   "title": "Index Server Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(haproxy_backend_http_responses_total{route=\"$indexRoute\",code=\"5xx\"}[5m])) /\nsum(rate(haproxy_backend_http_responses_total{route=\"$indexRoute\"}[5m]))"
    }
   ]
  },
  {
   "title": "OCI Server Availability",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1 -\nsum(increase(haproxy_backend_http_responses_total{route=\"$ociRoute\",code=\"5xx\"}[$__range]))\n/\nsum(increase(haproxy_backend_http_responses_total{route=\"$ociRoute\"}[$__range]))"
    }
   ]
  },
  {
   "title": "OCI Server Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (code) (rate(haproxy_backend_http_responses_total{route=\"$ociRoute\"}[5m]))"
    }
   ]
  },
  {
   "title": "OCI Server Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(haproxy_backend_http_responses_total{route=\"$ociRoute\",code=\"5xx\"}[5m])) /\nsum(rate(haproxy_backend_http_responses_total{route=\"$ociRoute\"}[5m]))"
    }
   ]
  },
  { "title": "Latencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Index Server Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(index_http_request_duration_seconds_bucket{namespace=\"$namespace\"}[5m])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le) (rate(index_http_request_duration_seconds_bucket{namespace=\"$namespace\"}[5m])))",
     "legendFormat": "p90"
    }
   ]
  },
  {
   "title": "OCI Server Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(registry_http_request_duration_seconds_bucket{namespace=\"$namespace\"}[5m])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le) (rate(registry_http_request_duration_seconds_bucket{namespace=\"$namespace\"}[5m])))",
     "legendFormat": "p90"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Container memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",container=~\"devfile-registry|oci-registry\"}) by (container)"
    }
   ]
  },
  {
   "title": "Container memory usage vs limits",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",container=~\"devfile-registry|oci-registry\"}) by (container) /\nsum(kube_pod_container_resource_limits{resource=\"memory\", namespace=\"$namespace\",container=~\"devfile-registry|oci-registry\"}) by (container)"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container=~\"devfile-registry|oci-registry\"}[5m])) by (container)"
    }
   ]
  },
  {
   "title": "CPU Throttle",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total{namespace=\"$namespace\", container=~\"devfile-registry|oci-registry\"}[5m])) by (container)\n"
    }
   ]
  }
 ]
}