{
 "title": "Integrations",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Slowest integrations (shard average)",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sort(topk(10, avg(qontract_reconcile_last_run_seconds) by (integration)))"
    }
   ]
  },
  {
   "title": "Errors in the last 10m",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sort(sum(increase(qontract_reconcile_run_status_total{status!~\"0|3|-9\"}[10m])) by (status, integration) > 0)"
    }
   ]
  },
  {
   "title": "Integrations p50 reconcile time openshift resources",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (integration, le) (qontract_reconcile_function_elapsed_seconds_since_bundle_commit_bucket{name=~\"reconcile.utils.oc.OC.(apply|replace|delete)\"}))",
     "legendFormat": "{{integration}}"
    }
   ]
  },
  {
   "title": "Integrations p90 reconcile time openshift resources",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (integration, le) (qontract_reconcile_function_elapsed_seconds_since_bundle_commit_bucket{name=~\"reconcile.utils.oc.OC.(apply|replace|delete)\"}))",
     "legendFormat": "{{integration}}"
    }
   ]
  },
  {
   "title": "Integrations p99 reconcile time openshift resources",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (integration, le) (qontract_reconcile_function_elapsed_seconds_since_bundle_commit_bucket{name=~\"reconcile.utils.oc.OC.(apply|replace|delete)\"}))",
     "legendFormat": "{{integration}}"
    }
   ]
  },
  {
   "title": "Integration run-time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(qontract_reconcile_last_run_seconds) by (integration, shard_id)"
    }
   ]
  },
  {
   "title": "Integration Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(qontract_reconcile_run_status_total{status!~\"0|3|-9\"}[5m])) by (integration, status)"
    }
   ]
  }
 ]
}