{
 "title": "Managed Services API SLOs",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Volume",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "requests/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(haproxy_backend_http_responses_total{route=\"managed-services-api\"}[5m]))",
     "legendFormat": "managed-service-api"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(1-haproxy_backend_http_responses_total:burnrate5m{exported_namespace=\"managed-services-stage\",route=\"managed-services-api\",service=\"managed-services-api\"}) * 100",
     "legendFormat": "managed-service-api"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(api_inbound_request_duration_bucket{job=\"managed-services-api-metrics\",namespace=\"managed-services-stage\",path=\"/api/managed-services-api/v1/kafkas\",code!~\"5..\"}[5m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(api_inbound_request_duration_bucket{job=\"managed-services-api-metrics\",namespace=\"managed-services-stage\",path=\"/api/managed-services-api/v1/kafkas\",code!~\"5..\"}[5m])) by (le))",
     "legendFormat": "p90"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(haproxy_backend_http_responses_total{route=\"managed-services-api\",exported_namespace=\"managed-services-stage\",code=\"5xx\"}[5m]))/sum(rate(haproxy_backend_http_responses_total{route=\"managed-services-api\",exported_namespace=\"managed-services-stage\"}[5m]))",
     "legendFormat": "managed-services-api"
    }
   ]
  },
  {
   "title": "Kafka Cluster Operations Correctness",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(managed_services_api_kafka_operations_success_count{job=\"managed-services-api-metrics\",namespace=\"managed-services-stage\",operation=\"create\"}[5m]))/sum(rate(managed_services_api_kafka_operations_total_count{job=\"managed-services-api-metrics\",namespace=\"managed-services-stage\",operation=\"create\"}[5m]))",
     "legendFormat": "Create Operation"
    },
    {
     "expr": "sum(rate(managed_services_api_kafka_operations_success_count{job=\"managed-services-api-metrics\",namespace=\"managed-services-stage\",operation=\"delete\"}[5m]))/sum(rate(managed_services_api_kafka_operations_total_count{job=\"managed-services-api-metrics\",namespace=\"managed-services-stage\",operation=\"delete\"}[5m]))",
     "legendFormat": "Delete Operation"
    }
   ]
  },
  {
   "title": "Kafka Cluster Operations Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(managed_services_api_worker_kafka_duration_bucket{job=\"managed-services-api-metrics\",namespace=\"managed-services-stage\",jobType=\"kafka_create\"}[5m])) by (le))",
     "legendFormat": "p99-create"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(managed_services_api_worker_kafka_duration_bucket{job=\"managed-services-api-metrics\",namespace=\"managed-services-stage\",jobType=\"kafka_create\"}[5m])) by (le))",
     "legendFormat": "p90-create"
    }
   ]
  },
  {
   "title": "SLO - Availability (99%) ",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(haproxy_backend_http_responses_total{route=\"managed-services-api\",exported_namespace=\"managed-services-stage\",code!=\"5xx\"}[$__range]))/sum(rate(haproxy_backend_http_responses_total{route=\"managed-services-api\",exported_namespace=\"managed-services-stage\"}[$__range]))) * 100",
     "legendFormat": "Create Operation"
    }
   ]
  },
  {
   "title": "SLO - Latency p99 < 2s",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(rate(api_inbound_request_duration_bucket{job=\"managed-services-api-metrics\",namespace=\"managed-services-stage\",le=\"2\",code!~\"5..\"}[$__range]))/sum(rate(api_inbound_request_duration_count{job=\"managed-services-api-metrics\",namespace=\"managed-services-stage\"}[$__range]))) * 100"
    }
   ]
  },
  {
   "title": "SLO - Latency p90 < 1s",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(rate(api_inbound_request_duration_bucket{job=\"managed-services-api-metrics\",namespace=\"managed-services-stage\",le=\"1\",code!~\"5..\"}[$__range]))/sum(rate(api_inbound_request_duration_count{job=\"managed-services-api-metrics\",namespace=\"managed-services-stage\"}[$__range]))) * 100"
    }
   ]
  },
  {
   "title": "SLO - Kafka Correctness  (Create)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(rate(managed_services_api_kafka_operations_success_count{job=\"managed-services-api-metrics\",namespace=\"managed-services-stage\",operation=\"create\"}[$__range]))/sum(rate(managed_services_api_kafka_operations_total_count{job=\"managed-services-api-metrics\",namespace=\"managed-services-stage\",operation=\"create\"}[$__range]))) * 100",
     "legendFormat": "Create Operation"
    }
   ]
  },
  {
   "title": "SLO - Kafka Correctness  (Delete)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(rate(managed_services_api_kafka_operations_success_count{job=\"managed-services-api-metrics\",namespace=\"managed-services-stage\",operation=\"delete\"}[$__range]))/sum(rate(managed_services_api_kafka_operations_total_count{job=\"managed-services-api-metrics\",namespace=\"managed-services-stage\",operation=\"delete\"}[$__range]))) * 100",
     "legendFormat": "Create Operation"
    }
   ]
  },
  {
   "title": "SLO - Kafka Latency p99 < 3600s",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(rate(managed_services_api_worker_kafka_duration_bucket{job=\"managed-services-api-metrics\",namespace=\"managed-services-stage\",le=\"3600\",jobType=\"kafka_create\"}[$__range]))/sum(rate(managed_services_api_worker_kafka_duration_count{job=\"managed-services-api-metrics\",namespace=\"managed-services-stage\",jobType=\"kafka_create\"}[$__range]))) * 100",
     "legendFormat": "Create Operation"
    }
   ]
  },
  {
   "title": "SLO - Kafka Latency p90 < 300s",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(rate(managed_services_api_worker_kafka_duration_bucket{job=\"managed-services-api-metrics\",namespace=\"managed-services-stage\",le=\"300\",jobType=\"kafka_create\"}[$__range]))/sum(rate(managed_services_api_worker_kafka_duration_count{job=\"managed-services-api-metrics\",namespace=\"managed-services-stage\",jobType=\"kafka_create\"}[$__range]))) * 100",
     "legendFormat": "Create Operation"
    }
   ]
  },
  {
   "title": "OSD Cluster Operations Correctness",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(managed_services_api_cluster_operations_success_count{job=\"managed-services-api-metrics\",namespace=\"managed-services-stage\",operation=\"create\"}[5m]))/sum(rate(managed_services_api_cluster_operations_total_count{job=\"managed-services-api-metrics\",namespace=\"managed-services-stage\",operation=\"create\"}[5m]))",
     "legendFormat": "Create Operation"
    }
   ]
  },
  {
   "title": "OSD Cluster Operations Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(managed_services_api_worker_cluster_duration_bucket{job=\"managed-services-api-metrics\",namespace=\"managed-services-stage\",le=\"3600\",jobType=\"cluster_create\"}[5m])) by (le))",
     "legendFormat": "p99-create"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(managed_services_api_worker_cluster_duration_bucket{job=\"managed-services-api-metrics\",namespace=\"managed-services-stage\",le=\"2400\",jobType=\"cluster_create\"}[5m])) by (le))",
     "legendFormat": "p90-create"
    }
   ]
  }
 ]
}