{
 "title": "Container Vulnerabilities",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(container_vulnerabilities_total,namespace)"
   },
   {
    "name": "saas_context",
    "label": "SaaS Context",
    "query": "label_values(container_vulnerabilities_total{namespace=\"$namespace\"},saas_context)"
   },
   {
    "name": "saas_service",
    "label": "SaaS Service",
    "query": "label_values(container_vulnerabilities_total{namespace=\"$namespace\",saas_context=\"$saas_context\"},saas_service)"
   },
   {
    "name": "container_name",
    "label": "Container Name",
    "query": "label_values(container_vulnerabilities_total{namespace=\"$namespace\",saas_context=\"$saas_context\",saas_service=\"$saas_service\"},container_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Pod Details for ($namespace) $saas_context::$saas_service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Table",
   "type": "table",
   "gridPos": { "h": 7, "w": 22, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "container_vulnerabilities_total{namespace=\"$namespace\",saas_context=\"$saas_context\",saas_service=\"$saas_service\",container_name=\"$container_name\"}"
    }
   ]
  },
  {
   "title": "($namespace) $saas_context::$saas_service [$container_name]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "repeat": "container_name"
  },
  {
   "title": "Defcon1",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "container_vulnerabilities_total{namespace=\"$namespace\",saas_context=\"$saas_context\",saas_service=\"$saas_service\",container_name=\"$container_name\",severity=\"defcon1\"}"
    }
   ]
  },
  {
   "title": "Critical",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "container_vulnerabilities_total{namespace=\"$namespace\",saas_context=\"$saas_context\",saas_service=\"$saas_service\",container_name=\"$container_name\",severity=\"critical\"}"
    }
   ]
  },
  {
   "title": "High",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "container_vulnerabilities_total{namespace=\"$namespace\",saas_context=\"$saas_context\",saas_service=\"$saas_service\",container_name=\"$container_name\",severity=\"high\"}"
    }
   ]
  },
  {
   "title": "Medium",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "container_vulnerabilities_total{namespace=\"$namespace\",saas_context=\"$saas_context\",saas_service=\"$saas_service\",container_name=\"$container_name\",severity=\"medium\"}"
    }
   ]
  },
  {
   "title": "Low",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "container_vulnerabilities_total{namespace=\"$namespace\",saas_context=\"$saas_context\",saas_service=\"$saas_service\",container_name=\"$container_name\",severity=\"low\"}"
    }
   ]
  },
  {
   "title": "Negligible",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "container_vulnerabilities_total{namespace=\"$namespace\",saas_context=\"$saas_context\",saas_service=\"$saas_service\",container_name=\"$container_name\",severity=\"negligible\"}"
    }
   ]
  },
  {
   "title": "Unknown",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "container_vulnerabilities_total{namespace=\"$namespace\",saas_context=\"$saas_context\",saas_service=\"$saas_service\",container_name=\"$container_name\",severity=\"unknown\"}"
    }
   ]
  }
 ]
}