{
 "title": "Telemeter Canary Deployment",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_pod_info, namespace)"
   }
  ]
 },
 "panels": [
  { "title": "All Handlers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests (Canary)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (code) (rate(http_requests_total{job=\"telemeter-server\",namespace=\"$namespace\",pod=~\"telemeter-server-canary-\\\\d\"}[5m]))",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "Errors (Canary)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"telemeter-server\",namespace=\"$namespace\",pod=~\"telemeter-server-canary-\\\\d\",code=~\"5..\"}[5m]))\n/\nsum(rate(http_requests_total{job=\"telemeter-server\",namespace=\"$namespace\",pod=~\"telemeter-server-canary-\\\\d\"}[5m]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Duration (Canary)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(http_request_duration_seconds_bucket{job=\"telemeter-server\",namespace=\"$namespace\",pod=~\"telemeter-server-canary-\\\\d\",code!~\"5..\"}[5m])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le) (rate(http_request_duration_seconds_bucket{job=\"telemeter-server\",namespace=\"$namespace\",pod=~\"telemeter-server-canary-\\\\d\",code!~\"5..\"}[5m])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le) (rate(http_request_duration_seconds_bucket{job=\"telemeter-server\",namespace=\"$namespace\",pod=~\"telemeter-server-canary-\\\\d\",code!~\"5..\"}[5m])))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (code) (rate(http_requests_total{job=\"telemeter-server\",namespace=\"$namespace\",pod=~\"telemeter-server-\\\\d\"}[5m]))",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"telemeter-server\",namespace=\"$namespace\",pod=~\"telemeter-server-\\\\d\",code=~\"5..\"}[5m]))\n/\nsum(rate(http_requests_total{job=\"telemeter-server\",namespace=\"$namespace\",pod=~\"telemeter-server-\\\\d\"}[5m]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(http_request_duration_seconds_bucket{job=\"telemeter-server\",namespace=\"$namespace\",pod=~\"telemeter-server-\\\\d\",code!~\"5..\"}[5m])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le) (rate(http_request_duration_seconds_bucket{job=\"telemeter-server\",namespace=\"$namespace\",pod=~\"telemeter-server-\\\\d\",code!~\"5..\"}[5m])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le) (rate(http_request_duration_seconds_bucket{job=\"telemeter-server\",namespace=\"$namespace\",pod=~\"telemeter-server-\\\\d\",code!~\"5..\"}[5m])))",
     "legendFormat": "p50"
    }
   ]
  }
 ]
}