{
 "title": "Openshift Dedicated Adoption",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Cluster Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "count(cluster_admin_enabled)" }
   ]
  },
  { "title": "Identity Provider", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Github",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(identity_provider{provider=\"GitHub\"})"
    }
   ]
  },
  {
   "title": "GitLab",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(identity_provider{provider=\"GitLab\"})"
    }
   ]
  },
  {
   "title": "LDAP",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(identity_provider{provider=\"LDAP\"})"
    }
   ]
  },
  {
   "title": "HTPasswd",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(identity_provider{provider=\"HTPasswd\"})"
    }
   ]
  },
  {
   "title": "OpenID",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(identity_provider{provider=\"OpenID\"})"
    }
   ]
  },
  {
   "title": "BasicAuth",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(identity_provider{provider=\"BasicAuth\"})"
    }
   ]
  },
  {
   "title": "RequestHeader",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(identity_provider{provider=\"RequestHeader\"})"
    }
   ]
  },
  {
   "title": "Google",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(identity_provider{provider=\"Google\"})"
    }
   ]
  },
  { "title": "Cluster Admin", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Cluster Admin",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(cluster_admin_enabled)" }
   ]
  }
 ]
}