{
 "title": "Ephemeral Cluster Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Master Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(cluster:master_nodes)" }
   ]
  },
  {
   "title": "CPU Usage (Current)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(instance:node_cpu:rate:sum) / sum(instance:node_num_cpu:sum)",
     "legendFormat": "CPU Utilization"
    }
   ]
  },
  {
   "title": "Cluster CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum(instance:node_cpu:rate:sum) / sum(instance:node_num_cpu:sum)",
     "legendFormat": "CPU Utilization"
    }
   ]
  },
  {
   "title": "Memory Usage (Current)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (sum(node_memory_MemAvailable_bytes) / sum(node_memory_MemTotal_bytes))",
     "legendFormat": "Percentage"
    }
   ]
  },
  {
   "title": "Cluster Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (sum(node_memory_MemAvailable_bytes) / sum(node_memory_MemTotal_bytes))",
     "legendFormat": "Memory Utilization"
    }
   ]
  },
  {
   "title": "Infra Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(cluster:infra_nodes)" }
   ]
  },
  {
   "title": "Worker Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(sre:node_workers:count)" }
   ]
  },
  {
   "title": "Total Worker Nodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 2, "y": 8 },
   "targets": [
    { "expr": "sum(sre:node_workers:count)", "legendFormat": "Node Count" }
   ]
  },
  {
   "title": "Operation Rates Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 8 },
   "targets": [
    {
     "expr": "sum by (method) (rate(rest_client_requests_total[1m]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Cluster CPU - Limits / Commitments / Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 2, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * cluster:node_cpu:ratio_rate5m{cluster=\"\"}",
     "legendFormat": "CPU Utilization"
    },
    {
     "expr": "100 * sum(namespace_cpu:kube_pod_container_resource_requests:sum{cluster=\"\"}) / sum(kube_node_status_allocatable{job=\"kube-state-metrics\",resource=\"cpu\",cluster=\"\"})",
     "legendFormat": "CPU Requests Commitment"
    },
    {
     "expr": "(100 * sum(namespace_cpu:kube_pod_container_resource_limits:sum{cluster=\"\"}) / sum(kube_node_status_allocatable{job=\"kube-state-metrics\",resource=\"cpu\",cluster=\"\"}))",
     "legendFormat": "CPU Limits Commitment"
    }
   ]
  },
  {
   "title": "Cluster Memory - Limits / Commitments / Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - sum(:node_memory_MemAvailable_bytes:sum{cluster=\"\"}) / sum(node_memory_MemTotal_bytes{job=\"node-exporter\",cluster=\"\"}))",
     "legendFormat": "Memory Utilization"
    },
    {
     "expr": "100 * sum(namespace_memory:kube_pod_container_resource_requests:sum{cluster=\"\"}) / sum(kube_node_status_allocatable{job=\"kube-state-metrics\",resource=\"memory\",cluster=\"\"})",
     "legendFormat": "Memory Requests Commitment"
    },
    {
     "expr": "100 * sum(namespace_memory:kube_pod_container_resource_limits:sum{cluster=\"\"}) / sum(kube_node_status_allocatable{job=\"kube-state-metrics\",resource=\"memory\",cluster=\"\"})",
     "legendFormat": "Memory Limits Commitment"
    }
   ]
  },
  {
   "title": "CPU Usage By Namespace",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate) by (namespace)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage By Namespace",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"\", container!=\"\"}) by (namespace)"
    }
   ]
  }
 ]
}