{
 "title": "Assisted-Installer Clusters Service",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Total Request Rate By Code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{endpoint=\"assisted-svc\"}[5m])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "500 Codes By Handlers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{endpoint=\"assisted-svc\", code=~\"5.*\"}[10m])) by (handler)",
     "legendFormat": "{{hander}}"
    }
   ]
  },
  {
   "title": "400 Codes By Handlers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 8 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{endpoint=\"assisted-svc\", code=~\"4.*\"}[10m])) by (handler)",
     "legendFormat": "{{hander}}"
    }
   ]
  },
  {
   "title": "Total Request Rate By Handler",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{endpoint=\"assisted-svc\"}[5m])) by (handler)",
     "legendFormat": "{{hander}}"
    }
   ]
  }
 ]
}