{
 "title": "General Overview",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Clusters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Installations results",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(sum(service_assisted_installer_cluster_creations{clusterId=~\".+\"})[$__range:])",
     "legendFormat": "Created clusters"
    },
    {
     "expr": "increase(sum(service_assisted_installer_cluster_installation_started{clusterId=~\".+\"})[$__range:])",
     "legendFormat": "Installation started"
    },
    {
     "expr": "increase(sum(service_assisted_installer_cluster_installation_seconds_count{clusterId=~\".+\", result=\"installed\"})[$__range:])",
     "legendFormat": "Installation completed successfully"
    },
    {
     "expr": "increase(sum(service_assisted_installer_cluster_installation_seconds_count{clusterId=~\".+\", result=\"error\"})[$__range:])",
     "legendFormat": "Installation error"
    },
    {
     "expr": "increase(sum(service_assisted_installer_cluster_installation_seconds_count{clusterId=~\".+\", result=\"canceled\"})[$__range:])",
     "legendFormat": "Installation canceled"
    }
   ]
  },
  {
   "title": "Average Hosts Per Cluster",
   "type": "stat",
   "description": "* _Clusters_: We measure clusters count only for those ever started an install process at least once.\n\n* _Hosts_: We measure hosts count only if those belong to the clusters we measure as described above.",
   "gridPos": { "h": 5, "w": 8, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(sum(service_assisted_installer_cluster_hosts{clusterId=~\".+\"} * on(clusterId) group_left() count by (clusterId)(service_assisted_installer_cluster_installation_started{clusterId=~\".+\"}))[$__range:])",
     "legendFormat": "Hosts"
    },
    {
     "expr": "increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started))[$__range:])",
     "legendFormat": "Clusters"
    },
    {
     "expr": "increase(sum(service_assisted_installer_cluster_hosts{clusterId=~\".+\"} * on(clusterId) group_left() count by (clusterId)(service_assisted_installer_cluster_installation_started{clusterId=~\".+\"}))[$__range:])  / increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started))[$__range:])",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Installations success rate",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{clusterId=~\".+\"})[$__range:])",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Average Install Attempts Per  Cluster",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(sum(service_assisted_installer_cluster_installation_started{clusterId=~\".+\"})[$__range:]) / increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started))[$__range:])",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Creation vs Installation rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "increase(sum(service_assisted_installer_cluster_installation_started{clusterId=~\".+\"})[$__range:])/increase(sum(service_assisted_installer_cluster_creations{clusterId=~\".+\"})[$__range:])"
    }
   ]
  },
  { "title": "Hosts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Average Phases duration (successful)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "s", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "increase(sum by (phase)(service_assisted_installer_host_installation_phase_seconds_sum{clusterId=~\".+\",result=\"Done\"})[$__range:]) / increase(sum by (phase)(service_assisted_installer_host_installation_phase_seconds_count{clusterId=~\".+\",result=\"Done\"})[$__range:])",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Hosts By Vendor",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 12 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(service_assisted_installer_cluster_hosts{vendor=~\".+\",product=~\".+\"}[$__range:])) by (vendor,product)",
     "legendFormat": "{{vendor}} {{product}}"
    }
   ]
  },
  {
   "title": "Hosts failures by role",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "failues", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "increase(sum by (role)(service_assisted_installer_cluster_hosts{clusterId=~\".+\", result=\"Failed\"})[$__range:])",
     "legendFormat": "{{role}}"
    }
   ]
  }
 ]
}