{
 "title": "UHC Account Manager",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": "uhc-integration,uhc-stage,uhc-production"
   },
   { "name": "rds_datasource", "query": "prometheus" },
   {
    "name": "rds_namespace",
    "query": "uhc-acct-mngr-production,uhc-acct-mngr-staging,uhc-acct-mngr-integration,uhc-acct-mngr-integration-v4,uhc-acct-mngr-ssotest01ue1"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "query_result(count_over_time(kube_pod_info{namespace=\"$namespace\",pod=~\"^uhc-acct-mngr-.*$\"}[$__range]))"
   }
  ]
 },
 "panels": [
  {
   "title": "API Overall",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Availability (selected time) ",
     "type": "singlestat",
     "description": "The percentage of time that the API is available (not returning 500 Internal Service Errors).",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",code!~\"5..|0\"}[$__range]))\n/\nsum(increase(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "graph",
     "description": "Number of requests per second by response codes.",
     "gridPos": { "h": 8, "w": 7, "x": 3, "y": 1 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by (code) (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\"}[5m]))",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "description": "The error percentage.",
     "gridPos": { "h": 8, "w": 7, "x": 10, "y": 1 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",code!~\"2..\"}[5m]))\n/\nsum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\"}[5m]))",
       "legendFormat": "non-2xx"
      },
      {
       "expr": "sum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",code!~\"2..|404\"}[5m]))\n/\nsum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\"}[5m]))",
       "legendFormat": "non-2xx and non-404"
      },
      {
       "expr": "sum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",code=~\"5..|0\"}[5m]))\n/\nsum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\"}[5m]))",
       "legendFormat": "5xx and timeout"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "description": "The request duration within which the API have served 99%, 95%, 50% of requests",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 1 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum (increase(api_inbound_request_duration_sum{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",code!~\"5..|0\"}[1m])) /\nsum (increase(api_inbound_request_duration_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",code!~\"5..|0\"}[1m]))",
       "legendFormat": "Avg. response duration (1m)"
      }
     ]
    },
    {
     "title": "Latency (< 1s) ",
     "type": "singlestat",
     "description": "The percentage of time that the API responds within 1 second.",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(api_inbound_request_duration_bucket{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",code!~\"5..|0\",le=\"1\"}[$__range]))\n/\nsum(increase(api_inbound_request_duration_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",code!~\"5..|0\"}[$__range]))"
      }
     ]
    }
   ]
  },
  {
   "title": "/cluster_registrations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Availability (selected time) ",
     "type": "singlestat",
     "description": "The percentage of time that the API is available (not returning 500 Internal Service Errors).",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 2 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/cluster_registrations\",code!~\"5..|0\"}[$__range]))\n/\nsum(increase(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/cluster_registrations\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "graph",
     "description": "Number of requests per second by response codes.",
     "gridPos": { "h": 8, "w": 7, "x": 3, "y": 2 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by (code) (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/cluster_registrations\"}[5m]))",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "description": "The error percentage.",
     "gridPos": { "h": 8, "w": 7, "x": 10, "y": 2 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/cluster_registrations\",code!~\"2..\"}[5m]))\n/\nsum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/cluster_registrations\"}[5m]))",
       "legendFormat": "non-2xx"
      },
      {
       "expr": "sum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/cluster_registrations\",code=\"409\"}[5m]))\n/\nsum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/cluster_registrations\"}[5m]))",
       "legendFormat": "token conflicts"
      },
      {
       "expr": "sum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/cluster_registrations\",code=~\"5..|0\"}[5m]))\n/\nsum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/cluster_registrations\"}[5m]))",
       "legendFormat": "5xx and timeout"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "description": "The request duration within which the API have served 99%, 95%, 50% of requests",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 2 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum (increase(api_inbound_request_duration_sum{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/cluster_registrations\",code!~\"5..|0\"}[1m])) /\nsum (increase(api_inbound_request_duration_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/cluster_registrations\",code!~\"5..|0\"}[1m]))",
       "legendFormat": "Avg. response duration (1m)"
      }
     ]
    },
    {
     "title": "Latency (< 1s) ",
     "type": "singlestat",
     "description": "The percentage of time that the API responds within 1 second.",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(api_inbound_request_duration_bucket{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/cluster_registrations\",code!~\"5..|0\",le=\"1\"}[$__range]))\n/\nsum(increase(api_inbound_request_duration_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/cluster_registrations\",code!~\"5..|0\"}[$__range]))"
      }
     ]
    }
   ]
  },
  {
   "title": "/cluster_authorizations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Availability (selected time) ",
     "type": "singlestat",
     "description": "The percentage of time that the API is available (not returning 500 Internal Service Errors).",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 3 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/cluster_authorizations\",code!~\"5..|0\"}[$__range]))\n/\nsum(increase(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/cluster_authorizations\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "graph",
     "description": "Number of requests per second by response codes.",
     "gridPos": { "h": 8, "w": 7, "x": 3, "y": 3 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by (code) (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/cluster_authorizations\"}[5m]))",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "description": "The error percentage.",
     "gridPos": { "h": 8, "w": 7, "x": 10, "y": 3 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/cluster_authorizations\",code!~\"2..\"}[5m]))\n/\nsum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/cluster_authorizations\"}[5m]))",
       "legendFormat": "non-2xx"
      },
      {
       "expr": "sum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/cluster_authorizations\",code=~\"5..|0\"}[5m]))\n/\nsum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/cluster_authorizations\"}[5m]))",
       "legendFormat": "5xx and timeout"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "description": "The request duration within which the API have served 99%, 95%, 50% of requests",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 3 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum (increase(api_inbound_request_duration_sum{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/cluster_authorizations\",code!~\"5..|0\"}[5m])) /\nsum (increase(api_inbound_request_duration_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/cluster_authorizations\",code!~\"5..|0\"}[5m]))",
       "legendFormat": "Avg. response duration (5m)"
      }
     ]
    },
    {
     "title": "Latency (< 1s) ",
     "type": "singlestat",
     "description": "The percentage of time that the API responds within 1 second.",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 7 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(api_inbound_request_duration_bucket{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/cluster_authorizations\",code!~\"5..|0\",le=\"1\"}[$__range]))\n/\nsum(increase(api_inbound_request_duration_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/cluster_authorizations\",code!~\"5..|0\"}[$__range]))"
      }
     ]
    }
   ]
  },
  {
   "title": "/pull_secrets & /access_token",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Availability (selected time) ",
     "type": "singlestat",
     "description": "The percentage of time that the API is available (not returning 500 Internal Service Errors).",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=~\"/api/accounts_mgmt/v1/(access_token|pull_secrets)\",method=\"POST\",code!~\"5..|0\"}[$__range]))\n/\nsum(increase(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=~\"/api/accounts_mgmt/v1/(access_token|pull_secrets)\",method=\"POST\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "graph",
     "description": "Number of requests per second by response codes.",
     "gridPos": { "h": 8, "w": 7, "x": 3, "y": 4 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by (code) (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=~\"/api/accounts_mgmt/v1/(access_token|pull_secrets)\",method=\"POST\"}[5m]))",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "description": "The error percentage.",
     "gridPos": { "h": 8, "w": 7, "x": 10, "y": 4 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=~\"/api/accounts_mgmt/v1/(access_token|pull_secrets)\",method=\"POST\",code!~\"2..\"}[5m]))\n/\nsum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=~\"/api/accounts_mgmt/v1/(access_token|pull_secrets)\",method=\"POST\"}[5m]))",
       "legendFormat": "non-2xx"
      },
      {
       "expr": "sum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=~\"/api/accounts_mgmt/v1/(access_token|pull_secrets)\",method=\"POST\",code=~\"5..|0\"}[5m]))\n/\nsum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=~\"/api/accounts_mgmt/v1/(access_token|pull_secrets)\",method=\"POST\"}[5m]))",
       "legendFormat": "5xx and timeout"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "description": "The request duration within which the API have served 99%, 95%, 50% of requests",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 4 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum (increase(api_inbound_request_duration_sum{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=~\"/api/accounts_mgmt/v1/(access_token|pull_secrets)\",method=\"POST\",code!~\"5..|0\"}[1m])) /\nsum (increase(api_inbound_request_duration_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=~\"/api/accounts_mgmt/v1/(access_token|pull_secrets)\",method=\"POST\",code!~\"5..|0\"}[1m]))",
       "legendFormat": "Avg. response duration (1m)"
      }
     ]
    },
    {
     "title": "Latency (< 1s) ",
     "type": "singlestat",
     "description": "The percentage of time that the API responds within 1 second.",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(api_inbound_request_duration_bucket{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=~\"/api/accounts_mgmt/v1/(access_token|pull_secrets)\",method=\"POST\",code!~\"5..|0\",le=\"1\"}[$__range]))\n/\nsum(increase(api_inbound_request_duration_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=~\"/api/accounts_mgmt/v1/(access_token|pull_secrets)\",method=\"POST\",code!~\"5..|0\"}[$__range]))"
      }
     ]
    }
   ]
  },
  {
   "title": "/certificates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Availability (selected time) ",
     "type": "singlestat",
     "description": "The percentage of time that the API is available (not returning 500 Internal Service Errors).",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=~\"/api/accounts_mgmt/v1/certificates\",method=\"POST\",code!~\"5..|0\"}[$__range]))\n/\nsum(increase(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=~\"/api/accounts_mgmt/v1/certificates\",method=\"POST\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "graph",
     "description": "Number of requests per second by response codes.",
     "gridPos": { "h": 8, "w": 7, "x": 3, "y": 5 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by (code) (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=~\"/api/accounts_mgmt/v1/certificates\",method=\"POST\"}[5m]))",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "description": "The error percentage.",
     "gridPos": { "h": 8, "w": 7, "x": 10, "y": 5 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=~\"/api/accounts_mgmt/v1/certificates\",method=\"POST\",code!~\"2..\"}[5m]))\n/\nsum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=~\"/api/accounts_mgmt/v1/certificates\",method=\"POST\"}[5m]))",
       "legendFormat": "non-2xx"
      },
      {
       "expr": "sum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=~\"/api/accounts_mgmt/v1/certificates\",method=\"POST\",code=~\"5..|0\"}[5m]))\n/\nsum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=~\"/api/accounts_mgmt/v1/certificates\",method=\"POST\"}[5m]))",
       "legendFormat": "5xx and timeout"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "description": "The request duration within which the API have served 99%, 95%, 50% of requests",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 5 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum (increase(api_inbound_request_duration_sum{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=~\"/api/accounts_mgmt/v1/certificates\",method=\"POST\",code!~\"5..|0\"}[1m])) /\nsum (increase(api_inbound_request_duration_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=~\"/api/accounts_mgmt/v1/certificates\",method=\"POST\",code!~\"5..|0\"}[1m]))",
       "legendFormat": "Avg. response duration (1m)"
      }
     ]
    },
    {
     "title": "Latency (< 1s) ",
     "type": "singlestat",
     "description": "The percentage of time that the API responds within 1 second.",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 9 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(api_inbound_request_duration_bucket{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=~\"/api/accounts_mgmt/v1/certificates\",method=\"POST\",code!~\"5..|0\",le=\"1\"}[$__range]))\n/\nsum(increase(api_inbound_request_duration_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=~\"/api/accounts_mgmt/v1/certificates\",method=\"POST\",code!~\"5..|0\"}[$__range]))"
      }
     ]
    }
   ]
  },
  {
   "title": "/subscriptions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Availability (selected time) ",
     "type": "singlestat",
     "description": "The percentage of time that the API is available (not returning 500 Internal Service Errors).",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/subscriptions\",method=\"GET\",code!~\"5..|0\"}[$__range]))\n/\nsum(increase(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/subscriptions\",method=\"GET\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "graph",
     "description": "Number of requests per second by response codes.",
     "gridPos": { "h": 8, "w": 7, "x": 3, "y": 6 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by (code) (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/subscriptions\",method=\"GET\"}[5m]))",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "description": "The error percentage.",
     "gridPos": { "h": 8, "w": 7, "x": 10, "y": 6 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/subscriptions\",method=\"GET\",code!~\"2..\"}[5m]))\n/\nsum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/subscriptions\",method=\"GET\"}[5m]))",
       "legendFormat": "non-2xx"
      },
      {
       "expr": "sum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/subscriptions\",method=\"GET\",code=~\"5..|0\"}[5m]))\n/\nsum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/subscriptions\",method=\"GET\"}[5m]))",
       "legendFormat": "5xx and timeout"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "description": "The request duration within which the API have served 99%, 95%, 50% of requests",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 6 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum (increase(api_inbound_request_duration_sum{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/subscriptions\",method=\"GET\",code!~\"5..|0\"}[1m])) /\nsum (increase(api_inbound_request_duration_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/subscriptions\",method=\"GET\",code!~\"5..|0\"}[1m]))",
       "legendFormat": "Avg. response duration (1m)"
      }
     ]
    },
    {
     "title": "Latency (< 1s) ",
     "type": "singlestat",
     "description": "The percentage of time that the API responds within 1 second.",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 10 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(api_inbound_request_duration_bucket{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/subscriptions\",method=\"GET\",code!~\"5..|0\",le=\"1\"}[$__range]))\n/\nsum(increase(api_inbound_request_duration_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/subscriptions\",method=\"GET\",code!~\"5..|0\"}[$__range]))"
      }
     ]
    }
   ]
  },
  {
   "title": "/subscriptions/{id}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Availability (selected time) ",
     "type": "singlestat",
     "description": "The percentage of time that the API is available (not returning 500 Internal Service Errors).",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 7 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/subscriptions/-\",method=\"GET\",code!~\"5..|0\"}[$__range]))\n/\nsum(increase(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/subscriptions/-\",method=\"GET\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "graph",
     "description": "Number of requests per second by response codes.",
     "gridPos": { "h": 8, "w": 7, "x": 3, "y": 7 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by (code) (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/subscriptions/-\",method=\"GET\"}[5m]))",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "description": "The error percentage.",
     "gridPos": { "h": 8, "w": 7, "x": 10, "y": 7 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/subscriptions/-\",method=\"GET\",code!~\"2..\"}[5m]))\n/\nsum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/subscriptions/-\",method=\"GET\"}[5m]))",
       "legendFormat": "non-2xx"
      },
      {
       "expr": "sum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/subscriptions/-\",method=\"GET\",code=~\"5..|0\"}[5m]))\n/\nsum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/subscriptions/-\",method=\"GET\"}[5m]))",
       "legendFormat": "5xx and timeout"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "description": "The request duration within which the API have served 99%, 95%, 50% of requests",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 7 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum (increase(api_inbound_request_duration_sum{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/subscriptions/-\",method=\"GET\",code!~\"5..|0\"}[1m])) /\nsum (increase(api_inbound_request_duration_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/subscriptions/-\",method=\"GET\",code!~\"5..|0\"}[1m]))",
       "legendFormat": "Avg. response duration (1m)"
      }
     ]
    },
    {
     "title": "Latency (< 1s) ",
     "type": "singlestat",
     "description": "The percentage of time that the API responds within 1 second.",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 11 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(api_inbound_request_duration_bucket{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/subscriptions/-\",method=\"GET\",code!~\"5..|0\",le=\"1\"}[$__range]))\n/\nsum(increase(api_inbound_request_duration_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/subscriptions/-\",method=\"GET\",code!~\"5..|0\"}[$__range]))"
      }
     ]
    }
   ]
  },
  {
   "title": "/subscriptions/{id} (update)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Availability (selected time) ",
     "type": "singlestat",
     "description": "The percentage of time that the API is available (not returning 500 Internal Service Errors).",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/subscriptions/-\",method=\"PATCH\",code!~\"5..|0\"}[$__range]))\n/\nsum(increase(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/subscriptions/-\",method=\"PATCH\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "graph",
     "description": "Number of requests per second by response codes.",
     "gridPos": { "h": 8, "w": 7, "x": 3, "y": 8 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by (code) (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/subscriptions/-\",method=\"PATCH\"}[5m]))",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "description": "The error percentage.",
     "gridPos": { "h": 8, "w": 7, "x": 10, "y": 8 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/subscriptions/-\",method=\"PATCH\",code!~\"2..\"}[5m]))\n/\nsum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/subscriptions/-\",method=\"PATCH\"}[5m]))",
       "legendFormat": "non-2xx"
      },
      {
       "expr": "sum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/subscriptions/-\",method=\"PATCH\",code=~\"5..|0\"}[5m]))\n/\nsum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/subscriptions/-\",method=\"PATCH\"}[5m]))",
       "legendFormat": "5xx and timeout"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "description": "The request duration within which the API have served 99%, 95%, 50% of requests",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 8 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum (increase(api_inbound_request_duration_sum{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/subscriptions/-\",method=\"PATCH\",code!~\"5..|0\"}[5m])) /\nsum (increase(api_inbound_request_duration_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/subscriptions/-\",method=\"PATCH\",code!~\"5..|0\"}[5m]))",
       "legendFormat": "Avg. response duration (5m)"
      }
     ]
    },
    {
     "title": "Latency (< 1s) ",
     "type": "singlestat",
     "description": "The percentage of time that the API responds within 1 second.",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 12 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(api_inbound_request_duration_bucket{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/subscriptions/-\",method=\"PATCH\",code!~\"5..|0\",le=\"1\"}[$__range]))\n/\nsum(increase(api_inbound_request_duration_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/subscriptions/-\",method=\"PATCH\",code!~\"5..|0\"}[$__range]))"
      }
     ]
    }
   ]
  },
  {
   "title": "/subscriptions (create disconnected)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Availability (selected time) ",
     "type": "singlestat",
     "description": "The percentage of time that the API is available (not returning 500 Internal Service Errors).",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 9 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/subscriptions\",method=\"POST\",code!~\"5..|0\"}[$__range]))\n/\nsum(increase(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/subscriptions\",method=\"POST\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "graph",
     "description": "Number of requests per second by response codes.",
     "gridPos": { "h": 8, "w": 7, "x": 3, "y": 9 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by (code) (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/subscriptions\",method=\"POST\"}[5m]))",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "description": "The error percentage.",
     "gridPos": { "h": 8, "w": 7, "x": 10, "y": 9 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/subscriptions\",method=\"POST\",code!~\"2..\"}[5m]))\n/\nsum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/subscriptions\",method=\"POST\"}[5m]))",
       "legendFormat": "non-2xx"
      },
      {
       "expr": "sum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/subscriptions\",method=\"POST\",code=~\"5..|0\"}[5m]))\n/\nsum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/subscriptions\",method=\"POST\"}[5m]))",
       "legendFormat": "5xx and timeout"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "description": "The request duration within which the API have served 99%, 95%, 50% of requests",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 9 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum (increase(api_inbound_request_duration_sum{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/subscriptions\",method=\"POST\",code!~\"5..|0\"}[5m])) /\nsum (increase(api_inbound_request_duration_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/subscriptions\",method=\"POST\",code!~\"5..|0\"}[5m]))",
       "legendFormat": "Avg. response duration (5m)"
      }
     ]
    },
    {
     "title": "Latency (< 1s) ",
     "type": "singlestat",
     "description": "The percentage of time that the API responds within 1 second.",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 13 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(api_inbound_request_duration_bucket{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/subscriptions\",method=\"POST\",code!~\"5..|0\",le=\"1\"}[$__range]))\n/\nsum(increase(api_inbound_request_duration_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/subscriptions\",method=\"POST\",code!~\"5..|0\"}[$__range]))"
      }
     ]
    }
   ]
  },
  {
   "title": "/token_authorization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Availability (selected time) ",
     "type": "singlestat",
     "description": "The percentage of time that the API is available (not returning 500 Internal Service Errors).",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 10 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/token_authorization\",method=\"POST\",code!~\"5..|0\"}[$__range]))\n/\nsum(increase(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/token_authorization\",method=\"POST\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "graph",
     "description": "Number of requests per second by response codes.",
     "gridPos": { "h": 8, "w": 7, "x": 3, "y": 10 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by (code) (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/token_authorization\",method=\"POST\"}[5m]))",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "description": "The error percentage.",
     "gridPos": { "h": 8, "w": 7, "x": 10, "y": 10 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/token_authorization\",method=\"POST\",code!~\"2..\"}[5m]))\n/\nsum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/token_authorization\",method=\"POST\"}[5m]))",
       "legendFormat": "non-2xx"
      },
      {
       "expr": "sum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/token_authorization\",method=\"POST\",code=~\"5..|0\"}[5m]))\n/\nsum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/token_authorization\",method=\"POST\"}[5m]))",
       "legendFormat": "5xx and timeout"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "description": "The request duration within which the API have served 99%, 95%, 50% of requests",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 10 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum (increase(api_inbound_request_duration_sum{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/token_authorization\",method=\"POST\",code!~\"5..|0\"}[1m])) /\nsum (increase(api_inbound_request_duration_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/token_authorization\",method=\"POST\",code!~\"5..|0\"}[1m]))",
       "legendFormat": "Avg. response duration (1m)"
      }
     ]
    },
    {
     "title": "Latency (< 1s) ",
     "type": "singlestat",
     "description": "The percentage of time that the API responds within 1 second.",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 14 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(api_inbound_request_duration_bucket{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/token_authorization\",method=\"POST\",code!~\"5..|0\",le=\"1\"}[$__range]))\n/\nsum(increase(api_inbound_request_duration_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",path=\"/api/accounts_mgmt/v1/token_authorization\",method=\"POST\",code!~\"5..|0\"}[$__range]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Registry Credential Pool Size",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "quay.io",
     "type": "singlestat",
     "description": "Number of free registry credentials in the pool.",
     "gridPos": { "h": 8, "w": 3, "x": 0, "y": 11 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (reg_cred_pool_size{registry=\"quay.io\"}) / scalar(count(count by (pod) (reg_cred_pool_size{registry=\"quay.io\"})))"
      }
     ]
    },
    {
     "title": "redhat",
     "type": "singlestat",
     "description": "Number of free registry credentials in the pool.",
     "gridPos": { "h": 8, "w": 3, "x": 3, "y": 11 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (reg_cred_pool_size{registry=~\"registry.redhat.io|registry.connect.redhat.com\"}) / scalar(count(count by (pod) (reg_cred_pool_size{registry=~\"registry.redhat.io|registry.connect.redhat.com\"})))"
      }
     ]
    },
    {
     "title": "Registry Credential Pool Size",
     "type": "graph",
     "description": "The pool size for each registry.",
     "gridPos": { "h": 8, "w": 18, "x": 6, "y": 11 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum by(registry) (reg_cred_pool_size) / scalar(count(count by (pod) (reg_cred_pool_size)))",
       "legendFormat": "{{registry}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Dependencies: Overall",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Availability (selected time) ",
     "type": "singlestat",
     "description": "The percentage of time that the API is available (not returning 500 Internal Service Errors).",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 12 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(api_outbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",code!~\"5..|0\"}[$__range]))\n/\nsum(increase(api_outbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "graph",
     "description": "Number of requests per second by response codes.",
     "gridPos": { "h": 8, "w": 7, "x": 3, "y": 12 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by (apiservice) (rate(api_outbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\"}[5m]))",
       "legendFormat": "{{apiservice}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "description": "The error percentage.",
     "gridPos": { "h": 8, "w": 7, "x": 10, "y": 12 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum (rate(api_outbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",code!~\"2..\"}[5m]))\n/\nsum (rate(api_outbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\"}[5m]))",
       "legendFormat": "non-2xx"
      },
      {
       "expr": "sum (rate(api_outbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",code=~\"5..|0\"}[5m]))\n/\nsum (rate(api_outbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\"}[5m]))",
       "legendFormat": "5xx and timeout"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "description": "The request duration within which the API have served 99%, 95%, 50% of requests",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 12 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum (increase(api_outbound_request_duration_sum{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",code!~\"5..|0\"}[1m])) /\nsum (increase(api_outbound_request_duration_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",code!~\"5..|0\"}[1m]))",
       "legendFormat": "Avg. response duration (1m)"
      }
     ]
    },
    {
     "title": "Latency (< 1s) ",
     "type": "singlestat",
     "description": "The percentage of time that the API responds within 1 second.",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 16 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(api_outbound_request_duration_bucket{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",code!~\"5..|0\",le=\"1\"}[$__range]))\n/\nsum(increase(api_outbound_request_duration_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",code!~\"5..|0\"}[$__range]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Dependencies: Quay",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Availability (selected time) ",
     "type": "singlestat",
     "description": "The percentage of time that the API is available (not returning 500 Internal Service Errors).",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 13 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(api_outbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"quay\",code!~\"5..|0\"}[$__range]))\n/\nsum(increase(api_outbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"quay\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "graph",
     "description": "Number of requests per second by response codes.",
     "gridPos": { "h": 8, "w": 7, "x": 3, "y": 13 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by (code) (rate(api_outbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"quay\"}[5m]))",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "description": "The error percentage.",
     "gridPos": { "h": 8, "w": 7, "x": 10, "y": 13 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum (rate(api_outbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"quay\",code!~\"2..\"}[5m]))\n/\nsum (rate(api_outbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"quay\"}[5m]))",
       "legendFormat": "non-2xx"
      },
      {
       "expr": "sum (rate(api_outbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"quay\",code=~\"5..|0\"}[5m]))\n/\nsum (rate(api_outbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"quay\"}[5m]))",
       "legendFormat": "5xx and timeout"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "description": "The request duration within which the API have served 99%, 95%, 50% of requests",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 13 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum (increase(api_outbound_request_duration_sum{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"quay\",code!~\"5..|0\"}[5m])) /\nsum (increase(api_outbound_request_duration_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"quay\",code!~\"5..|0\"}[5m]))",
       "legendFormat": "Avg. response duration (5m)"
      }
     ]
    },
    {
     "title": "Latency (< 1s) ",
     "type": "singlestat",
     "description": "The percentage of time that the API responds within 1 second.",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 17 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(api_outbound_request_duration_bucket{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"quay\",code!~\"5..|0\",le=\"1\"}[$__range]))\n/\nsum(increase(api_outbound_request_duration_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"quay\",code!~\"5..|0\"}[$__range]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Dependencies: RHIT",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Availability (selected time) ",
     "type": "singlestat",
     "description": "The percentage of time that the API is available (not returning 500 Internal Service Errors).",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 14 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(api_outbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"rhit\",code!~\"5..|0\"}[$__range]))\n/\nsum(increase(api_outbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"rhit\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "graph",
     "description": "Number of requests per second by response codes.",
     "gridPos": { "h": 8, "w": 7, "x": 3, "y": 14 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by (code) (rate(api_outbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"rhit\"}[5m]))",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "description": "The error percentage.",
     "gridPos": { "h": 8, "w": 7, "x": 10, "y": 14 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum (rate(api_outbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"rhit\",code!~\"2..\"}[5m]))\n/\nsum (rate(api_outbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"rhit\"}[5m]))",
       "legendFormat": "non-2xx"
      },
      {
       "expr": "sum (rate(api_outbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"rhit\",code=~\"5..|0\"}[5m]))\n/\nsum (rate(api_outbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"rhit\"}[5m]))",
       "legendFormat": "5xx and timeout"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "description": "The request duration within which the API have served 99%, 95%, 50% of requests",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 14 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum (increase(api_outbound_request_duration_sum{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"rhit\",code!~\"5..|0\"}[1m])) /\nsum (increase(api_outbound_request_duration_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"rhit\",code!~\"5..|0\"}[1m]))",
       "legendFormat": "Avg. response duration (1m)"
      }
     ]
    },
    {
     "title": "Latency (< 1s) ",
     "type": "singlestat",
     "description": "The percentage of time that the API responds within 1 second.",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 18 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(api_outbound_request_duration_bucket{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"rhit\",code!~\"5..|0\",le=\"1\"}[$__range]))\n/\nsum(increase(api_outbound_request_duration_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"rhit\",code!~\"5..|0\"}[$__range]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Dependencies: Terms and Conditions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Availability (selected time) ",
     "type": "singlestat",
     "description": "The percentage of time that the API is available (not returning 500 Internal Service Errors).",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 15 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(api_outbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"rhit/terms\",code!~\"5..|0\"}[$__range]))\n/\nsum(increase(api_outbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"rhit/terms\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "graph",
     "description": "Number of requests per second by response codes.",
     "gridPos": { "h": 8, "w": 7, "x": 3, "y": 15 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by (code) (rate(api_outbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"rhit/terms\"}[5m]))",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "description": "The error percentage.",
     "gridPos": { "h": 8, "w": 7, "x": 10, "y": 15 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum (rate(api_outbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"rhit/terms\",code!~\"2..\"}[5m]))\n/\nsum (rate(api_outbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"rhit/terms\"}[5m]))",
       "legendFormat": "non-2xx"
      },
      {
       "expr": "sum (rate(api_outbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"rhit/terms\",code=~\"5..|0\"}[5m]))\n/\nsum (rate(api_outbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"rhit/terms\"}[5m]))",
       "legendFormat": "5xx and timeout"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "description": "The request duration within which the API have served 99%, 95%, 50% of requests",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 15 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum (increase(api_outbound_request_duration_sum{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"rhit/terms\",code!~\"5..|0\"}[1m])) /\nsum (increase(api_outbound_request_duration_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"rhit/terms\",code!~\"5..|0\"}[1m]))",
       "legendFormat": "Avg. response duration (1m)"
      }
     ]
    },
    {
     "title": "Latency (< 1s) ",
     "type": "singlestat",
     "description": "The percentage of time that the API responds within 1 second.",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 19 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(api_outbound_request_duration_bucket{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"rhit/terms\",code!~\"5..|0\",le=\"1\"}[$__range]))\n/\nsum(increase(api_outbound_request_duration_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"rhit/terms\",code!~\"5..|0\"}[$__range]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Dependencies: Clusters Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Availability (selected time) ",
     "type": "singlestat",
     "description": "The percentage of time that the API is available (not returning 500 Internal Service Errors).",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 16 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(api_outbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"ocm-clusters-service\",code!~\"5..|0\"}[$__range]))\n/\nsum(increase(api_outbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"ocm-clusters-service\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "graph",
     "description": "Number of requests per second by response codes.",
     "gridPos": { "h": 8, "w": 7, "x": 3, "y": 16 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by (code) (rate(api_outbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"ocm-clusters-service\"}[5m]))",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "description": "The error percentage.",
     "gridPos": { "h": 8, "w": 7, "x": 10, "y": 16 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum (rate(api_outbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"ocm-clusters-service\",code!~\"2..\"}[5m]))\n/\nsum (rate(api_outbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"ocm-clusters-service\"}[5m]))",
       "legendFormat": "non-2xx"
      },
      {
       "expr": "sum (rate(api_outbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"ocm-clusters-service\",code=~\"5..|0\"}[5m]))\n/\nsum (rate(api_outbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"ocm-clusters-service\"}[5m]))",
       "legendFormat": "5xx and timeout"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "description": "The request duration within which the API have served 99%, 95%, 50% of requests",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 16 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum (increase(api_outbound_request_duration_sum{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"ocm-clusters-service\",code!~\"5..|0\"}[1m])) /\nsum (increase(api_outbound_request_duration_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"ocm-clusters-service\",code!~\"5..|0\"}[1m]))",
       "legendFormat": "Avg. response duration (1m)"
      }
     ]
    },
    {
     "title": "Latency (< 1s) ",
     "type": "singlestat",
     "description": "The percentage of time that the API responds within 1 second.",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 20 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(api_outbound_request_duration_bucket{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"ocm-clusters-service\",code!~\"5..|0\",le=\"1\"}[$__range]))\n/\nsum(increase(api_outbound_request_duration_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"ocm-clusters-service\",code!~\"5..|0\"}[$__range]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Dependencies: Logs Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Availability (selected time) ",
     "type": "singlestat",
     "description": "The percentage of time that the API is available (not returning 500 Internal Service Errors).",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 17 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(api_outbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"ocm-logs-service\",code!~\"5..|0\"}[$__range]))\n/\nsum(increase(api_outbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"ocm-logs-service\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "graph",
     "description": "Number of requests per second by response codes.",
     "gridPos": { "h": 8, "w": 7, "x": 3, "y": 17 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by (code) (rate(api_outbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"ocm-logs-service\"}[5m]))",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "description": "The error percentage.",
     "gridPos": { "h": 8, "w": 7, "x": 10, "y": 17 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum (rate(api_outbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"ocm-logs-service\",code!~\"2..\"}[5m]))\n/\nsum (rate(api_outbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"ocm-logs-service\"}[5m]))",
       "legendFormat": "non-2xx"
      },
      {
       "expr": "sum (rate(api_outbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"ocm-logs-service\",code=~\"5..|0\"}[5m]))\n/\nsum (rate(api_outbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"ocm-logs-service\"}[5m]))",
       "legendFormat": "5xx and timeout"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "description": "The request duration within which the API have served 99%, 95%, 50% of requests",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 17 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum (increase(api_outbound_request_duration_sum{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"ocm-logs-service\",code!~\"5..|0\"}[1m])) /\nsum (increase(api_outbound_request_duration_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"ocm-logs-service\",code!~\"5..|0\"}[1m]))",
       "legendFormat": "Avg. response duration (1m)"
      }
     ]
    },
    {
     "title": "Latency (< 1s) ",
     "type": "singlestat",
     "description": "The percentage of time that the API responds within 1 second.",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 21 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(api_outbound_request_duration_bucket{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"ocm-logs-service\",code!~\"5..|0\",le=\"1\"}[$__range]))\n/\nsum(increase(api_outbound_request_duration_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"ocm-logs-service\",code!~\"5..|0\"}[$__range]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Dependencies: Pendo",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Availability (selected time) ",
     "type": "singlestat",
     "description": "The percentage of time that the API is available (not returning 500 Internal Service Errors).",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 18 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(api_outbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"pendo\",code!~\"5..|0\"}[$__range]))\n/\nsum(increase(api_outbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"pendo\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "graph",
     "description": "Number of requests per second by response codes.",
     "gridPos": { "h": 8, "w": 7, "x": 3, "y": 18 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by (code) (rate(api_outbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"pendo\"}[5m]))",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "description": "The error percentage.",
     "gridPos": { "h": 8, "w": 7, "x": 10, "y": 18 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum (rate(api_outbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"pendo\",code!~\"2..\"}[5m]))\n/\nsum (rate(api_outbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"pendo\"}[5m]))",
       "legendFormat": "non-2xx"
      },
      {
       "expr": "sum (rate(api_outbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"pendo\",code=~\"5..|0\"}[5m]))\n/\nsum (rate(api_outbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"pendo\"}[5m]))",
       "legendFormat": "5xx and timeout"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "description": "The request duration within which the API have served 99%, 95%, 50% of requests",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 18 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum (increase(api_outbound_request_duration_sum{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"pendo\",code!~\"5..|0\"}[1m])) /\nsum (increase(api_outbound_request_duration_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"pendo\",code!~\"5..|0\"}[1m]))",
       "legendFormat": "Avg. response duration (1m)"
      }
     ]
    },
    {
     "title": "Latency (< 1s) ",
     "type": "singlestat",
     "description": "The percentage of time that the API responds within 1 second.",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 22 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(api_outbound_request_duration_bucket{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"pendo\",code!~\"5..|0\",le=\"1\"}[$__range]))\n/\nsum(increase(api_outbound_request_duration_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"pendo\",code!~\"5..|0\"}[$__range]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Dependencies: Candlepin",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Availability (selected time) ",
     "type": "singlestat",
     "description": "The percentage of time that the API is available (not returning 500 Internal Service Errors).",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 19 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(api_outbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"candlepin\",code!~\"5..|0\"}[$__range]))\n/\nsum(increase(api_outbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"candlepin\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "graph",
     "description": "Number of requests per second by response codes.",
     "gridPos": { "h": 8, "w": 7, "x": 3, "y": 19 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by (code) (rate(api_outbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"candlepin\"}[5m]))",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "description": "The error percentage.",
     "gridPos": { "h": 8, "w": 7, "x": 10, "y": 19 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum (rate(api_outbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"candlepin\",code!~\"2..\"}[5m]))\n/\nsum (rate(api_outbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"candlepin\"}[5m]))",
       "legendFormat": "non-2xx"
      },
      {
       "expr": "sum (rate(api_outbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"candlepin\",code=~\"5..|0\"}[5m]))\n/\nsum (rate(api_outbound_request_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"candlepin\"}[5m]))",
       "legendFormat": "5xx and timeout"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "description": "The request duration within which the API have served 99%, 95%, 50% of requests",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 19 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum (increase(api_outbound_request_duration_sum{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"candlepin\",code!~\"5..|0\"}[5m])) /\nsum (increase(api_outbound_request_duration_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"candlepin\",code!~\"5..|0\"}[5m]))",
       "legendFormat": "Avg. response duration (5m)"
      }
     ]
    },
    {
     "title": "Latency (< 1s) ",
     "type": "singlestat",
     "description": "The percentage of time that the API responds within 1 second.",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 23 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(api_outbound_request_duration_bucket{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"candlepin\",code!~\"5..|0\",le=\"1\"}[$__range]))\n/\nsum(increase(api_outbound_request_duration_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",apiservice=\"candlepin\",code!~\"5..|0\"}[$__range]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Database: Disk usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Free Space Availability",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "1 - avg(avg_over_time(db_table_size{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",type=\"data\",table=\"whole db\"}[24h])) / (28 * 1024)"
      }
     ]
    },
    {
     "title": "Total Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 19, "x": 5, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(db_table_size{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",type=\"data\",table=\"whole db\"})",
       "legendFormat": "{{table}}"
      }
     ]
    },
    {
     "title": "Table Size (KB)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "db_table_size{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",type=\"data\",table!=\"whole db\"}",
       "legendFormat": "{{table}}"
      }
     ]
    },
    {
     "title": "Index Size (KB)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(1, db_table_size{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",type=\"index\"}) by (table)",
       "legendFormat": "{{table}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Envoy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Envoy Request Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(envoy_cluster_upstream_rq_total{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics-envoy\",envoy_cluster_name=\"backend\",pod=~\"$pod\"}[10m]))",
       "legendFormat": "Inbound"
      },
      {
       "expr": "sum(rate(envoy_cluster_upstream_rq_total{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics-envoy\",envoy_cluster_name=\"clusters_mgmt\",pod=~\"$pod\"}[10m]))",
       "legendFormat": "Outbound - clusters_mgmt"
      },
      {
       "expr": "sum(rate(envoy_cluster_upstream_rq_total{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics-envoy\",envoy_cluster_name=\"authorizations\",pod=~\"$pod\"}[10m]))",
       "legendFormat": "Outbound - authorizations"
      },
      {
       "expr": "sum(rate(envoy_cluster_upstream_rq_total{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics-envoy\",envoy_cluster_name=\"service_logs\",pod=~\"$pod\"}[10m]))",
       "legendFormat": "Outbound - service_logs"
      }
     ]
    },
    {
     "title": "Envoy Request Duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(rate(envoy_cluster_upstream_rq_time_sum{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics-envoy\",envoy_cluster_name=\"backend\",pod=~\"$pod\"}[10m])) /\nsum(rate(envoy_cluster_upstream_rq_time_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics-envoy\",envoy_cluster_name=\"backend\",pod=~\"$pod\"}[10m]))",
       "legendFormat": "Inbound"
      },
      {
       "expr": "sum(rate(envoy_cluster_upstream_rq_time_sum{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics-envoy\",envoy_cluster_name=\"authorizations\",pod=~\"$pod\"}[10m])) /\nsum(rate(envoy_cluster_upstream_rq_time_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics-envoy\",envoy_cluster_name=\"authorizations\",pod=~\"$pod\"}[10m]))",
       "legendFormat": "Outbound - authorizations"
      },
      {
       "expr": "sum(rate(envoy_cluster_upstream_rq_time_sum{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics-envoy\",envoy_cluster_name=\"clusters_mgmt\",pod=~\"$pod\"}[10m])) /\nsum(rate(envoy_cluster_upstream_rq_time_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics-envoy\",envoy_cluster_name=\"clusters_mgmt\",pod=~\"$pod\"}[10m]))",
       "legendFormat": "Outbound - clusters_mgmt"
      },
      {
       "expr": "sum(rate(envoy_cluster_upstream_rq_time_sum{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics-envoy\",envoy_cluster_name=\"service_logs\",pod=~\"$pod\"}[10m])) /\nsum(rate(envoy_cluster_upstream_rq_time_count{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics-envoy\",envoy_cluster_name=\"service_logs\",pod=~\"$pod\"}[10m]))",
       "legendFormat": "Outbound - service_logs"
      }
     ]
    },
    {
     "title": "Envoy Inbound Codes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(envoy_cluster_upstream_rq{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics-envoy\",envoy_cluster_name=\"backend\",pod=~\"$pod\"}[10m])) by (envoy_response_code)",
       "legendFormat": "{{envoy_response_code}}"
      }
     ]
    },
    {
     "title": "Envoy Outbound Codes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(envoy_cluster_upstream_rq{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics-envoy\",envoy_cluster_name=~\"^(clusters_mgmt|authorizations|service_logs)$\",pod=~\"$pod\"}[10m])) by (envoy_response_code)",
       "legendFormat": "{{envoy_response_code}}"
      }
     ]
    },
    {
     "title": "Envoy CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "mc" }
     ],
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",pod=~\"^uhc-acct-mngr-.*$\",container=\"envoy\",pod=~\"$pod\"}[5m]) * 1000",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\",pod=~\"^uhc-acct-mngr-.*$\",container=\"envoy\"}) * 1000",
       "legendFormat": "Limit"
      },
      {
       "expr": "max(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\",pod=~\"^uhc-acct-mngr-.*$\",container=\"envoy\"}) * 1000",
       "legendFormat": "Request"
      }
     ]
    },
    {
     "title": "Envoy Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{namespace=\"$namespace\",pod=~\"^uhc-acct-mngr-.*\",container=\"envoy\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\",pod=~\"^uhc-acct-mngr-.*$\",container=\"envoy\"})",
       "legendFormat": "Request"
      },
      {
       "expr": "max(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\",pod=~\"^uhc-acct-mngr-.*$\",container=\"envoy\"})",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Envoy Network",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
     "yaxes": [
      { "format": "binbps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\",pod=~\"^uhc-acct-mngr-.*\",interface=\"eth0\"}[10m]))",
       "legendFormat": "Receive"
      },
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\",pod=~\"^uhc-acct-mngr-.*\",interface=\"eth0\"}[10m]))",
       "legendFormat": "Transmit"
      }
     ]
    }
   ]
  },
  {
   "title": "Database: Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connections",
     "type": "singlestat",
     "description": "The number of connections (idle + active).",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 20 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "max without(pod,instance) (aws_rds_database_connections_average{dbinstance_identifier=\"$rds_namespace\"})"
      }
     ]
    },
    {
     "title": "Connections",
     "type": "graph",
     "description": "The number of connections (idle + active).",
     "gridPos": { "h": 8, "w": 7, "x": 3, "y": 20 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "max without(pod,instance) (aws_rds_database_connections_average{dbinstance_identifier=\"$rds_namespace\"})",
       "legendFormat": "{{dbinstance_identifier}}"
      }
     ]
    },
    {
     "title": "Free Space",
     "type": "graph",
     "description": "The amount of available storage space.",
     "gridPos": { "h": 8, "w": 7, "x": 10, "y": 20 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "max without(pod,instance) (aws_rds_free_storage_space_average{dbinstance_identifier=\"$rds_namespace\"})",
       "legendFormat": "{{dbinstance_identifier}}"
      }
     ]
    },
    {
     "title": "Used Space by All Tables",
     "type": "graph",
     "description": "The amount of used storage space by all tables. This excludes space of the operational overhead.",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 20 },
     "yaxes": [
      { "format": "mbytes" }
     ],
     "targets": [
      {
       "expr": "max without(pod,instance) (db_table_size{namespace=\"$namespace\",service=\"uhc-acct-mngr-metrics\",table=\"whole db\"})",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Free Space",
     "type": "singlestat",
     "description": "The amount of available storage space.",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 24 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "max without(pod,instance) (aws_rds_free_storage_space_average{dbinstance_identifier=\"$rds_namespace\"})"
      }
     ]
    },
    {
     "title": "Free Space Change (selected time)",
     "type": "singlestat",
     "description": "The change of free space during the selected time range.",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 28 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "max without(pod,instance) (aws_rds_free_storage_space_average{dbinstance_identifier=\"$rds_namespace\"}) - max without(pod,instance) (aws_rds_free_storage_space_average{dbinstance_identifier=\"$rds_namespace\"} offset $__range)"
      }
     ]
    },
    {
     "title": "CPU Utilization",
     "type": "graph",
     "description": "The percentage of CPU utilization.",
     "gridPos": { "h": 8, "w": 7, "x": 3, "y": 28 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "max without(pod,instance) (aws_rds_cpuutilization_average{dbinstance_identifier=\"$rds_namespace\"})",
       "legendFormat": "{{dbinstance_identifier}}"
      }
     ]
    },
    {
     "title": "Read/Write IO Rate",
     "type": "graph",
     "description": "The average number of disk read and write I/O operations per second.",
     "gridPos": { "h": 8, "w": 7, "x": 10, "y": 28 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "max without(pod,instance) (aws_rds_read_iops_average{dbinstance_identifier=\"$rds_namespace\"})",
       "legendFormat": "Read"
      },
      {
       "expr": "max without(pod,instance) (aws_rds_write_iops_average{dbinstance_identifier=\"$rds_namespace\"})",
       "legendFormat": "Write"
      }
     ]
    },
    {
     "title": "Read/Write Latency",
     "type": "graph",
     "description": "The average amount of time taken per disk I/O operation.",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 28 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "max without(pod,instance) (aws_rds_read_latency_average{dbinstance_identifier=\"$rds_namespace\"})",
       "legendFormat": "Read"
      },
      {
       "expr": "max without(pod,instance) (aws_rds_write_latency_average{dbinstance_identifier=\"$rds_namespace\"})",
       "legendFormat": "Write"
      }
     ]
    },
    {
     "title": "CPU Utilization",
     "type": "singlestat",
     "description": "The percentage of CPU utilization.",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 32 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "max without(pod,instance) (aws_rds_cpuutilization_average{dbinstance_identifier=\"$rds_namespace\"})"
      }
     ]
    }
   ]
  }
 ]
}