{
 "title": "AWS Account Operator",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "environment",
    "label": "Hive Instance",
    "query": "label_values(aws_account_operator_reconcile_duration_seconds_sum, job)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Number of AWS Accounts",
   "type": "singlestat",
   "description": "Time series graph of how many AWS accounts have been created \n",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "aws_account_operator_aws_accounts{job=\"$environment\"}",
     "legendFormat": "Total AWS Accounts"
    }
   ]
  },
  {
   "title": "Number of Reused Accounts Available ",
   "type": "singlestat",
   "description": "The number of reused accounts available for claiming",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(aws_account_operator_aws_accounts_reusable{job=\"$environment\"})"
    }
   ]
  },
  {
   "title": "Difference Between Pool Size and Unclaimed CRs",
   "type": "singlestat",
   "description": "The difference between the pool size and the number of unclaimed account CRs. If this number > 0, it indicates an issue. ",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(aws_account_operator_account_crs{job=\"$environment\",reused=\"false\",claimed=\"false\", state!~\"Failed|\"})-sum(aws_account_operator_account_pool_size{job=\"$environment\"})"
    }
   ]
  },
  {
   "title": "Account Pool Size",
   "type": "singlestat",
   "description": "Account Pool Size",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "aws_account_operator_account_pool_size{job=\"$environment\"}",
     "legendFormat": "pool size"
    }
   ]
  },
  {
   "title": "Controller Reconcile Duration",
   "type": "graph",
   "description": "Duration of controller reconcile",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(aws_account_operator_reconcile_duration_seconds_sum{job=\"$environment\"}[10m])/rate(aws_account_operator_reconcile_duration_seconds_count{job=\"$environment\"}[10m])",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Controller Reconcile Count",
   "type": "graph",
   "description": "Rate of reconciles per controller",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(aws_account_operator_reconcile_duration_seconds_count{job=\"$environment\"}[10m])",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "API call duration",
   "type": "graph",
   "description": "Duration of external API calls by controller and resource",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(aws_account_operator_api_request_duration_seconds_sum{job=\"$environment\"}[10m])/rate(aws_account_operator_api_request_duration_seconds_count{job=\"$environment\"}[10m])",
     "legendFormat": "{{controller}} {{method}} {{resource}} {{status}}"
    }
   ]
  },
  {
   "title": "API call count",
   "type": "graph",
   "description": "Count of external API calls by controller and resource",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(aws_account_operator_api_request_duration_seconds_count{job=\"$environment\"}[10m])",
     "legendFormat": "{{controller}} {{method}} {{resource}} {{status}}"
    }
   ]
  },
  {
   "title": "Number of Available Reused AWS Accounts ",
   "type": "graph",
   "description": "Time series graph of the number of reused accounts available for claiming",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_account_operator_aws_accounts_reusable{job=\"$environment\"}",
     "legendFormat": "LegalID = {{legal_id}}"
    }
   ]
  },
  { "title": "non-CCS Account Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Number of non-CCS Accounts",
   "type": "singlestat",
   "description": "The number of non-CCS Accounts",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 49 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(aws_account_operator_account_crs{job=\"$environment\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "non-CCS Account CR Overview",
   "type": "grafana-piechart-panel",
   "description": "Overview graph for non-CCS Account CRs",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 49 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "aws_account_operator_account_crs{job=\"$environment\"}",
     "legendFormat": "State: {{state}} Claimed: {{claimed}} Reused: {{reused}}"
    }
   ]
  },
  {
   "title": "non-CCS Account Ready Duration",
   "type": "graph",
   "description": "Duration for non-CCS Account to get ready",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, aws_account_operator_account_ready_duration_seconds_bucket{job=\"$environment\"})",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.9, aws_account_operator_account_ready_duration_seconds_bucket{job=\"$environment\"})",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.5, aws_account_operator_account_ready_duration_seconds_bucket{job=\"$environment\"})",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "non-CCS Account Claim Ready Duration",
   "type": "graph",
   "description": "Duration for non-CCS Account Claim to get ready",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, aws_account_operator_account_claim_ready_duration_seconds_bucket{job=\"$environment\"})",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.9, aws_account_operator_account_claim_ready_duration_seconds_bucket{job=\"$environment\"})",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.5, aws_account_operator_account_claim_ready_duration_seconds_bucket{job=\"$environment\"})",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Number of Failed non-CCS Account CRs",
   "type": "graph",
   "description": "The number of non-CCS Account CRs that are failed",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aws_account_operator_account_crs{job=\"$environment\", state=\"Failed\"})",
     "legendFormat": "non-CCS Account"
    }
   ]
  },
  {
   "title": "Number of Unclaimed non-CCS Account CRs",
   "type": "graph",
   "description": "The number of non-CCS Account CRs that are unclaimed",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aws_account_operator_account_crs{job=\"$environment\", claimed=\"false\"})",
     "legendFormat": "non-CCS Account"
    }
   ]
  },
  {
   "title": "Number of Ready non-CCS Account CRs",
   "type": "graph",
   "description": "Number of ready non-CCS Account CRs",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aws_account_operator_account_crs{job=\"$environment\", state=\"Ready\"})",
     "legendFormat": "non-CCS Account"
    }
   ]
  },
  {
   "title": "Number of Account Pending Verification",
   "type": "graph",
   "description": "The number of accounts waiting for enterprise support and EC2 limit increases in AWS",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aws_account_operator_account_crs{job=\"$environment\", state=\"PendingVerification\"})",
     "legendFormat": "non-CCS Account"
    }
   ]
  },
  {
   "title": "Account Reuse Cleanup Duration",
   "type": "graph",
   "description": "Duration of account reuse cleanup",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, aws_account_operator_account_reuse_cleanup_duration_seconds_bucket{job=\"$environment\"})",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.9, aws_account_operator_account_reuse_cleanup_duration_seconds_bucket{job=\"$environment\"})",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.5, aws_account_operator_account_reuse_cleanup_duration_seconds_bucket{job=\"$environment\"})",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Error of Account Reuse Cleanup",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(aws_account_operator_account_reuse_cleanup_failures_total{job=\"$environment\"}[1h]))",
     "legendFormat": "error"
    }
   ]
  },
  { "title": "CCS Account Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 } },
  {
   "title": "Number of CCS Accounts",
   "type": "singlestat",
   "description": "The number of CCS Accounts",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 87 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(aws_account_operator_account_ccs_crs{job=\"$environment\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Account CR Overview",
   "type": "grafana-piechart-panel",
   "description": "Overview graph for Account CRs",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 87 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "aws_account_operator_account_ccs_crs{job=\"$environment\"}",
     "legendFormat": "State: {{state}} Claimed: {{claimed}}"
    }
   ]
  },
  {
   "title": "CCS Account Ready Duration",
   "type": "graph",
   "description": "Duration for CCS Account to get ready",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, aws_account_operator_account_ccs_ready_duration_seconds_bucket{job=\"$environment\"})",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.9, aws_account_operator_account_ccs_ready_duration_seconds_bucket{job=\"$environment\"})",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.5, aws_account_operator_account_ccs_ready_duration_seconds_bucket{job=\"$environment\"})",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "CCS Account Claim Ready duration",
   "type": "graph",
   "description": "Duration for CCS Account Claim to get ready",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 94 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, aws_account_operator_account_claim_ccs_ready_duration_seconds_bucket{job=\"$environment\"})",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.9, aws_account_operator_account_claim_ccs_ready_duration_seconds_bucket{job=\"$environment\"})",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.5, aws_account_operator_account_claim_ccs_ready_duration_seconds_bucket{job=\"$environment\"})",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Number of Failed CCS Account CRs",
   "type": "graph",
   "description": "The number of CCS Account CRs that are failed",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 102 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aws_account_operator_account_ccs_crs{job=\"$environment\", state=\"Failed\"})",
     "legendFormat": "CCS Account"
    }
   ]
  },
  {
   "title": "Number of Unclaimed CCS Account CRs",
   "type": "graph",
   "description": "The number of CCS Account CRs that are unclaimed",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 102 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aws_account_operator_account_ccs_crs{job=\"$environment\", claimed=\"false\"})",
     "legendFormat": "CCS Account"
    }
   ]
  },
  {
   "title": "Number of Ready CCS Account CRs",
   "type": "graph",
   "description": "Number of ready CCS Account CRs",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 109 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aws_account_operator_account_ccs_crs{job=\"$environment\", state=\"Ready\"})",
     "legendFormat": "CCS Account"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 116 } },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 117 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"$environment\"}",
     "legendFormat": "alloc all"
    },
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"$environment\"}",
     "legendFormat": "alloc heap"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=\"$environment\"}[30s])",
     "legendFormat": "alloc rate all"
    },
    {
     "expr": "rate(go_memstats_heap_alloc_bytes{job=\"$environment\"}[30s])",
     "legendFormat": "alloc rate heap"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{job=\"$environment\"}",
     "legendFormat": "inuse stack"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"$environment\"}",
     "legendFormat": "inuse heap"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 8, "y": 117 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"$environment\"}",
     "legendFormat": "goroutines"
    }
   ]
  },
  {
   "title": "GC Time Quantiles",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 117 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=\"$environment\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  }
 ]
}