{
 "title": "Qontract Server",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "route",
    "query": "label_values(haproxy_backend_http_responses_total, route)"
   },
   {
    "name": "namespace",
    "query": "label_values(http_request_duration_seconds_count, namespace)"
   }
  ]
 },
 "panels": [
  { "title": "Router", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Availability (selected time range)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1 -\nsum(increase(haproxy_backend_http_responses_total{route=\"$route\",code=\"5xx\"}[$__range]))\n/\nsum(increase(haproxy_backend_http_responses_total{route=\"$route\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (code) (rate(haproxy_backend_http_responses_total{route=\"$route\"}[5m]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(haproxy_backend_http_responses_total{route=\"$route\",code=\"5xx\"}[5m])) /\nsum(rate(haproxy_backend_http_responses_total{route=\"$route\"}[5m]))",
     "legendFormat": "errors"
    }
   ]
  },
  { "title": "Path latencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "/graphqlsha/#sha latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(http_request_duration_seconds_bucket{namespace=\"$namespace\",endpoint=\"app-interface\",code!~\"5xx\",path=\"/graphqlsha/#sha\"}[5m])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(http_request_duration_seconds_bucket{namespace=\"$namespace\",endpoint=\"app-interface\",code!~\"5xx\",path=\"/graphqlsha/#sha\"}[5m])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(http_request_duration_seconds_bucket{namespace=\"$namespace\",endpoint=\"app-interface\",code!~\"5xx\",path=\"/graphqlsha/#sha\"}[5m])))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "/graphql latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(http_request_duration_seconds_bucket{namespace=\"$namespace\",endpoint=\"app-interface\",code!~\"5xx\",path=\"/graphql\"}[5m])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(http_request_duration_seconds_bucket{namespace=\"$namespace\",endpoint=\"app-interface\",code!~\"5xx\",path=\"/graphql\"}[5m])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(http_request_duration_seconds_bucket{namespace=\"$namespace\",endpoint=\"app-interface\",code!~\"5xx\",path=\"/graphql\"}[5m])))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "/reload latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(http_request_duration_seconds_bucket{namespace=\"$namespace\",endpoint=\"app-interface\",code!~\"5xx\",path=\"/reload\"}[1h])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(http_request_duration_seconds_bucket{namespace=\"$namespace\",endpoint=\"app-interface\",code!~\"5xx\",path=\"/reload\"}[1h])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(http_request_duration_seconds_bucket{namespace=\"$namespace\",endpoint=\"app-interface\",code!~\"5xx\",path=\"/reload\"}[1h])))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "/sha256 latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(http_request_duration_seconds_bucket{namespace=\"$namespace\",endpoint=\"app-interface\",code!~\"5xx\",path=\"/sha256\"}[5m])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(http_request_duration_seconds_bucket{namespace=\"$namespace\",endpoint=\"app-interface\",code!~\"5xx\",path=\"/sha256\"}[5m])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(http_request_duration_seconds_bucket{namespace=\"$namespace\",endpoint=\"app-interface\",code!~\"5xx\",path=\"/sha256\"}[5m])))",
     "legendFormat": "p50"
    }
   ]
  },
  { "title": "Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Bundle Object Shas",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "qontract_server_bundle_object_shas or qontract_server_bundle_cache_object_shas",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Router Stack Layers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "qontract_server_router_stack_layers",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Containers memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Container memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",container=~\"app-interface|app-interface-nginx-gate|s3-reloader\"}) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Container memory usage vs limits",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",container=~\"app-interface|app-interface-nginx-gate|s3-reloader\"}) by (container) /\nsum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\",container=~\"app-interface|app-interface-nginx-gate|s3-reloader\"}) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container=~\"app-interface|app-interface-nginx-gate|s3-reloader\"}[5m])) by (container)\n",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "CPU Throttle",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total{namespace=\"$namespace\", container=~\"app-interface|app-interface-nginx-gate|s3-reloader\"}[5m])) by (container)\n",
     "legendFormat": "{{container}}"
    }
   ]
  },
  { "title": "NodeJS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "NodeJS heap used/total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(qontract_server_nodejs_heap_space_size_total_bytes)by(space)",
     "legendFormat": "total {{space}}"
    },
    {
     "expr": "sum(qontract_server_nodejs_heap_space_size_used_bytes)by(space)",
     "legendFormat": "used {{space}}"
    }
   ]
  },
  {
   "title": "GC duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(qontract_server_nodejs_gc_duration_seconds_bucket[5m])) by (le,kind))",
     "legendFormat": "p50 {{kind}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(qontract_server_nodejs_gc_duration_seconds_bucket[5m])) by (le,kind))",
     "legendFormat": "p90 {{kind}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(qontract_server_nodejs_gc_duration_seconds_bucket[5m])) by (le,kind))",
     "legendFormat": "p99 {{kind}}"
    }
   ]
  },
  {
   "title": "NodeJS eventloop lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "qontract_server_nodejs_eventloop_lag_seconds",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}