{
 "title": "Service Delivery Scale",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ocm_datasource", "query": "prometheus" },
   {
    "name": "ocm_namespace",
    "query": "label_values(api_inbound_request_duration_bucket,  namespace)"
   },
   { "name": "hive_datasource", "query": "prometheus" },
   {
    "name": "hive_instance",
    "query": "label_values(hive_cluster_deployments, job)"
   }
  ]
 },
 "panels": [
  { "title": "Hive", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Work Queue Depth",
   "type": "graph",
   "description": "Measures the depth of the queue controllers are trying to work through.",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "workqueue_depth{job=\"$hive_instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Average time to apply syncset resources",
   "type": "graph",
   "description": "Avg amount of time to apply a specific resource in a syncset.",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hive_syncsetinstance_apply_duration_seconds_sum{job=\"$hive_instance\"} / hive_syncsetinstance_apply_duration_seconds_count{job=\"$hive_instance\"}",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Syncset resource application rate",
   "type": "graph",
   "description": "Rate at which we’re applying the resources within each syncset.",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(hive_syncsetinstance_resources_applied_total{job=\"$hive_instance\"}[5m])",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Duration of requests to remote cluster Kube API",
   "type": "graph",
   "description": "Average duration of all requests to remote cluster Kube API. Change remote to false to also show local kube api requests in the Hive cluster.",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(instance,status,resource)(hive_kube_client_request_seconds_sum{job=\"$hive_instance\"} / hive_kube_client_request_seconds_count{job=\"$hive_instance\",remote=\"true\"})",
     "legendFormat": "{{controller}} - {{method}}"
    }
   ]
  },
  {
   "title": "Controller reconciliation rate",
   "type": "graph",
   "description": "Rate at which controllers are reconciling.",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(controller_runtime_reconcile_total{job=\"$hive_instance\"}[5m])",
     "legendFormat": "{{controller}} - {{result}}"
    }
   ]
  },
  {
   "title": "Average time to selector syncset first success",
   "type": "graph",
   "description": "Average length of time for selectorsyncsets to reach first success on a cluster.",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(name)(hive_selectorsyncset_apply_duration_seconds_sum{job=\"$hive_instance\"})/sum without(name)(hive_selectorsyncset_apply_duration_seconds_count{job=\"$hive_instance\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Kube API request rate",
   "type": "graph",
   "description": "Rate at which we’re making Kube API requests. (local and remote)",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(hive_kube_client_requests_total{job=\"$hive_instance\"}[5m])",
     "legendFormat": "{{resource}} - {{status}}"
    }
   ]
  },
  {
   "title": "AMS Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(haproxy_backend_connections_total{route=\"accounts-mgmt\"}[5m])",
     "legendFormat": "{{pod}} Traffic"
    },
    {
     "expr": "rate(haproxy_server_http_responses_total{route=\"accounts-mgmt\", code=\"5xx\"}[1m])",
     "legendFormat": "{{pod}} Errors"
    }
   ]
  },
  { "title": "OCM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": " Volume (reqs/sec)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(status_class:http_requests_total:rate5m{route=\"clusters-mgmt\", service=\"clusters-service\", component=\"uhc-clusters-service\"})"
    }
   ]
  },
  {
   "title": " Availability/Latency",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 16 },
   "targets": [
    {
     "expr": "100 * component:latency:slo_ok_5m{namespace=\"$ocm_namespace\",service=\"clusters-service\",component=\"uhc-clusters-service\"}"
    }
   ]
  },
  {
   "title": " Availability/Errors",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 16 },
   "targets": [
    {
     "expr": "100 * component:errors:slo_ok_5m{route=\"clusters-mgmt\",service=\"clusters-service\",component=\"uhc-clusters-service\"}"
    }
   ]
  },
  {
   "title": " Availability",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 16 },
   "targets": [
    {
     "expr": "100 * component:availability:slo_ok_5m{route=\"clusters-mgmt\",namespace=\"$ocm_namespace\",service=\"clusters-service\",component=\"uhc-clusters-service\"}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "component:latency:p90_rate5m{namespace=\"$ocm_namespace\",service=\"clusters-service\",component=\"uhc-clusters-service\"}",
     "legendFormat": "p90 latency"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 23 },
   "yaxes": [
    { "format": "short", "label": "percentage" }
   ],
   "targets": [
    {
     "expr": "100 * status_class_5xx:http_requests_total:ratio_rate5m{route=\"clusters-mgmt\", service=\"clusters-service\",component=\"uhc-clusters-service\"}",
     "legendFormat": "errors"
    }
   ]
  }
 ]
}