{
 "title": "OCM Gateway",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "uhc-integration,uhc-stage,uhc-production"
   }
  ]
 },
 "panels": [
  {
   "title": "Envoy Request Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_total{namespace=\"$namespace\",service=\"gateway-envoy-metrics\",envoy_cluster_name!~\"^(admin|site|sso)$\"}[10m])) by (envoy_cluster_name)",
     "legendFormat": "{{ envoy_cluster_name }}"
    }
   ]
  },
  {
   "title": "Envoy Connections",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(envoy_listener_downstream_cx_active{namespace=\"$namespace\",service=\"gateway-envoy-metrics\"}[5m]))",
     "legendFormat": "Downstream"
    },
    {
     "expr": "sum(avg_over_time(envoy_cluster_upstream_cx_active{namespace=\"$namespace\",service=\"gateway-envoy-metrics\",envoy_cluster_name!~\"^(admin|site|sso)$\"}[5m])) by (envoy_cluster_name)",
     "legendFormat": "Upstream - {{ envoy_cluster_name }}"
    }
   ]
  },
  {
   "title": "Envoy CPU",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "mc" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",pod=~\"^gateway-envoy-.*$\"}[5m])) by(pod) * 1000",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "max(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\",pod=~\"^gateway-envoy-.*$\"}) * 1000",
     "legendFormat": "Limit"
    },
    {
     "expr": "max(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\",pod=~\"^gateway-envoy-.*$\"}) * 1000",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Envoy Memory",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",pod=~\"^gateway-envoy-.*\"}) by(pod)",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{resource=\"memory\",namespace=\"$namespace\",pod=~\"^gateway-envoy-.*$\"})",
     "legendFormat": "Request"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{resource=\"memory\",namespace=\"$namespace\",pod=~\"^gateway-envoy-.*$\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Envoy Network",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "binbps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\",pod=~\"^gateway-envoy-.*\",interface=\"eth0\"}[10m]))",
     "legendFormat": "Receive"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\",pod=~\"^gateway-envoy-.*\",interface=\"eth0\"}[10m]))",
     "legendFormat": "Transmit"
    }
   ]
  }
 ]
}