{
 "title": "Ephemeral Cluster Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "nodes", "label": "Nodes", "query": { "query": "cluster:nodes_roles" } }
  ]
 },
 "panels": [
  {
   "title": "Master Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(cluster:master_nodes)" }
   ]
  },
  {
   "title": "Node Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 2, "y": 0 },
   "targets": [
    {
     "expr": "instance:node_memory_utilisation:ratio{instance=~\"$nodes\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "instance:node_cpu_utilisation:rate1m{instance=~\"$nodes\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Infra Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(cluster:infra_nodes)" }
   ]
  },
  {
   "title": "Worker Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(sre:node_workers:count)" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{node=~\"$nodes\"}) by (namespace)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Operation Rates Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum by (method) (rate(rest_client_requests_total{node=~\"$nodes\"}[1m]))",
     "legendFormat": "{{operation}}"
    }
   ]
  }
 ]
}