{
 "title": "Inventory",
 "tags": [
  "platform-health",
  "xjoin"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "kibana",
    "query": "https://kibana-kibana.1b13.insights.openshiftapps.com/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-12h,mode:quick,to:now))&_a=(columns:!(_source),index:'0a2575c0-65f9-11e9-ba88-097c6c9f6850',interval:auto"
   },
   {
    "name": "kibana_dev",
    "query": "https://kibana-kibana.5a9f.insights-dev.openshiftapps.com/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-12h,mode:quick,to:now))&_a=(columns:!(_source),index:d2da0310-7048-11e9-a501-7998195d35a8,interval:auto"
   },
   {
    "name": "kibana_prod",
    "query": "https://kibana-kibana.1b13.insights.openshiftapps.com/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-12h,mode:quick,to:now))&_a=(columns:!(_source),index:'0a2575c0-65f9-11e9-ba88-097c6c9f6850',interval:auto"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "content": "<center><h1>Inventory API</h1></center>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 9, "x": 12, "y": 0 },
   "content": "<center><h1>Inventory MQ Service</h1></center>"
  },
  {
   "title": "parser failures",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 0 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(inventory_ingress_message_parsing_failures_total{cause=\"error\", kubernetes_namespace='platform-$namespace'}[$__range])) OR vector(0)"
    }
   ]
  },
  {
   "title": "API Pod Count",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(up{service=\"insights-inventory\"})"
    }
   ]
  },
  {
   "title": "API restarts",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{container=\"insights-inventory\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Response Codes",
   "type": "table",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 2 },
   "targets": [
    {
     "expr": "sum(increase(inventory_http_request_total{service=\"insights-inventory\"}[$__range])) by (status) > 0",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Hosts deleted (API)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(inventory_delete_host_count_total{service=\"insights-inventory\"}[$__range]))"
    }
   ]
  },
  {
   "title": "MQ Pod Count",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 2 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(up{kubernetes_namespace='platform-$namespace', deploymentconfig=~\"inventory-mq-.*\"})"
    }
   ]
  },
  {
   "title": "MQ restarts",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{container=~\"inventory-mq-.*\"}[$__range]))"
    }
   ]
  },
  {
   "title": "underreplicated partitions",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_cluster_partition_underreplicated{topic=~\"platform.inventory.host-ingress.*\"})"
    }
   ]
  },
  {
   "title": "parser validation errors",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 2 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(inventory_ingress_message_parsing_failures_total{cause=\"invalid\"}[$__range]))"
    }
   ]
  },
  {
   "title": "4xx ratio",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 4 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(api_3scale_gateway_api_status{exported_service=\"inventory\", status=\"4xx\"}[$__range])) / sum(increase(api_3scale_gateway_api_status{exported_service=\"inventory\"}[$__range]))"
    }
   ]
  },
  {
   "title": "4xx ratio",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 4 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(increase(inventory_http_request_total{service=\"insights-inventory\", status=~\"4.*\"}[$__range])) OR vector(0)) / sum(increase(inventory_http_request_total{service=\"insights-inventory\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Hosts deleted (reaper)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum_over_time(inventory_delete_host_count_total{job=\"inventory-reaper-platform-$namespace\"}[$__range:59m])"
    }
   ]
  },
  {
   "title": "Host ingress stats",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "sum(increase(inventory_ingress_add_host_successes_total{result=\"created\"}[$__range])) by (reporter) > 0",
     "legendFormat": "added"
    },
    {
     "expr": "sum(increase(inventory_ingress_add_host_successes_total{result=\"updated\"}[$__range])) by (reporter) > 0",
     "legendFormat": "updated"
    },
    {
     "expr": "sum(increase(inventory_ingress_add_host_failures_total{cause=\"InventoryException\"}[$__range])) by (reporter)"
    },
    {
     "expr": "sum(increase(inventory_ingress_add_host_failures_total{cause=\"InventoryException\"}[$__range])) by (reporter) / (sum(increase(inventory_ingress_add_host_failures_total[$__range])) by (reporter) + sum(increase(inventory_ingress_add_host_successes_total[$__range])) by (reporter)) "
    },
    {
     "expr": "sum(increase(inventory_ingress_add_host_failures_total{cause=\"Exception\"}[$__range])) by (reporter)"
    }
   ]
  },
  {
   "title": "5xx ratio",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 6 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(api_3scale_gateway_api_status{exported_service=\"inventory\", status=\"5xx\"}[$__range])) / sum(increase(api_3scale_gateway_api_status{exported_service=\"inventory\"}[$__range]))"
    }
   ]
  },
  {
   "title": "5xx ratio",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 6 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(increase(inventory_http_request_total{service=\"insights-inventory\", status=~\"5.*\"}[$__range])) OR vector(0)) / sum(increase(inventory_http_request_total{service=\"insights-inventory\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Reaper failures",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "increase(inventory_reaper_fail_count{job=\"inventory-reaper-platform-$namespace\"}[$__range])"
    }
   ]
  },
  {
   "title": "3scale API Requests",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(api_3scale_gateway_api_status{exported_service=\"inventory\"}[$__range]))"
    }
   ]
  },
  {
   "title": "API Requests",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(inventory_http_request_total{service=\"insights-inventory\"}[$__range]))"
    }
   ]
  },
  {
   "title": "ingress consumer lag (ingress)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumer_group_lag{group='inventory-mq', topic=~'platform.inventory.host-ingress.*'}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(api_3scale_gateway_api_time_count{exported_service=\"inventory\"}[1m]))"
    }
   ]
  },
  {
   "title": "consumed message rate (ingress)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "sum(increase(kafka_consumer_group_offset{group='inventory-mq', topic=~'platform.inventory.host-ingress.*'}[1m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(increase(api_3scale_gateway_api_time_bucket{exported_service=\"inventory\"}[1m])) by (le)",
     "legendFormat": "{{le}} ms"
    }
   ]
  },
  {
   "title": "incoming message rate (ingress)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "sum(increase(kafka_server_brokertopicmetrics_messagesin_total{topic=~'platform.inventory.host-ingress.*'}[1m])) by (topic)",
     "legendFormat": "topic"
    }
   ]
  },
  {
   "title": "HTTP host create requests",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum(increase(rest_post_request_count_total[$__range])) by (reporter)"
    }
   ]
  },
  { "title": "Host delete", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Hosts deleted (API)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(inventory_delete_host_count_total[1m])) by (deployment)",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Hosts deleted (reaper)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "inventory_delete_host_count_total{job=\"inventory-reaper-platform-$namespace\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "5xx per minute",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(api_3scale_gateway_api_status{exported_service=\"inventory\", status=\"5xx\"}[1m]))"
    }
   ]
  },
  {
   "title": "Message handler failures per minute",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(inventory_ingress_message_handler_failures_total{kubernetes_namespace='platform-$namespace'}[1m])) by (deploymentconfig)",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Number of pods",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(up{service=\"insights-inventory\"})",
     "legendFormat": "number of pods"
    }
   ]
  },
  {
   "title": "Number of pods",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(up{kubernetes_namespace='platform-$namespace', deploymentconfig=~\"inventory-mq-.*\"}) by (deploymentconfig)",
     "legendFormat": "{{deploymentconfig}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=\"insights-inventory\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=~\"inventory-mq-.*\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container=\"insights-inventory\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container=~\"inventory-mq-.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}