{
 "title": "Che Server Stats",
 "time": { "from": "2019-04-10T14:14:47.704Z", "to": "2019-04-11T14:14:47.704Z" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "graphite" }
  ]
 },
 "panels": [
  { "title": "Che Workspace Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Che Running Workspaces",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "osio.prometheus.rhche_host.che_workspace_status.1 area~3Aworkspace status~3ARUNNING"
    }
   ]
  },
  {
   "title": "Che Stopped Workspaces",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "osio.prometheus.rhche_host.che_workspace_status.3 area~3Aworkspace status~3ASTOPPED"
    }
   ]
  },
  {
   "title": "Che Starting Workspaces",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 11, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "osio.prometheus.rhche_host.che_workspace_status.0 area~3Aworkspace status~3ASTARTING"
    }
   ]
  },
  {
   "title": "Che Stopping Workspaces",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "osio.prometheus.rhche_host.che_workspace_status.2 area~3Aworkspace status~3ASTOPPING"
    }
   ]
  },
  { "title": "Che Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Che Server responses",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "osio.prometheus.rhche_host.che_server_api_response.*"
    }
   ]
  },
  {
   "title": "Che Server Error rate 3xx",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "osio.prometheus.rhche_host.che_server_api_response.3 area~3Ahttp code~3A4xx"
    }
   ]
  },
  {
   "title": "Che Server Total responses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "osio.prometheus.rhche_host.che_server_api_response_total.*"
    }
   ]
  },
  {
   "title": "Che Workspace startup time Seconds",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "target": "osio.prometheus.rhche_host.che_workspace_start_time_seconds_bucket.*"
    }
   ]
  }
 ]
}