{
 "title": "OSIO Gluster",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "gluster_cluster",
    "label": "Gluster cluster",
    "query": "gluster-2,gluster-2a,gluster-1a,gluster-1b"
   }
  ]
 },
 "panels": [
  {
   "title": "kernel load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (zabbix_sender_hostname) (zabbix_impersonator_pcp_kernel_all_load{gluster_cluster=\"$gluster_cluster\", interval=\"1 minute\"})",
     "legendFormat": "{{zabbix_sender_hostname}}"
    }
   ]
  },
  {
   "title": "Brick BW",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "avg by (zabbix_sender_hostname, brick) (\r\nzabbix_impersonator_pcp_gluster_brick_write_bytes{gluster_cluster=\"$gluster_cluster\"} +\r\nzabbix_impersonator_pcp_gluster_brick_read_bytes{gluster_cluster=\"$gluster_cluster\"}\r\n)",
     "legendFormat": "{{brick}}"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "4000-avg by (zabbix_sender_hostname) (zabbix_impersonator_pcp_kernel_all_cpu_idle{gluster_cluster=\"$gluster_cluster\"})",
     "legendFormat": "{{zabbix_sender_hostname}}"
    }
   ]
  },
  {
   "title": "Memory Available",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "avg by (zabbix_sender_hostname) (zabbix_impersonator_pcp_mem_util_available{gluster_cluster=\"$gluster_cluster\"})",
     "legendFormat": "{{zabbix_sender_hostname}}"
    }
   ]
  }
 ]
}