{
 "title": "Assisted Installer Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Installations results",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(service_assisted_installer_cluster_creations)",
     "legendFormat": "Created clusters"
    },
    {
     "expr": "sum(service_assisted_installer_cluster_installation_started)",
     "legendFormat": "Installation started"
    },
    {
     "expr": "sum(service_assisted_installer_cluster_installation_seconds_count{result=\"installed\"})",
     "legendFormat": "Installation completed successfully"
    },
    {
     "expr": "sum(service_assisted_installer_cluster_installation_seconds_count{result=\"error\"})",
     "legendFormat": "Installation error"
    },
    {
     "expr": "sum(service_assisted_installer_cluster_installation_seconds_count{result=\"cancelled\"})",
     "legendFormat": "Installation canceled"
    },
    {
     "expr": "sum(http_request_duration_seconds_count{handler=\"/api/assisted-install/v1/clusters/{cluster_id}\",method=\"DELETE\"})",
     "legendFormat": "Deleted clusters"
    }
   ]
  },
  {
   "title": "Phases duration (successful)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "s", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum by (phase)(service_assisted_installer_host_installation_phase_seconds_sum{result=\"Done\"}) /sum by (phase)(service_assisted_installer_host_installation_phase_seconds_count{result=\"Done\"})",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Hosts failures by role",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "s", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum(service_assisted_installer_cluster_hosts{result=\"Failed\"}) by (role)",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "Creation vs Installation rate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 6 },
   "targets": [
    {
     "expr": "sum(service_assisted_installer_cluster_installation_started)/sum(service_assisted_installer_cluster_creations)"
    }
   ]
  }
 ]
}