{
 "title": "xjoin-elasticsearch",
 "tags": [ "xjoin" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "cluster", "query": "label_values(cluster)" }
  ]
 },
 "panels": [
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "scalar(elasticsearch_cluster_health_status{color=\"green\",cluster=~\"$cluster\"}) + scalar(elasticsearch_cluster_health_status{color=\"yellow\",cluster=~\"$cluster\"}) * 2 + scalar(elasticsearch_cluster_health_status{color=\"red\",cluster=~\"$cluster\"}) * 3"
    }
   ]
  },
  {
   "title": "Running Nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(elasticsearch_cluster_health_number_of_nodes{cluster=~\"$cluster\"})/count(elasticsearch_cluster_health_number_of_nodes{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Active Data Nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_number_of_data_nodes{cluster=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Pending Tasks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_number_of_pending_tasks{cluster=~\"$cluster\"}"
    }
   ]
  },
  { "title": "Shards", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Active Shards",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_active_shards{cluster=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Active Primary Shards",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_active_primary_shards{cluster=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Initializing Shards",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_initializing_shards{cluster=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Relocating Shards",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_relocating_shards{cluster=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Unassigned Shards",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_unassigned_shards{cluster=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Delayed Unassigned Shards",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_delayed_unassigned_shards{cluster=~\"$cluster\"}"
    }
   ]
  },
  { "title": "Filesystem", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Filesystem Free (data nodes)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 9 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (elasticsearch_filesystem_data_free_bytes{cluster=~\"$cluster\", es_data_node=\"true\"})"
    }
   ]
  },
  {
   "title": "Filesystem Used Percentage (data nodes)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "((elasticsearch_filesystem_data_size_bytes{cluster=~\"$cluster\", es_data_node=\"true\"} - elasticsearch_filesystem_data_free_bytes{cluster=~\"$cluster\", es_data_node=\"true\"}) / elasticsearch_filesystem_data_size_bytes{cluster=~\"$cluster\", es_data_node=\"true\"})",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Filesystem Size (data nodes)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 12 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (elasticsearch_filesystem_data_size_bytes{cluster=~\"$cluster\", es_data_node=\"true\"})"
    }
   ]
  },
  {
   "title": "Filesystem Free (non-data nodes)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 15 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (elasticsearch_filesystem_data_free_bytes{cluster=~\"$cluster\", es_data_node=\"false\"})"
    }
   ]
  },
  {
   "title": "Filesystem Used Percentage (non-data nodes)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 15 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "((elasticsearch_filesystem_data_size_bytes{cluster=~\"$cluster\", es_data_node=\"false\"} - elasticsearch_filesystem_data_free_bytes{cluster=~\"$cluster\", es_data_node=\"false\"}) / elasticsearch_filesystem_data_size_bytes{cluster=~\"$cluster\", es_data_node=\"false\"})",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Filesystem Size (non-data nodes)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 18 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (elasticsearch_filesystem_data_size_bytes{cluster=~\"$cluster\", es_data_node=\"false\"})"
    }
   ]
  },
  { "title": "Documents", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Documents Indexed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(elasticsearch_indices_docs{cluster=~\"$cluster\"})",
     "legendFormat": "Documents"
    }
   ]
  },
  {
   "title": "Index Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(elasticsearch_indices_store_size_bytes{cluster=~\"$cluster\"})",
     "legendFormat": "Index Size"
    }
   ]
  },
  {
   "title": "Documents Indexed Rate 5m",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short", "label": "Documents/s" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_indexing_index_total{cluster=~\"$cluster\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Query Rate 5m",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short", "label": "Queries/s" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_search_fetch_total{cluster=~\"$cluster\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Queue Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(elasticsearch_thread_pool_queue_count{cluster=~\"$cluster\", type!=\"management\"}) by (type)",
     "legendFormat": "Type: {{type}}"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_os_cpu_percent{cluster=~\"$cluster\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_os_mem_used_bytes{cluster=~\"$cluster\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Thread Pools",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(elasticsearch_thread_pool_active_count{cluster=~\"$cluster\", type!=\"management\"}) by (type)",
     "legendFormat": "Type: {{ type }}"
    }
   ]
  },
  {
   "title": "Memory available",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_os_mem_free_bytes{cluster=~\"$cluster\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Thread Pool Rejections 5m",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_thread_pool_rejected_count{cluster=~\"$cluster\", type!=\"management\"}[5m])",
     "legendFormat": "{{ name }} {{ type }}"
    }
   ]
  },
  {
   "title": "Avg Heap in 5min",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(elasticsearch_jvm_memory_used_bytes{area=\"heap\",cluster=~\"$cluster\"}[5m]) / elasticsearch_jvm_memory_max_bytes{area=\"heap\",cluster=~\"$cluster\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "GC Seconds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_jvm_gc_collection_seconds_sum{cluster=~\"$cluster\"}[1m])",
     "legendFormat": "{{name}} {{gc}}"
    }
   ]
  },
  {
   "title": "RX/TX Rate 5m",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(elasticsearch_transport_rx_packets_total{cluster=~\"$cluster\"}[5m]))",
     "legendFormat": "RX"
    },
    {
     "expr": "sum(rate(elasticsearch_transport_tx_packets_total{cluster=~\"$cluster\"}[5m])) * -1",
     "legendFormat": "TX"
    }
   ]
  }
 ]
}