{
 "title": "OSDv4: Tenant / Compute Resources / Namespace",
 "description": "Consumption of compute resources by namespace",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_pod_info, namespace)"
   }
  ]
 },
 "panels": [
  { "title": "Resource consumption", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "namespace" },
  {
   "title": "CPU Stats (Cores)",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\"})",
     "legendFormat": "CPU limits"
    },
    {
     "expr": "sum(namespace:container_cpu_usage:sum{namespace=\"$namespace\"})",
     "legendFormat": "CPU usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\"})",
     "legendFormat": "CPU requests"
    }
   ]
  },
  {
   "title": "Memory (GigaBytes)",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\",namespace=\"$namespace\"}) * 1e-9",
     "legendFormat": "Memory limits"
    },
    {
     "expr": "sum(namespace:container_memory_usage_bytes:sum{namespace=\"$namespace\"}) * 1e-9",
     "legendFormat": "Current Memory usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\",namespace=\"$namespace\"}) * 1e-9",
     "legendFormat": "Memory requests"
    }
   ]
  },
  {
   "title": "Persistent Volumes",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by (namespace) (kube_persistentvolumeclaim_resource_requests_storage_bytes{namespace=\"$namespace\"}) * 1e-9",
     "legendFormat": "Requested PV capacity (GigaBytes)"
    },
    {
     "expr": "sum(kubelet_volume_stats_used_bytes{job=\"kubelet\", namespace=\"$namespace\"}) / sum(kubelet_volume_stats_capacity_bytes{job=\"kubelet\",namespace=\"$namespace\"}) * 100",
     "legendFormat": "Used PV capacity (GigaBytes)"
    },
    {
     "expr": "sum(kube_persistentvolumeclaim_info{namespace=\"$namespace\"})",
     "legendFormat": "Number of PersistentVolumeClaims"
    }
   ]
  },
  {
   "title": "Average resource consumption wrt Limits",
   "type": "gauge",
   "description": "This is the average percentage of resource used as compared to the limits. ",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "namespace:container_cpu_usage:sum{namespace=\"$namespace\"} / sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\"}) * 100",
     "legendFormat": "CPU"
    },
    {
     "expr": "namespace:container_memory_usage_bytes:sum{namespace=\"$namespace\"} / sum(kube_pod_container_resource_limits{resource=\"memory\",namespace=\"$namespace\"})",
     "legendFormat": "Memory"
    },
    {
     "expr": "sum(kubelet_volume_stats_used_bytes{job=\"kubelet\", namespace=\"$namespace\"}) / sum(kubelet_volume_stats_capacity_bytes{job=\"kubelet\",namespace=\"$namespace\"}) * 100",
     "legendFormat": "Persistent Volumes"
    }
   ]
  }
 ]
}