{
 "title": "Quay Runtime by Service",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "rate",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": "label_values(process_cpu_seconds_total, namespace)"
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(quay_db_close_calls_created, service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{namespace=\"$namespace\",job=\"$service\"}[$rate])) by (pod) * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Max Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(process_resident_memory_bytes{host=~\"quay-app.+\",job=\"$service\"}) by (process_name)",
     "legendFormat": "{{process_name}}"
    }
   ]
  },
  {
   "title": "Image pulls",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(quay_registry_image_pulls_total{namespace=\"$namespace\",service=\"$service\"}[$rate]))",
     "legendFormat": "{{method}} {{route}} {{status}}"
    }
   ]
  },
  {
   "title": "Authentication",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(quay_authentication_attempts_total{namespace=\"$namespace\",service=\"$service\"}[$rate]))",
     "legendFormat": "auth attempts"
    },
    {}
   ]
  },
  {
   "title": "Image pushes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(quay_registry_image_pushes_total{namespace=\"$namespace\",service=\"$service\"}[$rate]))",
     "legendFormat": "{{method}} {{route}} {{status}}"
    }
   ]
  },
  {
   "title": "Build Queue",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(quay_queue_items_available_unlocked{queue_name=\"dockerfilebuild\",service=\"$service\"})",
     "legendFormat": "available unlocked"
    },
    {
     "expr": "max(quay_queue_items_available{queue_name=\"dockerfilebuild\",service=\"$service\"})",
     "legendFormat": "available locked"
    },
    {
     "expr": "max(quay_queue_items_locked{queue_name=\"dockerfilebuild\",service=\"$service\"})",
     "legendFormat": "locked"
    }
   ]
  },
  {
   "title": "Work Queues Actions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "actions" }
   ],
   "targets": [
    {
     "expr": "ceil(sum(rate(quay_queue_item_gets_total{service=\"$service\"}[$rate])) by (queue_name))",
     "legendFormat": "gets {{queue_name}}"
    },
    {
     "expr": "ceil(sum(rate(quay_queue_item_deletes_total{service=\"$service\"}[$rate])) by (queue_name))",
     "legendFormat": "deletes {{queue_name}}"
    },
    {
     "expr": "ceil(sum(rate(quay_queue_item_puts_total{service=\"$service\"}[$rate])) by (queue_name))",
     "legendFormat": "puts {{queue_name}}"
    }
   ]
  },
  {
   "title": "PushGateway Push Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(pushgateway_http_push_duration_seconds_sum{service=\"$service\"}[$rate]) / rate(pushgateway_http_push_duration_seconds_count{service=\"$service\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Gevent Duration (P95)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, max(rate(greenlet_duration_seconds_bucket{service=\"$service\"}[$rate])) by (le, process_name))",
     "legendFormat": "{{process_name}}"
    }
   ]
  },
  {
   "title": "Counts of Various Database Rows",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "max(quay_repository_rows{service=\"$service\"} > 0)",
     "legendFormat": "repos"
    },
    {
     "expr": "max(quay_user_rows{service=\"$service\"} > 0)",
     "legendFormat": "users"
    },
    {
     "expr": "max(quay_org_rows{service=\"$service\"} > 0)",
     "legendFormat": "orgs"
    },
    {
     "expr": "max(quay_robot_rows{service=\"$service\"} > 0)",
     "legendFormat": "robots"
    },
    {
     "expr": "min(quay_security_scanning_unscanned_images_remaining{service=\"$service\"} > 0)",
     "legendFormat": "unscanned images"
    }
   ]
  },
  {
   "title": "Max Open File Descriptors",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "max(ceil(process_open_fds{host=~\"quay.+\",service=\"$service\"} / process_max_fds{host=~\"quay.+\",service=\"$service\"} * 100)) by (process_name)",
     "legendFormat": "{{process_name}}"
    }
   ]
  },
  {
   "title": "Model Cache Hit Rate",
   "type": "graph",
   "description": "Number of cache hits / total cache gets for the given interval.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(quay_model_cache_total{type=\"hit\", namespace=\"$namespace\", service=\"$service\"}[$rate]))/sum(rate(quay_model_cache_total{namespace=\"$namespace\", service=\"$service\"}[$rate]))",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}