{
 "title": "UHC Clusters Service",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "namespace", "label": "Namespace", "query": "uhc-stage,uhc-production" },
   {
    "name": "pod",
    "label": "Pod",
    "query": "query_result(count_over_time(kube_pod_info{namespace=\"$namespace\",pod=~\"^clusters-service-.*$\"}[$__range]))"
   }
  ]
 },
 "panels": [
  {
   "title": "Envoy Request Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_total{namespace=\"$namespace\",service=\"clusters-service-metrics-envoy\",envoy_cluster_name=\"backend\",pod=~\"$pod\"}[10m]))",
     "legendFormat": "Inbound"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_total{namespace=\"$namespace\",service=\"clusters-service-metrics-envoy\",envoy_cluster_name=\"accounts_mgmt\",pod=~\"$pod\"}[10m]))",
     "legendFormat": "Outbound - accounts_mgmt"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_total{namespace=\"$namespace\",service=\"clusters-service-metrics-envoy\",envoy_cluster_name=\"authorizations\",pod=~\"$pod\"}[10m]))",
     "legendFormat": "Outbound - authorizations"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_total{namespace=\"$namespace\",service=\"clusters-service-metrics-envoy\",envoy_cluster_name=\"service_logs\",pod=~\"$pod\"}[10m]))",
     "legendFormat": "Outbound - service_logs"
    }
   ]
  },
  {
   "title": "Envoy Request Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_time_sum{namespace=\"$namespace\",service=\"clusters-service-metrics-envoy\",envoy_cluster_name=\"backend\",pod=~\"$pod\"}[10m])) /\nsum(rate(envoy_cluster_upstream_rq_time_count{namespace=\"$namespace\",service=\"clusters-service-metrics-envoy\",envoy_cluster_name=\"backend\",pod=~\"$pod\"}[10m]))",
     "legendFormat": "Inbound"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_time_sum{namespace=\"$namespace\",service=\"clusters-service-metrics-envoy\",envoy_cluster_name=\"authorizations\",pod=~\"$pod\"}[10m])) /\nsum(rate(envoy_cluster_upstream_rq_time_count{namespace=\"$namespace\",service=\"clusters-service-metrics-envoy\",envoy_cluster_name=\"authorizations\",pod=~\"$pod\"}[10m]))",
     "legendFormat": "Outbound - authorizations"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_time_sum{namespace=\"$namespace\",service=\"clusters-service-metrics-envoy\",envoy_cluster_name=\"accounts_mgmt\",pod=~\"$pod\"}[10m])) /\nsum(rate(envoy_cluster_upstream_rq_time_count{namespace=\"$namespace\",service=\"clusters-service-metrics-envoy\",envoy_cluster_name=\"accounts_mgmt\",pod=~\"$pod\"}[10m]))",
     "legendFormat": "Outbound - accounts_mgmt"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_time_sum{namespace=\"$namespace\",service=\"clusters-service-metrics-envoy\",envoy_cluster_name=\"service_logs\",pod=~\"$pod\"}[10m])) /\nsum(rate(envoy_cluster_upstream_rq_time_count{namespace=\"$namespace\",service=\"clusters-service-metrics-envoy\",envoy_cluster_name=\"service_logs\",pod=~\"$pod\"}[10m]))",
     "legendFormat": "Outbound - service_logs"
    }
   ]
  },
  {
   "title": "Envoy Inbound Codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq{namespace=\"$namespace\",service=\"clusters-service-metrics-envoy\",envoy_cluster_name=\"backend\",pod=~\"$pod\"}[10m])) by (envoy_response_code)",
     "legendFormat": "{{envoy_response_code}}"
    }
   ]
  },
  {
   "title": "Envoy Outbound Codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq{namespace=\"$namespace\",service=\"clusters-service-metrics-envoy\",envoy_cluster_name=~\"^(accounts_mgmt|authorizations|service_logs)$\",pod=~\"$pod\"}[10m])) by (envoy_response_code)",
     "legendFormat": "{{envoy_response_code}}"
    }
   ]
  },
  {
   "title": "Envoy CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "mc" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",pod=~\"^clusters-service-.*$\",container=\"envoy\",pod=~\"$pod\"}[5m]) * 1000",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "max(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\",pod=~\"^clusters-service-.*$\",container=\"envoy\"}) * 1000",
     "legendFormat": "Limit"
    },
    {
     "expr": "max(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\",pod=~\"^clusters-service-.*$\",container=\"envoy\"}) * 1000",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Envoy Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{namespace=\"$namespace\",pod=~\"^clusters-service-.*\",container=\"envoy\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{resource=\"memory\",namespace=\"$namespace\",pod=~\"^clusters-service-.*$\",container=\"envoy\"})",
     "legendFormat": "Request"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{resource=\"memory\",namespace=\"$namespace\",pod=~\"^clusters-service-.*$\",container=\"envoy\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Envoy Network",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "binbps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\",pod=~\"^clusters-service-.*\",interface=\"eth0\"}[10m]))",
     "legendFormat": "Receive"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\",pod=~\"^clusters-service-.*\",interface=\"eth0\"}[10m]))",
     "legendFormat": "Transmit"
    }
   ]
  },
  {
   "title": "Backend Request Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(api_inbound_request_count{namespace=\"$namespace\",service=\"clusters-service-metrics\",pod=~\"$pod\"}[10m]))",
     "legendFormat": "Inbound"
    },
    {
     "expr": "sum(rate(api_outbound_request_count{namespace=\"$namespace\",service=\"clusters-service-metrics\",pod=~\"$pod\"}[10m]))",
     "legendFormat": "Outbound"
    }
   ]
  },
  {
   "title": "Backend Request duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(api_inbound_request_duration_sum{namespace=\"$namespace\",service=\"clusters-service-metrics\",pod=~\"$pod\"}[10m])) /\nsum(rate(api_inbound_request_duration_count{namespace=\"$namespace\",service=~\"clusters-service-metrics\",pod=~\"$pod\"}[10m]))",
     "legendFormat": "Inbound"
    },
    {
     "expr": "sum(rate(api_outbound_request_duration_sum{namespace=\"$namespace\",service=\"clusters-service-metrics\",pod=~\"$pod\"}[10m])) /\nsum(rate(api_outbound_request_duration_count{namespace=\"$namespace\",service=~\"clusters-service-metrics\",pod=~\"$pod\"}[10m]))",
     "legendFormat": "Outbound"
    }
   ]
  },
  {
   "title": "Backend Inbound Codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(api_inbound_request_count{namespace=\"$namespace\",service=\"clusters-service-metrics\",pod=~\"$pod\"}[10m])) by (code)",
     "legendFormat": "{{envoy_response_code}}"
    }
   ]
  },
  {
   "title": "Backend Outbound Codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(api_outbound_request_count{namespace=\"$namespace\",service=\"clusters-service-metrics\",pod=~\"$pod\"}[10m])) by (code)",
     "legendFormat": "{{envoy_response_code}}"
    }
   ]
  },
  {
   "title": "Backend Memory",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{namespace=\"$namespace\",service=\"clusters-service-metrics\",pod=~\"$pod\"}",
     "legendFormat": "RSS - {{pod}}"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{namespace=\"$namespace\",service=\"clusters-service-metrics\",pod=~\"$pod\"} +\ngo_memstats_heap_idle_bytes{namespace=\"$namespace\",service=\"clusters-service-metrics\",pod=~\"$pod\"}",
     "legendFormat": "Heap total - {{pod}}"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{namespace=\"$namespace\",service=\"clusters-service-metrics\",pod=~\"$pod\"}",
     "legendFormat": "Heap in use - {{pod}}"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{resource=\"memory\",namespace=\"$namespace\",pod=~\"^clusters-service-.*$\",container=\"service\"})",
     "legendFormat": "Request"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{resource=\"memory\",namespace=\"$namespace\",pod=~\"^clusters-service-.*$\",container=\"service\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Backend CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "mc" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{namespace=\"$namespace\",service=\"clusters-service-metrics\",pod=~\"$pod\"}[5m]) * 1000",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "max(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\",pod=~\"^clusters-service-.*$\",container=\"service\"}) * 1000",
     "legendFormat": "Limit"
    },
    {
     "expr": "max(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\",pod=~\"^clusters-service-.*$\",container=\"service\"}) * 1000",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Backend Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{namespace=\"$namespace\",service=\"clusters-service-metrics\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "P90: Inbound Request duration",
   "type": "heatmap",
   "description": "90th Percentile Inbound request Duration",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(api_inbound_request_duration_bucket{namespace=\"$namespace\",service=\"clusters-service-metrics\",pod=~\"$pod\"}[5m])) by (le))",
     "legendFormat": "Inbound"
    }
   ]
  },
  {
   "title": "P90: Outbound Request duration",
   "type": "heatmap",
   "description": "90th Percentile Outbound request Duration",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 83 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(api_outbound_request_duration_bucket{namespace=\"$namespace\",service=\"clusters-service-metrics\",pod=~\"$pod\"}[5m])) by (le))",
     "legendFormat": "Inbound"
    }
   ]
  }
 ]
}