{
 "title": "CloudFlare Zone Analytics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "zone",
    "query": {
     "query": "label_values(cloudflare_zone_requests_total, zone)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(cloudflare_zone_requests_total{zone=~\"$zone\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Total Bandwidth",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(cloudflare_zone_bandwidth_total{zone=~\"$zone\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Requests / second",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(cloudflare_zone_requests_total{zone=~\"$zone\"}[$__interval])) "
    }
   ]
  },
  {
   "title": "Bandwidth / second",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(cloudflare_zone_bandwidth_total{zone=~\"$zone\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Total Unique Visitors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(cloudflare_zone_uniques_total{zone=~\"$zone\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Uniques / second",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(cloudflare_zone_uniques_total{zone=~\"$zone\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requests / second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (rate(cloudflare_zone_requests_total{zone=~\"$zone\"}[$__interval]))",
     "legendFormat": "total"
    },
    {
     "expr": "sum(rate(cloudflare_zone_requests_cached{zone=~\"$zone\"}[$__interval]))",
     "legendFormat": "cached"
    }
   ]
  },
  {
   "title": "Requests by Region / second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (region) (rate(cloudflare_zone_requests_country{zone=~\"$zone\"}[$__interval]))",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "Requests / Second (status codes)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status) (rate(cloudflare_zone_requests_status{zone=~\"$zone\"}[$__interval])) > 0",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Requests per Country / Second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (country) (rate(cloudflare_zone_requests_country{zone=~\"$zone\"}[$__interval])) > 0",
     "legendFormat": "{{country}}"
    }
   ]
  },
  {
   "title": "Cached Requests",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(cloudflare_zone_requests_cached{zone=~\"$zone\"}[$__range])) / sum(increase(cloudflare_zone_requests_total{zone=~\"$zone\"}[$__range]))",
     "legendFormat": "cached"
    },
    {
     "expr": "(sum(increase(cloudflare_zone_requests_total{zone=~\"$zone\"}[$__range])) - sum(increase(cloudflare_zone_requests_cached{zone=~\"$zone\"}[$__range]))) / sum(increase(cloudflare_zone_requests_total{zone=~\"$zone\"}[$__range]))",
     "legendFormat": "uncached"
    }
   ]
  },
  {
   "title": "Requests SSL",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(cloudflare_zone_requests_ssl_encrypted{zone=~\"$zone\"}[$__range])) / sum(increase(cloudflare_zone_requests_total{zone=~\"$zone\"}[$__range]))",
     "legendFormat": "encrypted"
    },
    {
     "expr": "(sum(increase(cloudflare_zone_requests_total{zone=~\"$zone\"}[$__range])) - sum(increase(cloudflare_zone_requests_ssl_encrypted{zone=~\"$zone\"}[$__range]))) / sum(increase(cloudflare_zone_requests_total{zone=~\"$zone\"}[$__range]))",
     "legendFormat": "unencrypted"
    }
   ]
  },
  {
   "title": "Request Country",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (country) (increase(cloudflare_zone_requests_country{zone=~\"$zone\"}[$__range]))",
     "legendFormat": "{{country}}"
    }
   ]
  },
  {
   "title": "Request Content Type",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (content_type) (increase(cloudflare_zone_requests_content_type{zone=~\"$zone\"}[$__range]))",
     "legendFormat": "{{content_type}}"
    }
   ]
  },
  {
   "title": "Requests Status Codes",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (increase(cloudflare_zone_requests_status{zone=~\"$zone\"}[$__range]))",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Bandwidth / second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(cloudflare_zone_bandwidth_total{zone=~\"$zone\"}[$__interval]))",
     "legendFormat": "total"
    },
    {
     "expr": "sum(rate(cloudflare_zone_bandwidth_cached{zone=~\"$zone\"}[$__interval]))",
     "legendFormat": "cached"
    }
   ]
  },
  {
   "title": "Cached Bandwidth",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(cloudflare_zone_bandwidth_cached{zone=~\"$zone\"}[$__range])) / sum(increase(cloudflare_zone_bandwidth_total{zone=~\"$zone\"}[$__range]))",
     "legendFormat": "cached"
    },
    {
     "expr": "(sum(increase(cloudflare_zone_bandwidth_total{zone=~\"$zone\"}[$__range])) - sum(increase(cloudflare_zone_bandwidth_cached{zone=~\"$zone\"}[$__range]))) / sum(increase(cloudflare_zone_bandwidth_total{zone=~\"$zone\"}[$__range]))",
     "legendFormat": "uncached"
    }
   ]
  },
  {
   "title": "Bandwidth Content Type",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 11, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (content_type) (rate(cloudflare_zone_bandwidth_content_type{zone=~\"$zone\"}[$__range]))",
     "legendFormat": "{{content_type}}"
    }
   ]
  }
 ]
}