{
 "title": "SD CI/CD Global Health Dashboard",
 "description": "A broad summary of the health of all CI/CD jobs managed by the Service Delivery CI/CD team. Only intended for consumption by those with a lot of context about our pipelines and their various purposes.",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Versions",
    "query": "select\n  distinct concat(split_part(openshift.cluster_version, '.', 1), '.', split_part(openshift.cluster_version, '.', 2)) as versions\nfrom\n( select distinct jobs.cluster_version\n from jobs\n where jobs.job_name != ''\n and  $__timeFilter(jobs.started)) as openshift\n order by versions asc "
   }
  ]
 },
 "panels": [
  {
   "title": "Job Overall Pass Rate",
   "type": "bargauge",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "with counts as (\n\tselect\n\t\tjobs.job_name,\n\t\tcount(case when jobs.result='passed' then 1 end) as passed,\n\t\tcount(case when jobs.result='failed' then 1 end) as failed,\n\t\tcount(case when jobs.result='aborted' then 1 end) as aborted\n\tfrom\n\t\tjobs\n\twhere\n\t\t$__timeFilter(jobs.started)\n\t\tand jobs.job_name != ''\n\t\tand jobs.cluster_version like '${Versions:raw}%'\n\tgroup by\n\t\tjobs.job_name\n)\nselect\n\tjob_name,\n\t(passed::float)/(greatest(failed+aborted+passed,1)::float) as pass_rate\nfrom counts\norder by pass_rate desc\n;"
    }
   ]
  },
  {
   "title": "Job Testcase Pass Rates",
   "type": "bargauge",
   "description": "The percentage of non-skipped tests executed within a given pipeline that passed.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "with recent_tests as (\n\tselect\n\t\tjobs.*,\n\t\ttestcases.result as testresult\n\tfrom\n\t\ttestcases\n\t\tjoin jobs on jobs.id = testcases.job_id\n\twhere\n\t\t$__timeFilter(jobs.started)\n\t\tand jobs.job_name != ''\n\t\tand jobs.cluster_version like '${Versions:raw}%'\n),\ncounts as (\n\tselect\n\t\trecent_tests.job_name,\n\t\tcount(case when recent_tests.testresult='failure' then 1 end) as failure,\n\t\tcount(case when recent_tests.testresult='error' then 1 end) as error,\n\t\tcount(case when recent_tests.testresult='passed' then 1 end) as passed,\n\t\tcount(case when recent_tests.testresult='skipped' then 1 end) as skipped\n\tfrom\n\t\trecent_tests\n\tgroup by\n\t\trecent_tests.job_name\n)\nselect\n\tjob_name as name,\n\t(passed::float)/(greatest(failure+error+passed,1)::float) as metric\nfrom counts\norder by metric\n;\n"
    }
   ]
  },
  {
   "title": "Job Testcase Skip Rates",
   "type": "bargauge",
   "description": "This shows the percentage of test cases skipped by each pipeline. A certain amount of skipping is expected, as some tests do not apply to some pipelines. However, pipelines skipping most of their tests deserve investigation.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "with recent_tests as (\n\tselect\n\t\tjobs.*,\n\t\ttestcases.result as testresult\n\tfrom\n\t\ttestcases\n\t\tjoin jobs on jobs.id = testcases.job_id\n\twhere\n\t\t$__timeFilter(jobs.started)\n\t\tand jobs.job_name != ''\n\t\tand jobs.cluster_version like '${Versions:raw}%'\n),\ncounts as (\n\tselect\n\t\trecent_tests.job_name,\n\t\tcount(case when recent_tests.testresult='failure' then 1 end) as failure,\n\t\tcount(case when recent_tests.testresult='error' then 1 end) as error,\n\t\tcount(case when recent_tests.testresult='passed' then 1 end) as passed,\n\t\tcount(case when recent_tests.testresult='skipped' then 1 end) as skipped\n\tfrom\n\t\trecent_tests\n\tgroup by\n\t\trecent_tests.job_name\n)\nselect\n\tjob_name as name,\n\t(skipped::float)/(greatest(failure+error+passed+skipped,1)::float) as metric\nfrom counts\norder by metric\n;\n"
    }
   ]
  },
  {
   "title": "Install Version Pass Rate (by Job)",
   "type": "bargauge",
   "description": "The percentage of jobs with a given install version that passed.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "with counts as (\n\tselect\n\t\tjobs.cluster_version,\n\t\tcount(case when jobs.result='passed' then 1 end) as passed,\n\t\tcount(case when jobs.result='failed' then 1 end) as failed,\n\t\tcount(case when jobs.result='aborted' then 1 end) as aborted\n\tfrom\n\t\tjobs\n\twhere\n\t\t$__timeFilter(jobs.started)\n\t\tand jobs.job_name != ''\n\t\tand jobs.cluster_version like '${Versions:raw}%'\n\tgroup by\n\t\tjobs.cluster_version\n)\nselect\n\tcluster_version,\n\t(passed::float)/(greatest(failed+aborted+passed,1)::float) as pass_rate\nfrom counts\norder by pass_rate asc\n;"
    }
   ]
  },
  {
   "title": "Cluster Provisioning Failure By Environment",
   "type": "stat",
   "description": "The percentage of clusters that failed to get a cluster ID.",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select\n\tfailures.environment,\n\tfailures.count::float / total.count::float as rate\nfrom\n(\n\tselect\n\t\tenvironment,\n\t\tcount(*)\n\tfrom\n\t\tjobs\n\twhere\n\t\t$__timeFilter(jobs.started)\n\t\tand jobs.cluster_id like ''\n\t\tand jobs.job_name != ''\n\t\tand jobs.cluster_version like '${Versions:raw}%'\n\tgroup by\n\t\tenvironment\n) as failures\njoin (\n\tselect\n\t\tenvironment,\n\t\tcount(*)\n\tfrom\n\t\tjobs\n\twhere\n\t\t$__timeFilter(jobs.started)\n\tgroup by\n\t\tenvironment\n) as total\non failures.environment = total.environment\n;"
    }
   ]
  },
  {
   "title": "Problematic Test Failures",
   "type": "bargauge",
   "description": "Testcases that fail more than once in the given time window, along with the number of times they failed.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "failures" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "with recent_tests as (\n    select \n        jobs.*,\n        regexp_replace(name, '\\[(install|upgrade)\\] (.*)', '\\2') as name,\n        testcases.result as testresult\n    from jobs\n        join testcases\n        on jobs.id = testcases.job_id\n    where\n        -- filter kinds of test we do not care about\n        testcases.name !~ '.*\\[Suite: (informing|addons|conformance)\\].*'\n        -- ensure this test does belong to a suite\n        and testcases.name ~ '.*\\[Suite:.*'\n        and testcases.name !~ '.*sig-.*'\n        and $__timeFilter(jobs.started)\n        -- filter out osde2e's own CI jobs\n        and jobs.job_id != '-1'\n        and jobs.cluster_version like '${Versions:raw}%'\n), counts as (\n        -- synthesize a table with the name of a test and columns counting how often it has resulted\n        -- in each result type\n        select\n            name,\n            count(CASE WHEN recent_tests.testresult='failure' THEN 1 END) as failure,\n            count(CASE WHEN recent_tests.testresult='error' THEN 1 END) as error\n        from recent_tests\n        group by name\n)\nselect \n    counts.name,\n    (counts.error + counts.failure) as problems\nfrom\n    counts\nwhere counts.error + counts.failure > 1\norder by problems desc\n;"
    }
   ]
  },
  {
   "title": "Install Version Pass Rate (by Testcase)",
   "type": "bargauge",
   "description": "The percentage of testcases with a given install version that passed.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "with recent_tests as (\n\tselect\n\t\tjobs.*,\n\t\ttestcases.result as testresult\n\tfrom\n\t\ttestcases\n\t\tjoin jobs on jobs.id = testcases.job_id\n\twhere\n\t\t$__timeFilter(jobs.started)\n\t\tand jobs.job_name != ''\n\t\tand jobs.cluster_version like '${Versions:raw}%'\n),\ncounts as (\n\tselect\n\t\trecent_tests.cluster_version,\n\t\tcount(case when recent_tests.testresult='failure' then 1 end) as failure,\n\t\tcount(case when recent_tests.testresult='error' then 1 end) as error,\n\t\tcount(case when recent_tests.testresult='passed' then 1 end) as passed,\n\t\tcount(case when recent_tests.testresult='skipped' then 1 end) as skipped\n\tfrom\n\t\trecent_tests\n\tgroup by\n\t\trecent_tests.cluster_version\n)\nselect\n\tcluster_version,\n\t(passed::float)/(greatest(failure+error+passed,1)::float) as pass_rate\nfrom counts\norder by pass_rate\n;\n"
    }
   ]
  },
  {
   "title": "Jobs Failing to Post Results",
   "type": "bargauge",
   "description": "The number of times each job has failed to report testcase results (excluding jobs that failed to provision a cluster).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "\nselect\n\tjob_name,\n\tcount(*)\nfrom\n\tjobs\n\tleft join testcases\n\ton testcases.job_id = jobs.id\nwhere\n\t$__timeFilter(jobs.started)\n\tand testcases.id IS NULL\n\tand cluster_id IS NOT NULL and cluster_id not like ''\n\tand jobs.job_name != ''\n\tand jobs.cluster_version like '${Versions:raw}%'\ngroup by job_name\norder by count desc\n;"
    }
   ]
  }
 ]
}
{
 "title": "Addon CI/CD Health",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "addon", "query": ".*" }
  ]
 },
 "panels": [
  {
   "title": "Addon Test Success Rate",
   "type": "bargauge",
   "description": "Passing tests divided by the number of non-skipped tests.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (\n  sum by (job) (\n    count_over_time(\n      cicd_jUnitResult{job=~\".*-addon-[[addon]].*\", result=\"failed\"}[$__range]\n    )\n  ) / (\n    sum by (job) (\n      count_over_time(\n        cicd_jUnitResult{job=~\".*-addon-[[addon]].*\", result=~\"(failed|passed)\"}[$__range]\n      )\n    )\n  )\n)"
    }
   ]
  },
  {
   "title": "Failures by test case",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "count by (testname) (cicd_jUnitResult{job=~\".*-addon-$addon.*\", result=\"failed\"})",
     "legendFormat": "{{testname}}"
    }
   ]
  }
 ]
}
{
 "title": "SD-CICD Weather Report",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Job Pass Rates",
   "type": "bargauge",
   "gridPos": { "h": 29, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1 - (sum by (job) (count_over_time(cicd_jUnitResult{job=~\".*-e2e-.*\", testname !~ \".*Log Metrics.*\", result =~ \"failed\"}[12h:4h]) or vector(0)) / on(job) group_right sum by (job) (count_over_time(cicd_jUnitResult{job=~\".*-e2e-.*\", testname !~ \".*Log Metrics.*\", result =~ \"passed|failed\"}[12h:4h]))) or (sum by (job) (count_over_time(cicd_jUnitResult{job=~\".*-e2e-.*\", testname !~ \".*Log Metrics.*\", result =~ \"passed\"}[12h:4h]) or vector(0)) / on(job) group_right sum by (job) (count_over_time(cicd_jUnitResult{job=~\".*-e2e-.*\", testname !~ \".*Log Metrics.*\", result =~ \"passed|failed\"}[12h:4h])))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Install Version Pass Rates",
   "type": "bargauge",
   "gridPos": { "h": 29, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1 - (sum by (install_version) (count_over_time(cicd_jUnitResult{phase=\"install\", job=~\".*-e2e-.*\", testname !~ \".*Log Metrics.*\", result =~ \"failed\"}[12h:4h]) or vector(0)) / on(install_version) group_right sum by (install_version) (count_over_time(cicd_jUnitResult{phase=\"install\", job=~\".*-e2e-.*\", testname !~ \".*Log Metrics.*\", result =~ \"passed|failed\"}[12h:4h]))) or (sum by (install_version) (count_over_time(cicd_jUnitResult{phase=\"install\", job=~\".*-e2e-.*\", testname !~ \".*Log Metrics.*\", result =~ \"passed\"}[12h:4h]) or vector(0)) / on(install_version) group_right sum by (install_version) (count_over_time(cicd_jUnitResult{phase=\"install\", job=~\".*-e2e-.*\", testname !~ \".*Log Metrics.*\", result =~ \"passed|failed\"}[12h:4h])))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Aggregate failures by JUnitResult",
   "type": "bargauge",
   "gridPos": { "h": 29, "w": 12, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "count by (testname) (cicd_jUnitResult{job=~\".*-e2e-.*\", testname !~ \".*Log Metrics.*\", result=\"failed\"})",
     "legendFormat": "{{testname}}"
    }
   ]
  },
  {
   "title": "Upgrade Version Pass Rates",
   "type": "bargauge",
   "gridPos": { "h": 29, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1 - (sum by (upgrade_version, install_version) (count_over_time(cicd_jUnitResult{phase=\"upgrade\", job=~\".*-e2e-.*\", testname !~ \".*Log Metrics.*\", result =~ \"failed\"}[12h:4h]) or vector(0)) / on(upgrade_version, install_version) group_right sum by (upgrade_version, install_version) (count_over_time(cicd_jUnitResult{phase=\"upgrade\", job=~\".*-e2e-.*\", testname !~ \".*Log Metrics.*\", result =~ \"passed|failed\"}[12h:4h]))) or (sum by (upgrade_version, install_version) (count_over_time(cicd_jUnitResult{phase=\"upgrade\", job=~\".*-e2e-.*\", testname !~ \".*Log Metrics.*\", result =~ \"passed\"}[12h:4h]) or vector(0)) / on(upgrade_version, install_version) group_right sum by (upgrade_version, install_version) (count_over_time(cicd_jUnitResult{phase=\"upgrade\", job=~\".*-e2e-.*\", testname !~ \".*Log Metrics.*\", result =~ \"passed|failed\"}[12h:4h])))",
     "legendFormat": "{{install_version}} to {{upgrade_version}}"
    }
   ]
  }
 ]
}