{
 "title": "Staging Assisted Service Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Pods CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total {namespace=\"assisted-installer-stage\",pod=~\"assisted-service-.*\"\n} [5m]))/ sum(kube_pod_container_resource_limits_cpu_cores {namespace=\"assisted-installer-stage\",pod=~\"assisted-service-.*\"})"
    }
   ]
  },
  {
   "title": "Pods Memory Utilization",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_memory_working_set_bytes{namespace=\"assisted-installer-stage\",pod=~\"assisted-service-.*\"}[5m])) / sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"assisted-installer-stage\",pod=~\"assisted-service-.*\"}) * 100"
    }
   ]
  },
  {
   "title": "Pods Network Received ",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_network_receive_bytes_total{namespace=\"assisted-installer-stage\",pod=~\"assisted-service-.*\"})"
    }
   ]
  },
  {
   "title": "Pods Network Transmited ",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_network_transmit_bytes_total{namespace=\"assisted-installer-stage\",pod=~\"assisted-service-.*\"})"
    }
   ]
  },
  {
   "title": "Pods CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total {namespace=\"assisted-installer-stage\",pod=~\"assisted-service-.*\"\n} [5m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Pods Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"assisted-installer-stage\", pod=~\"assisted-service-.*\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Pods Network Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{namespace=\"assisted-installer-stage\",pod=~\"assisted-service-.*\"}[5m])) by (pod)",
     "legendFormat": "-> {{ pod }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{namespace=\"assisted-installer-stage\",pod=~\"assisted-service-.*\"}[5m])) by (pod)",
     "legendFormat": "<- {{ pod }}"
    }
   ]
  },
  { "title": "Building blocks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Playground usage",
   "type": "text",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 32 },
   "options": {
    "content": "# How to bulid a dashboard using this Playground\n\n## Full documentation on creating Dashboards\n\nhttps://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/app-sre/monitoring.md#VisualizationwithGrafana\n\n## Getting started with the Playground dashboard\n\nBelow you wil find all available panels to be used for a dashboard.\n\nTo start, select a panel to use, and duplicate it (`Panel options > More > Duplicate`).\n\nDrag it to the top of the screen (above the Building blocks Row) and change the panel title, metrics, and any other settings as required.\n\n\n## Saving your dashboard to Grafana\n\nSince all dashboards are managed through source control, saving dashboards is not enabled.\n\nTo save your new dashboard, export it to a JSON file (through the options on the top right of the screen) and save it locally. You will now need to create a merge request to app-interface.\n\nPlease see: https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/app-sre/monitoring.md#adding-dashboards\n\n## Tips and Tricks\n\n* Keep the `Building blocks` Row as part of the dashboard in case you require changes in the future\n* Export the dashboard with the `Building blocks` Row collapsed\n* Group panels together using a Row object (you may find some below)\n\n\nGood luck!"
   },
   "content": "# How to bulid a dashboard using this Playground\n\n## Full documentation on creating Dashboards\n\nhttps://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/app-sre/monitoring.md#VisualizationwithGrafana\n\n## Getting started with the Playground dashboard\n\nBelow you wil find all available panels to be used for a dashboard.\n\nTo start, select a panel to use, and duplicate it (`Panel options > More > Duplicate`).\n\nDrag it to the top of the screen (above the Building blocks Row) and change the panel title, metrics, and any other settings as required.\n\n\n## Saving your dashboard to Grafana\n\nSince all dashboards are managed through source control, saving dashboards is not enabled.\n\nTo save your new dashboard, export it to a JSON file (through the options on the top right of the screen) and save it locally. You will now need to create a merge request to app-interface.\n\nPlease see: https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/app-sre/monitoring.md#adding-dashboards\n\n## Tips and Tricks\n\n* Keep the `Building blocks` Row as part of the dashboard in case you require changes in the future\n* Export the dashboard with the `Building blocks` Row collapsed\n* Group panels together using a Row object (you may find some below)\n\n\nGood luck!"
  },
  {
   "title": "Graph",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ]
  },
  {
   "title": "SingleStat",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 41 },
   "format": "none",
   "valueName": "avg"
  },
  { "title": "Table", "type": "table-old", "gridPos": { "h": 7, "w": 5, "x": 10, "y": 41 } },
  {
   "title": "Text",
   "type": "text",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 41 },
   "options": { "content": "# title" },
   "content": "# title"
  },
  { "title": "Heatmap", "type": "heatmap", "gridPos": { "h": 7, "w": 5, "x": 0, "y": 48 } },
  { "title": "Alert list", "type": "alertlist", "gridPos": { "h": 7, "w": 5, "x": 5, "y": 48 } },
  { "title": "Dashboard list", "type": "dashlist", "gridPos": { "h": 7, "w": 5, "x": 10, "y": 48 } },
  { "title": "Plugin list", "type": "pluginlist", "gridPos": { "h": 7, "w": 5, "x": 15, "y": 48 } },
  {
   "title": "Row",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true
  },
  {
   "title": "Row",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "collapsed": true
  },
  {
   "title": "Row",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true
  }
 ]
}