{
 "title": "Dash.DB",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "postgres" },
   {
    "name": "cluster",
    "query": "select cluster.name from cluster order by cluster.name;"
   },
   {
    "name": "namespace",
    "query": "select namespace.name from cluster, namespace where cluster.id = namespace.cluster_id and cluster.name = '$cluster' order by namespace.name;"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Vulnerabilities",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "WITH last_token as (\n            SELECT token.id\n            FROM token, pod, namespace, cluster\n            WHERE pod.token_id = token.id\n              AND namespace.id = pod.namespace_id\n              AND cluster.name = '$cluster'\n              AND namespace.name = '$namespace'\n              AND cluster.id = namespace.cluster_id\n            ORDER BY token.timestamp DESC\n            LIMIT 1),\nvulnerabilities as (\n        SELECT\n            DISTINCT vulnerability.name as vulnerability,\n                     feature.name as feature,\n                     severity.name as severity\n        FROM cluster,\n             namespace,\n             pod,\n             image,\n             imagefeature,\n             feature,\n             vulnerability,\n             severity,\n             last_token\n        WHERE pod.namespace_id = namespace.id\n          AND namespace.cluster_id = cluster.id\n          AND cluster.id = namespace.cluster_id\n          AND pod.image_id = image.id\n          AND image.id = imagefeature.image_id\n          AND imagefeature.feature_id = feature.id\n          AND feature.id = vulnerability.feature_id\n          AND vulnerability.severity_id = severity.id\n          AND pod.token_id = last_token.id\n          AND cluster.name =  '$cluster'\n          AND namespace.name = '$namespace'\n        GROUP BY feature.name,\n                 vulnerability.name,\n                 severity.name)\nSELECT severity as metric,\n       count(feature) as value\nFROM vulnerabilities\nGROUP BY severity;"
    }
   ]
  },
  {
   "title": "Validations",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "WITH last_token as (\n            SELECT token.id\n            FROM token\n             WHERE token.data_type = 'DVODataType'    \n            ORDER BY token.timestamp DESC\n            LIMIT 1),\ndeploymentvalidations as (\n        SELECT\n            deploymentvalidation.name as objectname,\n                     validation.name as validation,\n                     validation.status as status\n        FROM cluster,\n             namespace,\n             deploymentvalidation,\n             validation,\n             last_token\n        WHERE deploymentvalidation.namespace_id = namespace.id\n          AND namespace.cluster_id = cluster.id\n          AND cluster.id = namespace.cluster_id\n          AND deploymentvalidation.token_id = last_token.id\n          AND validation.id = deploymentvalidation.validation_id\n          AND cluster.name =  '$cluster'\n          AND namespace.name = '$namespace'\n        GROUP BY deploymentvalidation.name,\n                 validation.name,\n                 validation.status)\nSELECT CONCAT(\n        REPLACE(validation,'deployment_validation_operator_',''),' ',\n        case status\n          when 0 then 'Passing'\n          when 1 then 'Failures'\n          end\n        ) as metric,\n  count(validation) as value\nFROM deploymentvalidations\nGROUP BY validation, status"
    }
   ]
  },
  {
   "title": "Vulnerability Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Container Vulnerabilities",
     "type": "table-old",
     "gridPos": { "h": 20, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "rawSql": "        WITH last_token as (\n            SELECT token.id as id\n            FROM token, pod, namespace, cluster\n            WHERE pod.token_id = token.id\n              AND namespace.id = pod.namespace_id\n              AND cluster.name = '$cluster'\n              AND namespace.name = '$namespace'\n              AND cluster.id = namespace.cluster_id\n            ORDER BY token.timestamp DESC\n            LIMIT 1)\n        SELECT\n            image.name as image,\n            feature.namespacename as source,\n            SUBSTR(image.manifest, 1, 14) as manifest,\n            COUNT(pod.name) as affected_pods,\n            vulnerability.name as vulnerability,\n            severity.name as severity,\n            feature.name as package,\n            feature.version as current_version,\n            vulnerability.fixedby as fixed_in_version,\n            vulnerability.link as url\n        FROM cluster,\n             namespace,\n             pod,\n             image,\n             imagefeature,\n             feature,\n             vulnerability,\n             severity,\n             last_token\n        WHERE pod.namespace_id = namespace.id\n          AND namespace.cluster_id = cluster.id\n          AND cluster.id = namespace.cluster_id\n          AND pod.image_id = image.id\n          AND image.id = imagefeature.image_id\n          AND imagefeature.feature_id = feature.id\n          AND feature.id = vulnerability.feature_id\n          AND vulnerability.severity_id = severity.id\n          AND pod.token_id = last_token.id\n          AND cluster.name = '$cluster'\n          AND namespace.name = '$namespace'\n        GROUP BY\n            image.name,\n            feature.namespacename,\n            image.manifest,\n            vulnerability.name,\n            severity.name,\n            feature.name,\n            feature.version,\n            vulnerability.fixedby,\n            vulnerability.link;"
      }
     ]
    }
   ]
  },
  {
   "title": "Validation Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Validations",
     "type": "table-old",
     "gridPos": { "h": 20, "w": 24, "x": 0, "y": 10 },
     "targets": [
      {
       "rawSql": "WITH last_token as (\n            SELECT token.id\n            FROM token\n            WHERE token.data_type = 'DVODataType'\n            ORDER BY token.timestamp DESC\n            LIMIT 1)\n        SELECT\n          DISTINCT deploymentvalidation.name as objectname,\n            objectkind.name as objectkind,\n            validation.name as validation,\n            case validation.status\n              when 0 then 'Passed'\n              when 1 then 'Failed'\n            end as status\n        FROM cluster,\n             namespace,\n             deploymentvalidation,\n             validation,\n             objectkind,\n             last_token\n        WHERE deploymentvalidation.namespace_id = namespace.id\n          AND namespace.cluster_id = cluster.id\n          AND cluster.id = namespace.cluster_id\n          AND deploymentvalidation.token_id = last_token.id\n          AND objectkind.id = deploymentvalidation.objectkind_id\n          AND validation.id = deploymentvalidation.validation_id\n          AND cluster.name =  '$cluster'\n          AND namespace.name = '$namespace'"
      }
     ]
    }
   ]
  }
 ]
}