{
 "title": "OCM-Quay APIs",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "rate",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "request rate for app registry api calls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "req/s" }
   ],
   "targets": [
    {
     "expr": "sum by (route)(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=~\"appr.*\"})",
     "legendFormat": "{{route}} -- ocmquayrwp01ue1"
    },
    {
     "expr": "sum by (route)(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=~\"appr.*\"})",
     "legendFormat": "{{route}} -- ocmquayrop01ue1"
    }
   ]
  },
  {
   "title": "app registry latency p95",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, route) (aggregation:quay_request_duration_seconds_bucket:rate5m:sum{route=~\"appr.*\"}))",
     "legendFormat": "{{route}} - ocmquayrwp01ue1"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le, route) (aggregation:quay_request_duration_seconds_bucket:rate5m:sum{route=~\"appr.*\"}))",
     "legendFormat": "{{route}} - ocmquayrop01ue1"
    }
   ]
  },
  {
   "title": "request rate for v1 calls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "req/s" }
   ],
   "targets": [
    {
     "expr": "sum by (route)(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=~\"v1.*\"})",
     "legendFormat": "ocmquayrwp01ue1 - {{route}}"
    },
    {
     "expr": "sum by (route)(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=~\"v1.*\"})",
     "legendFormat": "ocmquayrwo01ue1 - {{route}}"
    }
   ]
  },
  {
   "title": "v1 latency p95",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, route) (aggregation:quay_request_duration_seconds_bucket:rate5m:sum{route=~\"v1.*\"}))",
     "legendFormat": "ocmquayrwp01ue1 - {{route}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le, route) (aggregation:quay_request_duration_seconds_bucket:rate5m:sum{route=~\"v1.*\"}))",
     "legendFormat": "ocmquayrop01ue1 - {{route}}"
    }
   ]
  },
  {
   "title": "request rate for v2 calls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "req/s" }
   ],
   "targets": [
    {
     "expr": "sum by (route)(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=~\"v2.*\"})",
     "legendFormat": "ocmquayrwp01ue1 - {{route}}"
    },
    {
     "expr": "sum by (route)(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=~\"v2.*\"})",
     "legendFormat": "ocmquayrop01ue1 - {{route}}"
    }
   ]
  },
  {
   "title": "v2 latency p95",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, route) (aggregation:quay_request_duration_seconds_bucket:rate5m:sum{route=~\"v2.*\"}))",
     "legendFormat": "ocmquayrwp01ue1 - {{route}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le, route) (aggregation:quay_request_duration_seconds_bucket:rate5m:sum{route=~\"v2.*\"}))",
     "legendFormat": "ocmquayrop01ue1 - {{route}}"
    }
   ]
  },
  {
   "title": "request rate for api-user calls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "req/s" }
   ],
   "targets": [
    {
     "expr": "sum by (route)(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=~\"api.+user.*\"})",
     "legendFormat": "ocmquayrwp01ue1 - {{route}}"
    },
    {
     "expr": "sum by (route)(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=~\"api.+user.*\"})",
     "legendFormat": "ocmquayrop01ue1 - {{route}}"
    }
   ]
  },
  {
   "title": "api-user latency p95",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, route) (aggregation:quay_request_duration_seconds_bucket:rate5m:sum{route=~\"api.+user.*\"}))",
     "legendFormat": "ocmquayrwp01ue1 - {{route}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le, route) (aggregation:quay_request_duration_seconds_bucket:rate5m:sum{route=~\"api.+user.*\"}))",
     "legendFormat": "ocmquayrop01ue1 - {{route}}"
    }
   ]
  },
  {
   "title": "request rate for api-repo calls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "req/s" }
   ],
   "targets": [
    {
     "expr": "sum by (route)(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=~\"api.+repositor[iy].*\"})",
     "legendFormat": "ocmquayrwp01ue1 - {{route}}"
    },
    {
     "expr": "sum by (route)(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=~\"api.+repositor[iy].*\"})",
     "legendFormat": "ocmquayrop01ue1 - {{route}}"
    }
   ]
  },
  {
   "title": "api-repo latency p95",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, route) (aggregation:quay_request_duration_seconds_bucket:rate5m:sum{route=~\"api.+repositor[iy].*\"}))",
     "legendFormat": "ocmquayrwp01ue1 - {{route}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le, route) (aggregation:quay_request_duration_seconds_bucket:rate5m:sum{route=~\"api.+repositor[iy].*\"}))",
     "legendFormat": "ocmquayrop01ue1 - {{route}}"
    }
   ]
  },
  {
   "title": "request rate for api-org calls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short", "label": "req/s" }
   ],
   "targets": [
    {
     "expr": "sum by (route)(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=~\"api.+org.*\"})",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "api-org latency p95",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, route) (aggregation:quay_request_duration_seconds_bucket:rate5m:sum{route=~\"api.+org.*\"}))",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "request rate for the rest of calls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short", "label": "req/s" }
   ],
   "targets": [
    {
     "expr": "sum by (route)(aggregation:quay_request_duration_seconds_count:rate1m:sum{route!~\"appr.+|v[12].+|api.+user.*|api.+org.*|api.+repositor[yi].*\"})",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "api-other latency p95",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, route) (aggregation:quay_request_duration_seconds_bucket:rate5m:sum{route!~\"appr.+|v[12].+|api.+user.*|api.+org.*|api.+repositor[yi].*\"}))",
     "legendFormat": "{{route}}"
    }
   ]
  }
 ]
}