{
 "title": "Quay Stage AWS Resources (us-east-1)",
 "time": { "from": "now-30m", "to": "now-5m" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "quayio-stage-prometheus" }
  ]
 },
 "panels": [
  { "title": "AWS/RDS (quay)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "[AWS/RDS] CPUUtilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "max without(pod,instance) (aws_rds_cpuutilization_average{dbinstance_identifier=\"quayio-stage\"})",
     "legendFormat": "quayio-stage"
    }
   ]
  },
  {
   "title": "[AWS/RDS] Database Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none", "label": "Database Connections" }
   ],
   "targets": [
    {
     "expr": "max without(pod,instance) (aws_rds_database_connections_average{dbinstance_identifier=\"quayio-stage\"})",
     "legendFormat": "quayio-stage"
    }
   ]
  },
  {
   "title": "[AWS/RDS] Free Storage Space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "max without(pod,instance) (aws_rds_free_storage_space_average{dbinstance_identifier=\"quayio-stage\"})",
     "legendFormat": "quayio-stage"
    }
   ]
  },
  {
   "title": "AWS/ElastiCache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "[AWS/ElastiCache] CPUUtilization",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "max without(pod,instance) (aws_elasticache_cpuutilization_average{cache_cluster_id=\"quay-redis-001\"})",
       "legendFormat": "quay-redis-001"
      },
      {
       "expr": "max without(pod,instance) (aws_elasticache_cpuutilization_average{cache_cluster_id=\"quay-redis-002\"})",
       "legendFormat": "quay-redis-002"
      }
     ]
    },
    {
     "title": "[AWS/ElastiCache] ReplicationLag",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "max without(pod,instance) (aws_elasticache_replication_lag_average{cache_cluster_id=\"quay-redis-001\"})",
       "legendFormat": "quay-redis-001"
      },
      {
       "expr": "max without(pod,instance) (aws_elasticache_replication_lag_average{cache_cluster_id=\"quay-redis-002\"})",
       "legendFormat": "quay-redis-002"
      }
     ]
    },
    {
     "title": "[AWS/ElastiCache] CurrConnections",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "max without(pod,instance) (aws_elasticache_curr_connections_average{cache_cluster_id=\"quay-redis-001\"})",
       "legendFormat": "quay-redis-001"
      },
      {
       "expr": "max without(pod,instance) (aws_elasticache_curr_connections_average{cache_cluster_id=\"quay-redis-002\"})",
       "legendFormat": "quay-redis-002"
      }
     ]
    },
    {
     "title": "[AWS/ElastiCache] NewConnections",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 51 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "max without(pod,instance) (aws_elasticache_new_connections_average{cache_cluster_id=\"quay-redis-001\"})",
       "legendFormat": "quay-redis-001"
      },
      {
       "expr": "max without(pod,instance) (aws_elasticache_new_connections_average{cache_cluster_id=\"quay-redis-002\"})",
       "legendFormat": "quay-redis-002"
      }
     ]
    },
    {
     "title": "[AWS/ElastiCache] CacheHits",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "max without(pod,instance) (aws_elasticache_cache_hits_average{cache_cluster_id=\"quay-redis-001\"})",
       "legendFormat": "quay-redis-001"
      },
      {
       "expr": "max without(pod,instance) (aws_elasticache_cache_hits_average{cache_cluster_id=\"quay-redis-002\"})",
       "legendFormat": "quay-redis-002"
      }
     ]
    },
    {
     "title": "[AWS/ElastiCache] CacheMisses",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "max without(pod,instance) (aws_elasticache_cache_misses_average{cache_cluster_id=\"quay-redis-001\"})",
       "legendFormat": "quay-redis-001"
      },
      {
       "expr": "max without(pod,instance) (aws_elasticache_cache_misses_average{cache_cluster_id=\"quay-redis-002\"})",
       "legendFormat": "quay-redis-002"
      }
     ]
    },
    {
     "title": "[AWS/ElastiCache] NetworkBytesIn",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "max without(pod,instance) (aws_elasticache_network_bytes_in_average{cache_cluster_id=\"quay-redis-001\"})",
       "legendFormat": "quay-redis-001"
      },
      {
       "expr": "max without(pod,instance) (aws_elasticache_network_bytes_in_average{cache_cluster_id=\"quay-redis-002\"})",
       "legendFormat": "quay-redis-002"
      }
     ]
    },
    {
     "title": "[AWS/ElastiCache] NetworkBytesOut",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "max without(pod,instance) (aws_elasticache_network_bytes_out_average{cache_cluster_id=\"quay-redis-001\"})",
       "legendFormat": "quay-redis-001"
      },
      {
       "expr": "max without(pod,instance) (aws_elasticache_network_bytes_out_average{cache_cluster_id=\"quay-redis-002\"})",
       "legendFormat": "quay-redis-002"
      }
     ]
    }
   ]
  },
  {
   "title": "AWS/CloudFront",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true
  },
  {
   "title": "AWS/RDS (apostille)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "[AWS/RDS] CPUUtilization",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "max without(pod,instance) (aws_rds_cpuutilization_average{dbinstance_identifier=\"apostille-rds\"})",
       "legendFormat": "apostille rds"
      }
     ]
    },
    {
     "title": "[AWS/RDS] Database Connections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "none", "label": "Database Connections" }
     ],
     "targets": [
      {
       "expr": "max without(pod,instance) (aws_rds_database_connections_average{dbinstance_identifier=\"apostille-rds\"})",
       "legendFormat": "apostille-rds"
      }
     ]
    },
    {
     "title": "[AWS/RDS] Free Storage Space",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "max without(pod,instance) (aws_rds_free_storage_space_average{dbinstance_identifier=\"apostille-rds\"})",
       "legendFormat": "apostille-rds"
      }
     ]
    }
   ]
  }
 ]
}