{
 "title": "patchman-engine",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "namespace", "query": "prod, stage, ci, qa" },
   { "name": "evaluator", "query": ".*, upload.*, recalc.*" },
   { "name": "event", "label": "event", "query": "upload, delete, .*" },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Current values", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Manager requests",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "delta",
   "targets": [
    {
     "expr": "sum(increase(patchman_engine_requests_total{kubernetes_namespace=\"patchman-engine-$namespace\", kubernetes_name=\"patchman-engine-manager\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Manager 2xx ratio",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(patchman_engine_requests_total{kubernetes_namespace=\"patchman-engine-$namespace\", kubernetes_name=\"patchman-engine-manager\", code=~\"2.*\"}[$__range])) / sum(increase(patchman_engine_requests_total{kubernetes_namespace=\"patchman-engine-$namespace\", kubernetes_name=\"patchman-engine-manager\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Manager restarts",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "delta",
   "targets": [
    {
     "expr": "max(sum(kube_pod_container_status_restarts_total{namespace=\"patchman-engine-$namespace\", container=\"patchman-engine-manager\"}))"
    }
   ]
  },
  {
   "title": "Listener restarts",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "delta",
   "targets": [
    {
     "expr": "max(sum(kube_pod_container_status_restarts_total{namespace=\"patchman-engine-$namespace\", container=\"patchman-engine-listener\"}))"
    }
   ]
  },
  {
   "title": "Evaluator-upload restarts",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "delta",
   "targets": [
    {
     "expr": "max(sum(kube_pod_container_status_restarts_total{namespace=\"patchman-engine-$namespace\", container=~\"patchman-engine-evaluator-upload\"}))"
    }
   ]
  },
  {
   "title": "Evaluator-recalc restarts",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "delta",
   "targets": [
    {
     "expr": "max(sum(kube_pod_container_status_restarts_total{namespace=\"patchman-engine-$namespace\", container=~\"patchman-engine-evaluator-recalc\"}))"
    }
   ]
  },
  {
   "title": "VMaaS-sync restarts",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "delta",
   "targets": [
    {
     "expr": "max(kube_pod_container_status_restarts_total{namespace=\"patchman-engine-$namespace\", container=\"patchman-engine-vmaas-sync\"})"
    }
   ]
  },
  {
   "title": "Database restarts",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "format": "none",
   "valueName": "delta",
   "targets": [
    {
     "expr": "max(kube_pod_container_status_restarts_total{namespace=\"patchman-engine-$namespace\", container=\"patchman-engine-database\"})"
    }
   ]
  },
  {
   "title": "Manager 5xx ratio",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(patchman_engine_requests_total{kubernetes_namespace=\"patchman-engine-$namespace\", kubernetes_name=\"patchman-engine-manager\", code=~\"5.*\"}[$__range])) / sum(increase(patchman_engine_requests_total{kubernetes_namespace=\"patchman-engine-$namespace\", kubernetes_name=\"patchman-engine-manager\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Manager 4xx ratio",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(patchman_engine_requests_total{kubernetes_namespace=\"patchman-engine-$namespace\", kubernetes_name=\"patchman-engine-manager\", code=~\"4.*\"}[$__range])) / sum(increase(patchman_engine_requests_total{kubernetes_namespace=\"patchman-engine-$namespace\", kubernetes_name=\"patchman-engine-manager\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Evaluated uploads",
   "type": "singlestat",
   "description": "Systems evaluated using component \"patchman-engine-evaluator-upload\".",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 4 },
   "format": "none",
   "valueName": "delta",
   "targets": [
    {
     "expr": "sum(patchman_engine_evaluator_evaluation{kubernetes_namespace=\"patchman-engine-$namespace\", deployment=~\"patchman-engine-evaluator-upload-.*\", type=\"success\", role=~\"mnm|mnm-ci\"})"
    }
   ]
  },
  {
   "title": "Evaluated recalcs",
   "type": "singlestat",
   "description": "Systems evaluated using component \"patchman-engine-evaluator-recalc\".",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 4 },
   "format": "none",
   "valueName": "delta",
   "targets": [
    {
     "expr": "sum(patchman_engine_evaluator_evaluation{kubernetes_namespace=\"patchman-engine-$namespace\", deployment=~\"patchman-engine-evaluator-recalc-.*\", type=\"success\", role=~\"mnm|mnm-ci\"})"
    }
   ]
  },
  {
   "title": "Listener messages",
   "type": "singlestat",
   "description": "Messages processed using Listener",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 4 },
   "format": "none",
   "valueName": "delta",
   "targets": [
    {
     "expr": "sum(patchman_engine_listener_kafka_message_received{kubernetes_namespace=\"patchman-engine-$namespace\", event=~\"$event\", role=~\"mnm|mnm-ci\"})"
    }
   ]
  },
  { "title": "Golden signals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Manager traffic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(patchman_engine_requests_total{kubernetes_namespace=\"patchman-engine-$namespace\", kubernetes_name=\"patchman-engine-manager\", role=~\"mnm|mnm-ci\"}[$interval])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Manager latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "1000 * sum(rate(patchman_engine_request_duration_seconds_sum{kubernetes_namespace=\"patchman-engine-$namespace\", kubernetes_name=\"patchman-engine-manager\", role=~\"mnm|mnm-ci\"}[$interval])) / sum(rate(patchman_engine_request_duration_seconds_count{kubernetes_namespace=\"patchman-engine-$namespace\", kubernetes_name=\"patchman-engine-manager\", role=~\"mnm|mnm-ci\"}[$interval]))"
    }
   ]
  },
  {
   "title": "CPU consumed",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"patchman-engine-$namespace\",container_name=\"patchman-engine-manager\"}[1m])) / sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"patchman-engine-$namespace\",container=\"patchman-engine-manager\"})",
     "legendFormat": "manager"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"patchman-engine-$namespace\",container_name=\"patchman-engine-listener\"}[1m])) / sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"patchman-engine-$namespace\",container=\"patchman-engine-listener\"})",
     "legendFormat": "listener"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"patchman-engine-$namespace\",container_name=~\"patchman-engine-evaluator-upload\"}[1m])) / sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"patchman-engine-$namespace\",container=~\"patchman-engine-evaluator-upload\"})",
     "legendFormat": "evaluator-upload"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"patchman-engine-$namespace\",container_name=~\"patchman-engine-evaluator-recalc\"}[1m])) / sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"patchman-engine-$namespace\",container=~\"patchman-engine-evaluator-recalc\"})",
     "legendFormat": "evaluator-recalc"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"patchman-engine-$namespace\",container_name=\"patchman-engine-vmaas-sync\"}[1m])) / sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"patchman-engine-$namespace\",container=\"patchman-engine-vmaas-sync\"})",
     "legendFormat": "vmaas-sync"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"patchman-engine-$namespace\",container_name=\"patchman-engine-database\"}[1m])) / sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"patchman-engine-$namespace\",container=\"patchman-engine-database\"})",
     "legendFormat": "database"
    }
   ]
  },
  {
   "title": "Memory consumed",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"patchman-engine-$namespace\",container_name=\"patchman-engine-manager\"}) / sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"patchman-engine-$namespace\",container=\"patchman-engine-manager\"})",
     "legendFormat": "manager"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"patchman-engine-$namespace\",container_name=\"patchman-engine-listener\"}) / sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"patchman-engine-$namespace\",container=\"patchman-engine-listener\"})",
     "legendFormat": "listener"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"patchman-engine-$namespace\",container_name=~\"patchman-engine-evaluator-upload\"}) / sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"patchman-engine-$namespace\",container=~\"patchman-engine-evaluator-upload\"})",
     "legendFormat": "evaluator-upload"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"patchman-engine-$namespace\",container_name=~\"patchman-engine-evaluator-recalc\"}) / sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"patchman-engine-$namespace\",container=~\"patchman-engine-evaluator-recalc\"})",
     "legendFormat": "evaluator-recalc"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"patchman-engine-$namespace\",container_name=\"patchman-engine-vmaas-sync\"}) / sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"patchman-engine-$namespace\",container=\"patchman-engine-vmaas-sync\"})",
     "legendFormat": "vmaas-sync"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"patchman-engine-$namespace\",container_name=\"patchman-engine-database\"}) / sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"patchman-engine-$namespace\",container=\"patchman-engine-database\"})",
     "legendFormat": "database"
    }
   ]
  },
  { "title": "Advanced", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Containers restarts",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"patchman-engine-$namespace\", container=~\"patchman-engine-.*\"}) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Kafka consumer lag",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumer_group_lag{kubernetes_namespace='platform-mq-$namespace', group='patchman', role=~\"mnm|mnm-ci\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Listener message handling duration",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum(increase(patchman_engine_listener_kafka_message_handling_duration_seconds_bucket{kubernetes_namespace=\"patchman-engine-$namespace\", event=~\"$event\", role=~\"mnm|mnm-ci\"}[$interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Listener processed messages",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(patchman_engine_listener_kafka_message_received{kubernetes_namespace=\"patchman-engine-$namespace\", event=~\"$event\", role=~\"mnm|mnm-ci\"}[$interval])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "System evaluation duration",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum(increase(patchman_engine_evaluator_evaluation_duration_seconds_bucket{kubernetes_namespace=\"patchman-engine-$namespace\", deployment=~\"patchman-engine-evaluator-$evaluator\", role=~\"mnm|mnm-ci\"}[$interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "System evaluations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(patchman_engine_evaluator_evaluation{kubernetes_namespace=\"patchman-engine-$namespace\", deployment=~\"patchman-engine-evaluator-$evaluator\", role=~\"mnm|mnm-ci\"}[$interval])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Evaluation part duration median",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(patchman_engine_evaluator_evaluation_part_duration_seconds_bucket{kubernetes_namespace=\"patchman-engine-$namespace\", deployment=~\"patchman-engine-evaluator-$evaluator\", role=~\"mnm|mnm-ci\"}[$interval])) by (part, le))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{part}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "System evaluations - patched/unpatched",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(patchman_engine_evaluator_updates{kubernetes_namespace=\"patchman-engine-$namespace\", deployment=~\"patchman-engine-evaluator-$evaluator\", role=~\"mnm|mnm-ci\"}[$interval])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Sync duration (vmaas_sync)",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "sum(increase(patchman_engine_vmaas_sync_sync_duration_seconds_bucket{kubernetes_namespace=\"patchman-engine-$namespace\", role=~\"mnm|mnm-ci\"}[$interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "External services",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(patchman_engine_vmaas_sync_vmaas_call{kubernetes_namespace=\"patchman-engine-$namespace\", role=~\"mnm|mnm-ci\"}[$interval])) by (type)",
     "legendFormat": "VMaaS Sync - {{type}}"
    },
    {
     "expr": "sum(increase(patchman_engine_manager_dependency_call{kubernetes_namespace=\"patchman-engine-$namespace\", name=\"rbac\"}[$interval])) by (name, status)",
     "legendFormat": "{{name}} - {{status}}"
    }
   ]
  },
  {
   "title": "Database items - systems",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(patchman_engine_vmaas_sync_systems{kubernetes_namespace=\"patchman-engine-$namespace\", role=~\"mnm|mnm-ci\", last_upload=~\"last.*\"}) by (last_upload)",
     "legendFormat": "last_upload: {{last_upload}}"
    },
    {
     "expr": "sum(patchman_engine_vmaas_sync_systems{kubernetes_namespace=\"patchman-engine-$namespace\", role=~\"mnm|mnm-ci\", opt_out=\"on\"})",
     "legendFormat": "opt outed"
    },
    {
     "expr": "sum(patchman_engine_vmaas_sync_systems{kubernetes_namespace=\"patchman-engine-$namespace\", role=~\"mnm|mnm-ci\", last_upload=\"all\"})",
     "legendFormat": "all"
    }
   ]
  },
  {
   "title": "Database items - advisories",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(patchman_engine_vmaas_sync_advisories{kubernetes_namespace=\"patchman-engine-$namespace\", role=~\"mnm|mnm-ci\"}) by (type)",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sum(patchman_engine_vmaas_sync_advisories{kubernetes_namespace=\"patchman-engine-$namespace\", role=~\"mnm|mnm-ci\"})",
     "legendFormat": "all"
    }
   ]
  },
  {
   "title": "RDS data capacity usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rdsosmetrics_fileSys_usedPercent{instance=\"patchman-prod\"}) by (mount_point)",
     "legendFormat": "{{mount_point}}"
    }
   ]
  },
  {
   "title": "RDS CPU usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(rdsosmetrics_processList_cpuUsedPc{instance=\"patchman-prod\", role=\"mnm\"}, \"db_user\", \"$1\", \"name\", \"postgres: ([^ ]+) .+\")) by (db_user)",
     "legendFormat": "{{db_user}}"
    },
    {
     "expr": "sum(rdsosmetrics_processList_cpuUsedPc{instance='patchman-prod', role=~\"mnm\"})",
     "legendFormat": "sum"
    }
   ]
  }
 ]
}