{
 "title": "Deadman's Snitch Operator",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hive",
    "label": "Hive Cluster",
    "query": "label_values(dms_operator_reconcile_duration_seconds_count, job)"
   }
  ]
 },
 "panels": [
  {
   "title": "Controller P90 Reconcile Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(dms_operator_reconcile_duration_seconds_bucket{name=\"deadmanssnitch-operator\", job=\"$hive\"}[5m]))"
    }
   ]
  },
  {
   "title": "Controller Reconciler Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(dms_operator_reconcile_duration_seconds_count{name=\"deadmanssnitch-operator\", job=\"$hive\"}[5m])"
    }
   ]
  },
  {
   "title": "Kube API Call P90 Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by (method, resource, le) (rate(dms_operator_api_request_duration_seconds_bucket{name=\"deadmanssnitch-operator\", job=\"$hive\"}[5m])))",
     "legendFormat": "{{method}} {{resource}}"
    }
   ]
  },
  {
   "title": "Kube API Calls",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (method, resource) (rate(dms_operator_api_request_duration_seconds_count{name=\"deadmanssnitch-operator\", job=\"$hive\"}[5m]))",
     "legendFormat": "{{method}} {{resource}}"
    }
   ]
  },
  {
   "title": "Snitch API P90 Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by (method, le) (rate(dms_operator_snitch_api_call_duration_seconds_bucket{name=\"deadmanssnitch-operator\", job=\"$hive\"}[5m])))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Snitch API Calls",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (method) (rate(dms_operator_snitch_api_call_duration_seconds_count{name=\"deadmanssnitch-operator\", job=\"$hive\"}[5m]))",
     "legendFormat": "{{method}}"
    }
   ]
  }
 ]
}