{
 "title": "Draft-AppSRE Overview",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  { "title": "app-interface", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "app-interface merged MRs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(qontract_reconcile_merged_merge_requests_total{project_id=\"13582\"}[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Merge requests merged in <1 hour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(qontract_reconcile_time_to_merge_merge_request_minutes_bucket{project_id=\"13582\", le=\"60.0\"}[24h])) / sum(increase(qontract_reconcile_time_to_merge_merge_request_minutes_bucket{project_id=\"13582\", le=\"+Inf\"}[24h])) * 100",
     "legendFormat": "All MRs"
    }
   ]
  },
  {
   "title": "Tenant SLOs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true
  },
  {
   "title": "Tenant SLO achievement for previous month",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(case when serviceslo.target > serviceslo.value then 1 else 0 end) as missed, sum(case when serviceslo.target <= serviceslo.value then 1 else 0 end) as achieved\nFROM cluster, namespace, service, serviceslo, slitype, slodoc\nWHERE serviceslo.slitype_id = slitype.id\n  AND serviceslo.slodoc_id = slodoc.id\n  AND serviceslo.service_id = service.id\n  AND serviceslo.namespace_id = namespace.id\n  AND namespace.cluster_id = cluster.id\n  AND serviceslo.token_id = (\n        SELECT distinct(token.id)\n        FROM token, latesttokens, serviceslo\n        WHERE token.id = latesttokens.token_id\n        AND token.data_type = 'SLODataType'\n        AND serviceslo.token_id = token.id\n  );"
    }
   ]
  },
  {
   "title": "Tenant Missed SLOs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT service.name as service_name, serviceslo.name as slo_name, serviceslo.target as target_slo, serviceslo.value as observed_value\nFROM cluster, namespace, service, serviceslo, slitype, slodoc\nWHERE serviceslo.slitype_id = slitype.id\n  AND serviceslo.slodoc_id = slodoc.id\n  AND serviceslo.service_id = service.id\n  AND serviceslo.namespace_id = namespace.id\n  AND namespace.cluster_id = cluster.id\n  AND serviceslo.token_id = (\n        SELECT distinct(token.id)\n        FROM token, latesttokens, serviceslo\n        WHERE token.id = latesttokens.token_id\n        AND token.data_type = 'SLODataType'\n        AND serviceslo.token_id = token.id\n  )\n  AND serviceslo.target > serviceslo.value;"
    }
   ]
  }
 ]
}