{
 "title": "OSIO Capacity",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  { "title": "starter-us-east-2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilisation",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "1 - avg(rate(node_cpu{mode=\"idle\"}[1m]))"
    }
   ]
  },
  {
   "title": "Memory Utilisation",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "1 - sum(:node_memory_MemFreeCachedBuffers:sum) / sum(:node_memory_MemTotal:sum)"
    }
   ]
  },
  {
   "title": "PV available",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_persistentvolume_status_phase{phase=\"Available\"})"
    }
   ]
  },
  {
   "title": "Che namespaces",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_namespace_status_phase{phase=\"Active\",namespace=~\"^.*che$\"})"
    }
   ]
  },
  {
   "title": "Workspace pods",
   "type": "singlestat",
   "description": "2 pods per workspace",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_info{pod=~\"^workspace.*\"})",
     "legendFormat": "Pods"
    }
   ]
  },
  {
   "title": "Pod count (excl. system pods)",
   "type": "singlestat",
   "description": "Excludes system pods (see query)",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace!~\"^(default|openshift-|kube-|logging|ops-|gluster-|k8s-image-puller).*\",phase=\"Running\"})",
     "legendFormat": "Pods"
    }
   ]
  },
  {
   "title": "Subscribers",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "onlinereg_subscriber_limit{plan=\"starter-us-east-2\"}",
     "legendFormat": "Limit"
    },
    {
     "expr": "onlinereg_capacity_consumed{plan=\"starter-us-east-2\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "onlinereg_hidden{plan=\"starter-us-east-2\"}",
     "legendFormat": "Hidden"
    }
   ]
  },
  { "title": "starter-us-east-2a", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU Utilisation",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "1 - avg(rate(node_cpu{mode=\"idle\"}[1m]))"
    }
   ]
  },
  {
   "title": "Memory Utilisation",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 6 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "1 - sum(:node_memory_MemFreeCachedBuffers:sum) / sum(:node_memory_MemTotal:sum)"
    }
   ]
  },
  {
   "title": "PV available",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_persistentvolume_status_phase{phase=\"Available\"})"
    }
   ]
  },
  {
   "title": "Che namespaces",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_namespace_status_phase{phase=\"Active\",namespace=~\"^.*che$\"})"
    }
   ]
  },
  {
   "title": "Workspace pods",
   "type": "singlestat",
   "description": "2 pods per workspace",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_info{pod=~\"^workspace.*\"})",
     "legendFormat": "Pods"
    }
   ]
  },
  {
   "title": "Pod count (excl. system pods)",
   "type": "singlestat",
   "description": "Excludes system pods (see query)",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace!~\"^(default|openshift-|kube-|logging|ops-|gluster-|k8s-image-puller).*\",phase=\"Running\"})"
    }
   ]
  },
  {
   "title": "Subscribers",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 18, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "onlinereg_subscriber_limit{plan=\"starter-us-east-2a\"}",
     "legendFormat": "Limit"
    },
    {
     "expr": "onlinereg_capacity_consumed{plan=\"starter-us-east-2a\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "onlinereg_hidden{plan=\"starter-us-east-2a\"}",
     "legendFormat": "Hidden"
    }
   ]
  },
  { "title": "starter-us-east-1a", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "CPU Utilisation",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 11 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "1 - avg(rate(node_cpu{mode=\"idle\"}[1m]))"
    }
   ]
  },
  {
   "title": "Memory Utilisation",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 11 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "1 - sum(:node_memory_MemFreeCachedBuffers:sum) / sum(:node_memory_MemTotal:sum)"
    }
   ]
  },
  {
   "title": "PV available",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_persistentvolume_status_phase{phase=\"Available\"})"
    }
   ]
  },
  {
   "title": "Che namespaces",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_namespace_status_phase{phase=\"Active\",namespace=~\"^.*che$\"})"
    }
   ]
  },
  {
   "title": "Workspace pods",
   "type": "singlestat",
   "description": "2 pods per workspace",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_info{pod=~\"^workspace.*\"})",
     "legendFormat": "Pods"
    }
   ]
  },
  {
   "title": "Pod count (excl. system pods)",
   "type": "singlestat",
   "description": "Excludes system pods (see query)",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace!~\"^(default|openshift-|kube-|logging|ops-|gluster-|k8s-image-puller).*\",phase=\"Running\"})"
    }
   ]
  },
  {
   "title": "Subscribers",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 18, "y": 11 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "onlinereg_subscriber_limit{plan=\"starter-us-east-1a\"}",
     "legendFormat": "Limit"
    },
    {
     "expr": "onlinereg_capacity_consumed{plan=\"starter-us-east-1a\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "onlinereg_hidden{plan=\"starter-us-east-1a\"}",
     "legendFormat": "Hidden"
    }
   ]
  },
  { "title": "starter-us-east-1b", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "CPU Utilisation",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 16 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "1 - avg(rate(node_cpu{mode=\"idle\"}[1m]))"
    }
   ]
  },
  {
   "title": "Memory Utilisation",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 16 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "1 - sum(:node_memory_MemFreeCachedBuffers:sum) / sum(:node_memory_MemTotal:sum)"
    }
   ]
  },
  {
   "title": "PV available",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_persistentvolume_status_phase{phase=\"Available\"})"
    }
   ]
  },
  {
   "title": "Che namespaces",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_namespace_status_phase{phase=\"Active\",namespace=~\"^.*che$\"})"
    }
   ]
  },
  {
   "title": "Workspace pods",
   "type": "singlestat",
   "description": "2 pods per workspace",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_info{pod=~\"^workspace.*\"})",
     "legendFormat": "Pods"
    }
   ]
  },
  {
   "title": "Pod count (excl. system pods)",
   "type": "singlestat",
   "description": "Excludes system pods (see query)",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace!~\"^(default|openshift-|kube-|logging|ops-|gluster-|k8s-image-puller).*\",phase=\"Running\"})"
    }
   ]
  },
  {
   "title": "Subscribers",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 18, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "onlinereg_subscriber_limit{plan=\"starter-us-east-1b\"}",
     "legendFormat": "Limit"
    },
    {
     "expr": "onlinereg_capacity_consumed{plan=\"starter-us-east-1b\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "onlinereg_hidden{plan=\"starter-us-east-1b\"}",
     "legendFormat": "Hidden"
    }
   ]
  }
 ]
}