{
 "title": "Resource Utilization",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Pod CPU Usage In Seconds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "velocityms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"assisted-service-.*\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod Memory Usage In Megabytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{pod=~\"assisted-service-.*\"}) by (pod) / 1048576",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "HAProxy Backend Connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "connections" }
   ],
   "targets": [
    {
     "expr": "sum(rate(haproxy_backend_connections_total{route=\"assisted-service\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "HAProxy Backend Connections Total",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(haproxy_backend_connections_total{route=\"assisted-service\"}[5m]))"
    }
   ]
  },
  {
   "title": "External Services",
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 22 },
   "content": "\n# Database Metrics - AWS RDS\n\nFind those under the main AWS-RDS Grafana Folder.\n\n* [AWS-RDS Production](https://grafana.app-sre.devshift.net/d/aws-rds/aws-rds?var-region=default&var-dbinstanceidentifier=assisted-installer)\n\n\n* [AWS-RDS Stage](https://grafana.app-sre.devshift.net/d/mYKUDXdMk/aws-rds?orgId=1&var-region=default&var-dbinstanceidentifier=assisted-installer-stage)",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{pod=~\"assisted-service-.*\"}) by (pod) / 1048576"
    }
   ]
  }
 ]
}