{
 "title": "PagerDuty operator",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "environment",
    "label": "Hive Instance",
    "query": "label_values(pagerduty_heartbeat, job)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"$environment\"}",
     "legendFormat": "alloc all"
    },
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"$environment\"}",
     "legendFormat": "alloc heap"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=\"$environment\"}[30s])",
     "legendFormat": "alloc rate all"
    },
    {
     "expr": "rate(go_memstats_heap_alloc_bytes{job=\"$environment\"}[30s])",
     "legendFormat": "alloc rate heap"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{job=\"$environment\"}",
     "legendFormat": "inuse stack"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"$environment\"}",
     "legendFormat": "inuse heap"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"$environment\"}",
     "legendFormat": "goroutines"
    }
   ]
  },
  {
   "title": "GC Time Quantiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=\"$environment\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Building blocks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Playground usage",
     "type": "text",
     "gridPos": { "h": 9, "w": 20, "x": 0, "y": 10 },
     "content": "# How to bulid a dashboard using this Playground\n\n## Full documentation\n\nhttps://gitlab.cee.redhat.com/service/dev-guidelines/blob/master/monitoring.md\n\n## Getting started\n\nBelow you wil find all available panels to be used for a dashboard.\n\nTo start, select a panel to use, and duplicate it (`Panel options > More > Duplicate`).\n\nDrag it to the top of the screen (above the Building blocks Row) and change the panel title, metrics, and any other settings as required.\n\n\n## Saving your dashboard\n\n\nSince all dashboards are managed through source control, saving dashboards is not enabled.\n\nTo save your new dashboard, export it to a JSON file (through the options on the top right of the screen) and save it locally.\n\n\n## Adding your dashboard\n\nTo add your dashboard, follow these steps:\n\n1. Create a Merge Request to the following git repository:\nhttps://gitlab.cee.redhat.com/service/app-sre-observability\n\n2. Add the JSON content to a `ConfigMap` resource:\n\n```\nkind: ConfigMap\napiVersion: v1\nmetadata:\n  name: grafana-dashboard-my-dashboard\ndata:\n  my-dashboard.json: |-\n    $RAW_JSON\n```\n\nThe `ConfigMap` file name should conform with `grafana-dashboard-my-dashboard.configmap.yaml`. Add it under the `grafana` directory.\n\n3. Add a section to `volumes` and a corresponding `volumeMount` in the Deployment resource: `grafana/grafana.deployment.yaml`.\n\nSee this MR as an example: https://gitlab.cee.redhat.com/service/app-sre-observability/merge_requests/11\n\n## Tips and Tricks\n\n* Keep the `Building blocks` Row as part of the dashboard in case you require changes in the future\n* Export the dashboard with the `Building blocks` Row collapsed\n* Group panels together using a Row object (you may find some below)\n\n\nGood luck!"
    },
    {
     "title": "Graph",
     "type": "graph",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ]
    },
    {
     "title": "SingleStat",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 5, "x": 5, "y": 19 },
     "format": "none",
     "valueName": "avg"
    },
    { "title": "Table", "type": "table", "gridPos": { "h": 7, "w": 5, "x": 10, "y": 19 } },
    { "title": "Text", "type": "text", "gridPos": { "h": 7, "w": 5, "x": 15, "y": 19 }, "content": "# title" },
    { "title": "Heatmap", "type": "heatmap", "gridPos": { "h": 7, "w": 5, "x": 0, "y": 26 } },
    { "title": "Alert list", "type": "alertlist", "gridPos": { "h": 7, "w": 5, "x": 5, "y": 26 } },
    { "title": "Dashboard list", "type": "dashlist", "gridPos": { "h": 7, "w": 5, "x": 10, "y": 26 } },
    { "title": "Plugin list", "type": "pluginlist", "gridPos": { "h": 7, "w": 5, "x": 15, "y": 26 } }
   ]
  }
 ]
}