{
 "title": "Hive Metrics",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": "label_values(hive_cluster_deployments, job)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Clusters",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum without(instance, __name__, job, age_lt,endpoint,namespace,pod,service)(hive_cluster_deployments{age_lt=\"+Inf\",job=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Cluster Activity Last 24h",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "sum without(Time,instance,job,endpoint,namespace,pod,service)(increase(hive_cluster_deployments_created_total{job=\"$instance\"}[24h])) ",
     "legendFormat": "Created"
    },
    {
     "expr": "sum without(Time,instance,job,endpoint,namespace,pod,service)(increase(hive_cluster_deployments_installed_total{job=\"$instance\"}[24h])) ",
     "legendFormat": "Installed"
    },
    {
     "expr": "sum without(Time,instance,job,endpoint,namespace,pod,service)(increase(hive_cluster_deployments_deleted_total{job=\"$instance\"}[24h])) ",
     "legendFormat": "Deleted"
    }
   ]
  },
  {
   "title": "Clusters Provisioning Over 2h",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum without(instance,job,endpoint,namespace,pod,service)((hive_cluster_deployment_provision_underway_seconds{job=\"$instance\"} > 7200) / 60)"
    }
   ]
  },
  {
   "title": "Clusters Deprovisioning Over 2h",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 6 },
   "targets": [
    {
     "expr": "sum without(instance,job,endpoint,namespace,pod,service)((hive_cluster_deployment_deprovision_underway_seconds{job=\"$instance\"} > 7200) / 60)"
    }
   ]
  },
  {
   "title": "Total Clusters",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(endpoint,instance,job,pod,namespace,service)(hive_cluster_deployments{age_lt=\"+Inf\",job=\"$instance\"})",
     "legendFormat": "{{cluster_type}}"
    },
    {}
   ]
  },
  {
   "title": "Running Install Jobs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(endpoint,instance,job,namespace,pod,service)(hive_install_jobs{job=\"$instance\",state!=\"succeeded\"})",
     "legendFormat": "{{cluster_type}} {{state}}"
    }
   ]
  },
  {
   "title": "Install Job Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(sum without(endpoint,instance,job,namespace,pod,service)(rate(hive_cluster_deployment_install_job_duration_seconds_sum{job=\"$instance\"}[48h]))) / (sum without(endpoint,instance,job,namespace,pod,service)(rate(hive_cluster_deployment_install_job_duration_seconds_count{job=\"$instance\"}[48h])))",
     "legendFormat": "Duration"
    }
   ]
  },
  {
   "title": "DNS + Install Delay",
   "type": "graph",
   "description": "Delay due to creating and waiting for resolving DNS, and total wait for the install to launch.",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(sum without(instance,pod,namespace,service,job)(rate(hive_cluster_deployment_install_job_delay_seconds_sum{job=\"$instance\"}[6h]))) / (sum without(instance,pod,namespace,service,job)(rate(hive_cluster_deployment_install_job_delay_seconds_count{job=\"$instance\"}[6h])))",
     "legendFormat": "Total Install Delay"
    },
    {
     "expr": "(sum without(instance,pod,namespace,service,job)(rate(hive_cluster_deployment_dns_delay_seconds_sum{job=\"$instance\"}[6h]))) / (sum without(instance,pod,namespace,service,job)(rate(hive_cluster_deployment_dns_delay_seconds_count{job=\"$instance\"}[6h])))",
     "legendFormat": "DNS Delay"
    }
   ]
  },
  {
   "title": "Install Job Failure Rate",
   "type": "graph",
   "description": "Rate of install job failures for known reasons. (as determined by parsing install log summaries)",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(instance,pod,namespace,service,job)(rate(hive_install_errors{job=\"$instance\"}[6h]))",
     "legendFormat": "{{cluster_type}} {{reason}}"
    }
   ]
  },
  {
   "title": "Avg Install Restarts",
   "type": "graph",
   "description": "Average number of restarts across all install jobs.",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum without(instance,pod,namespace,service,job)(rate(hive_cluster_deployment_completed_install_restart_sum{job=\"$instance\"}[12h])))\n/ \n(sum without(instance,pod,namespace,service,job)(rate(hive_cluster_deployment_completed_install_restart_count{job=\"$instance\"}[12h])))",
     "legendFormat": "{{cluster_type}}"
    }
   ]
  },
  {
   "title": "90% Seconds to Install Job",
   "type": "graph",
   "description": "Time to install job for 90% of clusters installed over last 48 hours.",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, (sum without(instance,pod,namespace,service,job)(rate(hive_cluster_deployment_install_job_delay_seconds_bucket{job=\"$instance\"}[12h]))))"
    }
   ]
  },
  {
   "title": "SelectorSyncSet Time To First Success Per Cluster",
   "type": "graph",
   "description": "Average time for a matching cluster to first successfully apply this SelectorSyncSet.",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(sum without(instance,pod,namespace,service,job,endpoint)(hive_selectorsyncset_apply_duration_seconds_sum{job=\"$instance\"}))\n/\n(sum without(instance,pod,namespace,service,job,endpoint)(hive_selectorsyncset_apply_duration_seconds_count{job=\"$instance\"}))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "SyncSet Time To First Success Per Cluster",
   "type": "graph",
   "description": "Average time for a non-Selector SyncSet to first successfully apply per cluster. Includes all SyncSets.",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 38 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(sum without(instance,pod,namespace,service,job,endpoint)(hive_syncset_apply_duration_seconds_sum{job=\"$instance\"}))\n/\n(sum without(instance,pod,namespace,service,job,endpoint)(hive_syncset_apply_duration_seconds_count{job=\"$instance\"}))",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Cluster Conditions",
   "type": "graph",
   "description": "Gauge on clusters with conditions set to true.",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum without(instance,pod,namespace,service,job,endpoint)(hive_cluster_deployments_conditions{job=\"$instance\",cluster_type=\"managed\",age_lt=\"+Inf\"})) > 0",
     "legendFormat": "{{ condition }}"
    }
   ]
  },
  {
   "title": "SelectorSyncSets Failing %",
   "type": "table-old",
   "description": "Shows the percentage of failures for any SelectorSyncSets failing on more than 10% of the clusters that match the selector.",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 46 },
   "targets": [
    {
     "expr": "sum without(instance,job)((hive_selectorsyncset_clusters_unapplied_total{job=\"$instance\"} / hive_selectorsyncset_clusters_total{job=\"$instance\"}) * 100 > 10)"
    }
   ]
  },
  {
   "title": "Controller Reconcile Rate",
   "type": "graph",
   "description": "Rate of success/error from the cluster deployment controller reconcile loop.",
   "gridPos": { "h": 14, "w": 9, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short", "label": "reconciles per second" }
   ],
   "targets": [
    {
     "expr": "(sum without(instance,pod,namespace,service,job,endpoint)(rate(controller_runtime_reconcile_total{result=~\"success|error\",job=\"$instance\"}[15m])))",
     "legendFormat": "{{controller}} {{result}}"
    }
   ]
  },
  {
   "title": "Controller Reconcile Time",
   "type": "graph",
   "description": "Currently includes time spent in the queue if blocking.",
   "gridPos": { "h": 14, "w": 9, "x": 9, "y": 54 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(sum without(instance,pod,namespace,service,job,endpoint)(rate(hive_controller_reconcile_seconds_sum{job=\"$instance\"}[15m]))) \n/ \n(sum without(instance,pod,namespace,service,job,endpoint)(rate(hive_controller_reconcile_seconds_count{job=\"$instance\"}[15m])))",
     "legendFormat": "{{controller}} {{outcome}}"
    }
   ]
  },
  {
   "title": "Local (hive cluster) kube client requests - non-POST",
   "type": "graph",
   "description": "Rate of non-POST requests to the hive cluster's Kube API. Anything over 15 indicates a hotloop, but not urgent enough to scale down Hive.",
   "gridPos": { "h": 14, "w": 9, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short", "label": "requests per second" }
   ],
   "targets": [
    {
     "expr": "sum without(resource,response,status,instance,pod,namespace,job,service)(rate(hive_kube_client_requests_total{job=\"$instance\",method!=\"POST\",remote=\"false\"}[15m]))",
     "legendFormat": "{{ controller }} - {{ method }}"
    }
   ]
  },
  {
   "title": "Local (hive cluster) kube client requests - POST (anything near 20 is an urgent problem)",
   "type": "graph",
   "description": "Rate of POST requests to the hive cluster's Kube API. Anything in the 19-20 range indicates a hotloop of etcd creations. This is an urgent scale down Hive situation!",
   "gridPos": { "h": 14, "w": 9, "x": 9, "y": 68 },
   "yaxes": [
    { "format": "short", "label": "requests per second" }
   ],
   "targets": [
    {
     "expr": "sum without(resource,response,status,job,pod,namespace,instance,service)(rate(hive_kube_client_requests_total{job=\"$instance\",method=\"POST\",remote=\"false\"}[15m]))",
     "legendFormat": "{{ controller }} - {{ method }}"
    }
   ]
  },
  {
   "title": "Remote (to managed clusters) kube client requests - non-POST",
   "type": "graph",
   "description": "Rate of remote non-POST requests to the Kube API of managed clusters, e.g. for syncset applies. Anything over 15 indicates a hotloop, but not urgent enough to scale down Hive.",
   "gridPos": { "h": 14, "w": 9, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "short", "label": "requests per second" }
   ],
   "targets": [
    {
     "expr": "sum without(resource,response,status,instance,pod)(rate(hive_kube_client_requests_total{job=\"$instance\",remote=\"true\",method!=\"POST\"}[15m]))",
     "legendFormat": "{{controller}} - {{method}}"
    }
   ]
  },
  {
   "title": "Remote (to managed clusters) kube client requests - POST",
   "type": "graph",
   "description": "Rate of remote POST requests to the Kube API of managed clusters, e.g. for syncset applies.  Anything in the 19-20 range indicates a hotloop of etcd creations. This is an urgent scale down Hive situation!",
   "gridPos": { "h": 14, "w": 9, "x": 9, "y": 82 },
   "yaxes": [
    { "format": "short", "label": "requests per second" }
   ],
   "targets": [
    {
     "expr": "sum without(resource,response,status,instance,pod,namespace,service,job)(rate(hive_kube_client_requests_total{job=\"$instance\",remote=\"true\",method=\"POST\"}[15m]))",
     "legendFormat": "{{controller}} - {{method}}"
    }
   ]
  },
  {
   "title": "ClusterSync Apply Time",
   "type": "graph",
   "description": "Average time applys of individual resources are taking.",
   "gridPos": { "h": 14, "w": 9, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(sum without(endpoint,instance,job,namespace,pod,service)(rate(hive_syncsetinstance_apply_duration_seconds_sum[15m]))) \n/ \n(sum without(endpoint,instance,job,namespace,pod,service)(rate(hive_syncsetinstance_apply_duration_seconds_count[15m])))",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Remote Kube Request Time",
   "type": "graph",
   "description": "Average time requests to remote Kube clusters are taking.",
   "gridPos": { "h": 14, "w": 9, "x": 9, "y": 96 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(sum without(endpoint, instance, job, namespace, pod, service, resource, controller, remote, status)(rate(hive_kube_client_request_seconds_sum{remote=\"true\"}[15m])))\n/\n(sum without(endpoint, instance, job, namespace, pod, service, resource, controller, remote, status)(rate(hive_kube_client_request_seconds_count{remote=\"true\"}[15m])))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "ClusterSync Workqueue Depth",
   "type": "graph",
   "description": "Number of reconciles pending in the queue for each controller.",
   "gridPos": { "h": 14, "w": 9, "x": 0, "y": 110 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(endpoint,instance,job,namespace,pod,service)(workqueue_depth{name=\"clusterSync-controller\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "ClusterSync Resource Apply Rate",
   "type": "graph",
   "description": "Rate at which the clustersync controller is applying individual resources to clusters.",
   "gridPos": { "h": 14, "w": 9, "x": 9, "y": 110 },
   "yaxes": [
    { "format": "short", "label": "applies per second" }
   ],
   "targets": [
    {
     "expr": "sum without(endpoint,instance,job,namespace,pod,service,type)(rate(hive_syncsetinstance_resources_applied_total{job=\"$instance\"}[15m]))",
     "legendFormat": "{{result}}"
    }
   ]
  },
  { "title": "Building blocks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 124 } },
  {
   "title": "Playground usage",
   "type": "text",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 125 },
   "options": {
    "content": "# How to bulid a dashboard using this Playground\n\n## Getting started\n\nBelow you wil find all available panels to be used for a dashboard.\n\nTo start, select a panel to use, and duplicate it (`Panel options > More > Duplicate`).\n\nDrag it to the top of the screen (above the Building blocks Row) and change the panel title, metrics, and any other settings as required.\n\n\n## Saving your dashboard\n\n\nSince all dashboards are managed through source control, saving dashboards is not enabled.\n\nTo save your new dashboard, export it to a JSON file (through the options on the top right of the screen) and save it locally.\n\n\n## Adding your dashboard\n\nTo add your dashboard, follow these steps:\n\n1. Create a Merge Request to the following git repository:\nhttps://gitlab.cee.redhat.com/service/app-sre-observability\n\n2. Add the JSON content to a `ConfigMap` resource:\n\n```\nkind: ConfigMap\napiVersion: v1\nmetadata:\n  name: grafana-dashboard-my-dashboard\ndata:\n  my-dashboard.json: |-\n    $RAW_JSON\n```\n\nThe `ConfigMap` file name should conform with `grafana-dashboard-my-dashboard.configmap.yaml`. Add it under the `grafana` directory.\n\n3. Add a section to `volumes` and a corresponding `volumeMount` in the Deployment resource: `grafana/grafana.deployment.yaml`.\n\nSee this MR as an example: https://gitlab.cee.redhat.com/service/app-sre-observability/merge_requests/11\n\n## Tips and Tricks\n\n* Keep the `Building blocks` Row as part of the dashboard in case you require changes in the future\n* Export the dashboard with the `Building blocks` Row collapsed\n* Group panels together using a Row object (you may find some below)\n\n\nGood luck!"
   },
   "content": "# How to bulid a dashboard using this Playground\n\n## Getting started\n\nBelow you wil find all available panels to be used for a dashboard.\n\nTo start, select a panel to use, and duplicate it (`Panel options > More > Duplicate`).\n\nDrag it to the top of the screen (above the Building blocks Row) and change the panel title, metrics, and any other settings as required.\n\n\n## Saving your dashboard\n\n\nSince all dashboards are managed through source control, saving dashboards is not enabled.\n\nTo save your new dashboard, export it to a JSON file (through the options on the top right of the screen) and save it locally.\n\n\n## Adding your dashboard\n\nTo add your dashboard, follow these steps:\n\n1. Create a Merge Request to the following git repository:\nhttps://gitlab.cee.redhat.com/service/app-sre-observability\n\n2. Add the JSON content to a `ConfigMap` resource:\n\n```\nkind: ConfigMap\napiVersion: v1\nmetadata:\n  name: grafana-dashboard-my-dashboard\ndata:\n  my-dashboard.json: |-\n    $RAW_JSON\n```\n\nThe `ConfigMap` file name should conform with `grafana-dashboard-my-dashboard.configmap.yaml`. Add it under the `grafana` directory.\n\n3. Add a section to `volumes` and a corresponding `volumeMount` in the Deployment resource: `grafana/grafana.deployment.yaml`.\n\nSee this MR as an example: https://gitlab.cee.redhat.com/service/app-sre-observability/merge_requests/11\n\n## Tips and Tricks\n\n* Keep the `Building blocks` Row as part of the dashboard in case you require changes in the future\n* Export the dashboard with the `Building blocks` Row collapsed\n* Group panels together using a Row object (you may find some below)\n\n\nGood luck!"
  },
  {
   "title": "Graph",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 134 },
   "yaxes": [
    { "format": "short" }
   ]
  },
  {
   "title": "SingleStat",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 134 },
   "format": "none",
   "valueName": "avg"
  },
  { "title": "Table", "type": "table-old", "gridPos": { "h": 7, "w": 5, "x": 10, "y": 134 } },
  {
   "title": "Text",
   "type": "text",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 134 },
   "options": { "content": "# title" },
   "content": "# title"
  },
  { "title": "Heatmap", "type": "heatmap", "gridPos": { "h": 7, "w": 5, "x": 0, "y": 141 } },
  { "title": "Alert list", "type": "alertlist", "gridPos": { "h": 7, "w": 5, "x": 5, "y": 141 } },
  { "title": "Dashboard list", "type": "dashlist", "gridPos": { "h": 7, "w": 5, "x": 10, "y": 141 } },
  { "title": "Plugin list", "type": "pluginlist", "gridPos": { "h": 7, "w": 5, "x": 15, "y": 141 } },
  {
   "title": "Row",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 148 },
   "collapsed": true
  },
  {
   "title": "Row",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 149 },
   "collapsed": true
  },
  {
   "title": "Row",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 150 },
   "collapsed": true
  }
 ]
}