{
 "title": "Jenkins: Performance and health overview",
 "description": "Jobs queue speeds and rates, Executors availability, Nodes status, Jenkins and JVM resource usage.\r\n\r\nCreated as copy of a bit nicer dashboard, which is using graphite datasource.",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "jenkins_instance",
    "label": "Jenkins Instance",
    "query": "label_values(jenkins_health_check_count,instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Processing speed",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(jenkins_job_building_duration_count{instance=\"$jenkins_instance\"}[1m])"
    }
   ]
  },
  {
   "title": "Job queue duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jenkins_job_queuing_duration{instance=\"$jenkins_instance\"}"
    }
   ]
  },
  {
   "title": "Queued rate",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(jenkins_job_queuing_duration_count{instance=\"$jenkins_instance\"}[1m])"
    }
   ]
  },
  {
   "title": "JVM free memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(vm_memory_total_max{instance=\"$jenkins_instance\"} - vm_memory_total_used{instance=\"$jenkins_instance\"}) / vm_memory_total_max{instance=\"$jenkins_instance\"} * 100.0"
    }
   ]
  },
  {
   "title": "JVM uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 7 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "vm_uptime_milliseconds{instance=\"$jenkins_instance\"}"
    }
   ]
  },
  {
   "title": "Jenkins health",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jenkins_health_check_score{instance=\"$jenkins_instance\"}"
    }
   ]
  },
  {
   "title": "Jenkins plugins failed",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jenkins_plugins_failed{instance=\"$jenkins_instance\"}"
    }
   ]
  },
  {
   "title": "Jenkins nodes offline",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jenkins_node_offline_value{instance=\"$jenkins_instance\"}"
    }
   ]
  },
  {
   "title": "Jenkins queue size",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jenkins_queue_size_value{instance=\"$jenkins_instance\"}"
    }
   ]
  },
  {
   "title": "Executors free",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jenkins_executor_free_value{instance=\"$jenkins_instance\"}"
    }
   ]
  },
  {
   "title": "Executors Used %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 4, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 * (jenkins_executor_in_use_value{instance=\"$jenkins_instance\"} / jenkins_executor_count_value{instance=\"$jenkins_instance\"})"
    }
   ]
  },
  {
   "title": "Executors In-use",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jenkins_executor_in_use_value{instance=\"$jenkins_instance\"}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "vm_cpu_load{instance=\"$jenkins_instance\"}"
    }
   ]
  }
 ]
}