{
 "title": "Strimzi and Kafka Version Upgrade Information",
 "tags": [ "kas-fleet-manager" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Strimzi Versions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Strimzi Versions Count",
   "type": "graph",
   "description": "Count of actual Strimzi versions",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(count(strimzi_version{type=\"actual\",version!=\"\"}) by (kafka_id, version)) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Strimzi Version Per Kafka",
   "type": "table",
   "description": "The actual and desired version of Strimzi per Kafka",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "count(strimzi_version{type=\"actual\"}) by (cluster_id, kafka_id, type, version) "
    },
    {
     "expr": "count(label_replace(strimzi_version{type=\"desired\"}, \"desired_version\", \"$1\", \"version\", \"(.*)\")) by (kafka_id, type, desired_version)"
    }
   ]
  },
  {
   "title": "Upgrading Strimzi Count",
   "type": "graph",
   "description": "Count of Strimzi that are being upgraded",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(count(strimzi_version{type=\"upgrade\",version!=\"\"}) by (kafka_id, version)) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Upgrading Strimzi",
   "type": "table",
   "description": "Strimzi instances that are being upgraded",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "count(strimzi_version{type=\"upgrade\"}) by (cluster_id, kafka_id, type, version) "
    }
   ]
  },
  { "title": "Kafka Versions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Kafka Versions Count",
   "type": "graph",
   "description": "Count of actual Kafka versions",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(count(kafka_version{type=\"actual\",version!=\"\"}) by (kafka_id, version)) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Kafka Version Per Kafka",
   "type": "table",
   "description": "The actual and desired version of Kafka",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "count(kafka_version{type=\"actual\"}) by (cluster_id, kafka_id, type, version) "
    },
    {
     "expr": "count(label_replace(kafka_version{type=\"desired\"}, \"desired_version\", \"$1\", \"version\", \"(.*)\")) by (kafka_id, type, desired_version)"
    }
   ]
  },
  {
   "title": "Upgrading Kafka Count",
   "type": "graph",
   "description": "Count of Kafka that are being upgraded",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(count(kafka_version{type=\"upgrade\",version!=\"\"}) by (kafka_id, version)) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Upgrading Kafka",
   "type": "table",
   "description": "Kafka instances that are being upgraded",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "count(kafka_version{type=\"upgrade\"}) by (cluster_id, kafka_id, type, version) "
    }
   ]
  },
  {
   "title": "Kafka IBP Versions Count",
   "type": "graph",
   "description": "Count of actual Kafka IBP versions",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(count(kafka_ibp_version{type=\"actual\",version!=\"\"}) by (kafka_id, version)) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Kafka IBP Version Per Kafka",
   "type": "table",
   "description": "The actual and desired version of Kafka IBP",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "count(kafka_ibp_version{type=\"actual\"}) by (cluster_id, kafka_id, type, version) "
    },
    {
     "expr": "count(label_replace(kafka_ibp_version{type=\"desired\"}, \"desired_version\", \"$1\", \"version\", \"(.*)\")) by (kafka_id, type, desired_version)"
    }
   ]
  },
  {
   "title": "Upgrading Kafka IBP Count",
   "type": "graph",
   "description": "Count of Kafka IBP that are being upgraded",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(count(kafka_ibp_version{type=\"upgrade\",version!=\"\"}) by (kafka_id, version)) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Upgrading Kafka IBP",
   "type": "table",
   "description": "Kafka instances whose Kafka IBP is being upgraded",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "count(kafka_ibp_version{type=\"upgrade\"}) by (cluster_id, kafka_id, type, version) "
    }
   ]
  }
 ]
}