{
 "title": "MAS SSO",
 "description": "Monitoring MAS SSO metrics",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(keycloak_request_duration_count,namespace)"
   },
   {
    "name": "realm",
    "label": "Realm",
    "query": "label_values(keycloak_logins{namespace=\"$namespace\",job=\"keycloak\",provider=\"keycloak\"},realm)"
   },
   {
    "name": "ClientId",
    "label": "ClientId",
    "query": "label_values(keycloak_logins{namespace=\"$namespace\",job=\"keycloak\",provider=\"keycloak\",realm=\"$realm\"},client_id)"
   }
  ]
 },
 "panels": [
  { "title": "System Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Readiness Probes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Ready" }
   ],
   "targets": [
    {
     "expr": "sum(up{namespace=\"$namespace\", job=\"keycloak\"}) by (pod)",
     "legendFormat": "Pod {{pod}}"
    },
    {
     "expr": "sum((wildfly_datasources_pool_available_count{namespace=\"$namespace\", xa_data_source=\"keycloak_postgresql-DB\"} + wildfly_datasources_pool_active_count{namespace=\"$namespace\", xa_data_source=\"keycloak_postgresql-DB\"}) >bool 0) by (pod)",
     "legendFormat": "Database"
    }
   ]
  },
  {
   "title": "HTTP Errors [30m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 5, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "# of errors" }
   ],
   "targets": [
    {
     "expr": "sum(increase(keycloak_response_errors{namespace=\"$namespace\", job=\"keycloak\"}[30m])) by (route, code)"
    },
    {}
   ]
  },
  {
   "title": "Endpoint latency [15m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(keycloak_request_duration_sum{namespace=\"$namespace\", route=~\".+/auth\"}[15m])) / count(rate(keycloak_request_duration_sum{namespace=\"$namespace\", route=~\".+/auth\"}[15m]))",
     "legendFormat": "/auth"
    },
    {
     "expr": "sum(rate(keycloak_request_duration_sum{namespace=\"$namespace\", route=~\".+/token\"}[15m])) / count(rate(keycloak_request_duration_sum{namespace=\"$namespace\", route=~\".+/token\"}[15m]))",
     "legendFormat": "/token"
    },
    {
     "expr": "sum(rate(keycloak_request_duration_sum{namespace=\"$namespace\", route=~\".+/introspect\"}[15m])) / count(rate(keycloak_request_duration_sum{namespace=\"$namespace\", route=~\".+/introspect\"}[15m]))",
     "legendFormat": "/introspect"
    }
   ]
  },
  { "title": "Detailed metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Pod Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\", pod=\"keycloak-0\"}",
     "legendFormat": "Requests"
    },
    {
     "expr": "kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"memory\", pod=\"keycloak-0\"}",
     "legendFormat": "Limits"
    },
    {
     "expr": "container_memory_rss{namespace=\"$namespace\", container=\"keycloak\"}  ",
     "legendFormat": "RSS for {{pod}}"
    },
    {
     "expr": "sum(jvm_memory_bytes_committed{namespace=\"$namespace\",job=\"keycloak\"}) by (pod)",
     "legendFormat": "JVM Committed for {{pod}}"
    },
    {
     "expr": "sum(jvm_memory_bytes_max{namespace=\"$namespace\",job=\"keycloak\"}) by (pod)",
     "legendFormat": "JVM Max for {{pod}}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 7, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"cpu\", pod=\"keycloak-0\"}",
     "legendFormat": "CPU Limit for {{pod}}"
    },
    {
     "expr": "kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"cpu\", pod=\"keycloak-0\"}",
     "legendFormat": "CPU Request for {{pod}}"
    },
    {
     "expr": "node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", container=\"keycloak\"}",
     "legendFormat": "CPU Load for {{pod}}"
    }
   ]
  },
  {
   "title": "Number of GC Collections [30m]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(jvm_gc_collection_seconds_count{namespace=\"$namespace\", job=\"keycloak\"}[30m])) by (pod)",
     "legendFormat": "GC Collections for {{pod}}"
    }
   ]
  },
  {
   "title": "Number of entries in caches",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vendor_cache_manager_default_cache_sessions_statistics_number_of_entries{namespace=\"datagrid\"}) by (job)",
     "legendFormat": "Cache Sessions"
    },
    {
     "expr": "sum(vendor_cache_manager_default_cache_offline_sessions_statistics_number_of_entries{namespace=\"datagrid\"}) by (job)",
     "legendFormat": "Cache Offline Sessions"
    },
    {
     "expr": "sum(vendor_cache_manager_default_cache_client_sessions_statistics_number_of_entries{namespace=\"datagrid\"}) by (job)",
     "legendFormat": "Cache Client Sessions"
    },
    {
     "expr": "sum(vendor_cache_manager_default_cache_offline_client_sessions_statistics_number_of_entries{namespace=\"$datagrid_namespace\"}) by (job)",
     "legendFormat": "Cache Offline Client Sessions"
    },
    {
     "expr": "sum(vendor_cache_manager_default_cache_login_failures_statistics_number_of_entries{namespace=\"$datagrid_namespace\"}) by (job)",
     "legendFormat": "Cache Offline Client Sessions"
    },
    {
     "expr": "sum(vendor_cache_manager_default_cache_action_tokens_statistics_number_of_entries{namespace=\"$datagrid_namespace\"}) by (job)",
     "legendFormat": "Cache Offline Client Sessions"
    },
    {
     "expr": "sum(vendor_cache_manager_default_cache_work_statistics_number_of_entries{namespace=\"$datagrid_namespace\"}) by (job)",
     "legendFormat": "Cache Offline Client Sessions"
    }
   ]
  },
  {
   "title": "JVM Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\", pod=\"keycloak-0\"}",
     "legendFormat": "Requests"
    },
    {
     "expr": "kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"memory\", pod=\"keycloak-0\"}",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(base_memory_usedHeap_bytes{namespace=\"$namespace\"})",
     "legendFormat": "JVM Heap for {{pod}}"
    },
    {
     "expr": "sum(base_memory_usedNonHeap_bytes{namespace=\"$namespace\"})",
     "legendFormat": "JVM Non Heap for {{pod}}"
    }
   ]
  },
  {
   "title": "Total GC Time [30m]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(increase(jvm_gc_collection_seconds_sum{namespace=\"$namespace\", job=\"keycloak\"}[30m])) by (pod)",
     "legendFormat": "Total GC Time for {{pod}}"
    }
   ]
  },
  {
   "title": "Number of database connections in pool",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wildfly_datasources_pool_active_count{namespace=\"$namespace\", xa_data_source=\"keycloak_postgresql-DB\"}",
     "legendFormat": "Active for {{pod}}"
    },
    {
     "expr": "wildfly_datasources_pool_available_count{namespace=\"$namespace\", xa_data_source=\"keycloak_postgresql-DB\"}",
     "legendFormat": "Available for {{pod}}"
    }
   ]
  },
  {
   "title": "Number of transactions [30m]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(wildfly_datasources_pool_xacommit_count{namespace=\"$namespace\", xa_data_source=\"keycloak_postgresql-DB\"}[30m])",
     "legendFormat": "Number of commits for {{pod}}"
    },
    {
     "expr": "increase(wildfly_datasources_pool_xarollback_count{namespace=\"$namespace\", xa_data_source=\"keycloak_postgresql-DB\"}[30m])",
     "legendFormat": "Number of rollbacks for {{pod}}"
    },
    {
     "expr": "increase(wildfly_datasources_pool_blocking_failure_count{namespace=\"$namespace\", xa_data_source=\"keycloak_postgresql-DB\"}[30m])",
     "legendFormat": "Number of failures for {{pod}}"
    }
   ]
  },
  {
   "title": "IO Threads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wildfly_io_io_thread_count{namespace=\"$namespace\"}",
     "legendFormat": "IO Threads for {{pod}}"
    },
    {
     "expr": "wildfly_io_queue_size{namespace=\"$namespace\"}",
     "legendFormat": "I/O Queue size for {{pod}}"
    },
    {
     "expr": "wildfly_io_busy_task_thread_count{namespace=\"$namespace\"}",
     "legendFormat": "I/O Busy tasks for {{pod}}"
    },
    {
     "expr": "wildfly_io_max_pool_size{namespace=\"$namespace\"}",
     "legendFormat": "IO Max pool size for {{pod}}"
    },
    {
     "expr": "kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"cpu\", pod=\"keycloak-0\"}",
     "legendFormat": "CPU limit"
    }
   ]
  },
  {
   "title": "Operator metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Operator Readiness Probes",
     "type": "graph",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short", "label": "Ready" }
     ],
     "targets": [
      {
       "expr": "up{namespace=\"$namespace\", job=\"keycloak-operator-metrics\", endpoint=\"http-metrics\"}",
       "legendFormat": "Pod {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Experimental",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Logins per REALM",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum by (realm)(increase(keycloak_logins{namespace=\"$namespace\",job=\"keycloak\"}[1h]))",
       "legendFormat": "{{realm}}"
      }
     ]
    },
    {
     "title": "Login Errors on realm $realm",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 36 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "increase(keycloak_failed_login_attempts{namespace=\"$namespace\",job=\"keycloak\",provider=\"keycloak\",realm=\"$realm\"}[1h])",
       "legendFormat": "{{error}}"
      },
      {
       "expr": "increase(keycloak_failed_login_attempts{namespace=\"$namespace\",job=\"keycloak\",provider=\"keycloak\"}[1h])"
      }
     ]
    },
    {
     "title": "Logins per CLIENT on realm $realm",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "increase(keycloak_logins{namespace=\"$namespace\",job=\"keycloak\",realm=\"$realm\",provider=\"keycloak\"}[1h])",
       "legendFormat": "{{client_id}}"
      }
     ]
    },
    {
     "title": "Endpoint latency [5m]",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 46 },
     "targets": [
      {
       "expr": "sum(increase(keycloak_request_duration_bucket[5m])) by (le)",
       "legendFormat": "Request taking less or equal than {{le}}"
      }
     ]
    },
    {
     "title": "Endpoint latency [5m]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(increase(keycloak_request_duration_sum{namespace=\"$namespace\"}[5m])) by (route) / sum(increase(keycloak_request_duration_count{namespace=\"$namespace\"}[5m])) by (route)",
       "legendFormat": "{{route}}"
      }
     ]
    }
   ]
  }
 ]
}