{
 "title": "Quay APIs by service",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "service",
    "query": {
     "query": "label_values(aggregation:quay_request_duration_seconds_bucket:rate5m:sum, src_service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "request rate for app registry api calls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "req/s" }
   ],
   "targets": [
    {
     "expr": "sum by (route)(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=~\"appr.*\",src_service=\"$service\"})",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "app registry latency p95",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, route) (aggregation:quay_request_duration_seconds_bucket:rate5m:sum{route=~\"appr.*\",src_service=\"$service\"}))",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "request rate for v1 calls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "req/s" }
   ],
   "targets": [
    {
     "expr": "sum by (route)(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=~\"v1.*\",src_service=\"$service\"})",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "v1 latency p95",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, route) (aggregation:quay_request_duration_seconds_bucket:rate5m:sum{route=~\"v1.*\",src_service=\"$service\"}))",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "request rate for v2 calls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "req/s" }
   ],
   "targets": [
    {
     "expr": "sum by (route)(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=~\"v2.*\",src_service=\"$service\"})",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "v2 latency p95",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, route) (aggregation:quay_request_duration_seconds_bucket:rate5m:sum{route=~\"v2.*\",src_service=\"$service\"}))",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "request rate for api-user calls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "req/s" }
   ],
   "targets": [
    {
     "expr": "sum by (route)(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=~\"api.+user.*\",src_service=\"$service\"})",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "api-user latency p95",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, route) (aggregation:quay_request_duration_seconds_bucket:rate5m:sum{route=~\"api.+user.*\",src_service=\"$service\"}))",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "request rate for api-repo calls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "req/s" }
   ],
   "targets": [
    {
     "expr": "sum by (route)(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=~\"api.+repositor[iy].*\",src_service=\"$service\"})",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "api-repo latency p95",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, route) (aggregation:quay_request_duration_seconds_bucket:rate5m:sum{route=~\"api.+repositor[iy].*\",src_service=\"$service\"}))",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "request rate for api-org calls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short", "label": "req/s" }
   ],
   "targets": [
    {
     "expr": "sum by (route)(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=~\"api.+org.*\",src_service=\"$service\"})",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "api-org latency p95",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, route) (aggregation:quay_request_duration_seconds_bucket:rate5m:sum{route=~\"api.+org.*\",src_service=\"$service\"}))",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "request rate for the rest of calls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short", "label": "req/s" }
   ],
   "targets": [
    {
     "expr": "sum by (route)(aggregation:quay_request_duration_seconds_count:rate1m:sum{route!~\"appr.+|v[12].+|api.+user.*|api.+org.*|api.+repositor[yi].*\",src_service=\"$service\"})",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "api-other latency p95",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, route) (aggregation:quay_request_duration_seconds_bucket:rate5m:sum{route!~\"appr.+|v[12].+|api.+user.*|api.+org.*|api.+repositor[yi].*\",src_service=\"$service\"}))",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "5XX Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sum by (route,method)(aggregation:quay_request_duration_seconds_count:rate1m:sum{status=~\"5..\",src_service=\"$service\"})"
    }
   ]
  }
 ]
}