{
 "title": "AWS Web Application Firewall (WAF) Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DataSource", "query": "cloudwatch" },
   {
    "name": "WebACL",
    "query": "dimension_values(us-east-1,AWS/WAFV2,AllowedRequests,WebACL)"
   }
  ]
 },
 "panels": [
  {
   "title": "Blocked Requests By Rule",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dimensions": { "Region": "us-east-1", "WebACL": "$WebACL" },
     "metricName": "BlockedRequests",
     "namespace": "AWS/WAFV2",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Count Requests By Rule (Non Blocked)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dimensions": { "Region": "us-east-1", "WebACL": "$WebACL" },
     "metricName": "CountedRequests",
     "namespace": "AWS/WAFV2",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Allowed Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "dimensions": { "Region": "us-east-1", "WebACL": "$WebACL" },
     "metricName": "AllowedRequests",
     "namespace": "AWS/WAFV2",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  }
 ]
}