{
 "title": "Job Queue Service",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "namespace", "query": "uhc-stage,uhc-production" }
  ]
 },
 "panels": [
  {
   "title": "API Overall",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Availability (selected time) ",
     "type": "singlestat",
     "description": "The percentage of time that the API is available (not returning 500 Internal Service Errors).",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(api_inbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",code!~\"5..|0\"}[$__range]))\n/\nsum(increase(api_inbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "graph",
     "description": "Number of requests per second by response codes.",
     "gridPos": { "h": 8, "w": 7, "x": 3, "y": 1 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by (code) (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\"}[5m]))",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "description": "The error percentage.",
     "gridPos": { "h": 8, "w": 7, "x": 10, "y": 1 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",code!~\"2..\"}[5m]))\n/\nsum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\"}[5m]))",
       "legendFormat": "non-2xx"
      },
      {
       "expr": "sum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",code!~\"2..|404\"}[5m]))\n/\nsum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\"}[5m]))",
       "legendFormat": "non-2xx and non-404"
      },
      {
       "expr": "sum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",code=~\"5..|0\"}[5m]))\n/\nsum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\"}[5m]))",
       "legendFormat": "5xx and timeout"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "description": "The request duration within which the API have served 99%, 95%, 50% of requests",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 1 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(api_inbound_request_duration_bucket{namespace=\"$namespace\",service=\"job-queue-service-metrics\",code!~\"5..|0\"}[5m])))",
       "legendFormat": "99th"
      },
      {
       "expr": "histogram_quantile(0.90, sum by (le) (rate(api_inbound_request_duration_bucket{namespace=\"$namespace\",service=\"job-queue-service-metrics\",code!~\"5..|0\"}[5m])))",
       "legendFormat": "90th"
      },
      {
       "expr": "histogram_quantile(0.5, sum by (le) (rate(api_inbound_request_duration_bucket{namespace=\"$namespace\",service=\"job-queue-service-metrics\",code!~\"5..|0\"}[5m])))",
       "legendFormat": "50th"
      }
     ]
    },
    {
     "title": "Latency (< 1s) ",
     "type": "singlestat",
     "description": "The percentage of time that the API responds within 1 second.",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(api_inbound_request_duration_bucket{namespace=\"$namespace\",service=\"job-queue-service-metrics\",code!~\"5..|0\",le=\"1\"}[$__range]))\n/\nsum(increase(api_inbound_request_duration_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",code!~\"5..|0\"}[$__range]))"
      }
     ]
    }
   ]
  },
  { "title": "/job_queues LIST", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Availability (selected time) ",
   "type": "singlestat",
   "description": "The percentage of time that the API is available (not returning 500 Internal Service Errors).",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 2 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(api_inbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=\"/api/job_queue/v1/queues\",code!~\"5..|0\"}[$__range]))\n/\nsum(increase(api_inbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=\"/api/job_queue/v1/queues\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "description": "Number of requests per second by response codes.",
   "gridPos": { "h": 8, "w": 7, "x": 3, "y": 2 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (code) (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=\"/api/job_queue/v1/queues\"}[5m]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "description": "The error percentage.",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 2 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=\"/api/job_queue/v1/queues\",code!~\"2..\"}[5m]))\n/\nsum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=\"/api/job_queue/v1/queues\"}[5m]))",
     "legendFormat": "non-2xx"
    },
    {
     "expr": "sum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=\"/api/job_queue/v1/queues\",code=\"409\"}[5m]))\n/\nsum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=\"/api/job_queue/v1/queues\"}[5m]))",
     "legendFormat": "token conflicts"
    },
    {
     "expr": "sum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=\"/api/job_queue/v1/queues\",code=~\"5..|0\"}[5m]))\n/\nsum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=\"/api/job_queue/v1/queues\"}[5m]))",
     "legendFormat": "5xx and timeout"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "description": "The request duration within which the API have served 99%, 95%, 50% of requests",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 2 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(api_inbound_request_duration_bucket{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=\"/api/job_queue/v1/queues\",code!~\"5..|0\"}[5m])))",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le) (rate(api_inbound_request_duration_bucket{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=\"/api/job_queue/v1/queues\",code!~\"5..|0\"}[5m])))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(api_inbound_request_duration_bucket{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=\"/api/job_queue/v1/queues\",code!~\"5..|0\"}[5m])))",
     "legendFormat": "50th"
    }
   ]
  },
  {
   "title": "Latency (< 1s) ",
   "type": "singlestat",
   "description": "The percentage of time that the API responds within 1 second.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(api_inbound_request_duration_bucket{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=\"/api/job_queue/v1/queues\",code!~\"5..|0\",le=\"1\"}[$__range]))\n/\nsum(increase(api_inbound_request_duration_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=\"/api/job_queue/v1/queues\",code!~\"5..|0\"}[$__range]))"
    }
   ]
  },
  { "title": "/job_queues/{id} GET", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Availability (selected time) ",
   "type": "singlestat",
   "description": "The percentage of time that the API is available (not returning 500 Internal Service Errors).",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 11 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(api_inbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=\"/api/job_queue/v1/queues/-\",code!~\"5..|0\"}[$__range]))\n/\nsum(increase(api_inbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=\"/api/job_queue/v1/queues/-\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "description": "Number of requests per second by response codes.",
   "gridPos": { "h": 8, "w": 7, "x": 3, "y": 11 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (code) (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=\"/api/job_queue/v1/queues/-\"}[5m]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "description": "The error percentage.",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=\"/api/job_queue/v1/queues/-\",code!~\"2..\"}[5m]))\n/\nsum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=\"/api/job_queue/v1/queues/-\"}[5m]))",
     "legendFormat": "non-2xx"
    },
    {
     "expr": "sum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=\"/api/job_queue/v1/queues/-\",code=~\"5..|0\"}[5m]))\n/\nsum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=\"/api/job_queue/v1/queues/-\"}[5m]))",
     "legendFormat": "5xx and timeout"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "description": "The request duration within which the API have served 99%, 95%, 50% of requests",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(api_inbound_request_duration_bucket{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=\"/api/job_queue/v1/queues/-\",code!~\"5..|0\"}[5m])))",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le) (rate(api_inbound_request_duration_bucket{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=\"/api/job_queue/v1/queues/-\",code!~\"5..|0\"}[5m])))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(api_inbound_request_duration_bucket{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=\"/api/job_queue/v1/queues/-\",code!~\"5..|0\"}[5m])))",
     "legendFormat": "50th"
    }
   ]
  },
  {
   "title": "Latency (< 1s) ",
   "type": "singlestat",
   "description": "The percentage of time that the API responds within 1 second.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 15 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(api_inbound_request_duration_bucket{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=\"/api/job_queue/v1/queues/-\",code!~\"5..|0\",le=\"1\"}[$__range]))\n/\nsum(increase(api_inbound_request_duration_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=\"/api/job_queue/v1/queues/-\",code!~\"5..|0\"}[$__range]))"
    }
   ]
  },
  {
   "title": "/job_queues/{id}/push POST",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Availability (selected time) ",
     "type": "singlestat",
     "description": "The percentage of time that the API is available (not returning 500 Internal Service Errors).",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 20 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(api_inbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=~\"/api/job_queue/v1/queues/-/push\",method=\"POST\",code!~\"5..|0\"}[$__range]))\n/\nsum(increase(api_inbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=~\"/api/job_queue/v1/queues/-/push\",method=\"POST\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "graph",
     "description": "Number of requests per second by response codes.",
     "gridPos": { "h": 8, "w": 7, "x": 3, "y": 20 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by (code) (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=~\"/api/job_queue/v1/queues/-/push\",method=\"POST\"}[5m]))",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "description": "The error percentage.",
     "gridPos": { "h": 8, "w": 7, "x": 10, "y": 20 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=~\"/api/job_queue/v1/queues/-/push\",method=\"POST\",code!~\"2..\"}[5m]))\n/\nsum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=~\"/api/job_queue/v1/queues/-/push\",method=\"POST\"}[5m]))",
       "legendFormat": "non-2xx"
      },
      {
       "expr": "sum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=~\"/api/job_queue/v1/queues/-/push\",method=\"POST\",code=~\"5..|0\"}[5m]))\n/\nsum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=~\"/api/job_queue/v1/queues/-/push\",method=\"POST\"}[5m]))",
       "legendFormat": "5xx and timeout"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "description": "The request duration within which the API have served 99%, 95%, 50% of requests",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 20 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(api_inbound_request_duration_bucket{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=~\"/api/job_queue/v1/queues/-/push\",method=\"POST\",code!~\"5..|0\"}[5m])))",
       "legendFormat": "99th"
      },
      {
       "expr": "histogram_quantile(0.90, sum by (le) (rate(api_inbound_request_duration_bucket{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=~\"/api/job_queue/v1/queues/-/push\",method=\"POST\",code!~\"5..|0\"}[5m])))",
       "legendFormat": "90th"
      },
      {
       "expr": "histogram_quantile(0.5, sum by (le) (rate(api_inbound_request_duration_bucket{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=~\"/api/job_queue/v1/queues/-/push\",method=\"POST\",code!~\"5..|0\"}[5m])))",
       "legendFormat": "50th"
      }
     ]
    },
    {
     "title": "Latency (< 1s) ",
     "type": "singlestat",
     "description": "The percentage of time that the API responds within 1 second.",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 24 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(api_inbound_request_duration_bucket{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=~\"/api/job_queue/v1/queues/-/push\",method=\"POST\",code!~\"5..|0\",le=\"1\"}[$__range]))\n/\nsum(increase(api_inbound_request_duration_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=~\"/api/job_queue/v1/queues/-/push\",method=\"POST\",code!~\"5..|0\"}[$__range]))"
      }
     ]
    }
   ]
  },
  {
   "title": "/job_queues/{id}/pop GET",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Availability (selected time) ",
     "type": "singlestat",
     "description": "The percentage of time that the API is available (not returning 500 Internal Service Errors).",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 21 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(api_inbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=\"/api/job_queue/v1/queues/-/pop\",method=\"GET\",code!~\"5..|0\"}[$__range]))\n/\nsum(increase(api_inbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=\"/api/job_queue/v1/queues/-/pop\",method=\"GET\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "graph",
     "description": "Number of requests per second by response codes.",
     "gridPos": { "h": 8, "w": 7, "x": 3, "y": 21 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by (code) (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=\"/api/job_queue/v1/queues/-/pop\",method=\"GET\"}[5m]))",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "description": "The error percentage.",
     "gridPos": { "h": 8, "w": 7, "x": 10, "y": 21 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=\"/api/job_queue/v1/queues/-/pop\",method=\"GET\",code!~\"2..\"}[5m]))\n/\nsum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=\"/api/job_queue/v1/queues/-/pop\",method=\"GET\"}[5m]))",
       "legendFormat": "non-2xx"
      },
      {
       "expr": "sum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=\"/api/job_queue/v1/queues/-/pop\",method=\"GET\",code=~\"5..|0\"}[5m]))\n/\nsum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=\"/api/job_queue/v1/queues/-/pop\",method=\"GET\"}[5m]))",
       "legendFormat": "5xx and timeout"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "description": "The request duration within which the API have served 99%, 95%, 50% of requests",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 21 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(api_inbound_request_duration_bucket{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=\"/api/job_queue/v1/queues/-/pop\",method=\"GET\",code!~\"5..|0\"}[5m])))",
       "legendFormat": "99th"
      },
      {
       "expr": "histogram_quantile(0.90, sum by (le) (rate(api_inbound_request_duration_bucket{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=\"/api/job_queue/v1/queues/-/pop\",method=\"GET\",code!~\"5..|0\"}[5m])))",
       "legendFormat": "90th"
      },
      {
       "expr": "histogram_quantile(0.5, sum by (le) (rate(api_inbound_request_duration_bucket{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=\"/api/job_queue/v1/queues/-/pop\",method=\"GET\",code!~\"5..|0\"}[5m])))",
       "legendFormat": "50th"
      }
     ]
    },
    {
     "title": "Latency (< 1s) ",
     "type": "singlestat",
     "description": "The percentage of time that the API responds within 1 second.",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 25 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(api_inbound_request_duration_bucket{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=\"/api/job_queue/v1/queues/-/pop\",method=\"GET\",code!~\"5..|0\",le=\"1\"}[$__range]))\n/\nsum(increase(api_inbound_request_duration_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=\"/api/job_queue/v1/queues/-/pop\",method=\"GET\",code!~\"5..|0\"}[$__range]))"
      }
     ]
    }
   ]
  },
  {
   "title": "/jobs/{id}/success POST",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Availability (selected time) ",
     "type": "singlestat",
     "description": "The percentage of time that the API is available (not returning 500 Internal Service Errors).",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 22 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(api_inbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=\"/api/job_queue/v1/jobs/-/success\",method=\"POST\",code!~\"5..|0\"}[$__range]))\n/\nsum(increase(api_inbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=\"/api/job_queue/v1/jobs/-/success\",method=\"POST\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "graph",
     "description": "Number of requests per second by response codes.",
     "gridPos": { "h": 8, "w": 7, "x": 3, "y": 22 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by (code) (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=\"/api/job_queue/v1/jobs/-/success\",method=\"POST\"}[5m]))",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "description": "The error percentage.",
     "gridPos": { "h": 8, "w": 7, "x": 10, "y": 22 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=\"/api/job_queue/v1/jobs/-/success\",method=\"POST\",code!~\"2..\"}[5m]))\n/\nsum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=\"/api/job_queue/v1/jobs/-/success\",method=\"POST\"}[5m]))",
       "legendFormat": "non-2xx"
      },
      {
       "expr": "sum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=\"/api/job_queue/v1/jobs/-/success\",method=\"POST\",code=~\"5..|0\"}[5m]))\n/\nsum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=\"/api/job_queue/v1/jobs/-/success\",method=\"POST\"}[5m]))",
       "legendFormat": "5xx and timeout"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "description": "The request duration within which the API have served 99%, 95%, 50% of requests",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 22 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(api_inbound_request_duration_bucket{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=\"/api/job_queue/v1/jobs/-/success\",method=\"POST\",code!~\"5..|0\"}[5m])))",
       "legendFormat": "99th"
      },
      {
       "expr": "histogram_quantile(0.90, sum by (le) (rate(api_inbound_request_duration_bucket{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=\"/api/job_queue/v1/jobs/-/success\",method=\"POST\",code!~\"5..|0\"}[5m])))",
       "legendFormat": "90th"
      },
      {
       "expr": "histogram_quantile(0.5, sum by (le) (rate(api_inbound_request_duration_bucket{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=\"/api/job_queue/v1/jobs/-/success\",method=\"POST\",code!~\"5..|0\"}[5m])))",
       "legendFormat": "50th"
      }
     ]
    },
    {
     "title": "Latency (< 1s) ",
     "type": "singlestat",
     "description": "The percentage of time that the API responds within 1 second.",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 26 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(api_inbound_request_duration_bucket{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=\"/api/job_queue/v1/jobs/-/success\",method=\"POST\",code!~\"5..|0\",le=\"1\"}[$__range]))\n/\nsum(increase(api_inbound_request_duration_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=\"/api/job_queue/v1/jobs/-/success\",method=\"POST\",code!~\"5..|0\"}[$__range]))"
      }
     ]
    }
   ]
  },
  {
   "title": "/jobs/{id}/failure POST",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Availability (selected time) ",
     "type": "singlestat",
     "description": "The percentage of time that the API is available (not returning 500 Internal Service Errors).",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 23 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(api_inbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=\"/api/job_queue/v1/jobs/-/failure\",method=\"POST\",code!~\"5..|0\"}[$__range]))\n/\nsum(increase(api_inbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=\"/api/job_queue/v1/jobs/-/failure\",method=\"POST\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "graph",
     "description": "Number of requests per second by response codes.",
     "gridPos": { "h": 8, "w": 7, "x": 3, "y": 23 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by (code) (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=\"/api/job_queue/v1/jobs/-/failure\",method=\"POST\"}[5m]))",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "description": "The error percentage.",
     "gridPos": { "h": 8, "w": 7, "x": 10, "y": 23 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=\"/api/job_queue/v1/jobs/-/failure\",method=\"POST\",code!~\"2..\"}[5m]))\n/\nsum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=\"/api/job_queue/v1/jobs/-/failure\",method=\"POST\"}[5m]))",
       "legendFormat": "non-2xx"
      },
      {
       "expr": "sum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=\"/api/job_queue/v1/jobs/-/failure\",method=\"POST\",code=~\"5..|0\"}[5m]))\n/\nsum (rate(api_inbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=\"/api/job_queue/v1/jobs/-/failure\",method=\"POST\"}[5m]))",
       "legendFormat": "5xx and timeout"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "description": "The request duration within which the API have served 99%, 95%, 50% of requests",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 23 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(api_inbound_request_duration_bucket{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=\"/api/job_queue/v1/jobs/-/failure\",method=\"POST\",code!~\"5..|0\"}[5m])))",
       "legendFormat": "99th"
      },
      {
       "expr": "histogram_quantile(0.90, sum by (le) (rate(api_inbound_request_duration_bucket{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=\"/api/job_queue/v1/jobs/-/failure\",method=\"POST\",code!~\"5..|0\"}[5m])))",
       "legendFormat": "90th"
      },
      {
       "expr": "histogram_quantile(0.5, sum by (le) (rate(api_inbound_request_duration_bucket{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=\"/api/job_queue/v1/jobs/-/failure\",method=\"POST\",code!~\"5..|0\"}[5m])))",
       "legendFormat": "50th"
      }
     ]
    },
    {
     "title": "Latency (< 1s) ",
     "type": "singlestat",
     "description": "The percentage of time that the API responds within 1 second.",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 27 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(api_inbound_request_duration_bucket{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=\"/api/job_queue/v1/jobs/-/failure\",method=\"POST\",code!~\"5..|0\",le=\"1\"}[$__range]))\n/\nsum(increase(api_inbound_request_duration_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",path=\"/api/job_queue/v1/jobs/-/failure\",method=\"POST\",code!~\"5..|0\"}[$__range]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Dependencies: Overall",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Availability (selected time) ",
     "type": "singlestat",
     "description": "The percentage of time that the API is available (not returning 500 Internal Service Errors).",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 24 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(api_outbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",code!~\"5..|0\"}[$__range]))\n/\nsum(increase(api_outbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "graph",
     "description": "Number of requests per second by response codes.",
     "gridPos": { "h": 8, "w": 7, "x": 3, "y": 24 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by (apiservice) (rate(api_outbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\"}[5m]))",
       "legendFormat": "{{apiservice}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "description": "The error percentage.",
     "gridPos": { "h": 8, "w": 7, "x": 10, "y": 24 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum (rate(api_outbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",code!~\"2..\"}[5m]))\n/\nsum (rate(api_outbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\"}[5m]))",
       "legendFormat": "non-2xx"
      },
      {
       "expr": "sum (rate(api_outbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",code=~\"5..|0\"}[5m]))\n/\nsum (rate(api_outbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\"}[5m]))",
       "legendFormat": "5xx and timeout"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "description": "The request duration within which the API have served 99%, 95%, 50% of requests",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 24 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(api_outbound_request_duration_bucket{namespace=\"$namespace\",service=\"job-queue-service-metrics\",code!~\"5..|0\"}[5m])))",
       "legendFormat": "99th"
      },
      {
       "expr": "histogram_quantile(0.90, sum by (le) (rate(api_outbound_request_duration_bucket{namespace=\"$namespace\",service=\"job-queue-service-metrics\",code!~\"5..|0\"}[5m])))",
       "legendFormat": "90th"
      },
      {
       "expr": "histogram_quantile(0.5, sum by (le) (rate(api_outbound_request_duration_bucket{namespace=\"$namespace\",service=\"job-queue-service-metrics\",code!~\"5..|0\"}[5m])))",
       "legendFormat": "50th"
      }
     ]
    },
    {
     "title": "Latency (< 1s) ",
     "type": "singlestat",
     "description": "The percentage of time that the API responds within 1 second.",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 28 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(api_outbound_request_duration_bucket{namespace=\"$namespace\",service=\"job-queue-service-metrics\",code!~\"5..|0\",le=\"1\"}[$__range]))\n/\nsum(increase(api_outbound_request_duration_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",code!~\"5..|0\"}[$__range]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Dependencies: OCM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Availability (selected time) ",
     "type": "singlestat",
     "description": "The percentage of time that the API is available (not returning 500 Internal Service Errors).",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 25 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(api_outbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",apiservice=\"ocm\",code!~\"5..|0\"}[$__range]))\n/\nsum(increase(api_outbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",apiservice=\"ocm\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "graph",
     "description": "Number of requests per second by response codes.",
     "gridPos": { "h": 8, "w": 7, "x": 3, "y": 25 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by (code) (rate(api_outbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",apiservice=\"ocm\"}[5m]))",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "description": "The error percentage.",
     "gridPos": { "h": 8, "w": 7, "x": 10, "y": 25 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum (rate(api_outbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",apiservice=\"ocm\",code!~\"2..\"}[5m]))\n/\nsum (rate(api_outbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",apiservice=\"ocm\"}[5m]))",
       "legendFormat": "non-2xx"
      },
      {
       "expr": "sum (rate(api_outbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",apiservice=\"ocm\",code=~\"5..|0\"}[5m]))\n/\nsum (rate(api_outbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",apiservice=\"ocm\"}[5m]))",
       "legendFormat": "5xx and timeout"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "description": "The request duration within which the API have served 99%, 95%, 50% of requests",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 25 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(api_outbound_request_duration_bucket{namespace=\"$namespace\",service=\"job-queue-service-metrics\",apiservice=\"ocm\",code!~\"5..|0\"}[5m])))",
       "legendFormat": "99th"
      },
      {
       "expr": "histogram_quantile(0.90, sum by (le) (rate(api_outbound_request_duration_bucket{namespace=\"$namespace\",service=\"job-queue-service-metrics\",apiservice=\"ocm\",code!~\"5..|0\"}[5m])))",
       "legendFormat": "90th"
      },
      {
       "expr": "histogram_quantile(0.5, sum by (le) (rate(api_outbound_request_duration_bucket{namespace=\"$namespace\",service=\"job-queue-service-metrics\",apiservice=\"ocm\",code!~\"5..|0\"}[5m])))",
       "legendFormat": "50th"
      }
     ]
    },
    {
     "title": "Latency (< 1s) ",
     "type": "singlestat",
     "description": "The percentage of time that the API responds within 1 second.",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 29 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(api_outbound_request_duration_bucket{namespace=\"$namespace\",service=\"job-queue-service-metrics\",apiservice=\"ocm\",code!~\"5..|0\",le=\"1\"}[$__range]))\n/\nsum(increase(api_outbound_request_duration_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",apiservice=\"ocm\",code!~\"5..|0\"}[$__range]))"
      }
     ]
    }
   ]
  },
  { "title": "Dependencies: SQS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Availability (selected time) ",
   "type": "singlestat",
   "description": "The percentage of time that the API is available (not returning 500 Internal Service Errors).",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 26 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(api_outbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",apiservice=\"sqs\",code!~\"5..|0\"}[$__range]))\n/\nsum(increase(api_outbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",apiservice=\"sqs\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "description": "Number of requests per second by response codes.",
   "gridPos": { "h": 8, "w": 7, "x": 3, "y": 26 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (code) (rate(api_outbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",apiservice=\"sqs\"}[5m]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "description": "The error percentage.",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 26 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum (rate(api_outbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",apiservice=\"sqs\",code!~\"2..\"}[5m]))\n/\nsum (rate(api_outbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",apiservice=\"sqs\"}[5m]))",
     "legendFormat": "non-2xx"
    },
    {
     "expr": "sum (rate(api_outbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",apiservice=\"sqs\",code=~\"5..|0\"}[5m]))\n/\nsum (rate(api_outbound_request_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",apiservice=\"sqs\"}[5m]))",
     "legendFormat": "5xx and timeout"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "description": "The request duration within which the API have served 99%, 95%, 50% of requests",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(api_outbound_request_duration_bucket{namespace=\"$namespace\",service=\"job-queue-service-metrics\",apiservice=\"sqs\",code!~\"5..|0\"}[5m])))",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le) (rate(api_outbound_request_duration_bucket{namespace=\"$namespace\",service=\"job-queue-service-metrics\",apiservice=\"sqs\",code!~\"5..|0\"}[5m])))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(api_outbound_request_duration_bucket{namespace=\"$namespace\",service=\"job-queue-service-metrics\",apiservice=\"sqs\",code!~\"5..|0\"}[5m])))",
     "legendFormat": "50th"
    }
   ]
  },
  {
   "title": "Latency (< 1s) ",
   "type": "singlestat",
   "description": "The percentage of time that the API responds within 1 second.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 30 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(api_outbound_request_duration_bucket{namespace=\"$namespace\",service=\"job-queue-service-metrics\",apiservice=\"sqs\",code!~\"5..|0\",le=\"1\"}[$__range]))\n/\nsum(increase(api_outbound_request_duration_count{namespace=\"$namespace\",service=\"job-queue-service-metrics\",apiservice=\"sqs\",code!~\"5..|0\"}[$__range]))"
    }
   ]
  }
 ]
}