{
 "title": "SDB Cron Jobs",
 "description": "the cron jobs managed by service-development-b",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "namespace", "query": "uhc-stage,uhc-production" }
  ]
 },
 "panels": [
  {
   "title": "overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "account-reconciler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Job pass (selected time) ",
     "type": "stat",
     "description": "The percentage of time that the job passes (no major issues).",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(increase(job_results_job_count{jobname=\"account-reconciler\",namespace=\"$namespace\",status=\"pass\"}[$__range])) /\nsum(increase(job_results_job_count{jobname=\"account-reconciler\",namespace=\"$namespace\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "description": "The job run duration.",
     "gridPos": { "h": 8, "w": 10, "x": 4, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (increase(job_results_job_duration_sum{jobname=\"account-reconciler\",namespace=\"$namespace\"}[3m])) /\nsum (increase(job_results_job_duration_count{jobname=\"account-reconciler\",namespace=\"$namespace\"}[3m]))",
       "legendFormat": "Runtime in seconds"
      }
     ]
    },
    {
     "title": "Results",
     "type": "graph",
     "description": "The results of processed items by the job.",
     "gridPos": { "h": 8, "w": 10, "x": 14, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(result) (increase(job_results_job_result_sum{jobname=\"account-reconciler\",namespace=\"$namespace\"}[3m])) /\nsum by(result) (increase(job_results_job_result_count{jobname=\"account-reconciler\",namespace=\"$namespace\"}[3m]))",
       "legendFormat": "{{result}}"
      }
     ]
    }
   ]
  },
  {
   "title": "ebs-account-reconciler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Job pass (selected time) ",
     "type": "stat",
     "description": "The percentage of time that the job passes (no major issues).",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(increase(job_results_job_count{jobname=\"ebs-account-reconciler\",namespace=\"$namespace\",status=\"pass\"}[$__range])) /\nsum(increase(job_results_job_count{jobname=\"ebs-account-reconciler\",namespace=\"$namespace\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "description": "The job run duration.",
     "gridPos": { "h": 8, "w": 10, "x": 4, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (increase(job_results_job_duration_sum{jobname=\"ebs-account-reconciler\",namespace=\"$namespace\"}[3m])) /\nsum (increase(job_results_job_duration_count{jobname=\"ebs-account-reconciler\",namespace=\"$namespace\"}[3m]))",
       "legendFormat": "Runtime in seconds"
      }
     ]
    },
    {
     "title": "Results",
     "type": "graph",
     "description": "The results of processed items by the job.",
     "gridPos": { "h": 8, "w": 10, "x": 14, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(result) (increase(job_results_job_result_sum{jobname=\"ebs-account-reconciler\",namespace=\"$namespace\"}[3m])) /\nsum by(result) (increase(job_results_job_result_count{jobname=\"ebs-account-reconciler\",namespace=\"$namespace\"}[3m]))",
       "legendFormat": "{{result}}"
      }
     ]
    }
   ]
  },
  {
   "title": "fetch-telemeter-metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Job pass (selected time) ",
     "type": "stat",
     "description": "The percentage of time that the job passes (no major issues).",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(increase(job_results_job_count{jobname=\"fetch-telemeter-metrics\",namespace=\"$namespace\",status=\"pass\"}[$__range])) /\nsum(increase(job_results_job_count{jobname=\"fetch-telemeter-metrics\",namespace=\"$namespace\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "description": "The job run duration.",
     "gridPos": { "h": 8, "w": 10, "x": 4, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (increase(job_results_job_duration_sum{jobname=\"fetch-telemeter-metrics\",namespace=\"$namespace\"}[3m])) /\nsum (increase(job_results_job_duration_count{jobname=\"fetch-telemeter-metrics\",namespace=\"$namespace\"}[3m]))",
       "legendFormat": "Runtime in seconds"
      }
     ]
    },
    {
     "title": "Results",
     "type": "graph",
     "description": "The results of processed items by the job.",
     "gridPos": { "h": 8, "w": 10, "x": 14, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(result) (increase(job_results_job_result_sum{jobname=\"fetch-telemeter-metrics\",namespace=\"$namespace\"}[3m])) /\nsum by(result) (increase(job_results_job_result_count{jobname=\"fetch-telemeter-metrics\",namespace=\"$namespace\"}[3m]))",
       "legendFormat": "{{result}}"
      }
     ]
    }
   ]
  },
  {
   "title": "hydra-fetch-organizations-data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Job pass (selected time) ",
     "type": "stat",
     "description": "The percentage of time that the job passes (no major issues).",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(increase(job_results_job_count{jobname=\"hydra-fetch-organizations-data\",namespace=\"$namespace\",status=\"pass\"}[$__range])) /\nsum(increase(job_results_job_count{jobname=\"hydra-fetch-organizations-data\",namespace=\"$namespace\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "description": "The job run duration.",
     "gridPos": { "h": 8, "w": 10, "x": 4, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (increase(job_results_job_duration_sum{jobname=\"hydra-fetch-organizations-data\",namespace=\"$namespace\"}[10m])) /\nsum (increase(job_results_job_duration_count{jobname=\"hydra-fetch-organizations-data\",namespace=\"$namespace\"}[10m]))",
       "legendFormat": "Runtime in seconds"
      }
     ]
    },
    {
     "title": "Results",
     "type": "graph",
     "description": "The results of processed items by the job.",
     "gridPos": { "h": 8, "w": 10, "x": 14, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(result) (increase(job_results_job_result_sum{jobname=\"hydra-fetch-organizations-data\",namespace=\"$namespace\"}[10m])) /\nsum by(result) (increase(job_results_job_result_count{jobname=\"hydra-fetch-organizations-data\",namespace=\"$namespace\"}[10m]))",
       "legendFormat": "{{result}}"
      }
     ]
    }
   ]
  },
  {
   "title": "auto-entitlement-reconciler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Job pass (selected time) ",
     "type": "stat",
     "description": "The percentage of time that the job passes (no major issues).",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(increase(job_results_job_count{jobname=\"auto-entitlement-reconciler\",namespace=\"$namespace\",status=\"pass\"}[$__range])) /\nsum(increase(job_results_job_count{jobname=\"auto-entitlement-reconciler\",namespace=\"$namespace\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "description": "The job run duration.",
     "gridPos": { "h": 8, "w": 10, "x": 4, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (increase(job_results_job_duration_sum{jobname=\"auto-entitlement-reconciler\",namespace=\"$namespace\"}[10m])) /\nsum (increase(job_results_job_duration_count{jobname=\"auto-entitlement-reconciler\",namespace=\"$namespace\"}[10m]))",
       "legendFormat": "Runtime in seconds"
      }
     ]
    },
    {
     "title": "Results",
     "type": "graph",
     "description": "The results of processed items by the job.",
     "gridPos": { "h": 8, "w": 10, "x": 14, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(result) (increase(job_results_job_result_sum{jobname=\"auto-entitlement-reconciler\",namespace=\"$namespace\"}[10m])) /\nsum by(result) (increase(job_results_job_result_count{jobname=\"auto-entitlement-reconciler\",namespace=\"$namespace\"}[10m]))",
       "legendFormat": "{{result}}"
      }
     ]
    }
   ]
  },
  {
   "title": "ocp-usage-cleaner",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Job pass (selected time) ",
     "type": "stat",
     "description": "The percentage of time that the job passes (no major issues).",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(increase(job_results_job_count{jobname=\"ocp-usage-cleaner\",namespace=\"$namespace\",status=\"pass\"}[$__range])) /\nsum(increase(job_results_job_count{jobname=\"ocp-usage-cleaner\",namespace=\"$namespace\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "description": "The job run duration.",
     "gridPos": { "h": 8, "w": 10, "x": 4, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (increase(job_results_job_duration_sum{jobname=\"ocp-usage-cleaner\",namespace=\"$namespace\"}[10m])) /\nsum (increase(job_results_job_duration_count{jobname=\"ocp-usage-cleaner\",namespace=\"$namespace\"}[10m]))",
       "legendFormat": "Runtime in seconds"
      }
     ]
    },
    {
     "title": "Results",
     "type": "graph",
     "description": "The results of processed items by the job.",
     "gridPos": { "h": 8, "w": 10, "x": 14, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(result) (increase(job_results_job_result_sum{jobname=\"ocp-usage-cleaner\",namespace=\"$namespace\"}[10m])) /\nsum by(result) (increase(job_results_job_result_count{jobname=\"ocp-usage-cleaner\",namespace=\"$namespace\"}[10m]))",
       "legendFormat": "{{result}}"
      }
     ]
    }
   ]
  },
  {
   "title": "ocp-usage-reconciler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Job pass (selected time) ",
     "type": "stat",
     "description": "The percentage of time that the job passes (no major issues).",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(increase(job_results_job_count{jobname=\"ocp-usage-reconciler\",namespace=\"$namespace\",status=\"pass\"}[$__range])) /\nsum(increase(job_results_job_count{jobname=\"ocp-usage-reconciler\",namespace=\"$namespace\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "description": "The job run duration.",
     "gridPos": { "h": 8, "w": 10, "x": 4, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (increase(job_results_job_duration_sum{jobname=\"ocp-usage-reconciler\",namespace=\"$namespace\"}[10m])) /\nsum (increase(job_results_job_duration_count{jobname=\"ocp-usage-reconciler\",namespace=\"$namespace\"}[10m]))",
       "legendFormat": "Runtime in seconds"
      }
     ]
    },
    {
     "title": "Results",
     "type": "graph",
     "description": "The results of processed items by the job.",
     "gridPos": { "h": 8, "w": 10, "x": 14, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(result) (increase(job_results_job_result_sum{jobname=\"ocp-usage-reconciler\",namespace=\"$namespace\"}[10m])) /\nsum by(result) (increase(job_results_job_result_count{jobname=\"ocp-usage-reconciler\",namespace=\"$namespace\"}[10m]))",
       "legendFormat": "{{result}}"
      }
     ]
    }
   ]
  },
  {
   "title": "registry-credential-pool-loader",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Job pass (selected time) ",
     "type": "stat",
     "description": "The percentage of time that the job passes (no major issues).",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(increase(job_results_job_count{jobname=\"registry-credential-pool-loader\",namespace=\"$namespace\",status=\"pass\"}[$__range])) /\nsum(increase(job_results_job_count{jobname=\"registry-credential-pool-loader\",namespace=\"$namespace\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "description": "The job run duration.",
     "gridPos": { "h": 8, "w": 10, "x": 4, "y": 65 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (increase(job_results_job_duration_sum{jobname=\"registry-credential-pool-loader\",namespace=\"$namespace\"}[3m])) /\nsum (increase(job_results_job_duration_count{jobname=\"registry-credential-pool-loader\",namespace=\"$namespace\"}[3m]))"
      }
     ]
    },
    {
     "title": "Results",
     "type": "graph",
     "description": "The results of processed items by the job.",
     "gridPos": { "h": 8, "w": 10, "x": 14, "y": 65 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(result) (increase(job_results_job_result_sum{jobname=\"registry-credential-pool-loader\",namespace=\"$namespace\"}[3m])) /\nsum by(result) (increase(job_results_job_result_count{jobname=\"registry-credential-pool-loader\",namespace=\"$namespace\"}[3m]))",
       "legendFormat": "{{result}}"
      }
     ]
    }
   ]
  },
  {
   "title": "subscription-status-reconciler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Job pass (selected time) ",
     "type": "stat",
     "description": "The percentage of time that the job passes (no major issues).",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(increase(job_results_job_count{jobname=\"subscription-status-reconciler\",namespace=\"$namespace\",status=\"pass\"}[$__range])) /\nsum(increase(job_results_job_count{jobname=\"subscription-status-reconciler\",namespace=\"$namespace\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "description": "The job run duration.",
     "gridPos": { "h": 8, "w": 10, "x": 4, "y": 74 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (increase(job_results_job_duration_sum{jobname=\"subscription-status-reconciler\",namespace=\"$namespace\"}[3m])) /\nsum (increase(job_results_job_duration_count{jobname=\"subscription-status-reconciler\",namespace=\"$namespace\"}[3m]))"
      }
     ]
    },
    {
     "title": "Results",
     "type": "graph",
     "description": "The results of processed items by the job.",
     "gridPos": { "h": 8, "w": 10, "x": 14, "y": 74 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(result) (increase(job_results_job_result_sum{jobname=\"subscription-status-reconciler\",namespace=\"$namespace\"}[3m])) /\nsum by(result) (increase(job_results_job_result_count{jobname=\"subscription-status-reconciler\",namespace=\"$namespace\"}[3m]))",
       "legendFormat": "{{result}}"
      }
     ]
    }
   ]
  },
  {
   "title": "subscription-based-data-reconciler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Job pass (selected time) ",
     "type": "stat",
     "description": "The percentage of time that the job passes (no major issues).",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(increase(job_results_job_count{jobname=\"subscription-based-data-reconciler\",namespace=\"$namespace\",status=\"pass\"}[$__range])) /\nsum(increase(job_results_job_count{jobname=\"subscription-based-data-reconciler\",namespace=\"$namespace\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "description": "The job run duration.",
     "gridPos": { "h": 8, "w": 10, "x": 4, "y": 83 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (increase(job_results_job_duration_sum{jobname=\"subscription-based-data-reconciler\",namespace=\"$namespace\"}[3m])) /\nsum (increase(job_results_job_duration_count{jobname=\"subscription-based-data-reconciler\",namespace=\"$namespace\"}[3m]))"
      }
     ]
    },
    {
     "title": "Results",
     "type": "graph",
     "description": "The results of processed items by the job.",
     "gridPos": { "h": 8, "w": 10, "x": 14, "y": 83 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(result) (increase(job_results_job_result_sum{jobname=\"subscription-based-data-reconciler\",namespace=\"$namespace\"}[3m])) /\nsum by(result) (increase(job_results_job_result_count{jobname=\"subscription-based-data-reconciler\",namespace=\"$namespace\"}[3m]))",
       "legendFormat": "{{result}}"
      }
     ]
    }
   ]
  },
  {
   "title": "rh-marketplace-quota-reconciler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Job pass (selected time) ",
     "type": "stat",
     "description": "The percentage of time that the job passes (no major issues).",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(increase(job_results_job_count{jobname=\"rh-marketplace-quota-reconciler\",namespace=\"$namespace\",status=\"pass\"}[$__range])) /\nsum(increase(job_results_job_count{jobname=\"rh-marketplace-quota-reconciler\",namespace=\"$namespace\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "description": "The job run duration.",
     "gridPos": { "h": 8, "w": 10, "x": 4, "y": 92 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (increase(job_results_job_duration_sum{jobname=\"rh-marketplace-quota-reconciler\",namespace=\"$namespace\"}[3m])) /\nsum (increase(job_results_job_duration_count{jobname=\"rh-marketplace-quota-reconciler\",namespace=\"$namespace\"}[3m]))"
      }
     ]
    },
    {
     "title": "Results",
     "type": "graph",
     "description": "The results of processed items by the job.",
     "gridPos": { "h": 8, "w": 10, "x": 14, "y": 92 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(result) (increase(job_results_job_result_sum{jobname=\"rh-marketplace-quota-reconciler\",namespace=\"$namespace\"}[3m])) /\nsum by(result) (increase(job_results_job_result_count{jobname=\"rh-marketplace-quota-reconciler\",namespace=\"$namespace\"}[3m]))",
       "legendFormat": "{{result}}"
      }
     ]
    }
   ]
  }
 ]
}