{
 "title": "Weekly Overview",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "options": {
    "content": "# The Week of 3 Weeks Ago\n         "
   }
  },
  { "type": "text", "gridPos": { "h": 2, "w": 6, "x": 6, "y": 0 }, "options": { "content": "# The Week of 2 Weeks Ago" } },
  { "type": "text", "gridPos": { "h": 2, "w": 6, "x": 12, "y": 0 }, "options": { "content": "# Previous Week\n\n         " } },
  { "type": "text", "gridPos": { "h": 2, "w": 6, "x": 18, "y": 0 }, "options": { "content": "# Current Week\n\n         " } },
  {
   "title": "Clusters Created",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(sum(service_assisted_installer_cluster_creations{clusterId=~\".+\"})[28d:$__rate_interval]) - increase(sum(service_assisted_installer_cluster_creations{clusterId=~\".+\"})[21d:$__rate_interval])"
    }
   ]
  },
  {
   "title": "Clusters Created",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(sum(service_assisted_installer_cluster_creations{clusterId=~\".+\"})[21d:$__rate_interval]) - increase(sum(service_assisted_installer_cluster_creations{clusterId=~\".+\"})[14d:$__rate_interval])"
    }
   ]
  },
  {
   "title": "Clusters Created",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(sum(service_assisted_installer_cluster_creations{clusterId=~\".+\"})[14d:$__rate_interval]) - increase(sum(service_assisted_installer_cluster_creations{clusterId=~\".+\"})[7d:$__rate_interval])"
    }
   ]
  },
  {
   "title": "Clusters Created",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(sum(service_assisted_installer_cluster_creations{clusterId=~\".+\"})[7d:$__rate_interval])"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started))[28d:$__rate_interval]) - increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started))[21d:$__rate_interval])",
     "legendFormat": "Clusters Started Install (Unique by ClusterId)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started))[28d:$__rate_interval]) - increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started))[21d:$__rate_interval])) / (increase(sum(service_assisted_installer_cluster_creations{clusterId=~\".+\"})[28d:$__rate_interval]) - increase(sum(service_assisted_installer_cluster_creations{clusterId=~\".+\"})[21d:$__rate_interval]))",
     "legendFormat": "Creation vs Installation rate"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started))[21d:$__rate_interval]) - increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started))[14d:$__rate_interval])",
     "legendFormat": "Clusters Started Install (Unique by ClusterId)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started))[21d:$__rate_interval]) - increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started))[14d:$__rate_interval])) / (increase(sum(service_assisted_installer_cluster_creations{clusterId=~\".+\"})[21d:$__rate_interval]) - increase(sum(service_assisted_installer_cluster_creations{clusterId=~\".+\"})[14d:$__rate_interval]))",
     "legendFormat": "Creation vs Installation rate"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started))[14d:$__rate_interval]) - increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started))[7d:$__rate_interval])",
     "legendFormat": "Clusters Started Install (Unique by ClusterId)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started))[14d:$__rate_interval]) - increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started))[7d:$__rate_interval])) / (increase(sum(service_assisted_installer_cluster_creations{clusterId=~\".+\"})[14d:$__rate_interval]) - increase(sum(service_assisted_installer_cluster_creations{clusterId=~\".+\"})[7d:$__rate_interval]))",
     "legendFormat": "Creation vs Installation rate"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started))[7d:$__rate_interval])",
     "legendFormat": "Clusters Started Install (Unique by ClusterId)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started))[7d:$__rate_interval]) / increase(sum(service_assisted_installer_cluster_creations{clusterId=~\".+\"})[7d:$__rate_interval])",
     "legendFormat": "Creation vs Installation rate"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 8 },
   "options": {
    "content": "# Installation Results\n         "
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(sum(service_assisted_installer_cluster_installation_started{clusterId=~\".+\"})[28d:$__rate_interval]) - increase(sum(service_assisted_installer_cluster_installation_started{clusterId=~\".+\"})[21d:$__rate_interval])",
     "legendFormat": "Installation Start Triggered "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(increase(sum(service_assisted_installer_cluster_installation_started{clusterId=~\".+\"})[28d:$__rate_interval]) - increase(sum(service_assisted_installer_cluster_installation_started{clusterId=~\".+\"})[21d:$__rate_interval])) / (increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started))[28d:$__rate_interval]) - increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started))[21d:$__rate_interval]))",
     "legendFormat": "Average Install Attempts Per Cluster"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(sum(service_assisted_installer_cluster_installation_started{clusterId=~\".+\"})[21d:$__rate_interval]) - increase(sum(service_assisted_installer_cluster_installation_started{clusterId=~\".+\"})[14d:$__rate_interval])",
     "legendFormat": "Installation Start Triggered "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(increase(sum(service_assisted_installer_cluster_installation_started{clusterId=~\".+\"})[21d:$__rate_interval]) - increase(sum(service_assisted_installer_cluster_installation_started{clusterId=~\".+\"})[14d:$__rate_interval])) / (increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started))[21d:$__rate_interval]) - increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started))[14d:$__rate_interval]))",
     "legendFormat": "Average Install Attempts Per Cluster"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(sum(service_assisted_installer_cluster_installation_started{clusterId=~\".+\"})[14d:$__rate_interval]) - increase(sum(service_assisted_installer_cluster_installation_started{clusterId=~\".+\"})[7d:$__rate_interval])",
     "legendFormat": "Installation Start Triggered "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(increase(sum(service_assisted_installer_cluster_installation_started{clusterId=~\".+\"})[14d:$__rate_interval]) - increase(sum(service_assisted_installer_cluster_installation_started{clusterId=~\".+\"})[7d:$__rate_interval])) / (increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started))[14d:$__rate_interval]) - increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started))[7d:$__rate_interval]))",
     "legendFormat": "Average Install Attempts Per Cluster"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(sum(service_assisted_installer_cluster_installation_started{clusterId=~\".+\"})[7d:$__rate_interval])",
     "legendFormat": "Installation Start Triggered "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(sum(service_assisted_installer_cluster_installation_started{clusterId=~\".+\"})[7d:$__rate_interval]) / increase(count(count by (clusterId)(service_assisted_installer_cluster_installation_started))[7d:$__rate_interval])",
     "legendFormat": "Average Install Attempts Per Cluster"
    }
   ]
  },
  {
   "title": "Installations Success Rate",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 13 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{clusterId=~\".+\"})[28d:$__rate_interval]) - increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{clusterId=~\".+\"})[21d:$__rate_interval])",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Installations Success Rate",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 13 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{clusterId=~\".+\"})[21d:$__rate_interval]) - increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{clusterId=~\".+\"})[14d:$__rate_interval])",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Installations Success Rate",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 13 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{clusterId=~\".+\"})[14d:$__rate_interval]) - increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{clusterId=~\".+\"})[7d:$__rate_interval])",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Installations Success Rate",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 13 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{clusterId=~\".+\"})[7d:$__rate_interval])",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Installed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{result=\"installed\",clusterId=~\".+\"})[28d:$__rate_interval]) - increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{result=\"installed\",clusterId=~\".+\"})[21d:$__rate_interval]))",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Canceled",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{result=\"canceled\",clusterId=~\".+\"})[28d:$__rate_interval]) - increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{result=\"canceled\",clusterId=~\".+\"})[21d:$__rate_interval]))",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Error",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{result=\"error\",clusterId=~\".+\"})[28d:$__rate_interval]) - increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{result=\"error\",clusterId=~\".+\"})[21d:$__rate_interval]))",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Installed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{result=\"installed\",clusterId=~\".+\"})[21d:$__rate_interval]) - increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{result=\"installed\",clusterId=~\".+\"})[14d:$__rate_interval]))",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Canceled",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{result=\"canceled\",clusterId=~\".+\"})[21d:$__rate_interval]) - increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{result=\"canceled\",clusterId=~\".+\"})[14d:$__rate_interval]))",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Error",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{result=\"error\",clusterId=~\".+\"})[21d:$__rate_interval]) - increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{result=\"error\",clusterId=~\".+\"})[14d:$__rate_interval]))",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Installed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{result=\"installed\",clusterId=~\".+\"})[14d:$__rate_interval]) - increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{result=\"installed\",clusterId=~\".+\"})[7d:$__rate_interval]))",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Canceled",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{result=\"canceled\",clusterId=~\".+\"})[14d:$__rate_interval]) - increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{result=\"canceled\",clusterId=~\".+\"})[7d:$__rate_interval]))",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Error",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{result=\"error\",clusterId=~\".+\"})[14d:$__rate_interval]) - increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{result=\"error\",clusterId=~\".+\"})[7d:$__rate_interval]))",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Installed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{result=\"installed\",clusterId=~\".+\"})[7d:$__rate_interval]))",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Canceled",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{result=\"canceled\",clusterId=~\".+\"})[7d:$__rate_interval]))",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Error",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(sum by (result)(service_assisted_installer_cluster_installation_seconds_count{result=\"error\",clusterId=~\".+\"})[7d:$__rate_interval]))",
     "legendFormat": "Current"
    }
   ]
  }
 ]
}