{
 "title": "MAS SSO Monitoring",
 "description": "Monitoring MAS SSO metrics",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(keycloak_request_duration_count,namespace)"
   },
   {
    "name": "realm",
    "label": "Realm",
    "query": "label_values(keycloak_logins{namespace=\"$namespace\",job=\"keycloak\"},realm)"
   },
   {
    "name": "ClientId",
    "label": "ClientId",
    "query": "label_values(keycloak_logins{namespace=\"$namespace\",job=\"keycloak\",realm=\"$realm\"},client_id)"
   }
  ]
 },
 "panels": [
  {
   "title": "SLO Availability",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(haproxy_backend_http_responses_total{route=~\"^keycloak.*\",exported_namespace=\"$namespace\",code!=\"5xx\"}[$__range]))/sum(rate(haproxy_backend_http_responses_total{route=~\"^keycloak.*\",exported_namespace=\"$namespace\"}[$__range]))) * 100"
    }
   ]
  },
  {
   "title": "SLO Latency 99% < 1s",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(keycloak_request_duration_bucket{namespace=\"$namespace\",le=\"1000.0\"}[$__range]))/sum(rate(keycloak_request_duration_count{namespace=\"$namespace\"}[$__range]))) * 100"
    }
   ]
  },
  {
   "title": "Total Increase Requests",
   "type": "stat",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(haproxy_backend_http_responses_total{exported_namespace=\"$namespace\",route=~\"^keycloak.*\"}[$__range]))",
     "legendFormat": "Total Requests"
    },
    {
     "expr": "sum(increase(haproxy_backend_http_responses_total{exported_namespace=\"$namespace\", code=\"5xx\" , route=~\"^keycloak.*\"}[$__range]))",
     "legendFormat": "5xx Errors"
    },
    {
     "expr": "sum(increase(haproxy_backend_http_responses_total{exported_namespace=\"$namespace\", code=\"4xx\", route=~\"^keycloak.*\"}[$__range]))",
     "legendFormat": "4xx Errors"
    },
    {
     "expr": "sum(increase(keycloak_request_duration_count{namespace=\"$namespace\"}[$__range])) - sum(increase(keycloak_request_duration_bucket{namespace=\"$namespace\", le=\"1000.0\"}[$__range]))",
     "legendFormat": "> 1s"
    },
    {
     "expr": "sum(increase(keycloak_request_duration_count{namespace=\"$namespace\"}[$__range])) - sum(increase(keycloak_request_duration_bucket{namespace=\"$namespace\", le=\"10000.0\"}[$__range]))",
     "legendFormat": "> 10s"
    }
   ]
  },
  { "title": "System Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Error Request Rate (HA Proxy)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "# of errors" }
   ],
   "targets": [
    {
     "expr": "sum(rate(haproxy_backend_http_responses_total{route=~\"^keycloak.*\",exported_namespace=\"$namespace\", code=\"5xx\"}[$__range])) by ( code)",
     "legendFormat": "5xx"
    },
    {
     "expr": "sum(rate(haproxy_backend_http_responses_total{route=~\"^keycloak.*\",exported_namespace=\"$namespace\", code=\"4xx\"}[$__range])) by ( code)",
     "legendFormat": "4xx"
    }
   ]
  },
  {
   "title": "Request Rates (HA Proxy)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(haproxy_backend_http_responses_total{exported_namespace=\"$namespace\",route=~\"^keycloak.*\"}[$__range]))",
     "legendFormat": "Request Per Sec"
    }
   ]
  },
  {
   "title": "Request Rates By Resource (keycloak)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (resource) (rate(keycloak_request_duration_bucket{le=\"+Inf\"}[$__range]))",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Total Request By Resource (keycloak)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (resource) (increase(keycloak_request_duration_bucket{le=\"+Inf\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(keycloak_request_duration_bucket{namespace=\"$namespace\"}[$__range])>0) by (le, resource))",
     "legendFormat": "99th {{resource}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(keycloak_request_duration_bucket{namespace=\"$namespace\"}[$__range])>0) by (le, resource))",
     "legendFormat": "90th {{resource}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(keycloak_request_duration_bucket{namespace=\"$namespace\"}[$__range])>0) by (le))",
     "legendFormat": "99th ALL"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(keycloak_request_duration_bucket{namespace=\"$namespace\"}[$__range])>0) by (le))",
     "legendFormat": "90th ALL"
    }
   ]
  },
  {
   "title": "Operator Available Replicas",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short", "label": "Ready" }
   ],
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{namespace=\"$namespace\", deployment=\"rhsso-operator\"}",
     "legendFormat": "Replicas Available"
    }
   ]
  },
  {
   "title": "Readiness Probes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 34 },
   "yaxes": [
    { "format": "short", "label": "Ready" }
   ],
   "targets": [
    {
     "expr": "sum(up{namespace=\"$namespace\", job=\"keycloak\"}) by (pod)",
     "legendFormat": "Pod {{pod}}"
    },
    {
     "expr": "sum((wildfly_datasources_pool_available_count{namespace=\"$namespace\", xa_data_source=\"keycloak_postgresql-DB\"} + wildfly_datasources_pool_active_count{namespace=\"$namespace\", xa_data_source=\"keycloak_postgresql-DB\"}) >bool 0) by (pod)",
     "legendFormat": "Database"
    }
   ]
  },
  {
   "title": "Multi AZ Distribution - # of AZ(s)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "              count (sum by (label_topology_kubernetes_io_zone) \n              (kube_pod_info{created_by_kind != \"<none>\",created_by_name=\"keycloak\",namespace=\"$namespace\"} * on(node) \n              group_left(label_topology_kubernetes_io_zone) kube_node_labels{label_topology_kubernetes_io_zone != \"\", cluster =\"\"}))\n"
    }
   ]
  },
  {
   "title": "Rate of Error Response Codes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (code, resource, method) (rate(keycloak_response_errors{code=~\"5.*|400\"}[$__rate_interval]))"
    }
   ]
  },
  { "title": "Detailed metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Pod Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\", pod=\"keycloak-0\"}",
     "legendFormat": "Requests"
    },
    {
     "expr": "kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"memory\", pod=\"keycloak-0\"}",
     "legendFormat": "Limits"
    },
    {
     "expr": "container_memory_rss{namespace=\"$namespace\", container=\"keycloak\"}  ",
     "legendFormat": "RSS for {{pod}}"
    },
    {
     "expr": "sum(jvm_memory_bytes_committed{namespace=\"$namespace\",job=\"keycloak\"}) by (pod)",
     "legendFormat": "JVM Committed for {{pod}}"
    },
    {
     "expr": "sum(jvm_memory_bytes_max{namespace=\"$namespace\",job=\"keycloak\"}) by (pod)",
     "legendFormat": "JVM Max for {{pod}}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 7, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"cpu\", pod=\"keycloak-0\"}",
     "legendFormat": "CPU Limit for {{pod}}"
    },
    {
     "expr": "kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"cpu\", pod=\"keycloak-0\"}",
     "legendFormat": "CPU Request for {{pod}}"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container=\"keycloak\"}[1m])) by (pod)",
     "legendFormat": "CPU Load for {{pod}}"
    }
   ]
  },
  {
   "title": "Number of GC Collections [30m]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(jvm_gc_collection_seconds_count{namespace=\"$namespace\", job=\"keycloak\"}[30m])) by (pod)",
     "legendFormat": "GC Collections for {{pod}}"
    }
   ]
  },
  {
   "title": "JVM Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\", pod=\"keycloak-0\"}",
     "legendFormat": "Requests"
    },
    {
     "expr": "kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"memory\", pod=\"keycloak-0\"}",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(base_memory_usedHeap_bytes{namespace=\"$namespace\"})",
     "legendFormat": "JVM Heap for {{pod}}"
    },
    {
     "expr": "sum(base_memory_usedNonHeap_bytes{namespace=\"$namespace\"})",
     "legendFormat": "JVM Non Heap for {{pod}}"
    }
   ]
  },
  {
   "title": "Total GC Time [30m]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 7, "y": 59 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(increase(jvm_gc_collection_seconds_sum{namespace=\"$namespace\", job=\"keycloak\"}[30m])) by (pod)",
     "legendFormat": "Total GC Time for {{pod}}"
    }
   ]
  },
  {
   "title": "IO Threads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wildfly_io_io_thread_count{namespace=\"$namespace\"}",
     "legendFormat": "IO Threads for {{pod}}"
    },
    {
     "expr": "wildfly_io_queue_size{namespace=\"$namespace\"}",
     "legendFormat": "I/O Queue size for {{pod}}"
    },
    {
     "expr": "wildfly_io_busy_task_thread_count{namespace=\"$namespace\"}",
     "legendFormat": "I/O Busy tasks for {{pod}}"
    },
    {
     "expr": "wildfly_io_max_pool_size{namespace=\"$namespace\"}",
     "legendFormat": "IO Max pool size for {{pod}}"
    },
    {
     "expr": "kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"cpu\", pod=\"keycloak-0\"}",
     "legendFormat": "CPU limit"
    }
   ]
  },
  {
   "title": "Number of transactions [30m]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(wildfly_datasources_pool_xacommit_count{namespace=\"$namespace\", xa_data_source=\"keycloak_postgresql-DB\"}[30m])",
     "legendFormat": "Number of commits for {{pod}}"
    },
    {
     "expr": "increase(wildfly_datasources_pool_xarollback_count{namespace=\"$namespace\", xa_data_source=\"keycloak_postgresql-DB\"}[30m])",
     "legendFormat": "Number of rollbacks for {{pod}}"
    },
    {
     "expr": "increase(wildfly_datasources_pool_blocking_failure_count{namespace=\"$namespace\", xa_data_source=\"keycloak_postgresql-DB\"}[30m])",
     "legendFormat": "Number of failures for {{pod}}"
    }
   ]
  },
  {
   "title": "Number of database connections in pool",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wildfly_datasources_pool_active_count{namespace=\"$namespace\", xa_data_source=\"keycloak_postgresql-DB\"}",
     "legendFormat": "Active for {{pod}}"
    },
    {
     "expr": "wildfly_datasources_pool_available_count{namespace=\"$namespace\", xa_data_source=\"keycloak_postgresql-DB\"}",
     "legendFormat": "Available for {{pod}}"
    }
   ]
  },
  { "title": "Experimental", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Logins per REALM",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (realm)(increase(keycloak_logins{namespace=\"$namespace\",job=\"keycloak\"}[1h]))",
     "legendFormat": "{{realm}}"
    }
   ]
  },
  {
   "title": "Login Errors on realm $realm",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(client_id) (increase(keycloak_failed_login_attempts{namespace=\"$namespace\",job=\"keycloak\"}[$__range]))",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Logins per CLIENT on realm $realm",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(keycloak_logins{namespace=\"$namespace\",job=\"keycloak\",realm=\"$realm\"}[$__range])",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Endpoint latency [5m]",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 82 },
   "targets": [
    {
     "expr": "sum(increase(keycloak_request_duration_bucket[5m])) by (le)",
     "legendFormat": "Request taking less or equal than {{le}}"
    }
   ]
  },
  {
   "title": "Endpoint latency [5m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(increase(keycloak_request_duration_sum{namespace=\"$namespace\"}[5m])) by (route) / sum(increase(keycloak_request_duration_count{namespace=\"$namespace\"}[5m])) by (route)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Traffic Balance ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (increase(keycloak_request_duration_bucket{le=\"+Inf\",namespace=\"$namespace\"}[30m]))"
    }
   ]
  }
 ]
}