{
 "title": "Basic Cluster operation",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "POST Cluster By Status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v1/clusters\", method=\"POST\"}[5m])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "POST Cluster Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v1/clusters\", method=\"POST\"}[5m])) by (le))",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(http_request_duration_seconds_bucket{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v1/clusters\", method=\"POST\"}[5m])) by (le))",
     "legendFormat": "0.9"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(http_request_duration_seconds_bucket{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v1/clusters\", method=\"POST\"}[5m])) by (le))",
     "legendFormat": "0.75"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v1/clusters\", method=\"POST\"}[5m])) by (le))",
     "legendFormat": "0.5"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v1/clusters\", method=\"POST\"}[5m])) by (handler) / sum(rate(http_request_duration_seconds_count{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v1/clusters\", method=\"POST\"}[5m])) by (handler)",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "GET Cluster By Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v1/clusters/{cluster_id}\", method=\"GET\"}[5m])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "GET Cluster Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v1/clusters/{cluster_id}\", method=\"GET\"}[5m])) by (le))",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(http_request_duration_seconds_bucket{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v1/clusters/{cluster_id}\", method=\"GET\"}[5m])) by (le))",
     "legendFormat": "0.9"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(http_request_duration_seconds_bucket{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v1/clusters/{cluster_id}\", method=\"GET\"}[5m])) by (le))",
     "legendFormat": "0.75"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v1/clusters/{cluster_id}\", method=\"GET\"}[5m])) by (le))",
     "legendFormat": "0.5"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v1/clusters/{cluster_id}\", method=\"GET\"}[5m])) by (handler) / sum(rate(http_request_duration_seconds_count{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v1/clusters/{cluster_id}\", method=\"GET\"}[5m])) by (handler)",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Post Generate ISO Image",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v1/clusters/{cluster_id}/downloads/image\", method=\"POST\"}[5m])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "POST Generate ISO Image Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v1/clusters/{cluster_id}/downloads/image\", method=\"POST\"}[5m])) by (le))",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v1/clusters/{cluster_id}/downloads/image\", method=\"POST\"}[5m])) by (le))",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(http_request_duration_seconds_bucket{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v1/clusters/{cluster_id}/downloads/image\", method=\"POST\"}[5m])) by (le))",
     "legendFormat": "0.75"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(http_request_duration_seconds_bucket{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v1/clusters/{cluster_id}/downloads/image\", method=\"POST\"}[5m])) by (le))",
     "legendFormat": "0.9"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{endpoint=\"assisted-svc\",handler=\"/api/assisted-install/v1/clusters/{cluster_id}/downloads/image\", method=\"POST\"}[5m])) by (handler) / sum(rate(http_request_duration_seconds_count{endpoint=\"assisted-svc\",handler=\"/api/assisted-install/v1/clusters/{cluster_id}/downloads/image\", method=\"POST\"}[5m])) by (handler)\n",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "POST UploadHostLogs By status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v1/clusters/{cluster_id}/hosts/{host_id}/logs\", method=\"POST\"}[5m])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "POST UploadHostLogs Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v1/clusters/{cluster_id}/hosts/{host_id}/logs\", method=\"POST\"}[5m])) by (le))",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(http_request_duration_seconds_bucket{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v1/clusters/{cluster_id}/hosts/{host_id}/logs\", method=\"POST\"}[5m])) by (le))",
     "legendFormat": "0.9"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(http_request_duration_seconds_bucket{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v1/clusters/{cluster_id}/hosts/{host_id}/logs\", method=\"POST\"}[5m])) by (le))",
     "legendFormat": "0.75"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v1/clusters/{cluster_id}/hosts/{host_id}/logs\", method=\"POST\"}[5m])) by (le))",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket{endpoint=\"assisted-svc\", handler=\"/api/assisted-install/v1/clusters/{cluster_id}/hosts/{host_id}/logs\", method=\"POST\"}[5m])) by (le))",
     "legendFormat": "0.5"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{endpoint=\"assisted-svc\",handler=\"/api/assisted-install/v1/clusters/{cluster_id}/hosts/{host_id}/logs\", method=\"POST\"}[5m])) by (handler) / sum(rate(http_request_duration_seconds_count{endpoint=\"assisted-svc\",handler=\"/api/assisted-install/v1/clusters/{cluster_id}/hosts/{host_id}/logs\", method=\"POST\"}[5m])) by (handler)\n",
     "legendFormat": "avg"
    }
   ]
  }
 ]
}