{
 "title": "JVM Workspace Master",
 "description": "JVM  Che Workspace Master",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": "label_values(application)" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\"}, instance)"
   },
   {
    "name": "jvm_memory_pool_heap",
    "label": "JVM Memory Pools Heap",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"},id)"
   },
   {
    "name": "jvm_memory_pool_nonheap",
    "label": "JVM Memory Pools Non-Heap",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"},id)"
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Quick Facts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_uptime_seconds{application=\"$application\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_start_time_seconds{application=\"$application\", instance=\"$instance\"}*1000"
    }
   ]
  },
  {
   "title": "Heap used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{application=\"$application\",instance=\"$instance\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Non-Heap used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{application=\"$application\",instance=\"$instance\", area=\"nonheap\"})"
    }
   ]
  },
  { "title": "JVM Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "JVM Heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Non-Heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{application=\"$application\", instance=\"$instance\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Process Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_memory_rss_bytes{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "rss"
    },
    {
     "expr": "process_memory_pss_bytes{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "pss"
    },
    {
     "expr": "process_memory_swap_bytes{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "swap"
    },
    {
     "expr": "process_memory_swappss_bytes{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "swappss"
    },
    {
     "expr": "process_memory_pss_bytes{application=\"$application\", instance=\"$instance\"} + process_memory_swap_bytes{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "phys (pss+swap)"
    }
   ]
  },
  { "title": "JVM Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "system_cpu_usage{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "system"
    },
    {
     "expr": "process_cpu_usage{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "process"
    },
    {
     "expr": "avg_over_time(process_cpu_usage{application=\"$application\", instance=\"$instance\"}[1h])",
     "legendFormat": "process-1h"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_load_average_1m{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "system-1m"
    },
    {},
    {
     "expr": "system_cpu_count{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_live{application=\"$application\", instance=\"$instance\"} or jvm_threads_live_threads{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "live"
    },
    {
     "expr": "jvm_threads_daemon{application=\"$application\", instance=\"$instance\"} or jvm_threads_daemon_threads{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "daemon"
    },
    {
     "expr": "jvm_threads_peak{application=\"$application\", instance=\"$instance\"} or jvm_threads_peak_threads{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "peak"
    },
    {
     "expr": "process_threads{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "process"
    }
   ]
  },
  {
   "title": "Thread States",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_states_threads{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Log Events (1m)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(logback_events_total{application=\"$application\", instance=\"$instance\"}[1m])",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "open"
    },
    {
     "expr": "process_max_fds{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "max"
    },
    {
     "expr": "process_files_open{application=\"$application\", instance=\"$instance\"} or process_files_open_files{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "open"
    },
    {
     "expr": "process_files_max{application=\"$application\", instance=\"$instance\"} or process_files_max_files{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "JVM Memory Pools (Heap)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 }, "repeat": "persistence_counts" },
  {
   "title": "$jvm_memory_pool_heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "repeat": "jvm_memory_pool_heap",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", id=~\"$jvm_memory_pool_heap\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_committed_bytes{application=\"$application\", instance=\"$instance\", id=~\"$jvm_memory_pool_heap\"}",
     "legendFormat": "commited"
    },
    {
     "expr": "jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", id=~\"$jvm_memory_pool_heap\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "$jvm_memory_pool_heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", id=~\"$jvm_memory_pool_heap\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_committed_bytes{application=\"$application\", instance=\"$instance\", id=~\"$jvm_memory_pool_heap\"}",
     "legendFormat": "commited"
    },
    {
     "expr": "jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", id=~\"$jvm_memory_pool_heap\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "$jvm_memory_pool_heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", id=~\"$jvm_memory_pool_heap\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_committed_bytes{application=\"$application\", instance=\"$instance\", id=~\"$jvm_memory_pool_heap\"}",
     "legendFormat": "commited"
    },
    {
     "expr": "jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", id=~\"$jvm_memory_pool_heap\"}",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "JVM Memory Pools (Non-Heap)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "$jvm_memory_pool_nonheap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 36 },
   "repeat": "jvm_memory_pool_nonheap",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", id=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_committed_bytes{application=\"$application\", instance=\"$instance\", id=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "commited"
    },
    {
     "expr": "jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", id=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "$jvm_memory_pool_nonheap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 36 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", id=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_committed_bytes{application=\"$application\", instance=\"$instance\", id=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "commited"
    },
    {
     "expr": "jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", id=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "$jvm_memory_pool_nonheap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 36 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", id=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_committed_bytes{application=\"$application\", instance=\"$instance\", id=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "commited"
    },
    {
     "expr": "jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", id=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Collections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_count{application=\"$application\", instance=\"$instance\"}[1m])",
     "legendFormat": "{{action}} ({{cause}})"
    }
   ]
  },
  {
   "title": "Pause Durations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 44 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_sum{application=\"$application\", instance=\"$instance\"}[1m])/rate(jvm_gc_pause_seconds_count{application=\"$application\", instance=\"$instance\"}[1m])",
     "legendFormat": "avg {{action}} ({{cause}})"
    },
    {
     "expr": "jvm_gc_pause_seconds_max{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "max {{action}} ({{cause}})"
    }
   ]
  },
  {
   "title": "Allocated/Promoted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 44 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_memory_allocated_bytes_total{application=\"$application\", instance=\"$instance\"}[1m])",
     "legendFormat": "allocated"
    },
    {
     "expr": "rate(jvm_gc_memory_promoted_bytes_total{application=\"$application\", instance=\"$instance\"}[1m])",
     "legendFormat": "promoted"
    }
   ]
  },
  { "title": "Classloading", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Classes loaded",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded{application=\"$application\", instance=\"$instance\"} or jvm_classes_loaded_classes{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "loaded"
    }
   ]
  },
  {
   "title": "Class delta (5m)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(jvm_classes_loaded{application=\"$application\",instance=\"$instance\"}[5m]) or delta(jvm_classes_loaded_classes{application=\"$application\",instance=\"$instance\"}[5m])",
     "legendFormat": "delta"
    }
   ]
  },
  { "title": "Buffer Pools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Direct Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{application=\"$application\", instance=\"$instance\", id=\"direct\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{application=\"$application\", instance=\"$instance\", id=\"direct\"}",
     "legendFormat": "capacity"
    }
   ]
  },
  {
   "title": "Direct Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_count{application=\"$application\", instance=\"$instance\", id=\"direct\"} or jvm_buffer_count_buffers{application=\"$application\", instance=\"$instance\", id=\"direct\"}",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Mapped Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{application=\"$application\", instance=\"$instance\", id=\"mapped\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{application=\"$application\", instance=\"$instance\", id=\"mapped\"}",
     "legendFormat": "capacity"
    }
   ]
  },
  {
   "title": "Mapped Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_count{application=\"$application\", instance=\"$instance\", id=\"mapped\"} or jvm_buffer_count_buffers{application=\"$application\", instance=\"$instance\", id=\"mapped\"}",
     "legendFormat": "count"
    }
   ]
  }
 ]
}
{
 "title": "Che Server",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Users",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "che_user_total", "legendFormat": "Number of Users" }
   ]
  },
  {
   "title": "Number of Workspaces",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(che_workspace_status)", "legendFormat": "Number of Workspaces" }
   ]
  },
  {
   "title": "Workspace start attempts",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(che_workspace_starting_attempts_total)",
     "legendFormat": "Workspace start attempts"
    },
    {
     "expr": "che_workspace_starting_attempts_total{debug='true'}",
     "legendFormat": "Workspace start attempts in start-debug mode"
    }
   ]
  },
  { "title": "Workspaces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Workspace start rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(increase(che_workspace_failure_total{while=\"STARTING\"} [1h])) /(sum(increase(che_workspace_failure_total{while=\"STARTING\"} [1h])) + sum(increase(che_workspace_started_total [1h])))",
     "legendFormat": "fail"
    },
    {
     "expr": "sum(increase(che_workspace_started_total [1h]))/(sum(increase(che_workspace_failure_total{while=\"STARTING\"} [1h])) + sum(increase(che_workspace_started_total [1h])))",
     "legendFormat": "success"
    }
   ]
  },
  {
   "title": "Workspace stop rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(increase(che_workspace_failure_total{while=\"STOPPING\"} [1h])) /(sum(increase(che_workspace_failure_total{while=\"STOPPING\"} [1h])) + sum(increase(che_workspace_stopped_total [1h])))",
     "legendFormat": "fail"
    },
    {
     "expr": "sum(increase(che_workspace_stopped_total [1h]))/(sum(increase(che_workspace_failure_total{while=\"STOPPING\"} [1h])) + sum(increase(che_workspace_stopped_total [1h])))",
     "legendFormat": "success"
    }
   ]
  },
  {
   "title": "Starting Workspaces",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "che_workspace_status{status=\"STARTING\"}",
     "legendFormat": "starting"
    }
   ]
  },
  {
   "title": "Stopping Workspaces",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "che_workspace_status{status=\"STOPPING\"}",
     "legendFormat": "running"
    }
   ]
  },
  {
   "title": "Average workspace start time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(che_workspace_start_time_seconds_sum[1h])/increase(che_workspace_start_time_seconds_count [1h])",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Average workspace stop time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(che_workspace_stop_time_seconds_sum[1h])/increase(che_workspace_stop_time_seconds_count [1h])",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Workspace Failures",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(che_workspace_failure_total)",
     "legendFormat": "failure"
    }
   ]
  },
  {
   "title": "Running Workspaces",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "che_workspace_status{status=\"RUNNING\"}",
     "legendFormat": "running"
    }
   ]
  },
  {
   "title": "Workspaces started under 60 seconds",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "increase(che_workspace_start_time_seconds_bucket{le=\"62.992853672\",result=\"success\"}[1h]) / ignoring(le) increase(che_workspace_start_time_seconds_count{result=\"success\"}[1h])",
     "legendFormat": "workspace start ratio"
    }
   ]
  },
  {
   "title": "Number of Workspaces",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "sum(che_workspace_status)", "legendFormat": "Number of Workspaces" }
   ]
  },
  { "title": "Users", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Number of Users",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "che_user_total", "legendFormat": "Number of Users" }
   ]
  },
  { "title": "Request", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "req/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(deriv(che_server_api_response_total[1m]))",
     "legendFormat": "rate"
    }
   ]
  },
  { "title": "K8s API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "req/minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(okhttp_requests_seconds_count[1m])",
     "legendFormat": "{{method}}-{{status}}"
    }
   ]
  },
  {
   "title": "Avg execution time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(okhttp_requests_seconds_sum[1h])/increase(okhttp_requests_seconds_count[1h])",
     "legendFormat": "{{method}}-{{status}}"
    }
   ]
  },
  { "title": "Tomcat", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Max number of active sessions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tomcat_sessions_active_max_sessions",
     "legendFormat": "sessions"
    }
   ]
  },
  {
   "title": "Number of current active sessions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tomcat_sessions_active_current_sessions",
     "legendFormat": "sessions"
    }
   ]
  },
  {
   "title": "Total sessions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tomcat_sessions_created_sessions_total",
     "legendFormat": "sessions"
    }
   ]
  },
  {
   "title": "Expired sessions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tomcat_sessions_expired_sessions_total",
     "legendFormat": "sessions"
    }
   ]
  },
  {
   "title": "Rejected sessions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tomcat_sessions_rejected_sessions_total",
     "legendFormat": "sessions"
    }
   ]
  },
  {
   "title": "Longest time of an expired session",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 52 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "tomcat_sessions_alive_max_seconds",
     "legendFormat": "session time"
    }
   ]
  },
  { "title": "Executors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Thread running",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "thread_factory_running_threads", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Thread terminated",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "thread_factory_terminated_threads_total",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Thread created",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "thread_factory_created_threads_total",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Created thread/minute",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(thread_factory_created_threads_total[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Executor threads active",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "executor_active_threads", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Executor pool size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "executor_pool_size_threads", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Queued tasks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "executor_queued_tasks", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Queue occupancy",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100*(1-executor_queue_remaining_tasks/ (executor_queue_remaining_tasks + executor_queued_tasks ))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Rejected task",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "executor_rejected_tasks_total", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Rejected task/minute",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 87 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(executor_rejected_tasks_total[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Completed tasks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "executor_completed_tasks_total", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Completed tasks/minute ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 94 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(executor_completed_tasks_total[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Tasks execution seconds max",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 101 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "executor_seconds_max", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Tasks execution seconds avg",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 101 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(executor_seconds_sum[1h])/increase(executor_seconds_count[1h])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Executor idle seconds max",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 108 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "executor_idle_seconds_max", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Executor idle seconds avg",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 108 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(executor_idle_seconds_sum[1h])/increase(executor_idle_seconds_count[1h])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Scheduled repetitively",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 115 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "executor_scheduled_repetitively_total",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Executor scheduled once",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 115 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "executor_scheduled_once_total", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Executor scheduled cron",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 122 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "executor_scheduled_cron_total", "legendFormat": "{{name}}" }
   ]
  },
  { "title": "Traces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 129 } },
  {
   "title": "Workspace Start Max",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 130 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "che_server_api_tracing_span_seconds_max{operation=\"WorkspaceRuntimes#startAsync\"}",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "che_server_api_tracing_span_seconds_max{operation=\"OpenShiftInternalRuntime#start\"}",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Workspace Start Avg",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 130 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(che_server_api_tracing_span_seconds_sum{operation=\"WorkspaceRuntimes#startAsync\"}[1h]) / increase(che_server_api_tracing_span_seconds_count{operation=\"WorkspaceRuntimes#startAsync\"}[1h])",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "increase(che_server_api_tracing_span_seconds_sum{operation=\"OpenShiftInternalRuntime#start\"}[1h]) / increase(che_server_api_tracing_span_seconds_count{operation=\"OpenShiftInternalRuntime#start\"}[1h])",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Workspace Stop Max",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 137 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "che_server_api_tracing_span_seconds_max{operation=\"WorkspaceRuntimes#stopAsync\"}",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "che_server_api_tracing_span_seconds_max{operation=\"OpenShiftInternalRuntime#internalStop\"}",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Workspace Stop Avg",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 137 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(che_server_api_tracing_span_seconds_sum{operation=\"WorkspaceRuntimes#stopAsync\"}[1h]) / increase(che_server_api_tracing_span_seconds_count{operation=\"WorkspaceRuntimes#stopAsync\"}[1h])",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "increase(che_server_api_tracing_span_seconds_sum{operation=\"OpenShiftInternalRuntime#internalStop\"}[1h]) / increase(che_server_api_tracing_span_seconds_count{operation=\"OpenShiftInternalRuntime#internalStop\"}[1h])",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "OpenShiftInternalRuntime#start Max",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 144 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "che_server_api_tracing_span_seconds_max{operation=\"SidecarToolingProvisioner#provision\"}",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "che_server_api_tracing_span_seconds_max{operation=\"OpenShiftEnvironmentProvisioner#provision\"}",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "che_server_api_tracing_span_seconds_max{operation=\"PerWorkspacePVCStrategy#prepare\"}",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "che_server_api_tracing_span_seconds_max{operation=\"OpenShiftInternalRuntime#startMachines\"}",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "che_server_api_tracing_span_seconds_max{operation=\"WaitMachinesStart\"}",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "OpenShiftInternalRuntime#start avg",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 144 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(che_server_api_tracing_span_seconds_sum{operation=\"SidecarToolingProvisioner#provision\"}[1h]) / increase(che_server_api_tracing_span_seconds_count{operation=\"SidecarToolingProvisioner#provision\"}[1h])",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "increase(che_server_api_tracing_span_seconds_sum{operation=\"OpenShiftEnvironmentProvisioner#provision\"}[1h]) / increase(che_server_api_tracing_span_seconds_count{operation=\"OpenShiftEnvironmentProvisioner#provision\"}[1h])",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "increase(che_server_api_tracing_span_seconds_sum{operation=\"PerWorkspacePVCStrategy#prepare\"}[1h]) / increase(che_server_api_tracing_span_seconds_count{operation=\"PerWorkspacePVCStrategy#prepare\"}[1h])",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "increase(che_server_api_tracing_span_seconds_sum{operation=\"OpenShiftInternalRuntime#startMachines\"}[1h]) / increase(che_server_api_tracing_span_seconds_count{operation=\"OpenShiftInternalRuntime#startMachines\"}[1h])",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "increase(che_server_api_tracing_span_seconds_sum{operation=\"WaitMachinesStart\"}[1h]) / increase(che_server_api_tracing_span_seconds_count{operation=\"WaitMachinesStart\"}[1h])",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Plugin Brokering Execution Max",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 151 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "che_server_api_tracing_span_seconds_max{operation=\"PluginBrokerManager#getTooling\"}",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Plugin Brokering Execution Avg",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 151 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(che_server_api_tracing_span_seconds_sum{operation=\"PluginBrokerManager#getTooling\"}[1h]) / increase(che_server_api_tracing_span_seconds_count{operation=\"PluginBrokerManager#getTooling\"}[1h])",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "OpenShiftEnvironmentProvisioner#provision Max",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 158 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "che_server_api_tracing_span_seconds_max{operation=\"LogsVolumeMachineProvisioner#provision\"}",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "che_server_api_tracing_span_seconds_max{operation=\"ServersConverter#provision\"}",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "che_server_api_tracing_span_seconds_max{operation=\"EnvVarsConverter#provision\"}",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "che_server_api_tracing_span_seconds_max{operation=\"RestartPolicyRewriter#provision\"}",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "che_server_api_tracing_span_seconds_max{operation=\"RouteTlsProvisioner#provision\"}",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "che_server_api_tracing_span_seconds_max{operation=\"RamLimitRequestProvisioner#provision\"}",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "che_server_api_tracing_span_seconds_max{operation=\"PodTerminationGracePeriodProvisioner#provision\"}",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "che_server_api_tracing_span_seconds_max{operation=\"ImagePullSecretProvisioner#provision\"}",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "che_server_api_tracing_span_seconds_max{operation=\"ProxySettingsProvisioner#provision\"}",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "che_server_api_tracing_span_seconds_max{operation=\"ServiceAccountProvisioner#provision\"}",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "che_server_api_tracing_span_seconds_max{operation=\"VcsSshKeysProvisioner#provision\"}",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "OpenShiftEnvironmentProvisioner#provision avg",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 158 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(che_server_api_tracing_span_seconds_sum{operation=\"LogsVolumeMachineProvisioner#provision\"}[1h]) / increase(che_server_api_tracing_span_seconds_count{operation=\"LogsVolumeMachineProvisioner#provision\"}[1h])",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "increase(che_server_api_tracing_span_seconds_sum{operation=\"ServersConverter#provision\"}[1h]) / increase(che_server_api_tracing_span_seconds_count{operation=\"ServersConverter#provision\"}[1h])",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "increase(che_server_api_tracing_span_seconds_sum{operation=\"EnvVarsConverter#provision\"}[1h]) / increase(che_server_api_tracing_span_seconds_count{operation=\"EnvVarsConverter#provision\"}[1h])",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "increase(che_server_api_tracing_span_seconds_sum{operation=\"RestartPolicyRewriter#provision\"}[1h]) / increase(che_server_api_tracing_span_seconds_count{operation=\"RestartPolicyRewriter#provision\"}[1h])",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "increase(che_server_api_tracing_span_seconds_sum{operation=\"RouteTlsProvisioner#provision\"}[1h]) / increase(che_server_api_tracing_span_seconds_count{operation=\"RouteTlsProvisioner#provision\"}[1h])",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "increase(che_server_api_tracing_span_seconds_sum{operation=\"RamLimitRequestProvisioner#provision\"}[1h]) / increase(che_server_api_tracing_span_seconds_count{operation=\"RamLimitRequestProvisioner#provision\"}[1h])",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "increase(che_server_api_tracing_span_seconds_sum{operation=\"PodTerminationGracePeriodProvisioner#provision\"}[1h]) / increase(che_server_api_tracing_span_seconds_count{operation=\"PodTerminationGracePeriodProvisioner#provision\"}[1h])",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "increase(che_server_api_tracing_span_seconds_sum{operation=\"ImagePullSecretProvisioner#provision\"}[1h]) / increase(che_server_api_tracing_span_seconds_count{operation=\"ImagePullSecretProvisioner#provision\"}[1h])",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "increase(che_server_api_tracing_span_seconds_sum{operation=\"ProxySettingsProvisioner#provision\"}[1h]) / increase(che_server_api_tracing_span_seconds_count{operation=\"ProxySettingsProvisioner#provision\"}[1h])",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "increase(che_server_api_tracing_span_seconds_sum{operation=\"ServiceAccountProvisioner#provision\"}[1h]) / increase(che_server_api_tracing_span_seconds_count{operation=\"ServiceAccountProvisioner#provision\"}[1h])",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "increase(che_server_api_tracing_span_seconds_sum{operation=\"VcsSshKeysProvisioner#provision\"}[1h]) / increase(che_server_api_tracing_span_seconds_count{operation=\"VcsSshKeysProvisioner#provision\"}[1h])",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Plugin Brokering Execution Max",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 165 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "che_server_api_tracing_span_seconds_max{operation=\"OpenShiftEnvironmentProvisioner#provision\"}",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "che_server_api_tracing_span_seconds_max{operation=\"PrepareStorage\"}",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "che_server_api_tracing_span_seconds_max{operation=\"PerWorkspacePVCStrategy#prepare\"}",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "che_server_api_tracing_span_seconds_max{operation=\"DeployBroker\"}",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "che_server_api_tracing_span_seconds_max{operation=\"WaitBrokerResult\"}",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Plugin Brokering Execution Avg",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 165 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(che_server_api_tracing_span_seconds_sum{operation=\"OpenShiftEnvironmentProvisioner#provision\"}[1h]) / increase(che_server_api_tracing_span_seconds_count{operation=\"OpenShiftEnvironmentProvisioner#provision\"}[1h])",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "increase(che_server_api_tracing_span_seconds_sum{operation=\"PrepareStorage\"}[1h]) / increase(che_server_api_tracing_span_seconds_count{operation=\"PPrepareStorage\"}[1h])",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "increase(che_server_api_tracing_span_seconds_sum{operation=\"PerWorkspacePVCStrategy#prepare\"}[1h]) / increase(che_server_api_tracing_span_seconds_count{operation=\"PerWorkspacePVCStrategy#prepare\"}[1h])",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "increase(che_server_api_tracing_span_seconds_sum{operation=\"DeployBroker\"}[1h]) / increase(che_server_api_tracing_span_seconds_count{operation=\"DeployBroker\"}[1h])",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "increase(che_server_api_tracing_span_seconds_sum{operation=\"WaitBrokerResult\"}[1h]) / increase(che_server_api_tracing_span_seconds_count{operation=\"WaitBrokerResult\"}[1h])",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "WaitMachinesStart Max",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 172 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "che_server_api_tracing_span_seconds_max{operation=\"WaitRunningAsync\"}",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "che_server_api_tracing_span_seconds_max{operation=\"CheckServers\"}",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "WaitMachinesStart avg",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 172 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(che_server_api_tracing_span_seconds_sum{operation=\"WaitRunningAsync\"}[1h]) / increase(che_server_api_tracing_span_seconds_count{operation=\"WaitRunningAsync\"}[1h])",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "increase(che_server_api_tracing_span_seconds_sum{operation=\"CheckServers\"}[1h]) / increase(che_server_api_tracing_span_seconds_count{operation=\"CheckServers\"}[1h])",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "OpenShiftInternalRuntime#startMachines Max",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 179 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "che_server_api_tracing_span_seconds_max{operation=\"OpenShiftInternalRuntime#createSecrets\"}",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "che_server_api_tracing_span_seconds_max{operation=\"OpenShiftInternalRuntime#createConfigMaps\"}",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "che_server_api_tracing_span_seconds_max{operation=\"OpenShiftInternalRuntime#createServices\"}",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "che_server_api_tracing_span_seconds_max{operation=\"OpenShiftInternalRuntime#createRoutes\"}",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "che_server_api_tracing_span_seconds_max{operation=\"OpenShiftInternalRuntime#listenEvents\"}",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "che_server_api_tracing_span_seconds_max{operation=\"OpenShiftInternalRuntime#doStartMachine\"}",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "OpenShiftInternalRuntime#startMachines avg",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 179 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(che_server_api_tracing_span_seconds_sum{operation=\"OpenShiftInternalRuntime#createSecrets\"}[1h]) / increase(che_server_api_tracing_span_seconds_count{operation=\"OpenShiftInternalRuntime#createSecrets\"}[1h])",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "increase(che_server_api_tracing_span_seconds_sum{operation=\"OpenShiftInternalRuntime#createConfigMaps\"}[1h]) / increase(che_server_api_tracing_span_seconds_count{operation=\"OpenShiftInternalRuntime#createConfigMaps\"}[1h])",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "increase(che_server_api_tracing_span_seconds_sum{operation=\"OpenShiftInternalRuntime#createServices\"}[1h]) / increase(che_server_api_tracing_span_seconds_count{operation=\"OpenShiftInternalRuntime#createServices\"}[1h])",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "increase(che_server_api_tracing_span_seconds_sum{operation=\"OpenShiftInternalRuntime#createRoutes\"}[1h]) / increase(che_server_api_tracing_span_seconds_count{operation=\"OpenShiftInternalRuntime#createRoutes\"}[1h])",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "increase(che_server_api_tracing_span_seconds_sum{operation=\"OpenShiftInternalRuntime#listenEvents\"}[1h]) / increase(che_server_api_tracing_span_seconds_count{operation=\"OpenShiftInternalRuntime#listenEvents\"}[1h])",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "increase(che_server_api_tracing_span_seconds_sum{operation=\"OpenShiftInternalRuntime#doStartMachine\"}[1h]) / increase(che_server_api_tracing_span_seconds_count{operation=\"OpenShiftInternalRuntime#doStartMachine\"}[1h])",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Workspaces detailed",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 186 },
   "collapsed": true,
   "panels": [
    {
     "title": "Failed start",
     "type": "heatmap",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 81 },
     "targets": [
      {
       "expr": "increase(che_workspace_start_time_seconds_bucket{result=\"fail\"}[1h])",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Messages sent to runtime log",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 205 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "runtime_log_messages_message_total",
       "legendFormat": "Messages"
      }
     ]
    },
    {
     "title": "Bytes sent to runtime log",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 205 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "runtime_log_bytes_byte_total", "legendFormat": "Bytes" }
     ]
    },
    {
     "title": "Current Log Watchers",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 199 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "log_watchers", "legendFormat": "Log Watchers" }
     ]
    },
    {
     "title": "Success start",
     "type": "heatmap",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 81 },
     "targets": [
      {
       "expr": "increase(che_workspace_start_time_seconds_bucket{result=\"success\"} [1h])",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  }
 ]
}