{
 "title": "Quay SLO",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "rate",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "push_target_slo", "query": "99.5" },
   { "name": "pull_target_slo", "query": "99.9" },
   { "name": "catchpoint_datasource", "query": "prometheus" },
   { "name": "cloudwatch_datasource", "query": "cloudwatch" }
  ]
 },
 "panels": [
  {
   "title": "About",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "# Quay SLOs\n\nDescription goes here\n"
   }
  },
  { "title": "Push/Pull", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Push/Pull Service Level Compliance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (\n    sum(increase(catchpoint_check_failures_total{probe=\"quayio-pull-monitor-v2\"}[$rate]))\n    /\n    sum(increase(catchpoint_checks_total{probe=\"quayio-pull-monitor-v2\"}[$rate]))\n)\n",
     "legendFormat": "pull availability %"
    },
    {
     "expr": "1 - (\n    sum(increase(catchpoint_check_failures_total{probe=\"quayio-push-monitor-v2\"}[$rate]))\n    /\n    sum(increase(catchpoint_checks_total{probe=\"quayio-push-monitor-v2\"}[$rate]))\n)",
     "legendFormat": "push availability %"
    }
   ]
  },
  {
   "title": "Push Error Budget Burn Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(catchpoint_check_failures_total{probe=\"quayio-push-monitor-v2\"}[$rate])",
     "legendFormat": "budget burn rate"
    },
    {
     "expr": "(100 - $push_target_slo) * increase(catchpoint_checks_total{probe=\"quayio-push-monitor-v2\"}[$rate])",
     "legendFormat": "max budget"
    }
   ]
  },
  {
   "title": "Pull Error Budget Burn Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(catchpoint_check_failures_total{probe=\"quayio-pull-monitor-v2\"}[$rate]))",
     "legendFormat": "budget burn rate"
    },
    {
     "expr": "(100 - $pull_target_slo) * sum(increase(catchpoint_checks_total{probe=\"quayio-pull-monitor-v2\"}[$rate]))",
     "legendFormat": "max budget"
    }
   ]
  },
  {
   "title": "Pull Operations",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "$pull_target_slo", "legendFormat": "pull target" },
    {
     "expr": "100 - (\n    sum(increase(catchpoint_check_failures_total{probe=\"quayio-pull-monitor-v2\"}[$rate]))\n    /\n    sum(increase(catchpoint_checks_total{probe=\"quayio-pull-monitor-v2\"}[$rate]))\n)",
     "legendFormat": "pull availability"
    },
    {
     "expr": "100 * (\n  (100 - $pull_target_slo) - 100 * (\n    (\n      sum(increase(catchpoint_check_failures_total{probe=\"quayio-pull-monitor-v2\"}[$rate])) \n      / sum(increase(catchpoint_checks_total{probe=\"quayio-pull-monitor-v2\"}[$rate]))\n    )\n  )\n)\n/\n(100 - $pull_target_slo)",
     "legendFormat": "error budget left"
    }
   ]
  },
  {
   "title": "Push Operations",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "$push_target_slo", "legendFormat": "push target" },
    {
     "expr": "100 - (\n    sum(increase(catchpoint_check_failures_total{probe=\"quayio-push-monitor-v2\"}[$rate]))\n    /\n    sum(increase(catchpoint_checks_total{probe=\"quayio-push-monitor-v2\"}[$rate]))\n)",
     "legendFormat": "push availability"
    },
    {
     "expr": "100 * (\n  (100 - $push_target_slo) - 100 * (\n    (\n      sum(increase(catchpoint_check_failures_total{probe=\"quayio-push-monitor-v2\"}[$rate])) \n      / sum(increase(catchpoint_checks_total{probe=\"quayio-push-monitor-v2\"}[$rate]))\n    )\n  )\n)\n/\n(100 - $push_target_slo)",
     "legendFormat": "error budget left"
    }
   ]
  },
  { "title": "v1 API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "API v1 Availability",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"api.user\",status=\"200\",method=\"GET\"}[$rate]))\n/\nsum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"api.user\",method=\"GET\"}[$rate]))",
     "legendFormat": "GET api.user"
    },
    {
     "expr": "sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"api.repository\",status=\"200\",method=\"GET\"}[$rate]))\n/\nsum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"api.repository\",method=\"GET\"}[$rate]))",
     "legendFormat": "GET api.repository"
    },
    {
     "expr": "sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"api.listrepositorytags\",status=\"200\",method=\"GET\"}[$rate]))\n/\nsum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"api.listrepositorytags\",method=\"GET\"}[$rate]))",
     "legendFormat": "GET api.listrepositorytags"
    },
    {
     "expr": "sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"api.repositorymanifestsecurity\",status=\"200\",method=\"GET\"}[$rate]))\n/\nsum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"api.repositorymanifestsecurity\",method=\"GET\"}[$rate]))",
     "legendFormat": "GET api.repositorymanifestsecurity"
    }
   ]
  },
  {
   "title": "API v1 users endpoint",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "0.995", "legendFormat": "target availability" },
    {
     "expr": "sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"api.user\",status=\"200\",method=\"GET\"}[$rate]))\n/\nsum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"api.user\",method=\"GET\"}[$rate]))",
     "legendFormat": "GET api.user"
    },
    {
     "expr": "(1 - 0.995) - (1 - (\n  sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"api.user\",status=\"200\",method=\"GET\"}[$rate]))\n  /\n  sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"api.user\",method=\"GET\"}[$rate]))\n))",
     "legendFormat": "error budget left"
    }
   ]
  },
  {
   "title": "API v1 repository endpoint",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "0.995", "legendFormat": "target availability" },
    {
     "expr": "sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"api.repository\",status=\"200\",method=\"GET\"}[$rate]))\n/\nsum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"api.repository\",method=\"GET\"}[$rate]))",
     "legendFormat": "GET api.repository"
    },
    {
     "expr": "(1 - 0.995) - (1 - (\n  sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"api.repository\",status=\"200\",method=\"GET\"}[$rate]))\n  /\n  sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"api.repository\",method=\"GET\"}[$rate]))\n))",
     "legendFormat": "error budget left"
    }
   ]
  },
  {
   "title": "API v1 tags endpoint",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "0.995", "legendFormat": "target availability" },
    {
     "expr": "sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"api.listrepositorytags\",status=\"200\",method=\"GET\"}[$rate]))\n/\nsum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"api.listrepositorytags\",method=\"GET\"}[$rate]))",
     "legendFormat": "GET api.listrepositorytags"
    },
    {
     "expr": "(1 - 0.995) - (1 - (\n  sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"api.listrepositorytags\",status=\"200\",method=\"GET\"}[$rate]))\n  /\n  sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"api.listrepositorytags\",method=\"GET\"}[$rate]))\n))",
     "legendFormat": "error budget left"
    }
   ]
  },
  {
   "title": "API v1 security endpoint",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "0.90", "legendFormat": "target availability" },
    {
     "expr": "sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"api.repositorymanifestsecurity\",status=\"200\",method=\"GET\"}[$rate]))\n/\nsum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"api.repositorymanifestsecurity\",method=\"GET\"}[$rate]))",
     "legendFormat": "GET api.repositorymanifestsecurity"
    },
    {
     "expr": "(1 - 0.90) - (1 - (\n  sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"api.repositorymanifestsecurity\",status=\"200\",method=\"GET\"}[$rate]))\n  /\n  sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"api.repositorymanifestsecurity\",method=\"GET\"}[$rate]))\n))",
     "legendFormat": "error budget left"
    }
   ]
  },
  {
   "title": "HTTP response codes",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dimensions": {
      "LoadBalancer": "app/quayio-production-alb01/dd2a8a128b2029c6"
     },
     "label": "HTTP 2XX",
     "metricName": "HTTPCode_Target_2XX_Count",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "LoadBalancer": "app/quayio-production-alb01/dd2a8a128b2029c6"
     },
     "label": "HTTP 3XX",
     "metricName": "HTTPCode_Target_3XX_Count",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "LoadBalancer": "app/quayio-production-alb01/dd2a8a128b2029c6"
     },
     "label": "HTTP 4XX",
     "metricName": "HTTPCode_Target_4XX_Count",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "LoadBalancer": "app/quayio-production-alb01/dd2a8a128b2029c6"
     },
     "label": "HTTP 5XX",
     "metricName": "HTTPCode_Target_5XX_Count",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "HTTP response codes",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": {
      "LoadBalancer": "app/quayio-production-alb01/dd2a8a128b2029c6"
     },
     "label": "HTTP 2XX",
     "metricName": "HTTPCode_Target_2XX_Count",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "LoadBalancer": "app/quayio-production-alb01/dd2a8a128b2029c6"
     },
     "label": "HTTP 3XX",
     "metricName": "HTTPCode_Target_3XX_Count",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "LoadBalancer": "app/quayio-production-alb01/dd2a8a128b2029c6"
     },
     "label": "HTTP 4XX",
     "metricName": "HTTPCode_Target_4XX_Count",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "LoadBalancer": "app/quayio-production-alb01/dd2a8a128b2029c6"
     },
     "label": "HTTP 5XX",
     "metricName": "HTTPCode_Target_5XX_Count",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  { "title": "Builds", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Total Build Time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n    sum(\n        increase(quay_build_queue_duration_seconds_sum[$rate])\n    )\n    /\n    sum(\n        increase(quay_build_queue_duration_seconds_count[$rate])\n    )\n) + (\n    sum(\n        increase(quay_build_duration_seconds_sum[$rate])\n    )\n    /\n    sum(\n        increase(quay_build_duration_seconds_count[$rate])\n    )\n)"
    }
   ]
  },
  {
   "title": "Average Time in Build Queue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(quay_build_queue_duration_seconds_sum[$rate]))\n/\nsum(increase(quay_build_queue_duration_seconds_count[$rate]))"
    }
   ]
  },
  {
   "title": "Build Queue Duration",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quay_build_queue_duration_seconds_bucket",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}