{
 "title": "Kas Fleet Manager Metrics",
 "tags": [ "kas-fleet-manager" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "Filters" },
   { "name": "consoleurl", "label": "Console URL", "query": "label_values(console_url, url)" }
  ]
 },
 "panels": [
  {
   "title": "Kafka Requests Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Accepted",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum without (pod, instance) (kas_fleet_manager_kafka_requests_status_count{status=\"accepted\"})"
      }
     ]
    },
    {
     "title": "Preparing",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum without (pod, instance) (kas_fleet_manager_kafka_requests_status_count{status=\"preparing\"})"
      }
     ]
    },
    {
     "title": "Provisioning",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum without (pod,instance)(kas_fleet_manager_kafka_requests_status_count{status=\"provisioning\"})"
      }
     ]
    },
    {
     "title": "Ready",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum without (pod, instance) (kas_fleet_manager_kafka_requests_status_count{status=\"ready\"})"
      }
     ]
    },
    {
     "title": "Failed",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum without (pod, instance) (kas_fleet_manager_kafka_requests_status_count{status=\"failed\"})"
      }
     ]
    },
    {
     "title": "Deprovision",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum without (pod, instance) (kas_fleet_manager_kafka_requests_status_count{status=\"deprovision\"})"
      }
     ]
    },
    {
     "title": "Kafka Requests Status Count",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum without (pod, instance) (kas_fleet_manager_kafka_requests_status_count)",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Kafka Requests Status Since Creation",
     "type": "table",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (cluster_id,id,status)(kas_fleet_manager_kafka_requests_status_since_created_in_seconds)"
      }
     ]
    }
   ]
  },
  {
   "title": "Worker Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Leader Pods",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "sum by (pod, worker_type, namespace) (kas_fleet_manager_leader_worker) > 0"
      }
     ]
    },
    {
     "title": "Reconcile Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum without (pod, instance) (kas_fleet_manager_reconciler_duration_in_seconds)",
       "legendFormat": "{{worker_type}}"
      }
     ]
    },
    {
     "title": "Reconciler Success Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum without (pod, instance, endpoint, job, namespace, service, worker_type) (kas_fleet_manager_reconciler_success_count{worker_type=\"general_kafka_worker\"})/(( (sum without (pod, instance, endpoint, job, namespace, service, worker_type) (kas_fleet_manager_reconciler_failure_count{worker_type=\"general_kafka_worker\"})) or on() vector(0)) + sum without (pod, instance, endpoint, job, namespace, service, worker_type) (kas_fleet_manager_reconciler_success_count{worker_type=\"general_kafka_worker\"}))",
       "legendFormat": "General Kafka Worker"
      },
      {
       "expr": "sum without (pod, instance, endpoint, job, namespace, service, worker_type) (kas_fleet_manager_reconciler_success_count{worker_type=\"accepted_kafka\"})/(( (sum without (pod, instance, endpoint, job, namespace, service, worker_type) (kas_fleet_manager_reconciler_failure_count{worker_type=\"accepted_kafka\"})) or on() vector(0)) + sum without (pod, instance, endpoint, job, namespace, service, worker_type) (kas_fleet_manager_reconciler_success_count{worker_type=\"accepted_kafka\"}))",
       "legendFormat": "Accepted Kafka"
      },
      {
       "expr": "sum without (pod, instance, endpoint, job, namespace, service, worker_type) (kas_fleet_manager_reconciler_success_count{worker_type=\"preparing_kafka\"})/(( (sum without (pod, instance, endpoint, job, namespace, service, worker_type) (kas_fleet_manager_reconciler_failure_count{worker_type=\"preparing_kafka\"})) or on() vector(0)) + sum without (pod, instance, endpoint, job, namespace, service, worker_type) (kas_fleet_manager_reconciler_success_count{worker_type=\"preparing_kafka\"}))",
       "legendFormat": "Preparing kafka"
      },
      {
       "expr": "sum without (pod, instance, endpoint, job, namespace, service, worker_type) (kas_fleet_manager_reconciler_success_count{worker_type=\"provisioning_kafka\"})/(( (sum without (pod, instance, endpoint, job, namespace, service, worker_type) (kas_fleet_manager_reconciler_failure_count{worker_type=\"provisioning_kafka\"})) or on() vector(0)) + sum without (pod, instance, endpoint, job, namespace, service, worker_type) (kas_fleet_manager_reconciler_success_count{worker_type=\"provisioning_kafka\"}))",
       "legendFormat": "Provisioning Kafka"
      },
      {
       "expr": "sum without (pod, instance, endpoint, job, namespace, service, worker_type) (kas_fleet_manager_reconciler_success_count{worker_type=\"deleting_kafka\"})/(( (sum without (pod, instance, endpoint, job, namespace, service, worker_type) (kas_fleet_manager_reconciler_failure_count{worker_type=\"deleting_kafka\"})) or on() vector(0)) + sum without (pod, instance, endpoint, job, namespace, service, worker_type) (kas_fleet_manager_reconciler_success_count{worker_type=\"deleting_kafka\"}))",
       "legendFormat": "Deleting Kafka"
      },
      {
       "expr": "sum without (pod, instance, endpoint, job, namespace, service, worker_type) (kas_fleet_manager_reconciler_success_count{worker_type=\"ready_kafka\"})/(( (sum without (pod, instance, endpoint, job, namespace, service, worker_type) (kas_fleet_manager_reconciler_failure_count{worker_type=\"ready_kafka\"})) or on() vector(0)) + sum without (pod, instance, endpoint, job, namespace, service, worker_type) (kas_fleet_manager_reconciler_success_count{worker_type=\"ready_kafka\"}))",
       "legendFormat": "Ready Kafka"
      },
      {
       "expr": "sum without (pod, instance, endpoint, job, namespace, service, worker_type) (kas_fleet_manager_reconciler_success_count{worker_type=\"cluster\"})/(( (sum without (pod, instance, endpoint, job, namespace, service, worker_type) (kas_fleet_manager_reconciler_failure_count{worker_type=\"cluster\"})) or on() vector(0)) + sum without (pod, instance, endpoint, job, namespace, service, worker_type) (kas_fleet_manager_reconciler_success_count{worker_type=\"cluster\"}))",
       "legendFormat": "Cluster"
      },
      {
       "expr": "sum without (pod, instance, endpoint, job, namespace, service, worker_type) (kas_fleet_manager_reconciler_success_count{worker_type=\"connector\"})/(( (sum without (pod, instance, endpoint, job, namespace, service, worker_type) (kas_fleet_manager_reconciler_failure_count{worker_type=\"connector\"})) or on() vector(0)) + sum without (pod, instance, endpoint, job, namespace, service, worker_type) (kas_fleet_manager_reconciler_success_count{worker_type=\"connector\"}))",
       "legendFormat": "Connector"
      }
     ]
    },
    {
     "title": "Error Rate Per Minute",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum without (pod, instance) (rate(kas_fleet_manager_reconciler_errors_count[1m]))",
       "legendFormat": "{{worker_type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Data Plane Cluster Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Provisioning",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum without (pod,instance)(kas_fleet_manager_cluster_status_count{status=\"cluster_provisioning\"})\n"
      }
     ]
    },
    {
     "title": "Provisioned",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum without (pod,instance)(kas_fleet_manager_cluster_status_count{status=\"cluster_provisioned\"})\n"
      }
     ]
    },
    {
     "title": "Wait for Operator",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum without (pod,instance)(kas_fleet_manager_cluster_status_count{status=\"waiting_for_kas_fleetshard_operator\"})\n"
      }
     ]
    },
    {
     "title": "Ready",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum without (pod,instance)(kas_fleet_manager_cluster_status_count{status=\"ready\"})\n"
      }
     ]
    },
    {
     "title": "Failed",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum without (pod,instance)(kas_fleet_manager_cluster_status_count{status=\"failed\"})\n"
      }
     ]
    },
    {
     "title": "Deprovisioning",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum without (pod,instance)(kas_fleet_manager_cluster_status_count{status=\"deprovisioning\"})\n"
      }
     ]
    },
    {
     "title": "Data Plane Cluster Status Count",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum without (pod, instance) (kas_fleet_manager_cluster_status_count)",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Data Plane Cluster Status Since Creation",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (cluster_id,id,status)(kas_fleet_manager_cluster_status_since_created_in_seconds)"
      }
     ]
    },
    {
     "title": "Number of Kafkas Per Cluster",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum without (pod, instance) (kas_fleet_manager_kafka_per_cluster_count{cluster_id != \"\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "API Overall",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Availability (selected time) ",
     "type": "stat",
     "description": "The percentage of time that the API is available (not returning 500 Internal Service Errors).",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(increase(api_inbound_request_count{code!~\"5..|0\",service=\"kas-fleet-manager-metrics\"}[$__range]))\n/\nsum(increase(api_inbound_request_count{service=\"kas-fleet-manager-metrics\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "graph",
     "description": "Number of requests per second based on response code",
     "gridPos": { "h": 8, "w": 7, "x": 3, "y": 4 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by (code) (rate(api_inbound_request_count{service=\"kas-fleet-manager-metrics\"}[5m]))",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "description": "The error percentage",
     "gridPos": { "h": 8, "w": 7, "x": 10, "y": 4 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(api_inbound_request_count{service=\"kas-fleet-manager-metrics\", code!~\"2..\"}[5m]))/sum(rate(api_inbound_request_count{service=\"kas-fleet-manager-metrics\"}[5m]))",
       "legendFormat": "non-2xx"
      },
      {
       "expr": "sum(rate(api_inbound_request_count{service=\"kas-fleet-manager-metrics\", code=~\"5..|0\"}[5m]))/sum(rate(api_inbound_request_count{service=\"kas-fleet-manager-metrics\"}[5m]))",
       "legendFormat": "5xx and timeout"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "description": "The request duration within which the API have served 99%, 95%, 50% of requests",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 4 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(api_inbound_request_duration_bucket{service=\"kas-fleet-manager-metrics\", code!~\"5..|0\"}[5m])))",
       "legendFormat": "99th"
      },
      {
       "expr": "histogram_quantile(0.90, sum by (le) (rate(api_inbound_request_duration_bucket{service=\"kas-fleet-manager-metrics\", code!~\"5..|0\"}[5m])))",
       "legendFormat": "90th"
      },
      {
       "expr": "histogram_quantile(0.5, sum by (le) (rate(api_inbound_request_duration_bucket{service=\"kas-fleet-manager-metrics\", code!~\"5..|0\"}[5m])))",
       "legendFormat": "50th"
      }
     ]
    },
    {
     "title": "Latency (<1s)",
     "type": "stat",
     "description": "The percentage of time that the API responds within 1 second.",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(increase(api_inbound_request_duration_bucket{code!~\"5..|0\",service=\"kas-fleet-manager-metrics\",le=\"1\"}[$__range]))\n/\nsum(increase(api_inbound_request_duration_count{service=\"kas-fleet-manager-metrics\",code!~\"5..|0\"}[$__range]))"
      }
     ]
    }
   ]
  },
  {
   "title": "/kafkas",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Availability (selected time) ",
     "type": "stat",
     "description": "The percentage of time that the API is available (not returning 500 Internal Service Errors).",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(increase(api_inbound_request_count{path=~\"/api/kafkas_mgmt/v1/kafkas\",code!~\"5..|0\",service=\"kas-fleet-manager-metrics\"}[$__range]))\n/\nsum(increase(api_inbound_request_count{path=~\"/api/kafkas_mgmt/v1/kafkas\",service=\"kas-fleet-manager-metrics\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "graph",
     "description": "Number of requests per second based on response code",
     "gridPos": { "h": 8, "w": 7, "x": 3, "y": 5 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by (code) (rate(api_inbound_request_count{service=\"kas-fleet-manager-metrics\",path=~\"/api/kafkas_mgmt/v1/kafkas\"}[5m]))",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "description": "The error percentage",
     "gridPos": { "h": 8, "w": 7, "x": 10, "y": 5 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(api_inbound_request_count{path=~\"/api/kafkas_mgmt/v1/kafkas\", service=\"kas-fleet-manager-metrics\", code!~\"2..\"}[5m]))/sum(rate(api_inbound_request_count{path=~\"/api/kafkas_mgmt/v1/kafkas\", service=\"kas-fleet-manager-metrics\"}[5m]))",
       "legendFormat": "non-2xx"
      },
      {
       "expr": "sum(rate(api_inbound_request_count{path=~\"/api/kafkas_mgmt/v1/kafkas\", service=\"kas-fleet-manager-metrics\", code=~\"5..|0\"}[5m]))/sum(rate(api_inbound_request_count{path=~\"/api/kafkas_mgmt/v1/kafkas\", service=\"kas-fleet-manager-metrics\"}[5m]))",
       "legendFormat": "5xx and timeout"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "description": "The request duration within which the API have served 99%, 95%, 50% of requests",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 5 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(api_inbound_request_duration_bucket{path=~\"/api/kafkas_mgmt/v1/kafkas\", service=\"kas-fleet-manager-metrics\", code!~\"5..|0\"}[5m])))",
       "legendFormat": "99th"
      },
      {
       "expr": "histogram_quantile(0.90, sum by (le) (rate(api_inbound_request_duration_bucket{path=~\"/api/kafkas_mgmt/v1/kafkas\", service=\"kas-fleet-manager-metrics\", code!~\"5..|0\"}[5m])))",
       "legendFormat": "90th"
      },
      {
       "expr": "histogram_quantile(0.5, sum by (le) (rate(api_inbound_request_duration_bucket{path=~\"/api/kafkas_mgmt/v1/kafkas\", service=\"kas-fleet-manager-metrics\", code!~\"5..|0\"}[5m])))",
       "legendFormat": "50th"
      }
     ]
    },
    {
     "title": "Latency (<1s)",
     "type": "stat",
     "description": "The percentage of time that the API responds within 1 second.",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(increase(api_inbound_request_duration_bucket{path=~\"/api/kafkas_mgmt/v1/kafkas\",code!~\"5..|0\",service=\"kas-fleet-manager-metrics\",le=\"1\"}[$__range]))\n/\nsum(increase(api_inbound_request_duration_count{path=~\"/api/kafkas_mgmt/v1/kafkas\",service=\"kas-fleet-manager-metrics\",code!~\"5..|0\"}[$__range]))"
      }
     ]
    }
   ]
  },
  {
   "title": "/kafkas/{id}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Availability (selected time) ",
     "type": "stat",
     "description": "The percentage of time that the API is available (not returning 500 Internal Service Errors).",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(increase(api_inbound_request_count{path=\"/api/kafkas_mgmt/v1/kafkas/-\",code!~\"5..|0\",service=\"kas-fleet-manager-metrics\"}[$__range]))\n/\nsum(increase(api_inbound_request_count{path=\"/api/kafkas_mgmt/v1/kafkas/-\",service=\"kas-fleet-manager-metrics\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "graph",
     "description": "Number of requests per second based on response code",
     "gridPos": { "h": 8, "w": 7, "x": 3, "y": 6 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by (code) (rate(api_inbound_request_count{service=\"kas-fleet-manager-metrics\",path=\"/api/kafkas_mgmt/v1/kafkas/-\"}[5m]))",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "description": "The error percentage",
     "gridPos": { "h": 8, "w": 7, "x": 10, "y": 6 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(api_inbound_request_count{path=\"/api/kafkas_mgmt/v1/kafkas/-\", service=\"kas-fleet-manager-metrics\", code!~\"2..\"}[5m]))/sum(rate(api_inbound_request_count{path=\"/api/kafkas_mgmt/v1/kafkas/-\", service=\"kas-fleet-manager-metrics\"}[5m]))",
       "legendFormat": "non-2xx"
      },
      {
       "expr": "sum(rate(api_inbound_request_count{path=\"/api/kafkas_mgmt/v1/kafkas/-\", service=\"kas-fleet-manager-metrics\", code=~\"5..|0\"}[5m]))/sum(rate(api_inbound_request_count{path=\"/api/kafkas_mgmt/v1/kafkas/-\", service=\"kas-fleet-manager-metrics\"}[5m]))",
       "legendFormat": "5xx and timeout"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "description": "The request duration within which the API have served 99%, 95%, 50% of requests",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 6 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(api_inbound_request_duration_bucket{path=\"/api/kafkas_mgmt/v1/kafkas/-\", service=\"kas-fleet-manager-metrics\", code!~\"5..|0\"}[5m])))",
       "legendFormat": "99th"
      },
      {
       "expr": "histogram_quantile(0.90, sum by (le) (rate(api_inbound_request_duration_bucket{path=\"/api/kafkas_mgmt/v1/kafkas/-\", service=\"kas-fleet-manager-metrics\", code!~\"5..|0\"}[5m])))",
       "legendFormat": "90th"
      },
      {
       "expr": "histogram_quantile(0.5, sum by (le) (rate(api_inbound_request_duration_bucket{path=\"/api/kafkas_mgmt/v1/kafkas/-\", service=\"kas-fleet-manager-metrics\", code!~\"5..|0\"}[5m])))",
       "legendFormat": "50th"
      }
     ]
    },
    {
     "title": "Latency (<1s)",
     "type": "stat",
     "description": "The percentage of time that the API responds within 1 second.",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(increase(api_inbound_request_duration_bucket{path=\"/api/kafkas_mgmt/v1/kafkas/-\",code!~\"5..|0\",service=\"kas-fleet-manager-metrics\",le=\"1\"}[$__range]))\n/\nsum(increase(api_inbound_request_duration_count{path=\"/api/kafkas_mgmt/v1/kafkas/-\",service=\"kas-fleet-manager-metrics\",code!~\"5..|0\"}[$__range]))"
      }
     ]
    }
   ]
  },
  {
   "title": "/kafkas/{id}/metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Availability (selected time) ",
     "type": "stat",
     "description": "The percentage of time that the API is available (not returning 500 Internal Service Errors).",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(increase(api_inbound_request_count{path=~\"/api/kafkas_mgmt/v1/kafkas/-/metrics/(.*)\",code!~\"5..|0\",service=\"kas-fleet-manager-metrics\"}[$__range]))\n/\nsum(increase(api_inbound_request_count{path=~\"/api/kafkas_mgmt/v1/kafkas/-/metrics/(.*)\",service=\"kas-fleet-manager-metrics\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "graph",
     "description": "Number of requests per second based on response code",
     "gridPos": { "h": 8, "w": 7, "x": 3, "y": 7 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by (code) (rate(api_inbound_request_count{service=\"kas-fleet-manager-metrics\",path=~\"/api/kafkas_mgmt/v1/kafkas/-/metrics/(.*)\"}[5m]))",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "description": "The error percentage",
     "gridPos": { "h": 8, "w": 7, "x": 10, "y": 7 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(api_inbound_request_count{path=~\"/api/kafkas_mgmt/v1/kafkas/-/metrics/(.*)\", service=\"kas-fleet-manager-metrics\", code!~\"2..\"}[5m]))/sum(rate(api_inbound_request_count{path=~\"/api/kafkas_mgmt/v1/kafkas/-/metrics/(.*)\", service=\"kas-fleet-manager-metrics\"}[5m]))",
       "legendFormat": "non-2xx"
      },
      {
       "expr": "sum(rate(api_inbound_request_count{path=~\"/api/kafkas_mgmt/v1/kafkas/-/metrics/(.*)\", service=\"kas-fleet-manager-metrics\", code=~\"5..|0\"}[5m]))/sum(rate(api_inbound_request_count{path=~\"/api/kafkas_mgmt/v1/kafkas/-/metrics/(.*)\", service=\"kas-fleet-manager-metrics\"}[5m]))",
       "legendFormat": "5xx and timeout"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "description": "The request duration within which the API have served 99%, 95%, 50% of requests",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 7 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(api_inbound_request_duration_bucket{path=~\"/api/kafkas_mgmt/v1/kafkas/-/metrics/(.*)\", service=\"kas-fleet-manager-metrics\", code!~\"5..|0\"}[5m])))",
       "legendFormat": "99th"
      },
      {
       "expr": "histogram_quantile(0.90, sum by (le) (rate(api_inbound_request_duration_bucket{path=~\"/api/kafkas_mgmt/v1/kafkas/-/metrics/(.*)\", service=\"kas-fleet-manager-metrics\", code!~\"5..|0\"}[5m])))",
       "legendFormat": "90th"
      },
      {
       "expr": "histogram_quantile(0.5, sum by (le) (rate(api_inbound_request_duration_bucket{path=~\"/api/kafkas_mgmt/v1/kafkas/-/metrics/(.*)\", service=\"kas-fleet-manager-metrics\", code!~\"5..|0\"}[5m])))",
       "legendFormat": "50th"
      }
     ]
    },
    {
     "title": "Latency (<1s)",
     "type": "stat",
     "description": "The percentage of time that the API responds within 1 second.",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(increase(api_inbound_request_duration_bucket{path=~\"/api/kafkas_mgmt/v1/kafkas/-/metrics/(.*)\",code!~\"5..|0\",service=\"kas-fleet-manager-metrics\",le=\"1\"}[$__range]))\n/\nsum(increase(api_inbound_request_duration_count{path=~\"/api/kafkas_mgmt/v1/kafkas/-/metrics/(.*)\",service=\"kas-fleet-manager-metrics\",code!~\"5..|0\"}[$__range]))"
      }
     ]
    }
   ]
  },
  {
   "title": "/kafkas/{id}/metrics/federate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Availability (selected time) ",
     "type": "stat",
     "description": "The percentage of time that the API is available (not returning 500 Internal Service Errors).",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(increase(api_inbound_request_count{path=~\"/api/kafkas_mgmt/v1/kafkas/-/metrics/federate\",code!~\"5..|0\",service=\"kas-fleet-manager-metrics\"}[$__range]))\n/\nsum(increase(api_inbound_request_count{path=~\"/api/kafkas_mgmt/v1/kafkas/-/metrics/federate\",service=\"kas-fleet-manager-metrics\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "graph",
     "description": "Number of requests per second based on response code",
     "gridPos": { "h": 8, "w": 7, "x": 3, "y": 8 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by (code) (rate(api_inbound_request_count{service=\"kas-fleet-manager-metrics\",path=~\"/api/kafkas_mgmt/v1/kafkas/-/metrics/federate\"}[5m]))",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "description": "The error percentage",
     "gridPos": { "h": 8, "w": 7, "x": 10, "y": 8 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(api_inbound_request_count{path=~\"/api/kafkas_mgmt/v1/kafkas/-/metrics/federate\", service=\"kas-fleet-manager-metrics\", code!~\"2..\"}[5m]))/sum(rate(api_inbound_request_count{path=~\"/api/kafkas_mgmt/v1/kafkas/-/metrics/federate\", service=\"kas-fleet-manager-metrics\"}[5m]))",
       "legendFormat": "non-2xx"
      },
      {
       "expr": "sum(rate(api_inbound_request_count{path=~\"/api/kafkas_mgmt/v1/kafkas/-/metrics/federate\", service=\"kas-fleet-manager-metrics\", code=~\"5..|0\"}[5m]))/sum(rate(api_inbound_request_count{path=~\"/api/kafkas_mgmt/v1/kafkas/-/metrics/federate\", service=\"kas-fleet-manager-metrics\"}[5m]))",
       "legendFormat": "5xx and timeout"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "description": "The request duration within which the API have served 99%, 95%, 50% of requests",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 8 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(api_inbound_request_duration_bucket{path=~\"/api/kafkas_mgmt/v1/kafkas/-/metrics/federate\", service=\"kas-fleet-manager-metrics\", code!~\"5..|0\"}[5m])))",
       "legendFormat": "99th"
      },
      {
       "expr": "histogram_quantile(0.90, sum by (le) (rate(api_inbound_request_duration_bucket{path=~\"/api/kafkas_mgmt/v1/kafkas/-/metrics/federate\", service=\"kas-fleet-manager-metrics\", code!~\"5..|0\"}[5m])))",
       "legendFormat": "90th"
      },
      {
       "expr": "histogram_quantile(0.5, sum by (le) (rate(api_inbound_request_duration_bucket{path=~\"/api/kafkas_mgmt/v1/kafkas/-/metrics/federate\", service=\"kas-fleet-manager-metrics\", code!~\"5..|0\"}[5m])))",
       "legendFormat": "50th"
      }
     ]
    },
    {
     "title": "Latency (<1s)",
     "type": "stat",
     "description": "The percentage of time that the API responds within 1 second.",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(increase(api_inbound_request_duration_bucket{path=~\"/api/kafkas_mgmt/v1/kafkas/-/metrics/federate\",code!~\"5..|0\",service=\"kas-fleet-manager-metrics\",le=\"1\"}[$__range]))\n/\nsum(increase(api_inbound_request_duration_count{path=~\"/api/kafkas_mgmt/v1/kafkas/-/metrics/federate\",service=\"kas-fleet-manager-metrics\",code!~\"5..|0\"}[$__range]))"
      }
     ]
    }
   ]
  },
  {
   "title": "/service_accounts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Availability (selected time) ",
     "type": "stat",
     "description": "The percentage of time that the API is available (not returning 500 Internal Service Errors).",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(increase(api_inbound_request_count{path=\"/api/kafkas_mgmt/v1/service_accounts\",code!~\"5..|0\",service=\"kas-fleet-manager-metrics\"}[$__range]))\n/\nsum(increase(api_inbound_request_count{path=\"/api/kafkas_mgmt/v1/service_accounts\",service=\"kas-fleet-manager-metrics\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "graph",
     "description": "Number of requests per second based on response code",
     "gridPos": { "h": 8, "w": 7, "x": 3, "y": 7 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by (code) (rate(api_inbound_request_count{service=\"kas-fleet-manager-metrics\",path=\"/api/kafkas_mgmt/v1/service_accounts\"}[5m]))",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "description": "The error percentage",
     "gridPos": { "h": 8, "w": 7, "x": 10, "y": 7 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(api_inbound_request_count{path=\"/api/kafkas_mgmt/v1/service_accounts\", service=\"kas-fleet-manager-metrics\", code!~\"2..\"}[5m]))/sum(rate(api_inbound_request_count{path=\"/api/kafkas_mgmt/v1/service_accounts\", service=\"kas-fleet-manager-metrics\"}[5m]))",
       "legendFormat": "non-2xx"
      },
      {
       "expr": "sum(rate(api_inbound_request_count{path=\"/api/kafkas_mgmt/v1/service_accounts\", service=\"kas-fleet-manager-metrics\", code=~\"5..|0\"}[5m]))/sum(rate(api_inbound_request_count{path=\"/api/kafkas_mgmt/v1/service_accounts\", service=\"kas-fleet-manager-metrics\"}[5m]))",
       "legendFormat": "5xx and timeout"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "description": "The request duration within which the API have served 99%, 95%, 50% of requests",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 7 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(api_inbound_request_duration_bucket{path=\"/api/kafkas_mgmt/v1/service_accounts\", service=\"kas-fleet-manager-metrics\", code!~\"5..|0\"}[5m])))",
       "legendFormat": "99th"
      },
      {
       "expr": "histogram_quantile(0.90, sum by (le) (rate(api_inbound_request_duration_bucket{path=\"/api/kafkas_mgmt/v1/service_accounts\", service=\"kas-fleet-manager-metrics\", code!~\"5..|0\"}[5m])))",
       "legendFormat": "90th"
      },
      {
       "expr": "histogram_quantile(0.5, sum by (le) (rate(api_inbound_request_duration_bucket{path=\"/api/kafkas_mgmt/v1/service_accounts\", service=\"kas-fleet-manager-metrics\", code!~\"5..|0\"}[5m])))",
       "legendFormat": "50th"
      }
     ]
    },
    {
     "title": "Latency (<1s)",
     "type": "stat",
     "description": "The percentage of time that the API responds within 1 second.",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(increase(api_inbound_request_duration_bucket{path=\"/api/kafkas_mgmt/v1/service_accounts\",code!~\"5..|0\",service=\"kas-fleet-manager-metrics\",le=\"1\"}[$__range]))\n/\nsum(increase(api_inbound_request_duration_count{path=\"/api/kafkas_mgmt/v1/service_accounts\",service=\"kas-fleet-manager-metrics\",code!~\"5..|0\"}[$__range]))"
      }
     ]
    }
   ]
  },
  {
   "title": "/service_accounts/{id}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Availability (selected time) ",
     "type": "stat",
     "description": "The percentage of time that the API is available (not returning 500 Internal Service Errors).",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(increase(api_inbound_request_count{path=\"/api/kafkas_mgmt/v1/service_accounts/-\",code!~\"5..|0\",service=\"kas-fleet-manager-metrics\"}[$__range]))\n/\nsum(increase(api_inbound_request_count{path=\"/api/kafkas_mgmt/v1/service_accounts/-\",service=\"kas-fleet-manager-metrics\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "graph",
     "description": "Number of requests per second based on response code",
     "gridPos": { "h": 8, "w": 7, "x": 3, "y": 8 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by (code) (rate(api_inbound_request_count{service=\"kas-fleet-manager-metrics\",path=\"/api/kafkas_mgmt/v1/service_accounts/-\"}[5m]))",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "description": "The error percentage",
     "gridPos": { "h": 8, "w": 7, "x": 10, "y": 8 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(api_inbound_request_count{path=\"/api/kafkas_mgmt/v1/service_accounts/-\", service=\"kas-fleet-manager-metrics\", code!~\"2..\"}[5m]))/sum(rate(api_inbound_request_count{path=\"/api/kafkas_mgmt/v1/service_accounts/-\", service=\"kas-fleet-manager-metrics\"}[5m]))",
       "legendFormat": "non-2xx"
      },
      {
       "expr": "sum(rate(api_inbound_request_count{path=\"/api/kafkas_mgmt/v1/service_accounts/-\", service=\"kas-fleet-manager-metrics\", code=~\"5..|0\"}[5m]))/sum(rate(api_inbound_request_count{path=\"/api/kafkas_mgmt/v1/service_accounts/-\", service=\"kas-fleet-manager-metrics\"}[5m]))",
       "legendFormat": "5xx and timeout"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "description": "The request duration within which the API have served 99%, 95%, 50% of requests",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 8 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(api_inbound_request_duration_bucket{path=\"/api/kafkas_mgmt/v1/service_accounts/-\", service=\"kas-fleet-manager-metrics\", code!~\"5..|0\"}[5m])))",
       "legendFormat": "99th"
      },
      {
       "expr": "histogram_quantile(0.90, sum by (le) (rate(api_inbound_request_duration_bucket{path=\"/api/kafkas_mgmt/v1/service_accounts/-\", service=\"kas-fleet-manager-metrics\", code!~\"5..|0\"}[5m])))",
       "legendFormat": "90th"
      },
      {
       "expr": "histogram_quantile(0.5, sum by (le) (rate(api_inbound_request_duration_bucket{path=\"/api/kafkas_mgmt/v1/service_accounts/-\", service=\"kas-fleet-manager-metrics\", code!~\"5..|0\"}[5m])))",
       "legendFormat": "50th"
      }
     ]
    },
    {
     "title": "Latency (<1s)",
     "type": "stat",
     "description": "The percentage of time that the API responds within 1 second.",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(increase(api_inbound_request_duration_bucket{path=\"/api/kafkas_mgmt/v1/service_accounts/-\",code!~\"5..|0\",service=\"kas-fleet-manager-metrics\",le=\"1\"}[$__range]))\n/\nsum(increase(api_inbound_request_duration_count{path=\"/api/kafkas_mgmt/v1/service_accounts/-\",service=\"kas-fleet-manager-metrics\",code!~\"5..|0\"}[$__range]))"
      }
     ]
    }
   ]
  },
  {
   "title": "/agent-clusters/{id}/status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Availability (selected time) ",
     "type": "stat",
     "description": "The percentage of time that the API is available (not returning 500 Internal Service Errors).",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(increase(api_inbound_request_count{path=~\"/api/kafkas_mgmt/v1/agent-clusters/-(/status)?\",code!~\"5..|0\",service=\"kas-fleet-manager-metrics\"}[$__range]))\n/\nsum(increase(api_inbound_request_count{path=~\"/api/kafkas_mgmt/v1/agent-clusters/-(/status)?\",service=\"kas-fleet-manager-metrics\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "graph",
     "description": "Number of requests per second based on response code",
     "gridPos": { "h": 8, "w": 7, "x": 3, "y": 10 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by (code) (rate(api_inbound_request_count{service=\"kas-fleet-manager-metrics\",path=~\"/api/kafkas_mgmt/v1/agent-clusters/-(/status)?\"}[5m]))",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "description": "The error percentage",
     "gridPos": { "h": 8, "w": 7, "x": 10, "y": 10 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(api_inbound_request_count{path=~\"/api/kafkas_mgmt/v1/agent-clusters/-(/status)?\", service=\"kas-fleet-manager-metrics\", code!~\"2..\"}[5m]))/sum(rate(api_inbound_request_count{path=~\"/api/kafkas_mgmt/v1/agent-clusters/-(/status)?\", service=\"kas-fleet-manager-metrics\"}[5m]))",
       "legendFormat": "non-2xx"
      },
      {
       "expr": "sum(rate(api_inbound_request_count{path=~\"/api/kafkas_mgmt/v1/agent-clusters/-(/status)?\", service=\"kas-fleet-manager-metrics\", code=~\"5..|0\"}[5m]))/sum(rate(api_inbound_request_count{path=~\"/api/kafkas_mgmt/v1/agent-clusters/-(/status)?\", service=\"kas-fleet-manager-metrics\"}[5m]))",
       "legendFormat": "5xx and timeout"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "description": "The request duration within which the API have served 99%, 95%, 50% of requests",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 10 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(api_inbound_request_duration_bucket{path=~\"/api/kafkas_mgmt/v1/agent-clusters/-(/status)?\", service=\"kas-fleet-manager-metrics\", code!~\"5..|0\"}[5m])))",
       "legendFormat": "99th"
      },
      {
       "expr": "histogram_quantile(0.90, sum by (le) (rate(api_inbound_request_duration_bucket{path=~\"/api/kafkas_mgmt/v1/agent-clusters/-(/status)?\", service=\"kas-fleet-manager-metrics\", code!~\"5..|0\"}[5m])))",
       "legendFormat": "90th"
      },
      {
       "expr": "histogram_quantile(0.5, sum by (le) (rate(api_inbound_request_duration_bucket{path=~\"/api/kafkas_mgmt/v1/agent-clusters/-(/status)?\", service=\"kas-fleet-manager-metrics\", code!~\"5..|0\"}[5m])))",
       "legendFormat": "50th"
      }
     ]
    },
    {
     "title": "Latency (<1s)",
     "type": "stat",
     "description": "The percentage of time that the API responds within 1 second.",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(increase(api_inbound_request_duration_bucket{path=~\"/api/kafkas_mgmt/v1/agent-clusters/-(/status)?\",code!~\"5..|0\",service=\"kas-fleet-manager-metrics\",le=\"1\"}[$__range]))\n/\nsum(increase(api_inbound_request_duration_count{path=~\"/api/kafkas_mgmt/v1/agent-clusters/-(/status)?\",service=\"kas-fleet-manager-metrics\",code!~\"5..|0\"}[$__range]))"
      }
     ]
    }
   ]
  },
  {
   "title": "/agent-clusters/{id}/kafkas/status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Availability (selected time) ",
     "type": "stat",
     "description": "The percentage of time that the API is available (not returning 500 Internal Service Errors).",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(increase(api_inbound_request_count{path=~\"/api/kafkas_mgmt/v1/agent-clusters/-/kafkas(/status)?\",code!~\"5..|0\",service=\"kas-fleet-manager-metrics\"}[$__range]))\n/\nsum(increase(api_inbound_request_count{path=~\"/api/kafkas_mgmt/v1/agent-clusters/-/kafkas(/status)?\",service=\"kas-fleet-manager-metrics\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "graph",
     "description": "Number of requests per second based on response code",
     "gridPos": { "h": 8, "w": 7, "x": 3, "y": 19 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by (code) (rate(api_inbound_request_count{service=\"kas-fleet-manager-metrics\",path=~\"/api/kafkas_mgmt/v1/agent-clusters/-/kafkas(/status)?\"}[5m]))",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "description": "The error percentage",
     "gridPos": { "h": 8, "w": 7, "x": 10, "y": 19 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(api_inbound_request_count{path=~\"/api/kafkas_mgmt/v1/agent-clusters/-/kafkas(/status)?\", service=\"kas-fleet-manager-metrics\", code!~\"2..\"}[5m]))/sum(rate(api_inbound_request_count{path=~\"/api/kafkas_mgmt/v1/agent-clusters/-/kafkas(/status)?\", service=\"kas-fleet-manager-metrics\"}[5m]))",
       "legendFormat": "non-2xx"
      },
      {
       "expr": "sum(rate(api_inbound_request_count{path=~\"/api/kafkas_mgmt/v1/agent-clusters/-/kafkas(/status)?\", service=\"kas-fleet-manager-metrics\", code=~\"5..|0\"}[5m]))/sum(rate(api_inbound_request_count{path=~\"/api/kafkas_mgmt/v1/agent-clusters/-/kafkas(/status)?\", service=\"kas-fleet-manager-metrics\"}[5m]))",
       "legendFormat": "5xx and timeout"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "description": "The request duration within which the API have served 99%, 95%, 50% of requests",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 19 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(api_inbound_request_duration_bucket{path=~\"/api/kafkas_mgmt/v1/agent-clusters/-/kafkas(/status)?\", service=\"kas-fleet-manager-metrics\", code!~\"5..|0\"}[5m])))",
       "legendFormat": "99th"
      },
      {
       "expr": "histogram_quantile(0.90, sum by (le) (rate(api_inbound_request_duration_bucket{path=~\"/api/kafkas_mgmt/v1/agent-clusters/-/kafkas(/status)?\", service=\"kas-fleet-manager-metrics\", code!~\"5..|0\"}[5m])))",
       "legendFormat": "90th"
      },
      {
       "expr": "histogram_quantile(0.5, sum by (le) (rate(api_inbound_request_duration_bucket{path=~\"/api/kafkas_mgmt/v1/agent-clusters/-/kafkas(/status)?\", service=\"kas-fleet-manager-metrics\", code!~\"5..|0\"}[5m])))",
       "legendFormat": "50th"
      }
     ]
    },
    {
     "title": "Latency (<1s)",
     "type": "stat",
     "description": "The percentage of time that the API responds within 1 second.",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(increase(api_inbound_request_duration_bucket{path=~\"/api/kafkas_mgmt/v1/agent-clusters/-/kafkas(/status)?\",code!~\"5..|0\",service=\"kas-fleet-manager-metrics\",le=\"1\"}[$__range]))\n/\nsum(increase(api_inbound_request_duration_count{path=~\"/api/kafkas_mgmt/v1/agent-clusters/-/kafkas(/status)?\",service=\"kas-fleet-manager-metrics\",code!~\"5..|0\"}[$__range]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Dependencies: Overall",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Availability (selected time) ",
     "type": "stat",
     "description": "The percentage of time that the API is available (not returning 500 Internal Service Errors).",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(increase(api_outbound_request_count{code!~\"5..|0\",service=\"kas-fleet-manager-metrics\"}[$__range]))\n/\nsum(increase(api_outbound_request_count{service=\"kas-fleet-manager-metrics\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "graph",
     "description": "Number of requests per second based on response code",
     "gridPos": { "h": 8, "w": 7, "x": 3, "y": 12 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by (code) (rate(api_outbound_request_count{service=\"kas-fleet-manager-metrics\"}[5m]))",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "description": "The error percentage",
     "gridPos": { "h": 8, "w": 7, "x": 10, "y": 12 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(api_outbound_request_count{service=\"kas-fleet-manager-metrics\", code!~\"2..\"}[5m]))/sum(rate(api_outbound_request_count{service=\"kas-fleet-manager-metrics\"}[5m]))",
       "legendFormat": "non-2xx"
      },
      {
       "expr": "sum(rate(api_outbound_request_count{service=\"kas-fleet-manager-metrics\", code=~\"5..|0\"}[5m]))/sum(rate(api_outbound_request_count{service=\"kas-fleet-manager-metrics\"}[5m]))",
       "legendFormat": "5xx and timeout"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "description": "The request duration within which the API have served 99%, 95%, 50% of requests",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 12 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(api_outbound_request_duration_bucket{service=\"kas-fleet-manager-metrics\", code!~\"5..|0\"}[5m])))",
       "legendFormat": "99th"
      },
      {
       "expr": "histogram_quantile(0.90, sum by (le) (rate(api_outbound_request_duration_bucket{service=\"kas-fleet-manager-metrics\", code!~\"5..|0\"}[5m])))",
       "legendFormat": "90th"
      },
      {
       "expr": "histogram_quantile(0.5, sum by (le) (rate(api_outbound_request_duration_bucket{service=\"kas-fleet-manager-metrics\", code!~\"5..|0\"}[5m])))",
       "legendFormat": "50th"
      }
     ]
    },
    {
     "title": "Latency (<1s)",
     "type": "stat",
     "description": "The percentage of time that the API responds within 1 second.",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(increase(api_outbound_request_duration_bucket{code!~\"5..|0\",service=\"kas-fleet-manager-metrics\",le=\"1\"}[$__range]))\n/\nsum(increase(api_outbound_request_duration_count{service=\"kas-fleet-manager-metrics\",code!~\"5..|0\"}[$__range]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Dependencies: OCM Cluster Service ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Availability (selected time) ",
     "type": "stat",
     "description": "The percentage of time that the API is available (not returning 500 Internal Service Errors).",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(increase(api_outbound_request_count{code!~\"5..|0\",service=\"kas-fleet-manager-metrics\",apiservice=\"ocm-clusters-service\"}[$__range]))\n/\nsum(increase(api_outbound_request_count{service=\"kas-fleet-manager-metrics\",apiservice=\"ocm-clusters-service\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "graph",
     "description": "Number of requests per second based on response code",
     "gridPos": { "h": 8, "w": 7, "x": 3, "y": 11 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by (code) (rate(api_outbound_request_count{service=\"kas-fleet-manager-metrics\",apiservice=\"ocm-clusters-service\"}[5m]))",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "description": "The error percentage",
     "gridPos": { "h": 8, "w": 7, "x": 10, "y": 11 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(api_outbound_request_count{service=\"kas-fleet-manager-metrics\", code!~\"2..\",apiservice=\"ocm-clusters-service\"}[5m]))/sum(rate(api_outbound_request_count{service=\"kas-fleet-manager-metrics\",apiservice=\"ocm-clusters-service\"}[5m]))",
       "legendFormat": "non-2xx"
      },
      {
       "expr": "sum(rate(api_outbound_request_count{service=\"kas-fleet-manager-metrics\", code=~\"5..|0\",apiservice=\"ocm-clusters-service\"}[5m]))/sum(rate(api_outbound_request_count{service=\"kas-fleet-manager-metrics\",apiservice=\"ocm-clusters-service\"}[5m]))",
       "legendFormat": "5xx and timeout"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "description": "The request duration within which the API have served 99%, 95%, 50% of requests",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 11 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(api_outbound_request_duration_bucket{service=\"kas-fleet-manager-metrics\",code!~\"5..|0\",apiservice=\"ocm-clusters-service\"}[5m])))",
       "legendFormat": "99th"
      },
      {
       "expr": "histogram_quantile(0.90, sum by (le) (rate(api_outbound_request_duration_bucket{service=\"kas-fleet-manager-metrics\",code!~\"5..|0\",apiservice=\"ocm-clusters-service\"}[5m])))",
       "legendFormat": "90th"
      },
      {
       "expr": "histogram_quantile(0.5, sum by (le) (rate(api_outbound_request_duration_bucket{service=\"kas-fleet-manager-metrics\",code!~\"5..|0\",apiservice=\"ocm-clusters-service\"}[5m])))",
       "legendFormat": "50th"
      }
     ]
    },
    {
     "title": "Latency (<1s)",
     "type": "stat",
     "description": "The percentage of time that the API responds within 1 second.",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(increase(api_outbound_request_duration_bucket{code!~\"5..|0\",service=\"kas-fleet-manager-metrics\",le=\"1\",apiservice=\"ocm-clusters-service\"}[$__range]))\n/\nsum(increase(api_outbound_request_duration_count{service=\"kas-fleet-manager-metrics\",code!~\"5..|0\",apiservice=\"ocm-clusters-service\"}[$__range]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Dependencies: OCM Terms Review",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Availability (selected time) ",
     "type": "stat",
     "description": "The percentage of time that the API is available (not returning 500 Internal Service Errors).",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(increase(api_outbound_request_count{code!~\"5..|0\",service=\"kas-fleet-manager-metrics\",apiservice=\"ocm-authorizations-service\",path=\"/api/authorizations/v1/terms_review\"}[$__range]))\n/\nsum(increase(api_outbound_request_count{service=\"kas-fleet-manager-metrics\",apiservice=\"ocm-authorizations-service\",path=\"/api/authorizations/v1/terms_review\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "graph",
     "description": "Number of requests per second based on response code",
     "gridPos": { "h": 8, "w": 7, "x": 3, "y": 22 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by (code) (rate(api_outbound_request_count{service=\"kas-fleet-manager-metrics\",apiservice=\"ocm-authorizations-service\",path=\"/api/authorizations/v1/terms_review\"}[5m]))",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "description": "The error percentage",
     "gridPos": { "h": 8, "w": 7, "x": 10, "y": 22 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(api_outbound_request_count{service=\"kas-fleet-manager-metrics\", code!~\"2..\",apiservice=\"ocm-authorizations-service\",path=\"/api/authorizations/v1/terms_review\"}[5m]))/sum(rate(api_outbound_request_count{service=\"kas-fleet-manager-metrics\",apiservice=\"ocm-authorizations-service\",path=\"/api/authorizations/v1/terms_review\"}[5m]))",
       "legendFormat": "non-2xx"
      },
      {
       "expr": "sum(rate(api_outbound_request_count{service=\"kas-fleet-manager-metrics\", code=~\"5..|0\",apiservice=\"ocm-authorizations-service\",path=\"/api/authorizations/v1/terms_review\"}[5m]))/sum(rate(api_outbound_request_count{service=\"kas-fleet-manager-metrics\",apiservice=\"ocm-authorizations-service\",path=\"/api/authorizations/v1/terms_review\"}[5m]))",
       "legendFormat": "5xx and timeout"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "description": "The request duration within which the API have served 99%, 95%, 50% of requests",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 22 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(api_outbound_request_duration_bucket{service=\"kas-fleet-manager-metrics\",code!~\"5..|0\",apiservice=\"ocm-authorizations-service\",path=\"/api/authorizations/v1/terms_review\"}[5m])))",
       "legendFormat": "99th"
      },
      {
       "expr": "histogram_quantile(0.90, sum by (le) (rate(api_outbound_request_duration_bucket{service=\"kas-fleet-manager-metrics\",code!~\"5..|0\",apiservice=\"ocm-authorizations-service\",path=\"/api/authorizations/v1/terms_review\"}[5m])))",
       "legendFormat": "90th"
      },
      {
       "expr": "histogram_quantile(0.5, sum by (le) (rate(api_outbound_request_duration_bucket{service=\"kas-fleet-manager-metrics\",code!~\"5..|0\",apiservice=\"ocm-authorizations-service\",path=\"/api/authorizations/v1/terms_review\"}[5m])))",
       "legendFormat": "50th"
      }
     ]
    },
    {
     "title": "Latency (<1s)",
     "type": "stat",
     "description": "The percentage of time that the API responds within 1 second.",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(increase(api_outbound_request_duration_bucket{code!~\"5..|0\",service=\"kas-fleet-manager-metrics\",le=\"1\",apiservice=\"ocm-authorizations-service\",path=\"/api/authorizations/v1/terms_review\"}[$__range]))\n/\nsum(increase(api_outbound_request_duration_count{service=\"kas-fleet-manager-metrics\",code!~\"5..|0\",apiservice=\"ocm-authorizations-service\",path=\"/api/authorizations/v1/terms_review\"}[$__range]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Dependencies: Observatorium",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Availability (selected time) ",
     "type": "stat",
     "description": "The percentage of time that the Observatorium API is available.",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(increase(kas_fleet_manager_observatorium_request_count{code!~\"5..|0\"}[$__range]))\n/\nsum(increase(kas_fleet_manager_observatorium_request_count[$__range]))"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "graph",
     "description": "Number of requests per second based on response code",
     "gridPos": { "h": 8, "w": 7, "x": 3, "y": 23 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by (code) (rate(kas_fleet_manager_observatorium_request_count[5m]))",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "description": "The error percentage",
     "gridPos": { "h": 8, "w": 7, "x": 10, "y": 23 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(kas_fleet_manager_observatorium_request_count{code!~\"2..\"}[5m]))/sum(rate(kas_fleet_manager_observatorium_request_count[5m]))",
       "legendFormat": "non-2xx"
      },
      {
       "expr": "sum(rate(kas_fleet_manager_observatorium_request_count{code=~\"5..|0\"}[5m]))/sum(rate(kas_fleet_manager_observatorium_request_count[5m]))",
       "legendFormat": "5xx and timeout"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "description": "The request duration within which the API have served 99%, 95%, 50% of requests",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 23 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(kas_fleet_manager_observatorium_request_duration_bucket{code!~\"5..|0\"}[5m])))",
       "legendFormat": "99th"
      },
      {
       "expr": "histogram_quantile(0.90, sum by (le) (rate(kas_fleet_manager_observatorium_request_duration_bucket{code!~\"5..|0\"}[5m])))",
       "legendFormat": "90th"
      },
      {
       "expr": "histogram_quantile(0.5, sum by (le) (rate(kas_fleet_manager_observatorium_request_duration_bucket{code!~\"5..|0\"}[5m])))",
       "legendFormat": "50th"
      }
     ]
    },
    {
     "title": "Latency (<1s)",
     "type": "stat",
     "description": "The percentage of time that the API responds within 1 second.",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(increase(kas_fleet_manager_observatorium_request_duration_bucket{code!~\"5..|0\",le=\"1\"}[$__range]))\n/\nsum(increase(kas_fleet_manager_observatorium_request_duration_count{code!~\"5..|0\"}[$__range]))"
      }
     ]
    }
   ]
  }
 ]
}