{
 "title": "PRE - Production Cluster Versions",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "source",
    "query": "+ 0, + on (_id) group_left(_blah) (0 * topk by (_id) (1\\, subscription_labels{email_domain!~\"redhat.com|(^|.*\\\\.)ibm.com\"})), + on (_id) group_left(_blah) (0 * topk by (_id) (1\\, subscription_labels{support=~\"Premium|Standard\"}))"
   },
   {
    "name": "source_version",
    "query": "+ 0, + on (_id) group_left(_blah) (0 * topk by (_id) (1\\, cluster_version{type=\"current\"\\,version=~\"4\\\\.1\\\\.\\\\d+\"})),  + on (_id) group_left(_blah) (0 * topk by (_id) (1\\, cluster_version{type=\"current\"\\,version=~\"4\\\\.2\\\\.\\\\d+\"})), + on (_id) group_left(_blah) (0 * topk by (_id) (1\\, cluster_version{type=\"current\"\\,version=~\"4\\\\.3\\\\.\\\\d+.*\"})),  + on (_id) group_left(_blah) (0 * ((time() - topk by (_id) (1\\, cluster_version{type=\"completed\"\\,version=~\"4\\\\.\\\\d+\\\\.\\\\d+\"})) < (21 * 24 * 60 * 60))) + on (_id) group_left(_blah) (0 * ((time() - topk by (_id) (1\\, cluster_version{type=\"initial\"})) > (7 * 24 * 60 * 60))), + on (_id) group_left(_blah) (0 * topk by (_id) (1\\, cluster_version{type=\"current\"\\,version=~\"4\\\\.\\\\d+\\\\.\\\\d+-0\\\\.nightly.+\"}))"
   }
  ]
 },
 "panels": [
  {
   "title": "Clusters installed (7d)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count((time() - max by (_id)(max_over_time(cluster_version{type=\"cluster\"}[7d]))) < (7 * 24 * 60 * 60))"
    }
   ]
  },
  {
   "title": "Version Breakdown",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 9, "x": 3, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count by (version) (cluster_version{type=\"current\"} $source $source_version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "By Email Domain",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sort_desc(\n  count by (email_domain) (\n    (max by (_id, account, email_domain, organization, external_organization) (\n      subscription_labels\n    )) + on (_id) group_left (version) (0 * topk by (_id) (1, \n      cluster_version{type=\"current\"}\n    ))\n    $source $source_version\n  )\n)",
     "legendFormat": "{{email_domain}}"
    }
   ]
  },
  {
   "title": "Clusters (all)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count by (_id) (cluster_version{type=\"current\"} $source $source_version))"
    }
   ]
  },
  {
   "title": "Clusters (> 1w)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count((time() - cluster_version{type=\"cluster\"} $source $source_version) > 7 * 24 * 60 * 60)"
    }
   ]
  },
  {
   "title": "Clusters (< 1d)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count((time() - (cluster_version{type=\"cluster\"} $source $source_version)) < 24 * 60 * 60)"
    }
   ]
  },
  {
   "title": "Updated recently",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count by (_id) ((time() - max_over_time(cluster_version{type=\"updating\",from_version!=\"\"}[7d])) < (7 * 24 * 60 * 60)) $source $source_version)"
    }
   ]
  },
  {
   "title": "Most installed version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "topk(1, count by (version) ((time() - cluster_version{type=\"cluster\"}) > 24 * 60 * 60))"
    }
   ]
  },
  {
   "title": "Most upgraded to (7d)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "topk(1, count by (version) (changes(cluster_version{type=\"updating\"}[7d])))"
    }
   ]
  },
  {
   "title": "Version Breakdown",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (version) (\n  ((time() - topk by (_id) (1,\n    label_replace(\n      label_replace(cluster_version{type=\"current\"}, \"version\", \"4.$1-0.$2\", \"version\", \"4\\\\.(\\\\d+\\\\.\\\\d+)-0.(ci|nightly|okd).*\"),\n      \"version\",\n      \"ci-pull-requests\",\n      \"version\",\n      \"0.0.1-.*\"\n    )\n  )))\n  $source $source_version\n)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Cluster age distribution (days)",
   "type": "heatmap",
   "description": "Clusters by their current age in days, over time",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "max by (_id) (time() - (cluster_version{type=\"cluster\"} $source $source_version)) / (60 * 60 * 24)"
    }
   ]
  },
  {
   "title": "New clusters every 4h",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (version) (\n   ((time() - topk by (_id) (1,\n    label_replace(\n      label_replace(cluster_version{type=\"current\"}, \"version\", \"4.$1-0.$2\", \"version\", \"4\\\\.(\\\\d+\\\\.\\\\d+)-0.(ci|nightly|okd).*\"),\n      \"version\",\n      \"ci-pull-requests\",\n      \"version\",\n      \"0.0.1-.*\"\n    )\n   ) < (4 * 60 * 60)))\n)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Cluster usage (days)",
   "type": "graph",
   "description": "The cumulative age of all clusters in days.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum by (_id) (time() - (cluster_version{type=\"cluster\"} $source $source_version))) / (60 * 60 * 24)"
    }
   ]
  },
  {
   "title": "Upgrades every 4h",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (version) (\n  ((time() - topk by (_id) (1,\n    label_replace(\n      label_replace(cluster_version{type=\"current\"}, \"version\", \"4.$1-0.$2\", \"version\", \"4\\\\.(\\\\d+\\\\.\\\\d+)-0.(ci|nightly|okd).*\"),\n      \"version\",\n      \"ci-pull-requests\",\n      \"version\",\n      \"0.0.1-.*\"\n    )\n  ) < 4 * 60 * 60))\n)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Cluster-days by current version",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (version) ((time() - (\n  label_replace(\n    label_replace(cluster_version{type=\"current\"}, \"version\", \"4.$1-0.$2\", \"version\", \"4\\\\.(\\\\d+\\\\.\\\\d+)-0.(ci|nightly|okd).*\"),\n    \"version\",\n    \"ci-pull-requests\",\n    \"version\",\n    \"0.0.1-.*\"\n  )\n)) / (60 * 60 * 24))",
     "legendFormat": "{{version}}"
    }
   ]
  }
 ]
}