{
 "title": "PRE - Production Cluster Version Upgrades",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "release", "query": "prometheus" },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Running clusters that reported upgrade errors over 7 days",
   "type": "table",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "min by (_id, version, from_version) ((bottomk by (_id) (1,((time() - max_over_time(cluster_version{type=\"failure\",version=~\"$version\\\\.\\\\d+($|-rc.\\\\d+)\",from_version=~\"$previous_version\\\\..*\"}[7d])))) and on (_id) (topk by (_id) (1, cluster_version{type=\"current\"}))))"
    }
   ]
  },
  {
   "title": "Failed upgrades over 7 days",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 0 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count by (_id) (max_over_time(cluster_version{type=\"failure\",version=~\"$version\\\\.\\\\d+($|-rc.\\\\d+)\",from_version=~\"$previous_version\\\\..*\"}[7d]))) / count(count by (_id) (max_over_time(cluster_version{type=\"updating\",version=~\"$version\\\\.\\\\d+($|-rc.\\\\d+)\",from_version=~\"$previous_version\\\\..*\"}[7d])))"
    }
   ]
  },
  {
   "title": "From",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 5, "x": 14, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count by (from_version) (topk by (_id) (1, (max_over_time(cluster_version{type=\"updating\",version=~\"4.2.0($|-rc.\\\\d+)\",from_version=~\"4\\\\.1\\\\..*\"}[7d]))))",
     "legendFormat": "{{from_version}}"
    }
   ]
  },
  {
   "title": "To",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count by (version) (topk by (_id) (1, (max_over_time(cluster_version{type=\"updating\",version=~\"4.2.0($|-rc.\\\\d+)\",from_version=~\"4\\\\.1\\\\..*\"}[7d]))))",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Upgraded in last 7 days",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count by (_id) (max_over_time(cluster_version{type=\"updating\",version=~\"$version\\\\.\\\\d+($|-rc.\\\\d+)\",from_version=~\"$previous_version\\\\..*\"}[7d])))"
    }
   ]
  },
  {
   "title": "All clusters that reported upgrade errors over 7 days",
   "type": "table",
   "gridPos": { "h": 14, "w": 11, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "min by (_id, version, from_version) ((bottomk by (_id) (1,((time() - max_over_time(cluster_version{type=\"failure\",version=~\"$version\\\\.\\\\d+($|-rc.\\\\d+)\",from_version=~\"$previous_version\\\\..*\"}[7d]))) )))"
    }
   ]
  },
  {
   "title": "Edges",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 10 },
   "targets": [
    {
     "expr": "count by (from_version,version) (topk by (_id) (1, (max_over_time(cluster_version{type=\"updating\",version=~\"4.2.0($|-rc.\\\\d+)\",from_version=~\"4\\\\.1\\\\..*\"}[7d]))))"
    }
   ]
  },
  {
   "title": "Failed Edges",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 17 },
   "targets": [
    {
     "expr": "count by (from_version,version) (topk by (_id) (1, (max_over_time(cluster_version{type=\"failure\",version=~\"4.2.0($|-rc.\\\\d+)\",from_version=~\"4\\\\.1\\\\..*\"}[7d]))))"
    }
   ]
  }
 ]
}