{
 "title": "PRE - Production Cluster by ID",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "_id", "label": "Cluster ID", "query": "cluster_version" },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Degraded Operators",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max by (name,condition,reason) (cluster_operator_conditions{_id=\"$_id\",condition=\"Degraded\"} == 1 or cluster_operator_conditions{_id=\"$_id\",condition=\"Available\"} == 0)"
    }
   ]
  },
  {
   "title": "Down Nodes",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "max by (node,instance) (up{_id=\"$_id\",job=\"kubelet\"} == 0)"
    }
   ]
  },
  {
   "title": "Down Services",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "max by (job,namespace,service) (up{_id=\"$_id\",job!=\"kubelet\"} == 0)"
    }
   ]
  },
  {
   "title": "Version",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
   "format": "s",
   "valueName": "name",
   "targets": [
    {
     "expr": "topk(1,cluster_version{_id=\"$_id\",type=\"completed\",version!=\"\"})",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Updating To",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 6 },
   "format": "s",
   "valueName": "name",
   "targets": [
    {
     "expr": "topk(1, cluster_version{_id=\"$_id\",type=\"updating\"})",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Type",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "3 * (count by (_id) (count by (_id) (cluster:node_instance_type_count:sum{_id=\"$_id\",label_beta_kubernetes_io_instance_type=~\"Standard_.*\"}))) OR 2 * (count by (_id) (count by (_id) (cluster:node_instance_type_count:sum{_id=\"$_id\",label_beta_kubernetes_io_instance_type=~\"[ipmtrc]\\\\d(\\\\w)?\\\\.(\\\\w+)?(large|medium)\"}))) OR count by (_id) (count by (_id) (cluster:node_instance_type_count:sum{_id=\"$_id\",label_beta_kubernetes_io_instance_type=\"\"}))"
    }
   ]
  },
  {
   "title": "Etcd objects",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max by (_id) (instance:etcd_object_counts:sum{_id=\"$_id\"})"
    }
   ]
  },
  {
   "title": "API Error Rate",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "max by (code,_id) (code:apiserver_request_count:rate:sum{_id=\"$_id\",code=~\"[4-5]\\\\d+\"})> 0",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 6 },
   "targets": [
    {
     "expr": "max by (alertname,alertstate) (alerts{_id=\"$_id\"})"
    }
   ]
  },
  {
   "title": "Failing For",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 10 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max by (_id) (time() - cluster_version{_id=\"$_id\",type=\"failure\"} > 0)"
    }
   ]
  },
  {
   "title": "Updating For",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 10 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "topk(1, time() - cluster_version{_id=\"$_id\",type=\"updating\"} > 0)"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cluster:node_instance_type_count:sum{_id=\"$_id\"})"
    }
   ]
  },
  {
   "title": "Masters",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cluster:node_instance_type_count:sum{label_node_role_kubernetes_io=\"master\",_id=\"$_id\"})"
    }
   ]
  },
  {
   "title": "Operators by version",
   "type": "table",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 10 },
   "targets": [
    {
     "expr": "count by (version) (cluster_operator_up{_id=\"$_id\"})"
    }
   ]
  },
  {
   "title": "Age",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 14 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "topk(1, time() - cluster_version{_id=\"$_id\",type=\"cluster\"})"
    }
   ]
  },
  {
   "title": "Since last update",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 14 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "topk(1,time() - cluster_version{_id=\"$_id\",type=\"completed\"} < 1560000000)"
    }
   ]
  },
  {
   "title": "Cores",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cluster:cpu_usage_cores:sum{_id='$_id'})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 14 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "max by (_id) (cluster:cpu_usage_cores:sum{_id=\"$_id\"}) / on (_id) max by (_id) (sum by (_id) (cluster:capacity_cpu_cores:sum))"
    }
   ]
  }
 ]
}