{
 "title": "OLM Managed Operators",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "source",
    "query": "+ 0, + on (_id) group_left(_blah) (0 * topk by (_id) (1\\, cluster_version{type=\"current\"\\,version=~\"4\\\\.\\\\d+\\\\.\\\\d+\"})), + on (_id) group_left(_blah) (0 * ((time() - topk by (_id) (1\\, cluster_version{type=\"completed\"\\,version=~\"4\\\\.\\\\d+\\\\.\\\\d+\"})) < (21 * 24 * 60 * 60))) + on (_id) group_left(_blah) (0 * ((time() - topk by (_id) (1\\, cluster_version{type=\"initial\"})) > (7 * 24 * 60 * 60))), + on (_id) group_left(_blah) (0 * topk by (_id) (1\\, subscription_labels{email_domain!~\"redhat.com|(^|.*\\\\.)ibm.com\"})), + on (_id) group_left(_blah) (0 * topk by (_id) (1\\, subscription_labels{support=~\"Premium|Standard\"})),  + on (_id) group_left(_blah) (0 * topk by (_id) (1\\, cluster_version{type=\"current\"\\,version=~\"4\\\\.\\\\d+\\\\.\\\\d+\"})) + on (_id) group_left(_blah) (0 * topk by (_id) (1\\, subscription_labels{email_domain!=\"redhat.com\"})),  + on (_id) group_left(_blah) (0 * topk by (_id) (1\\, cluster_version{type=\"current\"\\,version=~\"4\\\\.\\\\d+\\\\.\\\\d+-0\\\\.nightly.+\"})) + on (_id) group_left(_blah) (0 * topk by (_id) (1\\, subscription_labels{email_domain!=\"redhat.com\"}))"
   },
   {
    "name": "source_version",
    "query": "+ 0, + on (_id) group_left(_blah) (0 * topk by (_id) (1\\, cluster_version{type=\"current\"\\,version=~\"4\\\\.1\\\\.\\\\d+\"})),  + on (_id) group_left(_blah) (0 * topk by (_id) (1\\, cluster_version{type=\"current\"\\,version=~\"4\\\\.2\\\\.\\\\d+\"})), + on (_id) group_left(_blah) (0 * topk by (_id) (1\\, cluster_version{type=\"current\"\\,version=~\"4\\\\.3\\\\.\\\\d+.*\"})),  + on (_id) group_left(_blah) (0 * ((time() - topk by (_id) (1\\, cluster_version{type=\"completed\"\\,version=~\"4\\\\.\\\\d+\\\\.\\\\d+\"})) < (21 * 24 * 60 * 60))) + on (_id) group_left(_blah) (0 * ((time() - topk by (_id) (1\\, cluster_version{type=\"initial\"})) > (7 * 24 * 60 * 60))), + on (_id) group_left(_blah) (0 * topk by (_id) (1\\, cluster_version{type=\"current\"\\,version=~\"4\\\\.\\\\d+\\\\.\\\\d+-0\\\\.nightly.+\"}))"
   }
  ]
 },
 "panels": [
  { "title": "Clusters Reporting OLM Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Clusters",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": " count(count by (_id) (cluster_version{type=\"current\"} $source $source_version))"
    }
   ]
  },
  {
   "title": "Clusters Reporting OLM Metrics",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count by (_id) (subscription_sync_total{installed=~\"packageserver.*\"} $source $source_version))"
    }
   ]
  },
  {
   "title": "Clusters Reporting OLM Metrics w/ 1+ Optional Operators Installed",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count by (_id) (subscription_sync_total{installed!~\"|packageserver.*\"} $source $source_version))"
    }
   ]
  },
  {
   "title": "% of Reporting Clusters w/ 1+ Optional Operators Installed",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count by (_id) (subscription_sync_total{installed!~\"|packageserver.*\"} $source $source_version)) / count(count by (_id, installed) (subscription_sync_total{installed=~\"packageserver.*\"} $source $source_version)) * 100"
    }
   ]
  },
  {
   "title": "Metrics on Clusters w/ 1+ Optional Operators Installed",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }
  },
  {
   "title": "README.md",
   "type": "text",
   "gridPos": { "h": 4, "w": 20, "x": 0, "y": 9 },
   "content": "\n# Optional Operator Data\n\nThis panel highlights information about OpenShift clusters that have installed at least one optional operator via a Subscription custom resource, where an optional operator is defined as an operator other than the PackageServer.\n\n"
  },
  {
   "title": "Avg Number of Optional Operators Installed",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(count by(_id)(count by (_id, installed) (subscription_sync_total{installed!~\"|packageserver.*\"} $source $source_version)))"
    }
   ]
  },
  {
   "title": "Max Number of Optional Operators Installed on a Cluster",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(count by(_id)(count by (_id, installed) (subscription_sync_total{installed!~\"|packageserver.*\"} $source $source_version)))"
    }
   ]
  },
  {
   "title": "Most Popular Operators",
   "type": "table",
   "gridPos": { "h": 20, "w": 5, "x": 10, "y": 13 },
   "targets": [
    {
     "expr": "sort_desc(count by (installed)(count by (_id, installed) (subscription_sync_total{installed!~\"|packageserver.*\"} $source $source_version)))"
    }
   ]
  },
  {
   "title": "Breakdown of Optional Operators",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 20, "w": 5, "x": 15, "y": 13 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count by (_id) (count by (_id, installed) (subscription_sync_total{installed!~\"|packageserver.*\"} $source $source_version)) < 5)\n",
     "legendFormat": "Less than 5 Optional Operators Installed"
    },
    {
     "expr": "count(count by (_id) (count by (_id, installed) (subscription_sync_total{installed!~\"|packageserver.*\"} $source $source_version)) < 10 >=5)\n",
     "legendFormat": "5 to 9 Optional Operators Installed"
    },
    {
     "expr": "count(count by (_id) (count by (_id, installed) (subscription_sync_total{installed!~\"|packageserver.*\"} $source $source_version)) < 15 >=10)",
     "legendFormat": "10 to 14 Optional Operators Installed"
    },
    {
     "expr": "count(count by (_id) (count by (_id, installed) (subscription_sync_total{installed!~\"|packageserver.*\"} $source $source_version)) < 20 >=15)",
     "legendFormat": "15 to 19 Optional Operators Installed"
    },
    {
     "expr": "count(count by (_id) (count by (_id, installed) (subscription_sync_total{installed!~\"|packageserver.*\"} $source $source_version)) >=20)",
     "legendFormat": "20 or more Optional Operators Installed"
    }
   ]
  }
 ]
}