{
 "title": "PRE - Production Cluster Versions",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Clusters installed (7d)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count((time() - max by (_id)(max_over_time(cluster_version{type=\"cluster\"}[7d]))) < (7 * 24 * 60 * 60))"
    }
   ]
  },
  {
   "title": "Version Breakdown",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 9, "x": 3, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count by (version) (cluster_version{type=\"current\"})",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Non Red-Hat Clusters",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sort_desc(count by (email_domain) ((max by (_id, account, email_domain, organization, external_organization) (subscription_labels{email_domain!=\"redhat.com\"})) + on (_id) group_left (version) (0 * topk by (_id) (1, cluster_version{type=\"current\",version=~\"4\\\\.\\\\d+\\\\.\\\\d+\"}))))",
     "legendFormat": "{{email_domain}}"
    }
   ]
  },
  {
   "title": "Clusters (all)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count by (_id) (cluster_version{type=\"current\"}))"
    }
   ]
  },
  {
   "title": "Clusters (> 1w)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count((time() - cluster_version{type=\"cluster\"}) > 7 * 24 * 60 * 60)"
    }
   ]
  },
  {
   "title": "Clusters (< 1d)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count((time() - cluster_version{type=\"cluster\"}) < 24 * 60 * 60)"
    }
   ]
  },
  {
   "title": "External Clusters (4.y.z)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count((max by (_id, account, email_domain, organization, external_organization) (subscription_labels{email_domain!=\"redhat.com\"})) + on (_id) group_left (version) (0 * topk by (_id) (1, cluster_version{type=\"current\",version=~\"4\\\\.\\\\d+\\\\.\\\\d+\"})))"
    }
   ]
  },
  {
   "title": "Most installed version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "topk(1, count by (version) ((time() - cluster_version{type=\"cluster\"}) > 24 * 60 * 60))"
    }
   ]
  },
  {
   "title": "Most upgraded to (7d)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "topk(1, count by (version) (changes(cluster_version{type=\"updating\"}[7d])))"
    }
   ]
  },
  {
   "title": "Version Breakdown (4.y.z, non-RH)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (version) (\n   ((time() - topk by (_id) (1,cluster_version{type=\"current\",version=~\"4\\\\.\\\\d+\\\\.\\\\d+\"}))) +\n   on (_id) group_right (version) (0 * count by (_id) (subscription_labels{email_domain!=\"redhat.com\"}))\n)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Cluster age distribution (days)",
   "type": "heatmap",
   "description": "Clusters by their current age in days, over time",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "max by (_id) (time() - cluster_version{type=\"cluster\"}) / 60 / 60 / 24"
    }
   ]
  },
  {
   "title": "New clusters every 4h (4.y.z, non-RH)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (version) (\n   ((time() - topk by (_id) (1,cluster_version{type=\"cluster\",version=~\"4\\\\.\\\\d+\\\\.\\\\d+\"}) < 4 * 60 * 60)) +\n   on (_id) group_right (version) (0 * count by (_id) (subscription_labels{email_domain!=\"redhat.com\"}))\n)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Cluster usage (days)",
   "type": "graph",
   "description": "The cumulative age of all clusters in days.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum by (_id) (time() - cluster_version{type=\"cluster\"})) / 60 / 60 / 24"
    }
   ]
  },
  {
   "title": "Upgrades every 4h (4.y.z, non-RH)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (version) (\n   ((time() - topk by (_id) (1,cluster_version{type=\"updating\",version=~\"4\\\\.\\\\d+\\\\.\\\\d+\"}) < 4 * 60 * 60)) +\n   on (_id) group_right (version) (0 * count by (_id) (subscription_labels{email_domain!=\"redhat.com\"}))\n)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Cluster-days by current version (4.y.z)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (version) ((time() - cluster_version{type=\"cluster\",version=~\"4\\\\.\\\\d+\\\\.\\\\d+\"}) / (60 * 60 * 24))"
    }
   ]
  }
 ]
}