{
 "title": "PRE - Production Cluster Health by Customer",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Clusters failing (subscribed)",
   "type": "table",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sort_desc(max by (_id,email_domain,version) ((time() - cluster_version{type=\"failure\",version=~\"4\\\\.\\\\d+\\\\.\\\\d+\"}) + on (_id) group_left (email_domain,support) (0 * max by (_id,email_domain,support) (subscription_labels{support=~\"Premium|Standard\"}))))"
    }
   ]
  },
  {
   "title": "Clusters (non-RH)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count((max by (_id) (cluster_version{type=\"current\"})) + on (_id) group_left(support,email_domain) (0 * max by (_id,support,email_domain) (subscription_labels{email_domain!~\"redhat.com\"})))"
    }
   ]
  },
  {
   "title": "Failing Clusters (non-RH)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count((max by (_id) (cluster_version{type=\"failure\"})) + on (_id) group_left(support,email_domain) (0 * max by (_id,support,email_domain) (subscription_labels{email_domain!~\"redhat.com\"})))"
    }
   ]
  },
  {
   "title": "Top important clusters (non-RH)",
   "type": "table",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "expr": "topk(30,\n((\n  (max by (_id) (subscription_labels{support!~\"Standard|Premium\",email_domain!=\"redhat.com\"}*1 or max by (_id) (subscription_labels{support=~\"Standard|Premium\",email_domain!=\"redhat.com\"}*5))) * \n  clamp_max(clamp_min((((time() - max by (_id) (cluster_version{type=\"cluster\"})) / 3600 / 24)) / 7 > 0.8, 1), 10) *\n  clamp_max(clamp_min( (max by (_id) (instance:etcd_object_counts:sum > 3200) - 3200)/1000 + 1, 1), 10) * \n  clamp_max(clamp_min( (max by (_id) (cluster:capacity_cpu_cores:sum > 12) - 12)/20 + 1, 1), 10) +\n  (0 * (sum by (_id) (cluster:node_instance_type_count:sum{label_node_role_kubernetes_io=\"master\"}) >= 2))\n) ^ (1/4) )\n)"
    }
   ]
  },
  {
   "title": "Subscribed Clusters (non-RH)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count((max by (_id) (cluster:capacity_cpu_cores:sum)) + on (_id) group_left(support,email_domain) (0 * max by (_id,support,email_domain) (subscription_labels{support=~\"Premium|Standard\",email_domain!~\"redhat.com\"})))"
    }
   ]
  },
  {
   "title": "Failing Subscribed Clusters (non-RH)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count((max by (_id) (cluster_version{type=\"failure\"})) + on (_id) group_left(support,email_domain) (0 * max by (_id,support,email_domain) (subscription_labels{support=~\"Premium|Standard\",email_domain!~\"redhat.com\"})))"
    }
   ]
  },
  {
   "title": "Clusters failing by user (non-RH)",
   "type": "table",
   "gridPos": { "h": 24, "w": 11, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sort_desc(max by (_id,email_domain,version) ((time() - cluster_version{type=\"failure\",version=~\"4\\\\.\\\\d+\\\\.\\\\d+\"}) + on (_id) group_left (email_domain,support) (0 * max by (_id,email_domain,support) (subscription_labels{email_domain!~\"redhat.com\"}))))"
    }
   ]
  },
  {
   "title": "Important Clusters (non-RH)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(\n((\n  (max by (_id) (subscription_labels{support!~\"Standard|Premium\",email_domain!=\"redhat.com\"}*1 or max by (_id) (subscription_labels{support=~\"Standard|Premium\",email_domain!=\"redhat.com\"}*5))) * \n  clamp_max(clamp_min((((time() - max by (_id) (cluster_version{type=\"cluster\"})) / 3600 / 24)) / 7 > 0.8, 1), 10) *\n  clamp_max(clamp_min( (max by (_id) (instance:etcd_object_counts:sum > 3200) - 3200)/1000 + 1, 1), 10) * \n  clamp_max(clamp_min( (max by (_id) (cluster:capacity_cpu_cores:sum > 12) - 12)/20 + 1, 1), 10) +\n  (0 * (sum by (_id) (cluster:node_instance_type_count:sum{label_node_role_kubernetes_io=\"master\"}) >= 2))\n) ^ (1/4) )\n)"
    }
   ]
  },
  {
   "title": "Non-GA Clusters (non-RH)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count by (_id) (\n  topk by (_id) (1,cluster_version{type=\"current\",version!~\"4\\\\.\\\\d+\\\\.\\\\d+|4\\\\.1\\\\.0-rc.+\"} + \n  on (_id) group_left (email_domain,support) (0 * max by (_id,email_domain,support) (subscription_labels{email_domain!~\"redhat.com\"})))\n))"
    }
   ]
  },
  {
   "title": "Clusters per domain (non-RH)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 6, "x": 11, "y": 9 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sort_desc(count by (email_domain) (max by (_id) (cluster:capacity_cpu_cores:sum) + on (_id) group_left (email_domain,support) (0 * max by (_id,email_domain,support) (subscription_labels{email_domain!~\"redhat.com\"}))))",
     "legendFormat": "{{email_domain}}"
    }
   ]
  },
  {
   "title": "Cores (non-RH)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum((max by (_id) (cluster:capacity_cpu_cores:sum)) + on (_id) group_left(support,email_domain) (0 * max by (_id,support,email_domain) (subscription_labels{email_domain!~\"redhat.com\"})))"
    }
   ]
  },
  {
   "title": "Subscribed Cores (non-RH)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum((max by (_id) (cluster:capacity_cpu_cores:sum)) + on (_id) group_left(support,email_domain) (0 * max by (_id,support,email_domain) (subscription_labels{support=~\"Premium|Standard\",email_domain!~\"redhat.com\"})))"
    }
   ]
  },
  {
   "title": "Cores by Subscription (non-RH)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 12 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (support) ((max by (_id) (cluster:capacity_cpu_cores:sum)) + on (_id) group_left(support,email_domain) (0 * max by (_id,support,email_domain) (subscription_labels{support!~\"\",email_domain!~\"redhat.com\"})))",
     "legendFormat": "{{support}}"
    }
   ]
  },
  {
   "title": "Cores per domain (non-RH)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 12, "w": 7, "x": 17, "y": 18 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sort_desc(sum by (email_domain) (max by (_id) (cluster:capacity_cpu_cores:sum) + on (_id) group_left (email_domain,support) (0 * max by (_id,email_domain,support) (subscription_labels{email_domain!~\"redhat.com\"}))))",
     "legendFormat": "{{email_domain}}"
    }
   ]
  },
  {
   "title": "Clusters per domain (2w, non-RH)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 6, "x": 11, "y": 19 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sort_desc(topk(100,count by (email_domain) (count by (_id,email_domain) ((max_over_time(cluster_version{type=\"current\"}[14d])) + on (_id) group_left(email_domain) (0 * max by (_id,support,email_domain) (subscription_labels{email_domain!~\"redhat.com\"}))))))",
     "legendFormat": "{{email_domain}}"
    }
   ]
  }
 ]
}