{
 "title": "PRE - Production Cluster Version Upgrades",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "version", "query": "prometheus" },
   { "name": "previous_version", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Clusters that reported upgrade errors over 7 days",
   "type": "table",
   "gridPos": { "h": 24, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sort_desc((sum_over_time(sum by (_id,version,from_version) (max by (_id,version,from_version) (cluster_version{type=\"failure\",version=~\"$version\\\\.\\\\d+($|-rc.\\\\d+)\",from_version=~\"$previous_version\\\\..*\"} * 0 + 1))[7d:5m]) > 1) \n+ on (_id) group_left(email_domain) topk by (_id) (1, 0 * max_over_time(subscription_labels{email_domain!~\"redhat.com|(^|.*\\\\.)ibm.com\"}[7d]))) * (5 * 60)"
    }
   ]
  },
  {
   "title": "Upgrades that failed more than 15m over 7 days",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 0 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count by (_id) (count_over_time(cluster_version{type=\"failure\",version=~\"$version\\\\.\\\\d+($|-rc.\\\\d+)\",from_version=~\"$previous_version\\\\..*\"}[7d:5m]) > 3) * (5 * 60)) / count(count by (_id) (max_over_time(cluster_version{type=\"updating\",version=~\"$version\\\\.\\\\d+($|-rc.\\\\d+)\",from_version=~\"$previous_version\\\\..*\"}[7d])))"
    }
   ]
  },
  {
   "title": "From",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 5, "x": 14, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count by (from_version) (topk by (_id) (1, (max_over_time(cluster_version{type=\"updating\",version=~\"4.2.0($|-rc.\\\\d+)\",from_version=~\"4\\\\.1\\\\..*\"}[7d]))))",
     "legendFormat": "{{from_version}}"
    }
   ]
  },
  {
   "title": "To",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count by (version) (topk by (_id) (1, (max_over_time(cluster_version{type=\"updating\",version=~\"4.2.0($|-rc.\\\\d+)\",from_version=~\"4\\\\.1\\\\..*\"}[7d]))))",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Upgraded in last 7 days",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count by (_id) (max_over_time(cluster_version{type=\"updating\",version=~\"$version\\\\.\\\\d+($|-rc.\\\\d+)\",from_version=~\"$previous_version\\\\..*\"}[7d])))"
    }
   ]
  },
  {
   "title": "Last $version release",
   "type": "singlestat",
   "description": "How old the latest code is",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 6 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - topk(1, cluster_version{type=\"current\",version=~\"$version\\\\.\\\\d+($|-rc.\\\\d+)\"})"
    }
   ]
  },
  {
   "title": "Last $previous_version release",
   "type": "singlestat",
   "description": "How old the latest code is",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 9 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - topk(1, cluster_version{type=\"current\",version=~\"$previous_version\\\\.\\\\d+($|-rc.\\\\d+)\"})"
    }
   ]
  },
  {
   "title": "Edges",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 10 },
   "targets": [
    {
     "expr": "count by (from_version,version) (topk by (_id) (1, (max_over_time(cluster_version{type=\"updating\",version=~\"4.2.0($|-rc.\\\\d+)\",from_version=~\"4\\\\.1\\\\..*\"}[7d]))))"
    }
   ]
  },
  {
   "title": "Channel Preference",
   "type": "table",
   "gridPos": { "h": 12, "w": 3, "x": 11, "y": 12 },
   "targets": [
    {
     "expr": "count by (channel) (topk by (_id) (1, cluster_version_available_updates))"
    }
   ]
  },
  {
   "title": "Failed Edges",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 17 },
   "targets": [
    {
     "expr": "count by (from_version,version) (topk by (_id) (1, (max_over_time(cluster_version{type=\"failure\",version=~\"4.2.0($|-rc.\\\\d+)\",from_version=~\"4\\\\.1\\\\..*\"}[7d]))))"
    }
   ]
  }
 ]
}