{
 "title": "PRE - Production Cluster by ID",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "_id", "label": "Cluster ID", "query": "cluster_version" },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Cloud Provider Type",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "cluster_infrastructure_provider{_id=\"$_id\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Install Type",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "label_replace(label_replace(cluster_installer{_id=\"$_id\"}, \"type\", \"UPI\", \"type\", \"\"), \"type\", \"IPI\", \"type\", \"openshift-install\")",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Interest Score",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(\n  (max by (_id) (absent(subscription_labels{_id=\"$_id\",support=~\"Standard|Premium\",email_domain!=\"redhat.com\"}) or max by (_id) (subscription_labels{_id=\"$_id\",support=~\"Standard|Premium\",email_domain!=\"redhat.com\"}*5))) * \n  clamp_max(clamp_min((((time() - max by (_id) (cluster_version{_id=\"$_id\",type=\"cluster\"})) / 3600 / 24)) / 7, 1), 10) *\n  clamp_max(clamp_min( (max by (_id) (instance:etcd_object_counts:sum{_id=\"$_id\"}) - 3200)/1000 + 1, 1), 10) * \n  clamp_max(clamp_min( (max by (_id) (cluster:capacity_cpu_cores:sum{_id=\"$_id\"}) - 12)/20 + 1, 1), 10)\n) ^ (1/4)\n"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "singlestat",
   "description": "The percentage of the current range (upper right) the cluster has been reported as available - no CVO failure conditions.",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "1 - (sum_over_time(max by (_id) ((cluster_version{type=\"failure\",_id=\"$_id\"} * 0 + 1) or (cluster_version{type=\"current\",_id=\"$_id\"}*0))[${__range_s}s:10m])) / (sum_over_time(max by (_id) (cluster_version{type=\"current\",_id=\"$_id\"} * 0 + 1)[${__range_s}s:10m]))"
    }
   ]
  },
  {
   "title": "Version",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 0 },
   "format": "s",
   "valueName": "name",
   "targets": [
    {
     "expr": "topk(1,cluster_version{_id=\"$_id\",type=\"completed\",version!=\"\"})",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Updating To",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 0 },
   "format": "s",
   "valueName": "name",
   "targets": [
    {
     "expr": "topk(1, cluster_version{_id=\"$_id\",type=\"updating\"})",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Degraded Operators",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (name,condition,reason) (cluster_operator_conditions{_id=\"$_id\",condition=\"Degraded\"} == 1 or cluster_operator_conditions{_id=\"$_id\",condition=\"Available\"} == 0)"
    }
   ]
  },
  {
   "title": "E-mail Domain",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "topk(1, subscription_labels{_id=\"$_id\"})",
     "legendFormat": "{{email_domain}}"
    }
   ]
  },
  {
   "title": "Support",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "topk(1, subscription_labels{_id=\"$_id\",support!=\"\"})",
     "legendFormat": "{{support}}"
    }
   ]
  },
  {
   "title": "Cores",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cluster:capacity_cpu_cores:sum{_id='$_id'})"
    }
   ]
  },
  {
   "title": "Availability (7d)",
   "type": "singlestat",
   "description": "The percentage of the last 7 days the cluster has been reported as available - no CVO failure conditions.",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 4 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "1 - (sum_over_time(max by (_id) ((cluster_version{type=\"failure\",_id=\"$_id\"} * 0 + 1) or (cluster_version{type=\"current\",_id=\"$_id\"}*0))[7d:10m])) / (sum_over_time(max by (_id) (cluster_version{type=\"current\",_id=\"$_id\"} * 0 + 1)[7d:10m]))"
    }
   ]
  },
  {
   "title": "Failing For",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 4 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max by (_id) (time() - cluster_version{_id=\"$_id\",type=\"failure\"} > 0)"
    }
   ]
  },
  {
   "title": "Updating For",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 4 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "topk(1, time() - cluster_version{_id=\"$_id\",type=\"updating\"} > 0)"
    }
   ]
  },
  {
   "title": "RH Org ID",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "topk(1,subscription_labels{_id=\"$_id\"})",
     "legendFormat": "{{external_organization}}"
    }
   ]
  },
  {
   "title": "EBS Account",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 8 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "topk(1,subscription_labels{_id=\"$_id\"})",
     "legendFormat": "{{ebs_account}}"
    }
   ]
  },
  {
   "title": "Etcd objects",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max by (_id) (instance:etcd_object_counts:sum{_id=\"$_id\"})"
    }
   ]
  },
  {
   "title": "Etcd Object Delta",
   "type": "singlestat",
   "description": "Net change over time range",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 8 },
   "format": "none",
   "valueName": "diff",
   "targets": [
    {
     "expr": "max without (monitor,job,endpoint,instance,namespace,pod,service,prometheus,prometheus_replica,replica) (instance:etcd_object_counts:sum{_id=\"$_id\"})"
    }
   ]
  },
  {
   "title": "Operators by version",
   "type": "table",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 8 },
   "targets": [
    {
     "expr": "count by (version) (cluster_operator_up{_id=\"$_id\"})"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "graph",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "count by (alertname,alertstate) (alerts{_id=\"$_id\",alertname!=\"Watchdog\",alertstate=\"firing\"})",
     "legendFormat": "{{alertname}}"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cluster:node_instance_type_count:sum{_id=\"$_id\"})"
    }
   ]
  },
  {
   "title": "Down Nodes",
   "type": "graph",
   "description": "Nodes that are reporting NotReady (are not able to contact the API server to perform node heartbeats).",
   "gridPos": { "h": 5, "w": 6, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (node,instance) (alerts{_id=\"$_id\",alertstate=\"firing\",alertname=\"KubeNodeNotReady\"})"
    }
   ]
  },
  {
   "title": "Age",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 12 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "topk(1, time() - cluster_version{_id=\"$_id\",type=\"cluster\"})"
    }
   ]
  },
  {
   "title": "Since last completed update",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 12 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "topk(1,time() - cluster_version{_id=\"$_id\",type=\"completed\"} < 1560000000)"
    }
   ]
  },
  {
   "title": "Accessing Insights Data",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "topk(1,subscription_labels{_id=\"$_id\"})",
     "legendFormat": "To see the insights data for this cluster, configure <a target=\"_blank\" href=\"https://mojo.redhat.com/docs/DOC-1206124\"><u>supportshell</u></a> and run<pre>ssh supportshell.prod.useraccess-us-west-2.redhat.com \\<br/> -t \"cd /ocp/{{external_organization}}/$_id/; bash --login\"</pre>"
    }
   ]
  },
  {
   "title": "Masters",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cluster:node_instance_type_count:sum{label_node_role_kubernetes_io=\"master\",_id=\"$_id\"})"
    }
   ]
  },
  {
   "title": "API Req/S",
   "type": "singlestat",
   "description": "Requests per second to the API",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(max without (monitor,job,endpoint,instance,namespace,pod,service,prometheus,prometheus_replica,replica) (code:apiserver_request_count:rate:sum{_id=\"$_id\"}))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "API Error Rate",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 16 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "max by (code,_id) (code:apiserver_request_count:rate:sum{_id=\"$_id\",code=~\"[4-5]\\\\d+\"})> 0",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Architecture",
   "type": "singlestat",
   "description": "Dominant cluster architecture",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 20 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "max by (label_kubernetes_io_arch) (node_role_os_version_machine:cpu_capacity_cores:sum{_id=\"$_id\"})",
     "legendFormat": "{{label_kubernetes_io_arch}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "max by (_id) (cluster:cpu_usage_cores:sum{_id=\"$_id\"}) / on (_id) max by (_id) (sum by (_id) (cluster:capacity_cpu_cores:sum{_id=\"$_id\"}))",
     "legendFormat": "Cluster"
    },
    {
     "expr": "max by (_id) (openshift:cpu_usage_cores:sum{_id=\"$_id\"}) / on (_id) max by (_id) (sum by (_id) (cluster:capacity_cpu_cores:sum{_id=\"$_id\"}))",
     "legendFormat": "Infrastructure"
    },
    {
     "expr": "max by (_id) (workload:cpu_usage_cores:sum{_id=\"$_id\"}) / on (_id) max by (_id) (sum by (_id) (cluster:capacity_cpu_cores:sum{_id=\"$_id\"}))",
     "legendFormat": "Workload"
    }
   ]
  },
  {
   "title": "Down Services",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count without (_id,instance,monitor,endpoint,prometheus,prometheus_replica,replica) (up{_id=\"$_id\"} == 0)"
    }
   ]
  },
  {
   "title": "Non-RHCOS Cores",
   "type": "singlestat",
   "description": "Cores from nodes that are not RHCOS.",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 23 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(max without (monitor,job,endpoint,instance,namespace,pod,service,prometheus,prometheus_replica,replica) (node_role_os_version_machine:cpu_capacity_cores:sum{label_node_openshift_io_os_id!=\"rhcos\",_id=\"$_id\"}))"
    }
   ]
  }
 ]
}