{
 "title": "PRE - Production Cluster Health",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" },
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "source",
    "query": "+ 0, + on (_id) group_left(_blah) (topk by (_id) (1\\, cluster_version{version=~\"4\\\\.\\\\d+\\\\.\\\\d+\"})), + on (_id) group_left(_blah) (topk by (_id) (1\\, subscription_labels{email_domain!=\"redhat.com\"})), + on (_id) group_left(_blah) (topk by (_id) (1\\, subscription_labels{support=~\"Premium|Standard\"\\,email_domain!=\"redhat.com\"})),  + on (_id) group_left(_blah) (topk by (_id) (1\\, cluster_version{version=~\"4\\\\.\\\\d+\\\\.\\\\d+\"})) + on (_id) group_left(_blah) (topk by (_id) (1\\, subscription_labels{email_domain!=\"redhat.com\"}))"
   }
  ]
 },
 "panels": [
  {
   "title": "Clusters (updating)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count by (_id) (cluster_version{type=\"updating\"} $source ))"
    }
   ]
  },
  {
   "title": "Clusters (updating < 3h)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count by (_id) ((time() - cluster_version{type=\"updating\"} < 60 * 60 * 3) $source))"
    }
   ]
  },
  {
   "title": "Clusters (updating > 3h)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count by (_id) ((time() - cluster_version{type=\"updating\"} > 60 * 60 * 3) $source ))"
    }
   ]
  },
  {
   "title": "Clusters Failing (4.y.z,>10m)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (version) (((time() - cluster_version{type=\"failure\"}) > 10 * 60) $source )"
    }
   ]
  },
  {
   "title": "Clusters (all)",
   "type": "singlestat",
   "description": "Count of all unique clusters reporting telemetry status.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count by (_id) (cluster_version{type=\"current\"} $source))"
    }
   ]
  },
  {
   "title": "Clusters older than 24h",
   "type": "singlestat",
   "description": "All clusters older than 24h, which generally excludes them from CI or automation launched clusters",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count((time() - cluster_version{type=\"cluster\"} > 24*60*60) $source )"
    }
   ]
  },
  {
   "title": "Degraded Clusters (all)",
   "type": "singlestat",
   "description": "Count of clusters that have installed an official 4.y.z version, vs CI or nightly builds.",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count (max by (_id) ((cluster_operator_conditions{condition=\"Degraded\"} == 1) $source))"
    }
   ]
  },
  {
   "title": "Infrastructure Types",
   "type": "grafana-piechart-panel",
   "description": "Clusters grouped by their infrastructure provider.",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count by(type) (cluster_infrastructure_provider $source)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Install Types",
   "type": "grafana-piechart-panel",
   "description": "Cluster installations grouped by their type. Clusters created before 4.1.10 are unable to accurately report their type, so they are unknown.",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count by(type) (label_replace(label_replace(cluster_installer and on(_id) cluster_version{type=\"initial\", version!~\"4\\\\.1\\\\.[0-9]-.*\"} $source, \"type\", \"UPI\", \"type\", \"\"), \"type\", \"IPI\", \"type\", \"openshift-install\") or on(_id) label_replace(cluster_installer and on(_id) cluster_version{type=\"initial\", version=~\"4\\\\.1\\\\.[0-9]-.*\"} $source, \"type\", \"Unknown\", \"type\", \".*\"))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Degraded Cluster Operators",
   "type": "graph",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (name,reason) ((cluster_operator_conditions{condition=\"Degraded\"} == 1) $source)",
     "legendFormat": "{{name}}: {{reason}}"
    }
   ]
  },
  {
   "title": "In-progress Updates (<3h)",
   "type": "table",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "max by (_id,from_version,version) (time() - max by (_id,from_version,version) (cluster_version{type=\"updating\"} $source)) < 3 * 60 * 60"
    }
   ]
  },
  {
   "title": "Degraded Operators",
   "type": "table",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 12 },
   "targets": [
    {
     "expr": "topk by (_id) (1, 0 * cluster_version{type=\"current\"}) $source +\non (_id) group_right(version) count by (_id) (cluster_operator_conditions{condition=\"Degraded\"} == 1 or cluster_operator_conditions{condition=\"Available\"} == 0)"
    }
   ]
  },
  {
   "title": "Stuck Updates (>3h)",
   "type": "table",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "max by (_id,from_version,version) ((time() - cluster_version{type=\"updating\"}) $source) >= 3 * 60 * 60"
    }
   ]
  },
  {
   "title": "Clusters Failing",
   "type": "table",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "max by (_id,version) ((time() - cluster_version{type=\"failure\"}) $source) > 3 * 60 * 60"
    }
   ]
  },
  {
   "title": "High API Error Rates",
   "type": "table",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 20 },
   "targets": [
    {
     "expr": "sort_desc(max by (_id,code) (code:apiserver_request_count:rate:sum{code=~\"(4|5)\\\\d\\\\d\"} $source) > 0.5)"
    }
   ]
  },
  {
   "title": "Firing Alerts",
   "type": "table",
   "gridPos": { "h": 11, "w": 15, "x": 9, "y": 28 },
   "targets": [
    {
     "expr": "count by (_id,alertname) (alerts{alertstate=\"firing\",alertname!=\"Watchdog\"} $source)"
    }
   ]
  },
  {
   "title": "In-progress Installs (<3h)",
   "type": "table",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "max by (_id,version) (time() - max by (_id,version) (cluster_version{type=\"updating\"} $source)) < 3 * 60 * 60"
    }
   ]
  },
  {
   "title": "Down Nodes",
   "type": "table",
   "description": "Clusters with nodes that are reporting NotReady (are not contacting the API server to report healthy).",
   "gridPos": { "h": 11, "w": 15, "x": 9, "y": 39 },
   "targets": [
    {
     "expr": "count by (_id) (max by (_id,node,instance) (alerts{alertstate=\"firing\",alertname=\"KubeNodeNotReady\"} $source))"
    }
   ]
  }
 ]
}