{
 "title": "OpenShift Eng / BU Sync",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Platform Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Clusters Installed over 7 days (Now)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count by (_id) (time() - (max_over_time(cluster_version{type=\"cluster\"}[7d])) < (7 * 24 * 60 * 60)))"
    }
   ]
  },
  {
   "title": "Clusters Installed over 7 days (Last Week)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 7, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count by (_id) (time() - (max_over_time(cluster_version{type=\"cluster\"}[7d] offset 7d)) < (14 * 24 * 60 * 60)))"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 8, "x": 14, "y": 1 },
   "content": "General metrics for usage on the platform.  \nIncludes dev/ci, etc\n"
  },
  { "title": "Real-world Cluster Growth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Clusters > 1w (Now)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count by (_id) ((time() - cluster_version{type=\"cluster\"}) > (7 * 24 * 60 * 60)))"
    }
   ]
  },
  {
   "title": "Clusters > 1w (Last Week)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 7, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count by (_id) ((time() - cluster_version{type=\"cluster\"} offset 7d) > (14 * 24 * 60 * 60)))"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 8, "x": 14, "y": 5 },
   "content": "Using clusters > 1w as a proxy for 'real world' clusters.  \nCan include dev/qe/internal.\n"
  },
  {
   "title": "# clusters with > 8 nodes (Now)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count((sum by (_id) (cluster:node_instance_type_count:sum{}) > 8))"
    }
   ]
  },
  {
   "title": "# clusters with > 8 nodes (Last Week)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 7, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count((sum by (_id) (cluster:node_instance_type_count:sum{}) > 8))"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 8, "x": 14, "y": 8 },
   "content": "Using clusters > 8 cores as a proxy for 'real world' clusters.  \nCan include dev/qe/internal.\n"
  },
  { "title": "Trusted Upgrades", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Most upgraded to version last 7 days",
   "type": "singlestat",
   "description": "Should be the version released last week",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "topk(1, count by (version) (changes(cluster_version{type=\"updating\"}[7d])))"
    }
   ]
  },
  {
   "title": "Most upgraded to version last 7 days (Last Week)",
   "type": "singlestat",
   "description": "Should be the version released last week",
   "gridPos": { "h": 3, "w": 7, "x": 7, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "topk(1, count by (version) (changes(cluster_version{type=\"updating\"}[7d] offset 7d)))"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 8, "x": 14, "y": 12 },
   "content": "If customers trust upgrades they will upgrade often.\nThe most-upgraded-to version should be the one released last week."
  },
  { "title": "Quality", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "% of Degraded Clusters (Now)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count by (_id) ((cluster_operator_conditions{condition=\"Degraded\"}) == 1)) / count(max by (_id) (cluster_version{type=\"current\"})) * 100"
    }
   ]
  },
  {
   "title": "% Degraded Clusters (Last week)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 7, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count by (_id) ((cluster_operator_conditions{condition=\"Degraded\"} offset 7d) == 1)) / count(max by (_id) (cluster_version{type=\"current\"} offset 7d)) * 100"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 8, "x": 14, "y": 16 },
   "content": "% of degraded cluster operators per cluster.  \nThe fewer issues, the lower the %.\nNOT SURE  if this is a) # of clusters that are degraded or b) number of operators that are degraded "
  }
 ]
}