{
 "title": "OSD Cluster Overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "OpenShift Cluster Versions",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count without (_id) (count by (majorversion, _id) (label_replace(cluster_version, \"majorversion\", \"$1\", \"version\", \"(\\\\d.\\\\d.\\\\d)(.*)\")))",
     "legendFormat": "{{majorversion}}"
    }
   ]
  },
  {
   "title": "Version Breakdown",
   "type": "graph",
   "gridPos": { "h": 10, "w": 14, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (version) (cluster_version{type=\"current\",version=~\"4\\\\.\\\\d+\\\\.\\\\d+\"})",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Critical Alerts Now ",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sort_desc(count by (alertname)(alerts{severity=\"critical\"}))"
    }
   ]
  },
  {
   "title": "ALL Critical Alerts  - 24H",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 5, "y": 10 },
   "targets": [
    {
     "expr": "sort_desc(sum(sum_over_time(alerts{alertstate=\"firing\", severity = \"critical\"}[24h])) by (alertname))"
    }
   ]
  },
  {
   "title": "ALL Critical Alerts  - 7H",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 11, "y": 10 },
   "targets": [
    {
     "expr": "sort_desc(sum(sum_over_time(alerts{alertstate=\"firing\", severity = \"critical\"}[7h])) by (alertname))"
    }
   ]
  },
  {
   "title": "Non-Critical Alerts Now",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 17, "y": 10 },
   "targets": [
    {
     "expr": "sort_desc(count by (alertname)(alerts{severity!=\"critical\"}))"
    }
   ]
  },
  {
   "title": "Firing Alerts",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "count by (_id,version,alertname) (alerts{alertstate=\"firing\",alertname!=\"Watchdog\"} + on (_id) group_left(version) ( 0 * max by (_id,version) (cluster_version{type=\"current\",version=~\"\\\\d.\\\\d+\\\\.\\\\d+\"} )))"
    }
   ]
  },
  {
   "title": "Clusters Failing (4.y.z)",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 18 },
   "targets": [
    {
     "expr": "max by (_id,version) ((time() - cluster_version{type=\"failure\",version=~\"4\\\\.\\\\d+\\\\.\\\\d+\"})) > 3 * 60 * 60"
    }
   ]
  },
  {
   "title": "Number of Clusters Running per AWS Region",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "count without (_id) (count by (_id, region) (label_replace(label_replace(up{node!=\"\"}, \"region\", \"$2\", \"node\", \"(.*)\\\\.([a-z]{0,2}-?[a-z]{2,3}-[a-z]+-\\\\d)\\\\.(.*)\"), \"region\", \"us-east-1\", \"node\", \"ip-\\\\d+-\\\\d+-\\\\d+-\\\\d+\\\\.ec2\\\\.internal\")))\n"
    }
   ]
  },
  { "title": "Updates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Clusters with Available Updates",
   "type": "table",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "(count by (_id) (cluster_version_available_updates > 0))"
    }
   ]
  },
  {
   "title": "Degraded Clusters",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 35 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count (max by (_id) (cluster_operator_conditions{condition=\"Degraded\"} == 1))"
    }
   ]
  },
  {
   "title": "Updating Clusters (< 3h)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 35 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count by (_id) (time() - cluster_version{type=\"updating\"} < 60 * 60 * 3))"
    }
   ]
  },
  {
   "title": "In-progress Updates (4.y.z, <3h)",
   "type": "table",
   "gridPos": { "h": 5, "w": 9, "x": 13, "y": 35 },
   "targets": [
    {
     "expr": "max by (_id,version) (time() - max by (_id,version) (cluster_version{type=\"updating\",version=~\"4\\\\.\\\\d+\\\\.\\\\d+\"})) < 3 * 60 * 60"
    }
   ]
  },
  {
   "title": "Updating Clusters",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 40 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count by (_id) (cluster_version{type=\"updating\"}))"
    }
   ]
  },
  {
   "title": "Total Clusters",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 40 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count by (_id) (cluster_version{type=\"current\"}))"
    }
   ]
  },
  {
   "title": "Stuck Updates (4.y.z, >3h)",
   "type": "table",
   "gridPos": { "h": 5, "w": 9, "x": 13, "y": 40 },
   "targets": [
    {
     "expr": "max by (_id,version) (time() - cluster_version{type=\"updating\",version=~\"4\\\\.\\\\d+\\\\.\\\\d+\"}) >= 3 * 60 * 60"
    }
   ]
  }
 ]
}