{
 "title": "PRE - Production Cluster Operators",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "name",
    "label": "Operator Name",
    "query": "label_values(cluster_operator_conditions, name)"
   },
   { "name": "datasource", "query": "prometheus" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "By Condition and Reason",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count_values by (reason, condition) (\"value\",(cluster_operator_conditions{name=\"$name\"}))"
    }
   ]
  },
  {
   "title": "Degraded",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "count by (_id,condition,reason) (cluster_operator_conditions{name=\"$name\",condition=\"Degraded\"} == 1)"
    }
   ]
  },
  {
   "title": "Operator versions",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count by (version) (cluster_operator_up{name=\"$name\",version!=\"\"})",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Progressing",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "count by (_id,condition,reason) (cluster_operator_conditions{name=\"$name\",condition=\"Progressing\"} == 1)"
    }
   ]
  },
  {
   "title": "(Not) Available",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "count by (_id,condition,reason) (cluster_operator_conditions{name=\"$name\",condition=\"Available\"} == 0)"
    }
   ]
  }
 ]
}