FROM centos:7

RUN yum install -y epel-release && yum install -y python-pip && yum clean all

COPY requirements.txt /
RUN pip install -r /requirements.txt

ENV APP_ROOT /validator

COPY validator ${APP_ROOT}

WORKDIR ${APP_ROOT}
ENTRYPOINT [ "./validate.py" ]
