FROM centos:7

# enable scl with nodejs8
RUN yum install centos-release-scl-rh rh-nodejs8 -y && yum install rh-nodejs8 -y

# Set PATH, because "scl enable" does not have any effects to "docker build"
ENV PATH $PATH:/opt/rh/rh-nodejs8/root/usr/bin

ADD graphql-server /service/app-sre
ADD data /service/app-sre

WORKDIR /service/app-sre

RUN npm install

EXPOSE 4000

CMD ["npm", "start"]
