{
 "title": "Cincinnati",
 "time": { "from": "now/M", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(kube_pod_info, cluster)"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\"}, namespace)"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\", namespace=\"$namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  { "title": "Service Level Indicators (SLI)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Graph-builder availability",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(up{job=\"cincinnati-graph-builder\", namespace=\"$namespace\", pod=~\"$pod\"}) by (pod, job)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Policy-engine availability",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(up{job=\"cincinnati-policy-engine\", namespace=\"$namespace\", pod=~\"$pod\"}) by (pod, job)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Graph-builder cached graph staleness",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (time()-(cincinnati_gb_graph_last_successful_refresh_timestamp{pod=~\"$pod\"} > 0))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Policy-engine response errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kind) (rate(cincinnati_pe_v1_graph_response_errors_total{namespace=\"$namespace\", pod=~\"$pod\"}[5m]))",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Policy-engine upstream errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cincinnati_pe_http_upstream_errors_total{namespace=\"$namespace\", pod=~\"$pod\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Policy-engine latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(cincinnati_pe_v1_graph_serve_duration_seconds_bucket{job=\"cincinnati-policy-engine\",namespace=\"$namespace\",pod=~\"$pod\"}[1m])) by (pod, le))",
     "legendFormat": "p99 - {{pod}}"
    }
   ]
  },
  { "title": "Graph-builder troubleshooting", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Upstream Scrape Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cincinnati_gb_graph_upstream_scrapes_total{job=\"cincinnati-graph-builder\",namespace=\"$namespace\",pod=~\"$pod\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Upstream Scrape Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cincinnati_gb_graph_upstream_errors_total{job=\"cincinnati-graph-builder\",namespace=\"$namespace\",pod=~\"$pod\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{pod_name=~\"$pod\", namespace=\"$namespace\", container_name=\"cincinnati-graph-builder\"}) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  { "title": "Policy-engine troubleshooting", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", pod_name=~\"$pod\", container_name=\"cincinnati-policy-engine\"}) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  }
 ]
}