{
 "title": "UHC Gateway",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "namespace", "query": "uhc-stage,uhc-production" }
  ]
 },
 "panels": [
  {
   "title": "Requests per second",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apache_accesses_total{job=\"gateway-server-metrics\",namespace=\"$namespace\"}[5m]))"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(apache_connections{job=\"gateway-server-metrics\",namespace=\"$namespace\",state=\"total\"}[5m]))"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(pod_name:container_memory_usage_bytes:sum{cluster=\"app-sre\",namespace=\"${namespace}\",pod_name=~\"^gateway-server-.*$\"})\n"
    }
   ]
  }
 ]
}