{
 "title": "UHC Account Manager",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "namespace", "query": "uhc-staging,uhc-production" },
   {
    "name": "rdsDB",
    "query": "dimension_values(us-east-1, AWS/RDS, DatabaseConnections, DBInstanceIdentifier)"
   },
   { "name": "aws_datasource", "query": "cloudwatch" }
  ]
 },
 "panels": [
  {
   "title": "Database connections",
   "type": "graph",
   "description": "Select rdsDB name above",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$rdsDB" },
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "region": "us-east-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Total Request Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(api_inbound_request_count{namespace=\"$namespace\"}[10m]))",
     "legendFormat": "Inbound"
    },
    {
     "expr": "sum(rate(api_outbound_request_count{namespace=\"$namespace\"}[10m]))",
     "legendFormat": "Outbound"
    }
   ]
  },
  {
   "title": "Inbound Request: Codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(api_inbound_request_count{namespace=\"$namespace\"}[10m])) by (code)",
     "legendFormat": "Code: {{code}}"
    }
   ]
  },
  {
   "title": "Outbound Request: Codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(api_outbound_request_count{namespace=\"$namespace\"}[10m])) by (code)",
     "legendFormat": "Code: {{code}}"
    }
   ]
  },
  {
   "title": "Request duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(api_inbound_request_duration_sum{namespace=\"$namespace\"}[10m])) / sum(rate(api_inbound_request_duration_count{namespace=\"$namespace\"}[10m]))",
     "legendFormat": "Inbound"
    },
    {
     "expr": "sum(rate(api_outbound_request_duration_sum{namespace=\"$namespace\"}[10m])) / sum(rate(api_outbound_request_duration_count{namespace=\"$namespace\"}[10m]))",
     "legendFormat": "Outbound"
    }
   ]
  },
  {
   "title": "P90: Inbound Request duration",
   "type": "heatmap",
   "description": "90th Percentile Inbound request Duration",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(api_inbound_request_duration_bucket{namespace=\"$namespace\"}[5m])) by (le)) ",
     "legendFormat": "Inbound"
    }
   ]
  },
  {
   "title": "P90: Outbound Request duration",
   "type": "heatmap",
   "description": "90th Percentile Outbound request Duration",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(api_outbound_request_duration_bucket{namespace=\"$namespace\"}[5m])) by (le))",
     "legendFormat": "Inbound"
    }
   ]
  }
 ]
}