{
 "title": "AWS Account Operator",
 "time": { "from": "now-2w", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "environment",
    "label": "Hive Instance",
    "query": "hive-aws-account-operator-stage,hive-aws-account-operator-production,hive-aws-account-operator-integration"
   }
  ]
 },
 "panels": [
  {
   "title": "Number of Account CRs Failed ",
   "type": "singlestat",
   "description": "The number of account CRs that are failed",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "aws_account_operator_total_accounts_crs_failed{job=\"$environment\"}"
    }
   ]
  },
  {
   "title": "Total Number of AWS Accounts Created",
   "type": "singlestat",
   "description": "The number of accounts created in AWS Org",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "aws_account_operator_total_aws_accounts{job=\"$environment\"}"
    }
   ]
  },
  {
   "title": "Total Number of AWS Accounts Created",
   "type": "graph",
   "description": "Time series graph of how many AWS accounts have been created \n",
   "gridPos": { "h": 9, "w": 14, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "aws_account_operator_total_aws_accounts{job=\"$environment\"}",
     "legendFormat": "Total AWS Accounts"
    }
   ]
  },
  {
   "title": "Number of Unclaimed CRs",
   "type": "singlestat",
   "description": "The number of account CRs that are unclaimed",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "aws_account_operator_total_accounts_crs_unclaimed{job=\"$environment\"}"
    }
   ]
  },
  {
   "title": "Accounts Pending Verification ",
   "type": "singlestat",
   "description": "The number of accounts waiting for enterprise support and EC2 limit increases in AWS",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "aws_account_operator_total_aws_account_pending_verification{job=\"$environment\"}"
    }
   ]
  },
  {
   "title": "Pending Verification with respect to Unclaimed Accounts",
   "type": "graph",
   "description": "Time series graph of AWS accounts pending verification, account CRs unclaimed, and ready CRs ",
   "gridPos": { "h": 9, "w": 14, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Number of Accounts" }
   ],
   "targets": [
    {
     "expr": "aws_account_operator_total_aws_account_pending_verification{job=\"$environment\"}",
     "legendFormat": "Pending Verification"
    },
    {
     "expr": "aws_account_operator_total_accounts_crs_unclaimed{job=\"$environment\"}",
     "legendFormat": "CRs Unclaimed"
    },
    {
     "expr": "aws_account_operator_total_aws_accounts_crs_ready{job=\"$environment\"}",
     "legendFormat": "CRs Ready"
    }
   ]
  },
  {
   "title": "Difference Between Pool Size and Unclaimed CRs",
   "type": "singlestat",
   "description": "The difference between the pool size and the number of unclaimed account CRs. If this number > 0, it indicates an issue. ",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "aws_account_operator_pool_size_vs_unclaimed{job=\"$environment\"}"
    }
   ]
  },
  {
   "title": "Number of Ready Account CRs",
   "type": "singlestat",
   "description": "Number of ready account CRs",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "aws_account_operator_total_aws_accounts_crs_ready{job=\"$environment\"}"
    }
   ]
  },
  {
   "title": "Number of Available Reused AWS Accounts ",
   "type": "graph",
   "description": "Time series graph of the number of reused accounts available for claiming",
   "gridPos": { "h": 10, "w": 14, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Reused Accounts Available " }
   ],
   "targets": [
    {
     "expr": "aws_account_operator_total_aws_account_reused_available{job=\"$environment\"}",
     "legendFormat": "LegalID = {{LegalID}}"
    }
   ]
  },
  {
   "title": "Number of Reused Accounts Available ",
   "type": "singlestat",
   "description": "The number of reused accounts available for claiming",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(aws_account_operator_total_aws_account_reused_available{job=\"$environment\"})"
    }
   ]
  },
  {
   "title": "Number of Reused Accounts  Failed ",
   "type": "singlestat",
   "description": "The number of accounts that failed during account reuse",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "aws_account_operator_total_aws_account_reused_failed{job=\"$environment\"}"
    }
   ]
  }
 ]
}