{
 "title": "Hive",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": "label_values(hive_cluster_deployments, job)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Clusters",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum without(instance, __name__, job, age_lt)(hive_cluster_deployments{age_lt=\"+Inf\",job=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Cluster Activity Last 24h",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "sum without(Time,instance,job)(increase(hive_cluster_deployments_created_total{job=\"$instance\"}[24h])) ",
     "legendFormat": "Created"
    },
    {
     "expr": "sum without(Time,instance,job)(increase(hive_cluster_deployments_installed_total{job=\"$instance\"}[24h])) ",
     "legendFormat": "Installed"
    },
    {
     "expr": "sum without(Time,instance,job)(increase(hive_cluster_deployments_deleted_total{job=\"$instance\"}[24h])) ",
     "legendFormat": "Deleted"
    }
   ]
  },
  {
   "title": "Clusters Provisioning Over 2h",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum without(instance,job)((hive_cluster_deployment_provision_underway_seconds{job=\"$instance\"} > 7200) / 60)"
    }
   ]
  },
  {
   "title": "Clusters Deprovisioning Over 2h",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 6 },
   "targets": [
    {
     "expr": "sum without(instance,job)((hive_cluster_deployment_deprovision_underway_seconds{job=\"$instance\"} > 7200) / 60)"
    }
   ]
  },
  {
   "title": "Total Clusters",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hive_cluster_deployments{age_lt=\"+Inf\",job=\"$instance\"}",
     "legendFormat": "{{cluster_type}} "
    },
    {}
   ]
  },
  {
   "title": "Running Install Jobs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hive_install_jobs{job=\"$instance\",state!=\"succeeded\"}",
     "legendFormat": "{{cluster_type}} {{state}}"
    }
   ]
  },
  {
   "title": "Install Job Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(hive_cluster_deployment_install_job_duration_seconds_sum{job=\"$instance\"}[48h]) / rate(hive_cluster_deployment_install_job_duration_seconds_count{job=\"$instance\"}[48h])",
     "legendFormat": "Duration"
    }
   ]
  },
  {
   "title": "DNS + Install Delay",
   "type": "graph",
   "description": "Delay due to creating and waiting for resolving DNS, and total wait for the install to launch.",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(hive_cluster_deployment_install_job_delay_seconds_sum{job=\"$instance\"}[6h]) / rate(hive_cluster_deployment_install_job_delay_seconds_count{job=\"$instance\"}[6h])",
     "legendFormat": "Total Install Delay"
    },
    {
     "expr": "rate(hive_cluster_deployment_dns_delay_seconds_sum{job=\"$instance\"}[6h]) / rate(hive_cluster_deployment_dns_delay_seconds_count{job=\"$instance\"}[6h])",
     "legendFormat": "DNS Delay"
    }
   ]
  },
  {
   "title": "Uninstalled Clusters Created in Last 48h",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 23 },
   "targets": [
    {
     "expr": "sum without(instance,job)(hive_cluster_deployments_uninstalled{job=\"$instance\",age_lt=\"48h\"}) > 0"
    }
   ]
  },
  {
   "title": "Avg Install Restarts",
   "type": "graph",
   "description": "Average number of restarts across all install jobs.",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(hive_cluster_deployment_completed_install_restart_sum{job=\"$instance\"}[12h]) / rate(hive_cluster_deployment_completed_install_restart_count{job=\"$instance\"}[12h])",
     "legendFormat": "{{cluster_type}}"
    }
   ]
  },
  {
   "title": "90% Time to Install Job",
   "type": "graph",
   "description": "Time to install job for 90% of clusters installed over last 48 hours.",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(hive_cluster_deployment_install_job_delay_seconds_bucket{job=\"$instance\"}[12h]))"
    }
   ]
  },
  {
   "title": "Cluster Conditions",
   "type": "graph",
   "description": "Gauge on clusters with conditions set to true.",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hive_cluster_deployments_conditions{job=\"$instance\",cluster_type=\"managed\",age_lt=\"+Inf\"} > 0",
     "legendFormat": "{{ condition }}"
    }
   ]
  },
  {
   "title": "Install Job Failure Rate",
   "type": "graph",
   "description": "Rate of install job failures for known reasons. (as determined by parsing install log summaries)",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(hive_install_errors{job=\"$instance\"}[6h])",
     "legendFormat": "{{cluster_type}} {{reason}}"
    }
   ]
  },
  {
   "title": "Controller Reconcile Rate",
   "type": "graph",
   "description": "Rate of success/error from the cluster deployment controller reconcile loop.",
   "gridPos": { "h": 14, "w": 9, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(controller_runtime_reconcile_total{result=~\"success|error\",job=\"$instance\"}[2h])",
     "legendFormat": "{{controller}} {{result}}"
    }
   ]
  },
  {
   "title": "Controller Reconcile Time",
   "type": "graph",
   "description": "Currently includes time spent in the queue if blocking.",
   "gridPos": { "h": 14, "w": 9, "x": 9, "y": 46 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(hive_controller_reconcile_seconds_sum{job=\"$instance\"}[2h]) / rate(hive_controller_reconcile_seconds_count{job=\"$instance\"}[2h])",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Local Kube Client Requests",
   "type": "graph",
   "description": "Rate of requests to the Kube API via clients.",
   "gridPos": { "h": 14, "w": 9, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(resource,method,response,status)(rate(hive_kube_client_requests_total{job=\"$instance\",remote=\"false\"}[2h]))",
     "legendFormat": "{{ controller }}"
    }
   ]
  },
  {
   "title": "Remote Kube Client Requests",
   "type": "graph",
   "description": "Rate of requests to the Kube API via clients.",
   "gridPos": { "h": 14, "w": 9, "x": 9, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(resource,method,response,status)(rate(hive_kube_client_requests_total{job=\"$instance\",remote=\"true\"}[2h]))",
     "legendFormat": "{{controller}} "
    }
   ]
  },
  { "title": "Building blocks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Playground usage",
   "type": "text",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 75 },
   "content": "# How to bulid a dashboard using this Playground\n\n## Getting started\n\nBelow you wil find all available panels to be used for a dashboard.\n\nTo start, select a panel to use, and duplicate it (`Panel options > More > Duplicate`).\n\nDrag it to the top of the screen (above the Building blocks Row) and change the panel title, metrics, and any other settings as required.\n\n\n## Saving your dashboard\n\n\nSince all dashboards are managed through source control, saving dashboards is not enabled.\n\nTo save your new dashboard, export it to a JSON file (through the options on the top right of the screen) and save it locally.\n\n\n## Adding your dashboard\n\nTo add your dashboard, follow these steps:\n\n1. Create a Merge Request to the following git repository:\nhttps://gitlab.cee.redhat.com/service/app-sre-observability\n\n2. Add the JSON content to a `ConfigMap` resource:\n\n```\nkind: ConfigMap\napiVersion: v1\nmetadata:\n  name: grafana-dashboard-my-dashboard\ndata:\n  my-dashboard.json: |-\n    $RAW_JSON\n```\n\nThe `ConfigMap` file name should conform with `grafana-dashboard-my-dashboard.configmap.yaml`. Add it under the `grafana` directory.\n\n3. Add a section to `volumes` and a corresponding `volumeMount` in the Deployment resource: `grafana/grafana.deployment.yaml`.\n\nSee this MR as an example: https://gitlab.cee.redhat.com/service/app-sre-observability/merge_requests/11\n\n## Tips and Tricks\n\n* Keep the `Building blocks` Row as part of the dashboard in case you require changes in the future\n* Export the dashboard with the `Building blocks` Row collapsed\n* Group panels together using a Row object (you may find some below)\n\n\nGood luck!"
  },
  {
   "title": "Graph",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ]
  },
  {
   "title": "SingleStat",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 84 },
   "format": "none",
   "valueName": "avg"
  },
  { "title": "Table", "type": "table", "gridPos": { "h": 7, "w": 5, "x": 10, "y": 84 } },
  { "title": "Text", "type": "text", "gridPos": { "h": 7, "w": 5, "x": 15, "y": 84 }, "content": "# title" },
  { "title": "Heatmap", "type": "heatmap", "gridPos": { "h": 7, "w": 5, "x": 0, "y": 91 } },
  { "title": "Alert list", "type": "alertlist", "gridPos": { "h": 7, "w": 5, "x": 5, "y": 91 } },
  { "title": "Dashboard list", "type": "dashlist", "gridPos": { "h": 7, "w": 5, "x": 10, "y": 91 } },
  { "title": "Plugin list", "type": "pluginlist", "gridPos": { "h": 7, "w": 5, "x": 15, "y": 91 } },
  {
   "title": "Row",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 },
   "collapsed": true
  },
  {
   "title": "Row",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 },
   "collapsed": true
  },
  {
   "title": "Row",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 },
   "collapsed": true
  }
 ]
}