{
 "title": "Jenkins: Performance and health overview",
 "description": "Jobs queue speeds and rates, Executors availability, Nodes status, Jenkins and JVM resource usage.\r\n\r\nCreated as copy of a bit nicer dashboard, which is using graphite datasource.",
 "time": { "from": "2019-04-24T07:09:00.051Z", "to": "2019-04-24T08:39:29.202Z" },
 "panels": [
  {
   "title": "Processing speed",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(jenkins_job_building_duration_count[1m])"
    }
   ]
  },
  {
   "title": "Job queue duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jenkins_job_queuing_duration" }
   ]
  },
  {
   "title": "Queued rate",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(jenkins_job_queuing_duration_count[1m])"
    }
   ]
  },
  {
   "title": "JVM free memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(vm_memory_total_max{job=\"jenkins_ext\"} - vm_memory_total_used{job=\"jenkins_ext\"}) / vm_memory_total_max{job=\"jenkins_ext\"} * 100.0"
    }
   ]
  },
  {
   "title": "JVM uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 7 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "vm_uptime_milliseconds{job=\"jenkins_ext\"}"
    }
   ]
  },
  {
   "title": "Jenkins health",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_health_check_score" }
   ]
  },
  {
   "title": "Jenkins plugins failed",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_plugins_failed" }
   ]
  },
  {
   "title": "Jenkins nodes offline",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_node_offline_value" }
   ]
  },
  {
   "title": "Jenkins queue size",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_queue_size_value" }
   ]
  },
  {
   "title": "Executors free",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_executor_free_value" }
   ]
  },
  {
   "title": "Executors Used %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 4, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 * (jenkins_executor_in_use_value / jenkins_executor_count_value)"
    }
   ]
  },
  {
   "title": "Executors In-use",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_executor_in_use_value" }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "vm_cpu_load{job=\"jenkins_ext\"}"
    }
   ]
  }
 ]
}