{
 "title": "Cincinnati",
 "time": { "from": "2019-04-10T08:00:31.936Z", "to": "2019-04-10T08:05:47.520Z" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(kube_pod_info, cluster)"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\"}, namespace)"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\", namespace=\"$namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Cincinnati Known Releases",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Releases Available in Graph",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "cincinnati_gb_graph_upstream_raw_releases{namespace=\"$namespace\"}"
      }
     ]
    },
    {
     "title": "Releases Fetched",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "cincinnati_gb_graph_upstream_raw_releases{namespace=\"$namespace\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Graph Builder",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Pods Active",
     "type": "singlestat",
     "gridPos": { "h": 9, "w": 4, "x": 0, "y": 2 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "count(up{job=\"cincinnati-graph-builder\", namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Upstream Scrape Rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 11, "x": 4, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(cincinnati_gb_graph_upstream_scrapes_total{job=\"cincinnati-graph-builder\",namespace=\"$namespace\"}[5m])"
      }
     ]
    },
    {
     "title": "Upstream Scrape Errors",
     "type": "graph",
     "gridPos": { "h": 9, "w": 9, "x": 15, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(cincinnati_gb_graph_upstream_errors_total{job=\"cincinnati-graph-builder\",namespace=\"$namespace\"}[5m])"
      }
     ]
    }
   ]
  },
  {
   "title": "Policy Engine",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request serve duration: P99",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_graph_serve_duration_seconds_bucket{job=\"cincinnati-policy-engine\",namespace=\"$namespace\"}[1m])) by (le))",
       "legendFormat": "{{job}} p99 request serve duration"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", pod_name=\"$pod\", container_name!=\"POD\", cluster=\"$cluster\"}) by (container_name)",
       "legendFormat": "{{container_name}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_rss{cluster=\"$cluster\", namespace=\"$namespace\", pod_name=\"$pod\", container_name!=\"POD\", container_name!=\"\"}) by (container_name)",
       "legendFormat": "{{container_name}} (RSS)"
      },
      {
       "expr": "sum(container_memory_cache{cluster=\"$cluster\", namespace=\"$namespace\", pod_name=\"$pod\", container_name!=\"POD\", container_name!=\"\"}) by (container_name)",
       "legendFormat": "{{container_name}} (Cache)"
      },
      {
       "expr": "sum(container_memory_swap{cluster=\"$cluster\", namespace=\"$namespace\", pod_name=\"$pod\", container_name!=\"POD\", container_name!=\"\"}) by (container_name)",
       "legendFormat": "{{container_name}} (Swap)"
      }
     ]
    }
   ]
  }
 ]
}