{
 "title": "OSIO Capacity",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "starter-us-east-2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilisation",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "1 - avg(rate(node_cpu{mode=\"idle\"}[1m]))"
    }
   ]
  },
  {
   "title": "Memory Utilisation",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "1 - sum(:node_memory_MemFreeCachedBuffers:sum) / sum(:node_memory_MemTotal:sum)"
    }
   ]
  },
  {
   "title": "PV available",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_persistentvolume_status_phase{phase=\"Available\"})"
    }
   ]
  },
  {
   "title": "Che namespaces",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_namespace_status_phase{phase=\"Active\",namespace=~\"^.*che$\"})"
    }
   ]
  },
  {
   "title": "Workspace pods",
   "type": "singlestat",
   "description": "Excludes system pods (see query)",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_info{pod=~\"^workspace.*\"})",
     "legendFormat": "Pods"
    }
   ]
  },
  {
   "title": "Pod count (excl. system pods)",
   "type": "singlestat",
   "description": "Excludes system pods (see query)",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_info{namespace!~\"^(openshift-|kube-|logging|ops-|gluster-|k8s-image-puller).*\"})",
     "legendFormat": "Pods"
    }
   ]
  },
  {
   "title": "Subscribers",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "onlinereg_subscriber_limit{plan=\"starter-us-east-2\"}",
     "legendFormat": "Limit"
    },
    {
     "expr": "onlinereg_capacity_consumed{plan=\"starter-us-east-2\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "onlinereg_hidden{plan=\"starter-us-east-2\"}",
     "legendFormat": "Hidden"
    }
   ]
  },
  { "title": "starter-us-east-2a", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU Utilisation",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "1 - avg(rate(node_cpu{mode=\"idle\"}[1m]))"
    }
   ]
  },
  {
   "title": "Memory Utilisation",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 6 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "1 - sum(:node_memory_MemFreeCachedBuffers:sum) / sum(:node_memory_MemTotal:sum)"
    }
   ]
  },
  {
   "title": "PV available",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_persistentvolume_status_phase{phase=\"Available\"})"
    }
   ]
  },
  {
   "title": "Che namespaces",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_namespace_status_phase{phase=\"Active\",namespace=~\"^.*che$\"})"
    }
   ]
  },
  {
   "title": "Workspace pods",
   "type": "singlestat",
   "description": "Excludes system pods (see query)",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_info{pod=~\"^workspace.*\"})",
     "legendFormat": "Pods"
    }
   ]
  },
  {
   "title": "Pod count (excl. system pods)",
   "type": "singlestat",
   "description": "Excludes system pods (see query)",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_info{namespace!~\"^(openshift-|kube-|logging|ops-|gluster-|k8s-image-puller).*\"})"
    }
   ]
  },
  {
   "title": "Subscribers",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 18, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "onlinereg_subscriber_limit{plan=\"starter-us-east-2a\"}",
     "legendFormat": "Limit"
    },
    {
     "expr": "onlinereg_capacity_consumed{plan=\"starter-us-east-2a\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "onlinereg_hidden{plan=\"starter-us-east-2a\"}",
     "legendFormat": "Hidden"
    }
   ]
  },
  { "title": "starter-us-east-1a", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "CPU Utilisation",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 11 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "1 - avg(rate(node_cpu{mode=\"idle\"}[1m]))"
    }
   ]
  },
  {
   "title": "Memory Utilisation",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 11 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "1 - sum(:node_memory_MemFreeCachedBuffers:sum) / sum(:node_memory_MemTotal:sum)"
    }
   ]
  },
  {
   "title": "PV available",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_persistentvolume_status_phase{phase=\"Available\"})"
    }
   ]
  },
  {
   "title": "Che namespaces",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_namespace_status_phase{phase=\"Active\",namespace=~\"^.*che$\"})"
    }
   ]
  },
  {
   "title": "Workspace pods",
   "type": "singlestat",
   "description": "Excludes system pods (see query)",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_info{pod=~\"^workspace.*\"})",
     "legendFormat": "Pods"
    }
   ]
  },
  {
   "title": "Pod count (excl. system pods)",
   "type": "singlestat",
   "description": "Excludes system pods (see query)",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_info{namespace!~\"^(openshift-|kube-|logging|ops-|gluster-|k8s-image-puller).*\"})"
    }
   ]
  },
  {
   "title": "Subscribers",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 18, "y": 11 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "onlinereg_subscriber_limit{plan=\"starter-us-east-1a\"}",
     "legendFormat": "Limit"
    },
    {
     "expr": "onlinereg_capacity_consumed{plan=\"starter-us-east-1a\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "onlinereg_hidden{plan=\"starter-us-east-1a\"}",
     "legendFormat": "Hidden"
    }
   ]
  },
  { "title": "starter-us-east-1b", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "CPU Utilisation",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 16 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "1 - avg(rate(node_cpu{mode=\"idle\"}[1m]))"
    }
   ]
  },
  {
   "title": "Memory Utilisation",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 16 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "1 - sum(:node_memory_MemFreeCachedBuffers:sum) / sum(:node_memory_MemTotal:sum)"
    }
   ]
  },
  {
   "title": "PV available",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_persistentvolume_status_phase{phase=\"Available\"})"
    }
   ]
  },
  {
   "title": "Che namespaces",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_namespace_status_phase{phase=\"Active\",namespace=~\"^.*che$\"})"
    }
   ]
  },
  {
   "title": "Workspace pods",
   "type": "singlestat",
   "description": "Excludes system pods (see query)",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_info{pod=~\"^workspace.*\"})",
     "legendFormat": "Pods"
    }
   ]
  },
  {
   "title": "Pod count (excl. system pods)",
   "type": "singlestat",
   "description": "Excludes system pods (see query)",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_info{namespace!~\"^(openshift-|kube-|logging|ops-|gluster-|k8s-image-puller).*\"})"
    }
   ]
  },
  {
   "title": "Subscribers",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 18, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "onlinereg_subscriber_limit{plan=\"starter-us-east-1b\"}",
     "legendFormat": "Limit"
    },
    {
     "expr": "onlinereg_capacity_consumed{plan=\"starter-us-east-1b\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "onlinereg_hidden{plan=\"starter-us-east-1b\"}",
     "legendFormat": "Hidden"
    }
   ]
  },
  {
   "title": "Building blocks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Playground usage",
     "type": "text",
     "gridPos": { "h": 9, "w": 20, "x": 0, "y": 21 },
     "content": "# How to bulid a dashboard using this Playground\n\n## Getting started\n\nBelow you wil find all available panels to be used for a dashboard.\n\nTo start, select a panel to use, and duplicate it (`Panel options > More > Duplicate`).\n\nDrag it to the top of the screen (above the Building blocks Row) and change the panel title, metrics, and any other settings as required.\n\n\n## Saving your dashboard\n\n\nSince all dashboards are managed through source control, saving dashboards is not enabled.\n\nTo save your new dashboard, export it to a JSON file (through the options on the top right of the screen) and save it locally.\n\n\n## Adding your dashboard\n\nTo add your dashboard, follow these steps:\n\n1. Create a Merge Request to the following git repository:\nhttps://gitlab.cee.redhat.com/service/app-sre-observability\n\n2. Add the JSON content to a `ConfigMap` resource:\n\n```\nkind: ConfigMap\napiVersion: v1\nmetadata:\n  name: grafana-dashboard-my-dashboard\ndata:\n  my-dashboard.json: |-\n    $RAW_JSON\n```\n\nThe `ConfigMap` file name should conform with `grafana-dashboard-my-dashboard.configmap.yaml`. Add it under the `grafana` directory.\n\n3. Add a section to `volumes` and a corresponding `volumeMount` in the Deployment resource: `grafana/grafana.deployment.yaml`.\n\nSee this MR as an example: https://gitlab.cee.redhat.com/service/app-sre-observability/merge_requests/11\n\n## Tips and Tricks\n\n* Keep the `Building blocks` Row as part of the dashboard in case you require changes in the future\n* Export the dashboard with the `Building blocks` Row collapsed\n* Group panels together using a Row object (you may find some below)\n\n\nGood luck!"
    },
    {
     "title": "Graph",
     "type": "graph",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ]
    },
    {
     "title": "SingleStat",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 5, "x": 5, "y": 30 },
     "format": "none",
     "valueName": "avg"
    },
    { "title": "Table", "type": "table", "gridPos": { "h": 7, "w": 5, "x": 10, "y": 30 } },
    { "title": "Text", "type": "text", "gridPos": { "h": 7, "w": 5, "x": 15, "y": 30 }, "content": "# title" },
    { "title": "Heatmap", "type": "heatmap", "gridPos": { "h": 7, "w": 5, "x": 0, "y": 37 } },
    { "title": "Alert list", "type": "alertlist", "gridPos": { "h": 7, "w": 5, "x": 5, "y": 37 } },
    { "title": "Dashboard list", "type": "dashlist", "gridPos": { "h": 7, "w": 5, "x": 10, "y": 37 } },
    { "title": "Plugin list", "type": "pluginlist", "gridPos": { "h": 7, "w": 5, "x": 15, "y": 37 } }
   ]
  }
 ]
}