{
 "title": "AWS Account Operator - Production",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Number of Unclaimed CRs",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "aws_account_operator_total_accounts_crs_unclaimed{job=\"hive-aws-account-operator-stage\"}"
    }
   ]
  },
  {
   "title": "Accounts Pending Verification ",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "aws_account_operator_total_aws_account_pending_verification{job=\"hive-aws-account-operator-production\"}"
    }
   ]
  },
  {
   "title": "Pending Verification with respect to Unclaimed Accounts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 14, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Accounts" }
   ],
   "targets": [
    {
     "expr": "aws_account_operator_total_aws_account_pending_verification{job=\"hive-aws-account-operator-production\"}",
     "legendFormat": "Pending Verification"
    },
    {
     "expr": "aws_account_operator_total_accounts_crs_unclaimed{job=\"hive-aws-account-operator-production\"}",
     "legendFormat": "CRs Unclaimed"
    }
   ]
  },
  {
   "title": "Number of Account CRs Failed ",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "aws_account_operator_total_accounts_crs_failed{job=\"hive-aws-account-operator-production\"}"
    }
   ]
  },
  {
   "title": "Total Number of AWS Accounts Created",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "aws_account_operator_total_aws_accounts{job=\"hive-aws-account-operator-production\"}"
    }
   ]
  },
  {
   "title": "Total Number of AWS Accounts Created",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_account_operator_total_aws_accounts{job=\"hive-aws-account-operator-production\"}",
     "legendFormat": "Total AWS Accounts"
    }
   ]
  },
  {
   "title": "Difference Between Pool Size and Unclaimed CRs",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "aws_account_operator_pool_size_vs_unclaimed{job=\"hive-aws-account-operator-production\"}"
    }
   ]
  },
  {
   "title": "Number of Ready Account CRs",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "aws_account_operator_total_accounts_crs_ready{job=\"hive-aws-account-operator-production\"}"
    }
   ]
  },
  {
   "title": "Difference between Pool Size  and Unclaimed CRs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "Difference" }
   ],
   "targets": [
    {
     "expr": "aws_account_operator_pool_size_vs_unclaimed{job=\"hive-aws-account-operator-production\"}",
     "legendFormat": "Pool  Size  – Unclaimed"
    }
   ]
  }
 ]
}