{
 "title": "Operations - Rbac w/CPU",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Latency",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(api_3scale_gateway_api_time_bucket{service=\"rbac\"}[5m])) by (le)",
     "legendFormat": "{{le}} ms"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(api_3scale_gateway_api_time_count{service=\"rbac\"}[5m]))"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "graph",
   "description": "Proportion of 5xx status codes returned from this service.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(api_3scale_gateway_api_status{service=\"rbac\",status=\"5xx\"}[5m])) / sum(rate(api_3scale_gateway_api_time_count{service=\"rbac\"}[5m]))"
    }
   ]
  },
  {
   "title": "Container Restarts",
   "type": "graph",
   "description": "Plots the number of container restarts in 5 minute chunks",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{namespace=\"rbac-prod\",pod=~\".*rbac.*\"}[5m]))"
    }
   ]
  },
  {
   "title": "Percentage of CPU limit consumed",
   "type": "graph",
   "description": "CPU consumption plotted against configured CPU limit of service",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"rbac-prod\",pod_name=~\".*rbac.*\"}[5m])) / sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"rbac-prod\",pod=~\".*rbac.*\"})"
    }
   ]
  },
  {
   "title": "Percentage of memory limit consumed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"rbac-prod\",pod_name=~\".*rbac.*\",container!~\"sti-build|deployment|lifecycle\",name=\"\"}) / sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"rbac-prod\",pod=~\".*rbac.*\",container!~\"sti-build|deployment|lifecycle\",name=\"\"})"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"rbac-prod\",pod_name=~\".*rbac.*\"}[5m])",
     "legendFormat": "{{pod_name}}:{{container_name}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"rbac-prod\",pod_name=~\".*rbac.*\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  }
 ]
}