{
 "title": "BackplaneAPI",
 "time": { "from": "2021-04-26T01:34:25.983Z", "to": "2021-04-26T02:09:49.347Z" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "BudgetBurn5m",
   "type": "graph",
   "description": "Error budget burn for backplane-api logins over 5 mins",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "backplane_500_response:burnrate5m"
    }
   ]
  },
  {
   "title": "BudgetBurn30m",
   "type": "graph",
   "description": "Error budget burn for backplane-api logins over 30 mins",
   "gridPos": { "h": 7, "w": 6, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Time Over Error Rate" }
   ],
   "targets": [
    {
     "expr": "backplane_500_response:burnrate30m"
    }
   ]
  },
  {
   "title": "BudgetBurn1Hour",
   "type": "graph",
   "description": "Error budget burn for backplane-api logins over 1 Hour",
   "gridPos": { "h": 7, "w": 6, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Time Over Error Rate" }
   ],
   "targets": [
    {
     "expr": "backplane_500_response:burnrate1h"
    }
   ]
  },
  {
   "title": "BudgetBurn2Hour",
   "type": "graph",
   "description": "High error budget burn for backplane-api logins over last 2 hours",
   "gridPos": { "h": 7, "w": 6, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Time Over Error Rate" }
   ],
   "targets": [
    {
     "expr": "backplane_500_response:burnrate2h"
    }
   ]
  },
  {
   "title": "BudgetBurn6hour",
   "type": "graph",
   "description": "Error budget burn for backplane-api logins over 6 hour",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "Time Over Error Rate" }
   ],
   "targets": [
    {
     "expr": "backplane_500_response:burnrate6h"
    }
   ]
  },
  {
   "title": "BudgetBurn1Day",
   "type": "graph",
   "description": "High error budget burn for backplane-api logins over 1 Day ",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "Time Over Error Rate" }
   ],
   "targets": [
    {
     "expr": "backplane_500_response:burnrate1d"
    }
   ]
  },
  {
   "title": "BudgetBurn3Day",
   "type": "graph",
   "description": "High error budget burn for backplane-api logins over 3 Days ",
   "gridPos": { "h": 7, "w": 7, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "Time Over Error Rate" }
   ],
   "targets": [
    {
     "expr": "backplane_500_response:burnrate3d"
    }
   ]
  },
  {
   "title": "Count of all HTTP requests",
   "type": "graph",
   "description": "HTTP requests  ",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "http_requests_total" }
   ]
  },
  {
   "title": "Durations of HTTP requests",
   "type": "graph",
   "description": "Durations of HTTP requests",
   "gridPos": { "h": 6, "w": 12, "x": 11, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "Time Over Error Rate" }
   ],
   "targets": [
    {
     "expr": "http_request_duration_seconds_bucket"
    }
   ]
  }
 ]
}