{
 "title": "Cyndi",
 "tags": [
  "platform-health",
  "cyndi"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "environment",
    "query": "up{kubernetes_namespace=~\"platform-mq-.*\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Consumer lag by application",
   "type": "graph",
   "gridPos": { "h": 11, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min(\nsum(\nlabel_replace(\nkafka_consumer_group_lag{kubernetes_namespace=~\"platform-mq-$env\", topic=\"platform.inventory.events\", group=~\"connect-syndication-sink-.*\"},\n\"cyndi_application\", \"$1\", \"group\", \"connect-syndication-sink-(.*)\\\\.v.*\")\n) by (group, cyndi_application)\n) by (cyndi_application)",
     "legendFormat": "{{cyndi_application}}"
    }
   ]
  },
  {
   "title": "Consumer lag by group",
   "type": "table",
   "gridPos": { "h": 18, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum(kafka_consumer_group_lag{kubernetes_namespace=~\"platform-mq-$env\", topic=\"platform.inventory.events\", group=~\"connect-syndication-sink-.*\"}) by (group)",
     "legendFormat": "Number of messages"
    },
    {
     "expr": "max(kafka_consumergroup_group_lag_seconds{kubernetes_namespace=~\"platform-mq-$env\", topic=\"platform.inventory.events\", group=~\"connect-syndication-sink-.*\"}) by (group)",
     "legendFormat": "Delay (s)"
    }
   ]
  },
  {
   "title": "Incoming Message Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum (rate(kafka_server_brokertopicmetrics_messagesin_total{kubernetes_namespace=\"platform-mq-$env\", topic=\"platform.inventory.events\"}[1m]))",
     "legendFormat": "platform.inventory.events"
    }
   ]
  }
 ]
}