{
 "title": "Code Ready Analytics Stats",
 "tags": [
  "Code Ready Analytics",
  "CRA",
  "Bayesian",
  "f8a",
  "fabric8-analytics"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "graphite" }
  ]
 },
 "panels": [
  {
   "title": "Component Analyses - Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "datasource"
  },
  {
   "title": "Component Analysis - Response Time Moving Average",
   "type": "graph",
   "description": "Moving Average of Component Analysis API calls aka LSP calls triggered when opening a manifest file inside IDE",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "osio.prometheus.bayesian.analytics_api_http_request_gauge.*get_component_analysis method~3AGET status~3A2*"
    }
   ]
  },
  {
   "title": "Component Analysis - Success Count - Status 200",
   "type": "graph",
   "description": "Component Analysis success count for dependency known to our platform.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "osio.prometheus.bayesian.analytics_api_request_count_gauge.*get_component_analysis*GET*200"
    }
   ]
  },
  {
   "title": "Component Analyses - Success Count - Status 202",
   "type": "graph",
   "description": "Count of dependency not known to the f8a platform, but will trigger unknown dependency flow (based on the settings). If a dependency is public, it will be known in the next 24 hours. Status Code 202.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "osio.prometheus.bayesian.analytics_api_request_count_gauge.*get_component_analysis*GET*202"
    }
   ]
  },
  {
   "title": "Component Analysis - Failure Count",
   "type": "graph",
   "description": "Count of dependency not known to the f8a platform and will not trigger unknown dependency flow (based on the settings). Status code 404.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "osio.prometheus.bayesian.analytics_api_request_count_gauge.*get_component_analysis*GET*4??"
    }
   ]
  },
  { "title": "Stack Analysis - Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Stack Analysis - Response Time Moving Average",
   "type": "graph",
   "description": "Moving Average of Stack Analysis API calls ",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "osio.prometheus.bayesian.analytics_api_http_request_gauge.*get_stack_analyses*POST status*200"
    }
   ]
  },
  {
   "title": "Stack Analysis - Success Count - Status 200",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "osio.prometheus.bayesian.analytics_api_request_count_gauge.*get_stack_analyses*status~3A200"
    }
   ]
  },
  {
   "title": "Stack Analysis - Failure Count",
   "type": "graph",
   "description": "Status code 404.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "osio.prometheus.bayesian.analytics_api_request_count_guage.*get_stack_analyses*POST*4??"
    }
   ]
  }
 ]
}