{
 "title": "Certman- Operator",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "environment",
    "label": "Hive Job",
    "query": "label_values(certman_operator_certificate_issue_duration_count, job)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Controller Reconcile Duration for certificate-request",
   "type": "graph",
   "description": "Duration of Reconcile for certificate-request",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(certman_operator_certificate_request_reconcile_duration_seconds_sum{job=\"$environment\"}[10m]) ) by (controller) / sum(rate (certman_operator_certificate_request_reconcile_duration_seconds_count{job=\"$environment\"}[10m])) by (controller) ",
     "legendFormat": "certificate-request"
    }
   ]
  },
  {
   "title": "Controller Reconcile Duration for cluster-deployment",
   "type": "graph",
   "description": "Duration of Reconcile per controller type for cluster-deployment",
   "gridPos": { "h": 9, "w": 10, "x": 10, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(certman_operator_cluster_deployment_reconcile_duration_seconds_sum{job=\"$environment\"}[10m]) ) by (controller) / sum(rate (certman_operator_cluster_deployment_reconcile_duration_seconds_count{job=\"$environment\"}[10m])) by (controller) ",
     "legendFormat": "cluster-deployment"
    }
   ]
  },
  {
   "title": "Controller reconcile count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(certman_operator_certificate_request_reconcile_duration_seconds_count{job=\"$environment\"}[10m])) by (controller)",
     "legendFormat": "certificate-request"
    },
    {
     "expr": "sum(rate(certman_operator_cluster_deployment_reconcile_duration_seconds_count{job=\"$environment\"}[10m])) by (controller)",
     "legendFormat": "cluster-deployment"
    }
   ]
  },
  {
   "title": "Issued certificate count",
   "type": "graph",
   "description": "Number of certificate issued in the past 7days per domain",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(certman_operator_certs_in_last_week_devshift_org{job=\"$environment\"})/count(certman_operator_certs_in_last_week_devshift_org{job=\"$environment\"})",
     "legendFormat": "devshift.org"
    },
    {
     "expr": "sum(certman_operator_certs_in_last_week_openshift_apps_com{job=\"$environment\"})/count(certman_operator_certs_in_last_week_openshift_apps_com{job=\"$environment\"})",
     "legendFormat": "openshiftapps.com"
    }
   ]
  },
  {
   "title": "Certificate issuance rate (per minute)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(certman_operator_issued_certficates_count{job=\"$environment\"}[10m]) ) by (controller, action) * 60",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Count of Certificate Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "certman_operator_certificate_requests_count{job=\"$environment\"}"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_alloc_bytes{job=\"$environment\"}",
       "legendFormat": "alloc all - {{instance}}"
      },
      {
       "expr": "go_memstats_heap_alloc_bytes{job=\"$environment\"}",
       "legendFormat": "alloc heap - {{instance}}"
      },
      {
       "expr": "rate(go_memstats_alloc_bytes_total{job=\"$environment\"}[30s])",
       "legendFormat": "alloc rate all - {{instance}}"
      },
      {
       "expr": "rate(go_memstats_heap_alloc_bytes{job=\"$environment\"}[30s])",
       "legendFormat": "alloc rate heap - {{instance}}"
      },
      {
       "expr": "go_memstats_stack_inuse_bytes{job=\"$environment\"}",
       "legendFormat": "inuse stack - {{instance}}"
      },
      {
       "expr": "go_memstats_heap_inuse_bytes{job=\"$environment\"}",
       "legendFormat": "inuse heap - {{instance}}"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 7, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_goroutines{job=\"$environment\"}",
       "legendFormat": "goroutines - {{instance}}"
      }
     ]
    },
    {
     "title": "GC Time Quantiles",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 14, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_gc_duration_seconds{job=\"$environment\"}",
       "legendFormat": "{{quantile}} - {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Building blocks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Playground usage",
     "type": "text",
     "gridPos": { "h": 9, "w": 20, "x": 0, "y": 37 },
     "options": {
      "content": "# How to bulid a dashboard using this Playground\n\n## Full documentation on creating Dashboards\n\nhttps://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/app-sre/monitoring.md#VisualizationwithGrafana\n\n## Getting started with the Playground dashboard\n\nBelow you wil find all available panels to be used for a dashboard.\n\nTo start, select a panel to use, and duplicate it (`Panel options > More > Duplicate`).\n\nDrag it to the top of the screen (above the Building blocks Row) and change the panel title, metrics, and any other settings as required.\n\n\n## Saving your dashboard to Grafana\n\nSince all dashboards are managed through source control, saving dashboards is not enabled.\n\nTo save your new dashboard, export it to a JSON file (through the options on the top right of the screen) and save it locally. You will now need to create a merge request to app-interface.\n\nPlease see: https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/app-sre/monitoring.md#adding-dashboards\n\n## Tips and Tricks\n\n* Keep the `Building blocks` Row as part of the dashboard in case you require changes in the future\n* Export the dashboard with the `Building blocks` Row collapsed\n* Group panels together using a Row object (you may find some below)\n\n\nGood luck!"
     },
     "content": "# How to bulid a dashboard using this Playground\n\n## Full documentation on creating Dashboards\n\nhttps://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/app-sre/monitoring.md#VisualizationwithGrafana\n\n## Getting started with the Playground dashboard\n\nBelow you wil find all available panels to be used for a dashboard.\n\nTo start, select a panel to use, and duplicate it (`Panel options > More > Duplicate`).\n\nDrag it to the top of the screen (above the Building blocks Row) and change the panel title, metrics, and any other settings as required.\n\n\n## Saving your dashboard to Grafana\n\nSince all dashboards are managed through source control, saving dashboards is not enabled.\n\nTo save your new dashboard, export it to a JSON file (through the options on the top right of the screen) and save it locally. You will now need to create a merge request to app-interface.\n\nPlease see: https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/app-sre/monitoring.md#adding-dashboards\n\n## Tips and Tricks\n\n* Keep the `Building blocks` Row as part of the dashboard in case you require changes in the future\n* Export the dashboard with the `Building blocks` Row collapsed\n* Group panels together using a Row object (you may find some below)\n\n\nGood luck!"
    },
    {
     "title": "Graph",
     "type": "graph",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ]
    },
    {
     "title": "SingleStat",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 5, "x": 5, "y": 46 },
     "format": "none",
     "valueName": "avg"
    },
    { "title": "Table", "type": "table-old", "gridPos": { "h": 7, "w": 5, "x": 10, "y": 46 } },
    {
     "title": "Text",
     "type": "text",
     "gridPos": { "h": 7, "w": 5, "x": 15, "y": 46 },
     "options": { "content": "# title" },
     "content": "# title"
    },
    { "title": "Heatmap", "type": "heatmap", "gridPos": { "h": 7, "w": 5, "x": 0, "y": 53 } },
    { "title": "Alert list", "type": "alertlist", "gridPos": { "h": 7, "w": 5, "x": 5, "y": 53 } },
    { "title": "Dashboard list", "type": "dashlist", "gridPos": { "h": 7, "w": 5, "x": 10, "y": 53 } },
    { "title": "Plugin list", "type": "pluginlist", "gridPos": { "h": 7, "w": 5, "x": 15, "y": 53 } }
   ]
  },
  {
   "title": "Row",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true
  }
 ]
}