{
 "title": "xjoin-search",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "namespace",
    "query": "up{kubernetes_namespace=~\"xjoin-.*\"}"
   }
  ]
 },
 "panels": [
  { "title": "Current values", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(xjoin_search_http_request_duration_seconds_count{kubernetes_namespace=\"$namespace\", kubernetes_name=\"xjoin-search\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Number of pods",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(up{kubernetes_namespace=\"$namespace\", app=\"xjoin-search\"})"
    }
   ]
  },
  {
   "title": "4xx ratio",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(xjoin_search_http_request_duration_seconds_count{kubernetes_namespace=\"$namespace\", kubernetes_name=\"xjoin-search\", status_code=~\"4.*\"}[$__range])) / sum(increase(xjoin_search_http_request_duration_seconds_count{kubernetes_namespace=\"$namespace\", kubernetes_name=\"xjoin-search\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Validation errors",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(xjoin_search_errors_total{kubernetes_namespace=\"$namespace\", type=\"validation\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Pod count",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(up{kubernetes_namespace=\"$namespace\", app=\"xjoin-search\"})",
     "legendFormat": "pod count"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 3 },
   "format": "none",
   "valueName": "delta",
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{namespace=\"$namespace\", container=\"xjoin-search\"}[$__range]))"
    }
   ]
  },
  {
   "title": "5xx ratio",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 3 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(xjoin_search_http_request_duration_seconds_count{kubernetes_namespace=\"$namespace\", status_code=~\"5.*\"}[$__range])) or 0 / sum(increase(xjoin_search_http_request_duration_seconds_count{kubernetes_namespace=\"$namespace\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Failures",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 3 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(xjoin_search_errors_total{kubernetes_namespace=\"$namespace\", type=\"system\"}[$__range]))"
    }
   ]
  },
  { "title": "Golden signals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(xjoin_search_http_request_duration_seconds_count{kubernetes_namespace=\"$namespace\", kubernetes_name=\"xjoin-search\"}[$interval])) by (status_code)",
     "legendFormat": "{{status_code}}"
    },
    {
     "expr": "sum(increase(xjoin_search_errors_total{kubernetes_namespace=\"$namespace\"}[$interval])) by (type)",
     "legendFormat": "{{type}} errors"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(xjoin_search_http_request_duration_seconds_bucket{kubernetes_namespace=\"$namespace\", kubernetes_name=\"xjoin-search\"}[$interval])) by (le)",
     "legendFormat": "{{le}} ms"
    }
   ]
  },
  {
   "title": "CPU consumed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container_name=\"xjoin-search\"}[1m])) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Memory consumed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\",container_name=\"xjoin-search\"}) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Advanced",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Elasticsearch Latency",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "sum(rate(xjoin_search_es_request_duration_seconds_bucket{kubernetes_namespace=\"$namespace\", kubernetes_name=\"xjoin-search\"}[$interval])) by (le)",
       "legendFormat": "{{le}} ms"
      }
     ]
    }
   ]
  }
 ]
}