{
 "title": "xjoin-Kafka-Connectors",
 "tags": [
  "platform-health",
  "xjoin"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "environment",
    "query": "up{kubernetes_namespace=~\"platform-mq-.*\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Restarts",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{namespace=\"xjoin-$env\", container=\"xjoin-kafka-connect\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{namespace=\"xjoin-$env\", container=\"xjoin-kafka-connect\"})"
    }
   ]
  },
  {
   "title": "Processed Messages",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(kafka_consumer_group_offset{kubernetes_namespace=\"platform-mq-$env\", topic=~\".*xjoin.*\"}[$__range]))"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"xjoin-$env\", container_name=\"xjoin-kafka-connect\"}[1m])",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"xjoin-$env\", container_name=\"xjoin-kafka-connect\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{namespace=\"xjoin-$env\", container=\"xjoin-kafka-connect\"}[$__range]))",
     "legendFormat": "Pod Restarts"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 2 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{namespace=\"xjoin-$env\", container=\"xjoin-kafka-connect\"})",
     "legendFormat": "Pod Restarts"
    }
   ]
  },
  {
   "title": "Incoming Message Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (topic) (rate(kafka_server_brokertopicmetrics_messagesin_total{kubernetes_namespace=\"platform-mq-$env\", topic=~\".*xjoin\\\\..*\"}[1m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Lag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (topic) (kafka_consumer_group_lag{kubernetes_namespace=~\"platform-mq-$env\", topic=~\".*xjoin.*\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Consumed Message Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (topic, group) (rate(kafka_consumer_group_offset{kubernetes_namespace=\"platform-mq-$env\", topic=~\".*xjoin.*\"}[1m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Lag Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg by (topic) (kafka_consumergroup_group_lag_seconds{kubernetes_namespace=~\"platform-mq-$env\", topic=~\".*xjoin.*\"})",
     "legendFormat": "avg/{{topic}}"
    }
   ]
  }
 ]
}