{
 "title": "Code Ready Analytics Stats",
 "tags": [
  "Code Ready Analytics",
  "Bayesian",
  "f8a",
  "fabric8-analytics",
  "CRDA "
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": "bayesian-production, bayesian-preview"
   }
  ]
 },
 "panels": [
  { "title": "Platform Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Replica Count - Online Flow",
   "type": "stat",
   "description": "Replica Count of Services in namespace",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_info{namespace=\"$namespace\", created_by_name=~\"bayesian-api-.+\" })",
     "legendFormat": "API Server"
    },
    {
     "expr": "count(kube_pod_info{namespace=\"$namespace\", created_by_name=~\"f8a-server-backbone-.+\" })",
     "legendFormat": "Backbone"
    },
    {
     "expr": "count(kube_pod_info{namespace=\"$namespace\", created_by_name=~\"bayesian-gremlin-http-.+\" })",
     "legendFormat": "Gremlin HTTP"
    },
    {
     "expr": "count(kube_pod_info{namespace=\"$namespace\", created_by_name=~\"bayesian-pgbouncer-.+\" })",
     "legendFormat": "PgBouncer"
    },
    {
     "expr": "count(kube_pod_info{namespace=\"$namespace\", created_by_name=~\"f8a-license-analysis-.+\" })",
     "legendFormat": "License Analyses"
    },
    {
     "expr": "count(kube_pod_info{namespace=\"$namespace\", created_by_name=~\"fabric8-analytics-stack-report-ui-.+\" })",
     "legendFormat": "Stack Report UI"
    },
    {
     "expr": "count(kube_pod_info{namespace=\"$namespace\", created_by_name=~\"bayesian-worker-api-.+\" })",
     "legendFormat": "Worker API"
    }
   ]
  },
  {
   "title": "Cron Job Errors",
   "type": "graph",
   "description": "Cron Job Errors",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_job_status_failed{namespace=\"bayesian-preview\"} != 0",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  { "title": "API Server - Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Component Analysis API  -  Rate of Requests",
   "type": "graph",
   "description": "Total Rate of Requests of Component Analyses ",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(http_request_duration_seconds_count{exported_endpoint=\"api_v2.component_analyses_get\", namespace=\"$namespace\"}[5m]))",
     "legendFormat": "CA GET"
    },
    {
     "expr": "sum(irate(http_request_duration_seconds_count{exported_endpoint=\"api_v2.component_analyses_post\", namespace=\"$namespace\"}[5m]))",
     "legendFormat": "CA POST"
    }
   ]
  },
  {
   "title": "Component Analysis API - Response Time Average",
   "type": "graph",
   "description": "Component Analyses Response Time Average",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{exported_endpoint=\"api_v2.component_analyses_get\", status=~\"20.\", namespace=\"$namespace\"}[5m])) / sum(rate(http_request_duration_seconds_count{exported_endpoint=\"api_v2.component_analyses_get\", status=~\"20.\", namespace=\"$namespace\"}[5m]))",
     "legendFormat": "CA GET"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{exported_endpoint=\"api_v2.component_analyses_post\", status=~\"20.\", namespace=\"$namespace\"}[5m])) / sum(rate(http_request_duration_seconds_count{exported_endpoint=\"api_v2.component_analyses_post\", status=~\"20.\", namespace=\"$namespace\"}[5m]))",
     "legendFormat": "CA POST"
    }
   ]
  },
  {
   "title": "Component Analysis API  -  Total Requests Count",
   "type": "graph",
   "description": "Total Request Count of Component Analyses ",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_count{exported_endpoint=\"api_v2.component_analyses_get\", namespace=\"$namespace\"})",
     "legendFormat": "CA GET"
    },
    {
     "expr": "sum(http_request_duration_seconds_count{exported_endpoint=\"api_v2.component_analyses_post\", namespace=\"$namespace\"})",
     "legendFormat": "CA POST"
    }
   ]
  },
  {
   "title": "Component Analysis API - Error Rate",
   "type": "graph",
   "description": "Component Analyses Error Rate",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{exported_endpoint=\"api_v2.component_analyses_get\", status!~\"20+\", namespace=\"$namespace\"}[5m]))",
     "legendFormat": "CA GET",
     "target": "osio.prometheus.bayesian.analytics_api_http_request_gauge.*get_component_analysis method~3AGET status~3A2*"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_count{exported_endpoint=\"api_v2.component_analyses_post\", status!~\"20+\", namespace=\"$namespace\"}[5m]))",
     "legendFormat": "CA POST"
    }
   ]
  },
  {
   "title": "Stack Analysis API  -  Rate of Requests",
   "type": "graph",
   "description": "Total Rate of Requests of Stack Analyses ",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(http_request_duration_seconds_count{exported_endpoint=\"api_v2.stack_analyses_with_request_id\", method=\"GET\", namespace=\"$namespace\"}[5m]))",
     "legendFormat": "SA GET"
    },
    {
     "expr": "sum(irate(http_request_duration_seconds_count{exported_endpoint=\"api_v2.stack_analyses\", method=\"POST\", namespace=\"$namespace\"}[5m]))",
     "legendFormat": "SA POST"
    }
   ]
  },
  {
   "title": "Stack Analysis API  -  Response Time Average",
   "type": "graph",
   "description": "Total Response Time Average of Stack Analyses ",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{exported_endpoint=\"api_v2.stack_analyses_with_request_id\", status=~\"20.\", namespace=\"$namespace\"}[5m])) / sum(rate(http_request_duration_seconds_count{exported_endpoint=\"api_v2.stack_analyses_with_request_id\", status=~\"20.\", namespace=\"$namespace\"}[5m]))",
     "legendFormat": "SA GET"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{exported_endpoint=\"api_v2.stack_analyses\", status=~\"20.\", namespace=\"$namespace\"}[5m])) / sum(rate(http_request_duration_seconds_count{exported_endpoint=\"api_v2.stack_analyses\", status=~\"20.\", namespace=\"$namespace\"}[5m]))",
     "legendFormat": "SA POST"
    }
   ]
  },
  {
   "title": "Stack Analysis API  -  Total Requests Count",
   "type": "graph",
   "description": "Total Request Count of Stack Analyses ",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_count{exported_endpoint=\"api_v2.stack_analyses_with_request_id\", method=\"GET\", namespace=\"$namespace\"})",
     "legendFormat": "SA GET"
    },
    {
     "expr": "sum(http_request_duration_seconds_count{exported_endpoint=\"api_v2.stack_analyses\", method=\"POST\", namespace=\"$namespace\"})",
     "legendFormat": "SA POST"
    }
   ]
  },
  {
   "title": "Stack Analysis API  -  Error Rate",
   "type": "graph",
   "description": "Total Error Rate of Stack Analyses ",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(http_request_duration_seconds_count{exported_endpoint=\"api_v2.stack_analyses_with_request_id\", method=\"GET\", status!~\"20.\", namespace=\"$namespace\"}[5m]))",
     "legendFormat": "SA GET"
    },
    {
     "expr": "sum(irate(http_request_duration_seconds_count{exported_endpoint=\"api_v2.stack_analyses\", method=\"POST\", status!~\"20.\", namespace=\"$namespace\"}[5m]))",
     "legendFormat": "SA POST"
    }
   ]
  },
  { "title": "Gremlin Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Gremlin Query Rate",
   "type": "graph",
   "description": "Gremlin Query Rate",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(metrics_org_apache_tinkerpop_gremlin_server_GremlinServer_op_eval_Count{job=\"bayesian-gremlin-http\"}[5m]))",
     "legendFormat": "Gremlin HTTP"
    },
    {
     "expr": "sum(rate(metrics_org_apache_tinkerpop_gremlin_server_GremlinServer_op_eval_Count{job=\"bayesian-gremlin-httpingestion\"}[5m]))",
     "legendFormat": "Gremlin HTTP Ingestion"
    }
   ]
  }
 ]
}