{
 "title": "Backplane",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "BudgetBurn5m",
   "type": "graph",
   "description": "Error budget burn for backplane-api logins over mins",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Time Over Error Rate" }
   ],
   "targets": [
    {
     "expr": "backplane_500_response:burnrate5m"
    }
   ]
  },
  {
   "title": "BudgetBurn30m",
   "type": "graph",
   "description": "Error budget burn for backplane-api logins over 5 mins",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Time Over Error Rate" }
   ],
   "targets": [
    {
     "expr": "backplane_500_response:burnrate30m"
    }
   ]
  },
  {
   "title": "BudgetBurn1Hour",
   "type": "graph",
   "description": "Error budget burn for backplane-api logins over 1 hour",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Time Over Error Rate" }
   ],
   "targets": [
    {
     "expr": "backplane_500_response:burnrate1h"
    }
   ]
  },
  {
   "title": "BudgetBurn2Hour",
   "type": "graph",
   "description": "High error budget burn for backplane-api logins over last 2 hours",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Time Over Error Rate" }
   ],
   "targets": [
    {
     "expr": "backplane_500_response:burnrate2h"
    }
   ]
  },
  {
   "title": "BudgetBurn6hour",
   "type": "graph",
   "description": "Error budget burn for backplane-api logins over 6 hour",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Time Over Error Rate" }
   ],
   "targets": [
    {
     "expr": "backplane_500_response:burnrate6h"
    }
   ]
  },
  {
   "title": "BudgetBurn1Day",
   "type": "graph",
   "description": "High error budget burn for backplane-api logins over 1 Day ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Time Over Error Rate" }
   ],
   "targets": [
    {
     "expr": "backplane_500_response:burnrate1d"
    }
   ]
  },
  {
   "title": "BudgetBurn3Day",
   "type": "graph",
   "description": "High error budget burn for backplane-api logins over 3 Days",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "Time Over Error Rate" }
   ],
   "targets": [
    {
     "expr": "backplane_500_response:burnrate3d"
    }
   ]
  },
  {
   "title": "Count of all HTTP requests",
   "type": "graph",
   "description": "HTTP requests  ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "http_requests_total " }
   ]
  },
  {
   "title": "Durations of HTTP requests",
   "type": "graph",
   "description": "Durations of HTTP requests",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_request_duration_seconds_bucket"
    }
   ]
  }
 ]
}